/**
 * Learn Library seed catalogue — batch 3b (sleep · play · screens). Editorial
 * stance per learnLibrary.ts design rules: general developmental education,
 * wide-normal ranges, no diagnosis-shaped copy. EN/HE are parallel
 * transcreations, not translations.
 */
import type { LocalizedText } from "../content/governance";
import type { LearnCard } from "./learnLibrary";

const L = (en: string, he: string): LocalizedText => ({ en, he });

export const LEARN_CARDS_BATCH3B: LearnCard[] = [
  // ── Sleep & Rest ─────────────────────────────────────────────────────────
  {
    id: "sleep-needs-by-age",
    category: "sleep",
    domains: ["independence_adaptive_skills"],
    ageMin: 0,
    ageMax: 10,
    minutes: 4,
    concerns: ["sleep"],
    title: L("Sleep needs by age: the real ranges", "כמה שינה צריך בכל גיל: הטווחים האמיתיים"),
    hook: L("Sleep charts print single numbers; sleep science publishes wide ranges. Your child's number lives somewhere inside them.", "טבלאות שינה מדפיסות מספר אחד; מדע השינה מפרסם טווחים רחבים. המספר של הילד שלכם נמצא איפשהו בתוכם."),
    keyPoints: [
      L("Pediatric sleep bodies publish ranges, not targets: roughly 12–16 hours for infants, 11–14 for toddlers, 10–13 for preschoolers, 9–12 for school-age — naps included.", "גופי שינה פדיאטריים מפרסמים טווחים, לא יעדים: בערך 12–16 שעות לתינוקות, 11–14 לפעוטות, 10–13 לגילאי הגן, 9–12 לגיל בית הספר — כולל שנת צהריים."),
      L("Within every range sit genuinely different children: some healthy five-year-olds run near ten hours, others near thirteen, and both can be fine.", "בתוך כל טווח יושבים ילדים שונים באמת: יש בני חמש בריאים שמסתדרים עם קרוב לעשר שעות, אחרים עם קרוב לשלוש־עשרה, ושניהם יכולים להיות בסדר."),
      L("Daytime behavior is the better gauge than the clock: waking on their own, reasonably even moods, and energy that lasts the day suggest enough sleep.", "ההתנהגות ביום היא מד טוב יותר מהשעון: התעוררות עצמאית, מצב רוח יציב יחסית ואנרגיה שמחזיקה את היום מרמזים על מספיק שינה."),
      L("Naps fold into the total and fade on their own schedule — most children drop them somewhere between three and five, with wide normal variation.", "שנת צהריים נכללת בסך הכולל ונעלמת בלוח זמנים משלה — רוב הילדים מוותרים עליה איפשהו בין שלוש לחמש, עם שונות תקינה רחבה."),
      L("Work the math backwards: a fixed wake time minus the hours your child seems to need equals the bedtime — then protect it on most nights.", "עשו את החשבון אחורה: שעת השכמה קבועה פחות מספר השעות שהילד נראה צריך שווה שעת שינה — ואז שמרו עליה ברוב הערבים."),
    ],
    body: L(
      "Somewhere on a fridge or in a group chat there's a chart declaring that a four-year-old needs exactly 11.5 hours of sleep, and somewhere there's a parent doing anxious arithmetic against it. It helps to know what the source material actually says. The major pediatric sleep organizations publish recommended ranges — spans of two to four hours per age band — precisely because children genuinely differ. Infants under one commonly land around 12–16 hours across a day, toddlers around 11–14, preschoolers around 10–13, and school-age children around 9–12, naps counted in. These are populations described, not prescriptions issued.\n\nInside each range, the variation is real and largely constitutional. Sleep researchers consistently find that individual sleep need has a strong inborn component: some children are simply shorter sleepers, some longer, in the same way adults differ. Two siblings raised on the same routine can sit at opposite ends of the same healthy band. Chasing the midpoint of a chart for a child built for its lower edge produces a familiar scene — an hour of lying awake, protest, and a parent concluding they have a sleep problem when they may have a math problem.\n\nSo how do you find your child's number? Watch mornings and afternoons rather than the clock. A child getting enough sleep tends to wake on their own steam (or easily), holds a reasonably even mood, and makes it to evening without daily collapse. Chronic hard wake-ups, heavy afternoon fading well past nap age, or falling asleep the moment the car moves suggest the total is short. Adjust bedtime in 15-minute steps and watch for a week — the behavior answers faster than any chart.\n\nTwo footnotes worth keeping. Naps are part of the sum, and giving them up follows its own wide timeline; a fading nap often shifts hours into the night. And while amounts vary, a few things are worth describing to your pediatrician whenever you notice them — regular loud snoring, pauses in breathing, or a child who seems exhausted despite generous hours in bed. Those are observations a professional can work with, and a short conversation settles them best.",
      "איפשהו על מקרר או בקבוצת ואטסאפ יש טבלה שמכריזה שילד בן ארבע צריך בדיוק 11.5 שעות שינה, ואיפשהו יש הורה שעושה מולה חשבון חרד. עוזר לדעת מה חומר המקור באמת אומר. ארגוני שינה פדיאטריים מרכזיים מפרסמים טווחים מומלצים — מרווחים של שעתיים עד ארבע שעות לכל קבוצת גיל — בדיוק כי ילדים באמת שונים זה מזה. תינוקות עד גיל שנה נוחתים בדרך כלל סביב 12–16 שעות ביממה, פעוטות סביב 11–14, ילדי גן סביב 10–13, וילדי בית ספר סביב 9–12, כולל שנת צהריים. אלה אוכלוסיות שמתוארות, לא מרשמים שנכתבים.\n\nבתוך כל טווח, השונות אמיתית ובמידה רבה מולדת. חוקרי שינה מוצאים בעקביות שלצורך השינה האישי יש מרכיב תורשתי חזק: יש ילדים שהם פשוט ישנים קצרים, ויש ארוכים — בדיוק כמו שמבוגרים נבדלים. שני אחים שגדלים על אותו סדר יום יכולים לשבת בשני קצוות של אותה רצועה בריאה. לרדוף אחרי אמצע הטבלה עם ילד שבנוי לקצה התחתון שלה מייצר סצנה מוכרת — שעה של שכיבה ערה, מחאה, והורה שמסיק שיש לו בעיית שינה כשאולי יש לו בעיית חשבון.\n\nאז איך מוצאים את המספר של הילד שלכם? הסתכלו על הבקרים ואחר הצהריים במקום על השעון. ילד שישן מספיק נוטה להתעורר בכוחות עצמו (או בקלות), מחזיק מצב רוח יציב יחסית, ומגיע לערב בלי קריסה יומית. השכמות קשות כרוניות, דעיכה כבדה אחר הצהריים הרבה אחרי גיל שנת הצהריים, או הירדמות ברגע שהאוטו זז — מרמזים שהסכום קצר. הזיזו את שעת השינה בצעדים של רבע שעה ותצפו שבוע — ההתנהגות עונה מהר יותר מכל טבלה.\n\nשתי הערות ששוות שמירה. שנת הצהריים היא חלק מהסכום, והוויתור עליה הולך בלוח זמנים רחב משלו; צהריים שדועכים מזיזים לרוב שעות אל הלילה. ולצד השונות בכמויות, כמה דברים שווה לתאר לרופא הילדים בכל פעם שמבחינים בהם — נחירות רועשות קבועות, הפסקות בנשימה, או ילד שנראה מותש למרות שעות נדיבות במיטה. אלה תצפיות שאיש מקצוע יכול לעבוד איתן, ושיחה קצרה מסדרת אותן הכי טוב."
    ),
    tryToday: L(
      "Pick the wake time your family actually needs, count back your child's current hours, and write tonight's bedtime down. Run it a week before judging it.",
      "בחרו את שעת ההשכמה שהמשפחה באמת צריכה, ספרו אחורה את השעות הנוכחיות של הילד, ורשמו את שעת השינה של הערב. הריצו אותה שבוע לפני שאתם שופטים אותה."
    ),
    ask: L("How do I tell if my child is getting enough sleep for their age?", "איך אדע אם הילד שלי ישן מספיק לגיל שלו?"),
  },
  {
    id: "screens-before-bed",
    category: "sleep",
    domains: ["independence_adaptive_skills", "ecosystem_stressors"],
    ageMin: 1,
    ageMax: 10,
    minutes: 3,
    concerns: ["sleep", "screens"],
    title: L("Screens, melatonin, and the hour before bed", "מסכים, מלטונין, והשעה שלפני השינה"),
    hook: L("The tablet at bedtime works against sleep twice — once through the eyes, once through the plot.", "הטאבלט לפני השינה פועל נגד השינה פעמיים — פעם דרך העיניים, פעם דרך העלילה."),
    keyPoints: [
      L("Evening light — especially the short-wavelength light screens emit up close — is associated with suppressed melatonin, the hormone that opens the door to sleep.", "אור ערב — במיוחד האור קצר־הגל שמסכים פולטים מקרוב — נקשר לדיכוי מלטונין, ההורמון שפותח את הדלת לשינה."),
      L("Children's eyes let in more light than adult eyes, and research suggests their evening melatonin response is more sensitive, not less.", "עיניים של ילדים מכניסות יותר אור מעיניים של מבוגרים, ומחקרים מרמזים שתגובת המלטונין הערבית שלהם רגישה יותר, לא פחות."),
      L("Content is the second dose: cliffhangers, fast pacing and excitement raise arousal exactly when the body should be powering down.", "התוכן הוא המנה השנייה: מותחנים, קצב מהיר והתרגשות מעלים עוררות בדיוק כשהגוף אמור לכבות מנועים."),
      L("Studies repeatedly associate devices in the bedroom — even switched off — with shorter, later, poorer-quality child sleep.", "מחקרים קושרים שוב ושוב מכשירים בחדר השינה — גם כבויים — לשינה קצרה, מאוחרת ואיכותית פחות אצל ילדים."),
      L("The practical rule is a buffer, not a ban: screens land roughly an hour before lights-out, and the bedroom stays a device-free room.", "הכלל המעשי הוא חיץ, לא חרם: המסכים נוחתים בערך שעה לפני כיבוי אורות, וחדר השינה נשאר חדר נקי ממכשירים."),
    ],
    body: L(
      "Bedtime and screens have a specific chemistry problem. As evening darkens, the brain releases melatonin — the internal signal that sleep is coming. Light pushes back against that release, and the light that matters most is exactly the kind screens deliver: short-wavelength, bright, and held close to the face. Research on evening light exposure repeatedly finds it associated with delayed melatonin onset, and some studies suggest children's responses are stronger than adults' — young eyes have larger pupils and clearer lenses, so more of the light gets through. The tablet at 7:40 isn't just entertainment; it's a physiological message that the day is still on.\n\nLight is only half the transaction. The other half is what's playing. Fast cuts, cliffhangers, victory music and one-more-level loops raise excitement and alertness — a state researchers politely call arousal — at the precise moment the bedtime routine is supposed to be lowering it. A wound-up brain doesn't become a sleeping brain on command. This is why 'he watched something calm' still often ends badly: even gentle content delivered with autoplay and bright light keeps the system leaning forward instead of settling back.\n\nThe sleep literature adds one more consistent finding that surprises many parents: the mere presence of a device in the bedroom is associated with worse child sleep — later bedtimes, shorter nights — even when it's supposedly off. A reachable screen is a standing invitation, and children know where the invitations live. Charging phones and tablets outside the bedroom, family-wide, removes the negotiation entirely.\n\nNone of this requires a household screen ban — just a landing pattern. Aim for a buffer of roughly an hour between the last screen and lights-out, and fill it with the boring, beloved machinery of bedtime: bath, pajamas, books, talk. If evenings currently run screen-to-bed, move the cutoff earlier in 15-minute steps rather than all at once, and expect a few nights of protest as the routine renegotiates. Dim the house lights in that final hour too — the melatonin story is about all evening light, and warm, low lamps are on sleep's side.",
      "לשעת השינה ולמסכים יש בעיית כימיה ספציפית. כשהערב מחשיך, המוח משחרר מלטונין — האות הפנימי שהשינה מתקרבת. אור דוחף נגד השחרור הזה, והאור שהכי משנה הוא בדיוק מהסוג שמסכים מספקים: קצר־גל, בהיר, ומוחזק קרוב לפנים. מחקרים על חשיפה לאור בערב מוצאים שוב ושוב קשר לדחיית תחילת המלטונין, וחלקם מרמזים שהתגובות של ילדים חזקות משל מבוגרים — לעיניים צעירות אישונים גדולים יותר ועדשות צלולות יותר, כך שיותר מהאור עובר. הטאבלט ב־19:40 אינו רק בידור; הוא הודעה פיזיולוגית שהיום עדיין נמשך.\n\nהאור הוא רק חצי מהעסקה. החצי השני הוא מה שמתנגן. חיתוכים מהירים, מותחנים, מוזיקת ניצחון ולולאות של עוד־שלב־אחד מעלים התרגשות ודריכות — מצב שחוקרים מכנים בנימוס עוררות — בדיוק ברגע שבו טקס השינה אמור להוריד אותה. מוח דרוך לא הופך למוח ישן לפי פקודה. לכן \"הוא צפה במשהו רגוע\" עדיין נגמר לא פעם רע: גם תוכן עדין, כשהוא מוגש עם ניגון אוטומטי ואור בהיר, משאיר את המערכת רכונה קדימה במקום נשענת אחורה.\n\nספרות השינה מוסיפה ממצא עקבי נוסף שמפתיע הורים רבים: עצם הנוכחות של מכשיר בחדר השינה נקשרת לשינה גרועה יותר אצל ילדים — שעות שינה מאוחרות יותר, לילות קצרים יותר — גם כשהוא כביכול כבוי. מסך בהישג יד הוא הזמנה מתמדת, וילדים יודעים איפה גרות ההזמנות. הטענת טלפונים וטאבלטים מחוץ לחדר השינה, לכל המשפחה, מבטלת את המשא ומתן לגמרי.\n\nשום דבר מזה לא דורש חרם מסכים ביתי — רק דפוס נחיתה. כוונו לחיץ של בערך שעה בין המסך האחרון לכיבוי אורות, ומלאו אותו במכונה המשעממת והאהובה של שעת השינה: אמבטיה, פיג'מה, ספרים, שיחה. אם הערבים רצים כרגע ממסך למיטה, הזיזו את שעת הסיום מוקדם יותר בצעדים של רבע שעה במקום בבת אחת, וצפו לכמה ערבי מחאה כשהשגרה עוברת משא ומתן מחודש. עמעמו גם את אורות הבית בשעה האחרונה — סיפור המלטונין הוא על כל אור הערב, ומנורות חמות ונמוכות משחקות בקבוצה של השינה."
    ),
    tryToday: L(
      "Tonight, end screens one hour before lights-out and dim the living room when they go off. Put the tablet to bed in the kitchen — visibly, like a ritual.",
      "הערב, סיימו מסכים שעה לפני כיבוי אורות ועמעמו את הסלון כשהם נכבים. השכיבו את הטאבלט לישון במטבח — בגלוי, כמו טקס."
    ),
    ask: L("Help me redesign our last hour before bed without screens.", "עזור לי לתכנן מחדש את השעה האחרונה שלנו לפני השינה בלי מסכים."),
  },
  {
    id: "bedtime-stalling",
    category: "sleep",
    domains: ["independence_adaptive_skills"],
    ageMin: 2,
    ageMax: 8,
    minutes: 3,
    concerns: ["sleep", "routines"],
    title: L("Curtain calls: bedtime stalling decoded", "הדרן: פענוח סחבת של שעת השינה"),
    hook: L("One more water, one more hug, one more urgent fact about dinosaurs — stalling is a strategy, and it responds to design.", "עוד מים, עוד חיבוק, עוד עובדה דחופה על דינוזאורים — הסחבת היא אסטרטגיה, והיא מגיבה לתכנון."),
    keyPoints: [
      L("Sleep researchers literally call them 'curtain calls' — the encore requests after lights-out — and they're one of the most common bedtime patterns in early childhood.", "חוקרי שינה באמת קוראים לזה 'הדרן' — בקשות הביס אחרי כיבוי אורות — וזה אחד מדפוסי השינה הנפוצים ביותר בילדות המוקדמת."),
      L("The requests are rarely about water: bedtime is the day's biggest separation, and stalling usually buys connection, control, or delay of being alone.", "הבקשות כמעט אף פעם לא באמת על מים: שעת השינה היא הפרידה הגדולה של היום, וסחבת קונה בדרך כלל קרבה, שליטה, או דחייה של להישאר לבד."),
      L("Front-load what the child is fishing for: unhurried one-on-one connection inside the routine shrinks the need to chase it afterwards.", "הקדימו את מה שהילד מחפש: קרבה רגועה אחד־על־אחד בתוך השגרה מכווצת את הצורך לרדוף אחריה אחר כך."),
      L("Close the known loops in advance — water bottle by the bed, bathroom last stop, 'what's tomorrow' answered — so the classic requests are pre-satisfied.", "סגרו מראש את הלולאות המוכרות — בקבוק מים ליד המיטה, שירותים כתחנה אחרונה, \"מה יש מחר\" עם תשובה — כך שהבקשות הקלאסיות מסופקות מראש."),
      L("A bedtime pass — one card, redeemable for one extra request per night — converts endless testing into a single, child-controlled choice.", "כרטיס לילה — קלף אחד, שווה בקשה נוספת אחת בלילה — הופך בדיקות אינסופיות לבחירה אחת שבשליטת הילד."),
    ],
    body: L(
      "Ten minutes after goodnight, the door opens. Water. Then a hug. Then a sock feels wrong. Then a question about whether jellyfish sleep. Sleep researchers have a name for this nightly encore — curtain calls — and its familiarity across households should be the first comfort: this is one of the most ordinary bedtime patterns of early childhood, not a discipline failure and not insomnia.\n\nDecoding it helps more than fighting it. Bedtime is the longest separation of a young child's day, arriving exactly when their reserves are lowest. Most curtain calls are bids — for connection, for a little control over an experience they didn't choose, or simply for postponing the moment of being alone in the dark. The child asking for a fourth glass of water is rarely thirsty; they're negotiating nearness with the vocabulary available. Seeing it that way changes the parental job from 'defeating requests' to 'meeting the need earlier in the evening, on purpose.'\n\nTwo structural moves do most of the work. First, front-load the connection: ten unhurried minutes inside the routine — books, talk about the day, the same questions in the same order — often shrink the after-hours chase, because the tank is already full. Predictability itself is soothing; a routine that runs the same way each night tells the nervous system what's coming. Second, close the loops before lights-out: water bottle already by the bed, bathroom as the fixed last stop, tomorrow's plan spoken aloud. Each pre-answered request is one fewer door opening.\n\nFor persistent stallers, the bedtime pass — a small card the child may trade for one extra request per night, no questions asked — has real research behind it and a certain elegance: it grants the control the child was fishing for, caps the total, and turns each request into a spending decision. Many children hoard the pass proudly and stop using it. Then hold the boundary warmly and identically: brief, boring returns to bed, the same six words every time. Consistency, not sternness, is what finally lowers the curtain — and if stalling comes wrapped in intense nightly distress that doesn't ease over weeks, that's a pattern worth describing to your pediatrician in plain observational terms.",
      "עשר דקות אחרי לילה טוב, הדלת נפתחת. מים. אחר כך חיבוק. אחר כך גרב מרגיש לא נכון. אחר כך שאלה אם מדוזות ישנות. לחוקרי שינה יש שם להדרן הלילי הזה — curtain calls — והשכיחות שלו בכל כך הרבה בתים היא הנחמה הראשונה: זה אחד מדפוסי השינה הרגילים ביותר של הילדות המוקדמת, לא כישלון חינוכי ולא נדודי שינה.\n\nלפענח עוזר יותר מלהילחם. שעת השינה היא הפרידה הארוכה ביותר ביום של ילד צעיר, והיא מגיעה בדיוק כשהמאגרים שלו בשפל. רוב ההדרנים הם הצעות התקשרות — לקרבה, לקצת שליטה בחוויה שהוא לא בחר, או פשוט לדחיית הרגע של להיות לבד בחושך. הילד שמבקש כוס מים רביעית כמעט אף פעם לא צמא; הוא מנהל משא ומתן על קרבה באוצר המילים הזמין לו. לראות את זה כך משנה את תפקיד ההורה מ'להביס בקשות' ל'לפגוש את הצורך מוקדם יותר בערב, בכוונה'.\n\nשני מהלכים מבניים עושים את רוב העבודה. ראשית, הקדימו את הקרבה: עשר דקות רגועות בתוך השגרה — ספרים, שיחה על היום, אותן שאלות באותו סדר — מכווצות לא פעם את המרדף שאחרי, כי המכל כבר מלא. הצפיוּת עצמה מרגיעה; שגרה שרצה אותו דבר כל ערב מספרת למערכת העצבים מה בא עכשיו. שנית, סגרו את הלולאות לפני כיבוי אורות: בקבוק מים כבר ליד המיטה, שירותים כתחנה אחרונה קבועה, תוכנית המחר נאמרת בקול. כל בקשה שנענתה מראש היא דלת אחת פחות שנפתחת.\n\nלסחבנים עקשנים, כרטיס הלילה — קלף קטן שהילד רשאי להחליף בבקשה נוספת אחת בלילה, בלי שאלות — נשען על מחקר אמיתי ויש בו אלגנטיות מסוימת: הוא מעניק את השליטה שהילד חיפש, מגביל את הסכום, והופך כל בקשה להחלטת הוצאה. ילדים רבים אוגרים את הקלף בגאווה ומפסיקים להשתמש בו. ואז החזיקו את הגבול בחום ובאופן זהה: החזרות למיטה קצרות ומשעממות, אותן שש מילים בכל פעם. עקביות, לא חומרה, היא מה שמוריד לבסוף את המסך — ואם הסחבת עטופה במצוקה לילית עזה שלא מתרככת לאורך שבועות, זה דפוס ששווה לתאר לרופא הילדים במילים תצפיתיות פשוטות."
    ),
    tryToday: L(
      "Make a bedtime pass together this afternoon — let your child decorate the card. Tonight it buys exactly one encore. Watch how they spend it.",
      "הכינו יחד כרטיס לילה אחר הצהריים — תנו לילד לקשט את הקלף. הערב הוא שווה בדיוק הדרן אחד. ראו איך הוא מוציא אותו."
    ),
    ask: L("What should my bedtime routine include so the stalling stops?", "מה כדאי שטקס השינה שלנו יכלול כדי שהסחבת תיפסק?"),
  },

  // ── Play & Learning ──────────────────────────────────────────────────────
  {
    id: "music-and-brain",
    category: "play",
    domains: ["cognition_executive_function", "language_communication"],
    ageMin: 0,
    ageMax: 8,
    minutes: 3,
    title: L("Music and the developing brain", "מוזיקה והמוח המתפתח"),
    hook: L("Forget the myth about symphonies raising IQ — the real story, making music together, is better and much cheaper.", "שכחו את המיתוס על סימפוניות שמעלות איי־קיו — הסיפור האמיתי, לעשות מוזיקה יחד, טוב יותר וזול בהרבה."),
    keyPoints: [
      L("The famous 'Mozart effect' didn't survive scrutiny — passive listening isn't a brain upgrade, and no soundtrack purchase is required.", "'אפקט מוצרט' המפורסם לא שרד את הביקורת — האזנה סבילה אינה שדרוג מוח, ואין צורך לקנות שום פסקול."),
      L("What research does keep finding: active music-making — singing, clapping, moving to a beat — is associated with growth in the same auditory skills language depends on.", "מה שהמחקר כן מוצא שוב ושוב: עשיית מוזיקה פעילה — שירה, מחיאות כפיים, תנועה לפי קצב — נקשרת לצמיחה באותן מיומנויות שמיעה שהשפה נשענת עליהן."),
      L("Rhythm and speech share machinery: keeping a beat draws on the timing skills involved in parsing syllables, and studies associate the two across childhood.", "קצב ודיבור חולקים מנגנון: לשמור על ביט מפעיל את מיומנויות התזמון שמעורבות בפירוק הברות, ומחקרים קושרים בין השניים לאורך הילדות."),
      L("Songs are language delivered in slow motion — stretched vowels, repeated lines, rhyme — which is why lullabies and nursery songs double as speech practice.", "שירים הם שפה בהילוך איטי — תנועות מתארכות, שורות חוזרות, חרוזים — ולכן שירי ערש ושירי ילדים הם גם אימון דיבור."),
      L("Your untrained voice is the ideal instrument: babies prefer their parent's live, imperfect singing to any recording.", "הקול הלא־מאומן שלכם הוא הכלי האידיאלי: תינוקות מעדיפים את השירה החיה והלא־מושלמת של ההורה על כל הקלטה."),
    ],
    body: L(
      "The 1990s left parents a strange inheritance: the idea that playing classical music at a baby upgrades their intelligence. The original 'Mozart effect' study involved college students, a spatial task, and an effect lasting minutes; the leap to baby albums was marketing, and later research didn't back it up. That's the myth cleared. What's left is a genuinely rich story — but it runs through participation, not playback.\n\nWhen researchers look at children who actively make music — sing, drum, clap games, bounce to a beat, eventually play instruments — they consistently find associations with sharpened auditory processing: the brain gets better at noticing fine differences in sound, timing and pitch. Those are not niche musical skills. They are the same raw abilities speech comprehension is built from, which is why studies keep finding links between early rhythm skills and language development, including the sound-awareness skills that later feed reading. Music, in this picture, is ear training for language — done as a game.\n\nSongs themselves are engineered for young learners, and every culture seems to have discovered this independently. Sung language slows down, stretches its vowels, repeats its structures and rhymes its endings — exactly the exaggerations that make word boundaries easier for a small brain to find. A child who knows twenty songs has rehearsed hundreds of words with melody as the memory aid. And the emotional layer matters just as much: infants relax to lullabies, prefer their own parent's voice to polished recordings, and treat shared songs as a form of connection. Singing to a baby is regulation and language lesson in one act.\n\nThe practical program is almost embarrassingly simple. Sing — in whatever voice you have, in any language you love. Keep beats with hands, spoons and knees. Make up rhyming nonsense in the bath. Put on music you enjoy and dance in the kitchen. If your child later wants lessons, lovely — instrument learning has its own associations with attention and perseverance — but the foundation is laid for free, by families who treat music as something you do together rather than something you buy.",
      "שנות התשעים הורישו להורים ירושה מוזרה: הרעיון שהשמעת מוזיקה קלאסית לתינוק משדרגת את האינטליגנציה שלו. המחקר המקורי של 'אפקט מוצרט' עסק בסטודנטים, במטלה מרחבית ובאפקט שנמשך דקות; הקפיצה לאלבומי תינוקות הייתה שיווק, ומחקרי המשך לא גיבו אותה. זה המיתוס, מסולק. מה שנשאר הוא סיפור עשיר באמת — אבל הוא עובר דרך השתתפות, לא דרך השמעה.\n\nכשחוקרים מסתכלים על ילדים שעושים מוזיקה באופן פעיל — שרים, מתופפים, משחקי מחיאות, מקפצים לפי ביט, ובהמשך מנגנים — הם מוצאים בעקביות קשרים לחידוד העיבוד השמיעתי: המוח נעשה טוב יותר בהבחנה בהבדלים עדינים של צליל, תזמון וגובה. אלה אינן מיומנויות מוזיקליות נישתיות. אלה בדיוק היכולות הגולמיות שהבנת דיבור בנויה מהן, ולכן מחקרים מוצאים שוב ושוב קשרים בין מיומנויות קצב מוקדמות להתפתחות שפה, כולל מודעות הצלילים שמזינה בהמשך את הקריאה. מוזיקה, בתמונה הזאת, היא אימון אוזניים לשפה — בצורת משחק.\n\nשירים עצמם מהונדסים ללומדים צעירים, ונדמה שכל תרבות גילתה זאת בנפרד. שפה מושרת מאטה, מותחת את התנועות, חוזרת על מבנים וחורזת את הסופים — בדיוק ההגזמות שמקלות על מוח קטן למצוא גבולות של מילים. ילד שמכיר עשרים שירים חזר על מאות מילים כשהמנגינה משמשת עוגן זיכרון. והשכבה הרגשית חשובה לא פחות: תינוקות נרגעים לשירי ערש, מעדיפים את קול ההורה שלהם על הקלטות מלוטשות, ומתייחסים לשירים משותפים כאל צורת קרבה. לשיר לתינוק זה ויסות ושיעור שפה במעשה אחד.\n\nהתוכנית המעשית פשוטה כמעט במבוכה. שירו — בקול שיש לכם, בכל שפה שאתם אוהבים. שמרו על קצב עם ידיים, כפיות וברכיים. המציאו שטויות מחורזות באמבטיה. שימו מוזיקה שאתם נהנים ממנה ורקדו במטבח. אם הילד ירצה בהמשך חוגים — נהדר; ללמידת כלי נגינה יש קשרים משלה עם קשב והתמדה — אבל היסוד מונח בחינם, על ידי משפחות שמתייחסות למוזיקה כאל משהו שעושים יחד ולא כאל משהו שקונים."
    ),
    tryToday: L(
      "Pick one daily transition — teeth, car seat, cleanup — and give it a song, invented or borrowed. Same tune every time. Watch it start doing the work for you.",
      "בחרו מעבר יומי אחד — שיניים, כיסא בטיחות, סידור — ותנו לו שיר, מומצא או מושאל. אותה מנגינה בכל פעם. ראו איך הוא מתחיל לעבוד בשבילכם."
    ),
    ask: L("Give me five musical games I can play with my child at their age.", "תן לי חמישה משחקים מוזיקליים שאפשר לשחק עם הילד בגיל שלו."),
  },
  {
    id: "process-over-product",
    category: "play",
    domains: ["cognition_executive_function"],
    ageMin: 2,
    ageMax: 8,
    minutes: 3,
    title: L("Process over product in children's art", "תהליך לפני תוצר ביצירה של ילדים"),
    hook: L("The brown swirl that used to be six colors did its job perfectly — the making was the point, not the fridge.", "המערבולת החומה שהייתה פעם שישה צבעים עשתה את עבודתה בשלמות — העשייה הייתה העיקר, לא המקרר."),
    keyPoints: [
      L("Early-childhood educators distinguish process art (open materials, no model to copy) from product crafts (everyone assembles the same ladybug) — and the developmental action is in the process.", "אנשי חינוך לגיל הרך מבחינים בין יצירת תהליך (חומרים פתוחים, בלי דגם להעתיק) לבין מלאכת תוצר (כולם מרכיבים את אותה חיפושית) — והפעולה ההתפתחותית נמצאת בתהליך."),
      L("While making, children are running experiments: what mixes, what drips, what tears, what happens if — planning, testing and revising in miniature.", "תוך כדי יצירה ילדים מריצים ניסויים: מה מתערבב, מה מטפטף, מה נקרע, מה קורה אם — תכנון, בדיקה ותיקון בזעיר אנפין."),
      L("Scribbles have a developmental arc of their own, from motion-for-its-own-sake toward shapes and symbols — each stage worth having, none worth rushing.", "לשרבוטים יש קשת התפתחותית משלהם, מתנועה לשם עצמה אל צורות וסמלים — כל שלב שווה קיום, אף שלב לא שווה זירוז."),
      L("'What is it?' is a trick question — often it isn't anything. 'Tell me about your picture' or naming what you see ('so many red circles!') opens more.", "\"מה זה?\" היא שאלה מכשילה — לעיתים קרובות זה לא כלום. \"ספרו לי על הציור\" או תיאור של מה שרואים (\"כמה עיגולים אדומים!\") פותחים יותר."),
      L("Correcting, finishing or 'fixing' a child's work teaches one lesson above all: there was a right answer and you missed it.", "לתקן, להשלים או 'לסדר' יצירה של ילד מלמד שיעור אחד מעל כולם: הייתה תשובה נכונה, ופספסת אותה."),
    ],
    body: L(
      "Two tables at a preschool. At one, children follow steps to assemble identical paper ladybugs — precut circles, dots where the dots go. At the other, there's paint, paper, glue, string and no instructions. The ladybug table produces better refrigerator material. Early-childhood educators will tell you the other table is where the development happens, and the distinction has a name: product versus process art.\n\nWatch a child deep in process work and you can see the cognition running. Mixing colors is an experiment with a result. Gluing a heavy button to a vertical surface is an engineering problem. Deciding the picture needs 'more' — and then deciding it's done — is planning, evaluation and an early act of taste. Because there's no model to match, there's no way to fail, which keeps the child in the productive zone where they take risks and revise. A craft with one right outcome teaches following instructions (a fine skill, honestly acquired elsewhere); open materials exercise the generating, testing and deciding that educators group under executive function and creativity.\n\nThe marks themselves grow through a well-described arc. Toddler scribbling starts as pure motion — the discovery that arms leave traces. Circles and radiating suns emerge, then the beloved head-with-legs people, then intentional symbols: a child drawing what they know, not what they see. The ages vary widely and the sequence is not a race; each stage is doing its own work, and a child left to scribble abundantly tends to arrive at symbols with more to say.\n\nThe adult role is curator of materials and audience, not art director. Offer varied stuff — crayons, chalk, dough, junk-box treasures — and protect it from your own helpful hands: every well-meant correction ('suns are yellow, sweetie') teaches that there was a right answer after all. Skip 'what is it?', which assumes representation where there may be none; try 'tell me about your picture,' or simply describe — 'you covered every corner.' And praise the verbs, not the artifact: the mixing, the trying, the sticking-with-it. That's the part they'll reuse everywhere else.",
      "שני שולחנות בגן. באחד, ילדים עוקבים אחרי שלבים ומרכיבים חיפושיות נייר זהות — עיגולים גזורים מראש, נקודות איפה שהנקודות אמורות להיות. בשני יש צבעים, נייר, דבק, חוטים — ואין הוראות. שולחן החיפושיות מייצר חומר טוב יותר למקרר. אנשי חינוך לגיל הרך יגידו לכם שהשולחן השני הוא המקום שבו קורית ההתפתחות, ולהבחנה יש שם: יצירת תוצר מול יצירת תהליך.\n\nהתבוננו בילד שקוע בעבודת תהליך ותוכלו לראות את הקוגניציה רצה. ערבוב צבעים הוא ניסוי עם תוצאה. הדבקת כפתור כבד למשטח אנכי היא בעיה הנדסית. להחליט שהציור צריך 'עוד' — ואז להחליט שהוא גמור — זה תכנון, הערכה ומעשה טעם מוקדם. מכיוון שאין דגם להשוות אליו, אין דרך להיכשל, וזה משאיר את הילד באזור הפורה שבו לוקחים סיכונים ומתקנים. מלאכה עם תוצאה נכונה אחת מלמדת לעקוב אחרי הוראות (מיומנות בסדר גמור, שנרכשת ביושר במקומות אחרים); חומרים פתוחים מאמנים את ההמצאה, הבדיקה וההכרעה שאנשי חינוך מקבצים תחת תפקודים ניהוליים ויצירתיות.\n\nהסימנים עצמם צומחים דרך קשת מתוארת היטב. שרבוט של פעוטות מתחיל כתנועה טהורה — הגילוי שידיים משאירות עקבות. עיגולים ושמשות קורנות מופיעים, אחר כך אנשי הראש־עם־רגליים האהובים, ואז סמלים מכוונים: ילד שמצייר את מה שהוא יודע, לא את מה שהוא רואה. הגילאים משתנים מאוד והרצף אינו מרוץ; כל שלב עושה את עבודתו, וילד שהורשה לשרבט בשפע מגיע בדרך כלל לסמלים עם יותר מה לומר.\n\nתפקיד המבוגר הוא אוצֵר חומרים וקהל, לא במאי אמנותי. הציעו מגוון — צבעי פנדה, גירים, בצק, אוצרות מקופסת גרוטאות — והגנו עליו מהידיים העוזרות של עצמכם: כל תיקון שנעשה מכוונה טובה (\"שמש היא צהובה, מתוקה\") מלמד שבכל זאת הייתה תשובה נכונה. ותרו על \"מה זה?\", שמניחה ייצוג במקום שבו אולי אין כזה; נסו \"ספרו לי על הציור\", או פשוט תארו — \"כיסית כל פינה.\" ושבחו את הפעלים, לא את החפץ: את הערבוב, את הניסיון, את ההתמדה. זה החלק שהם ייקחו איתם לכל מקום אחר."
    ),
    tryToday: L(
      "Put out paper and any three materials with zero instructions. When something emerges, say only \"tell me about it\" — and let the answer be the whole review.",
      "הניחו נייר ושלושה חומרים כלשהם בלי שום הוראות. כשמשהו נוצר, אמרו רק \"ספרו לי עליו\" — ותנו לתשובה להיות כל הביקורת."
    ),
    ask: L("What open-ended art materials suit my child's age and our small apartment?", "אילו חומרי יצירה פתוחים מתאימים לגיל של הילד ולדירה הקטנה שלנו?"),
  },

  // ── Screens & Digital ────────────────────────────────────────────────────
  {
    id: "quality-over-quantity",
    category: "screens",
    domains: ["ecosystem_stressors"],
    ageMin: 1,
    ageMax: 8,
    minutes: 3,
    concerns: ["screens"],
    title: L("Judging content: quality beats quantity", "לשפוט תוכן: איכות מנצחת כמות"),
    hook: L("Thirty minutes of what matters more than sixty versus forty — here's how to judge an episode in two minutes of watching.", "שלושים דקות של מה חשובות יותר משישים מול ארבעים — כך שופטים פרק בשתי דקות צפייה."),
    keyPoints: [
      L("Research on children's media increasingly points past the stopwatch: what plays and with whom is associated more strongly with outcomes than raw minutes.", "מחקר על מדיה לילדים מצביע יותר ויותר מעבר לסטופר: מה מוקרן ועם מי נקשר לתוצאות חזק יותר ממספר דקות גולמי."),
      L("Pacing is the first tell: slow scenes, real pauses and room to think versus rapid cuts and constant noise built to hold the eye.", "הקצב הוא הסימן הראשון: סצנות איטיות, שהיות אמיתיות ומקום לחשוב מול חיתוכים מהירים ורעש מתמיד שנבנו להחזיק את העין."),
      L("Story beats stimulation: content with characters, problems and feelings gives a child something to carry away; pure spectacle leaves nothing behind.", "סיפור מנצח גירוי: תוכן עם דמויות, בעיות ורגשות נותן לילד משהו לקחת איתו; ראווה טהורה לא משאירה כלום."),
      L("Participation is a quality marker — programs that ask, pause and wait for the child's answer treat viewers as conversation partners, not targets.", "השתתפות היא סימן איכות — תוכניות ששואלות, עוצרות ומחכות לתשובת הילד מתייחסות לצופים כאל שותפי שיחה, לא כאל מטרות."),
      L("Brands and 'educational' labels guarantee nothing; two minutes of watching alongside your child tells you more than any thumbnail.", "מותגים ותוויות 'חינוכי' לא מבטיחים דבר; שתי דקות צפייה לצד הילד מספרות לכם יותר מכל תמונה ממוזערת."),
    ],
    body: L(
      "The family screen conversation is usually conducted in minutes — how many, starting when, ending with which fight. But when researchers pull children's media apart, the stopwatch keeps turning out to be the crudest variable in the room. Studies repeatedly associate outcomes less with total minutes than with what was playing and whether an adult was involved. An hour of slow, story-rich, participatory content co-watched with a parent and an hour of frantic algorithmic filler are both 'one hour of screen time,' and that phrase hides everything that mattered.\n\nSo how does a busy parent judge quality without a media-studies degree? A few tells do most of the work. Pacing first: high-quality children's content moves at the speed of a child's thought — scenes last, characters pause, silence exists. Content engineered for retention moves at the speed of a flinch: cuts every second or two, relentless sound, novelty stacked on novelty so the eye can't leave. Watch two minutes with the sound off and you can often classify a show by cuts alone. Then story: is there a character who wants something, a problem, a feeling named and resolved? Narrative gives a child material to replay, retell and ask about at dinner. Spectacle without story is closer to a slot machine than a book.\n\nThe third marker is respect for the viewer. The best children's programming asks the child questions and actually waits; it assumes a mind on the other side. And notice what the content is selling — shows built around characters whose toys fill a store aisle, or 'kids' videos' that are really unboxing ads, have a business model where your child is the product being developed.\n\nNone of this requires prescreening everything. Sit in for the first two minutes of anything new; you'll know. Keep a short 'yes list' of shows that pass, so the choice at screen time is between three good options rather than an open feed. And let quality do double duty: content worth watching is content worth talking about afterwards, and those two minutes of conversation are where an episode turns into language, questions and shared jokes — the residue that good media leaves behind.",
      "שיחת המסכים המשפחתית מתנהלת בדרך כלל בדקות — כמה, ממתי, ונגמרת באיזה ריב. אבל כשחוקרים מפרקים מדיה לילדים לגורמים, הסטופר מתגלה שוב ושוב כמשתנה הגס בחדר. מחקרים קושרים תוצאות פחות לסך הדקות ויותר למה שהוקרן ולשאלה אם מבוגר היה מעורב. שעה של תוכן איטי, עשיר בסיפור ומשתף שנצפית יחד עם הורה ושעה של מילוי אלגוריתמי קדחתני הן שתיהן 'שעת מסך', והביטוי הזה מסתיר את כל מה שחשוב.\n\nאז איך הורה עסוק שופט איכות בלי תואר בלימודי מדיה? כמה סימנים עושים את רוב העבודה. קודם כול קצב: תוכן ילדים איכותי נע במהירות המחשבה של ילד — סצנות נמשכות, דמויות עוצרות, שקט קיים. תוכן שהונדס לשימור נע במהירות של רתיעה: חיתוך כל שנייה־שתיים, סאונד בלתי פוסק, חידוש על גבי חידוש כדי שהעין לא תוכל לעזוב. צפו שתי דקות בלי קול ולעיתים קרובות תוכלו לסווג תוכנית לפי החיתוכים בלבד. אחר כך סיפור: יש דמות שרוצה משהו, בעיה, רגש שנקרא בשמו ונפתר? נרטיב נותן לילד חומר לשחזר, לספר מחדש ולשאול עליו בארוחת ערב. ראווה בלי סיפור קרובה יותר למכונת מזל מאשר לספר.\n\nהסימן השלישי הוא כבוד לצופה. תוכניות הילדים הטובות ביותר שואלות את הילד שאלות ובאמת מחכות; הן מניחות שיש מוח בצד השני. ושימו לב מה התוכן מוכר — תוכניות שבנויות סביב דמויות שהצעצועים שלהן ממלאים מעבר בחנות, או 'סרטוני ילדים' שהם בעצם פרסומות פתיחת־קופסאות, פועלות לפי מודל עסקי שבו הילד שלכם הוא המוצר שבפיתוח.\n\nשום דבר מזה לא דורש צפייה מוקדמת בהכול. שבו בשתי הדקות הראשונות של כל דבר חדש; תדעו. החזיקו 'רשימת כן' קצרה של תוכניות שעברו, כך שהבחירה בזמן מסך היא בין שלוש אפשרויות טובות ולא פיד פתוח. ותנו לאיכות לעבוד פעמיים: תוכן ששווה צפייה הוא תוכן ששווה שיחה אחריו, ושתי דקות השיחה האלה הן המקום שבו פרק הופך לשפה, לשאלות ולבדיחות משותפות — המשקע שמדיה טובה משאירה אחריה."
    ),
    tryToday: L(
      "Audit your child's current favorite: watch two minutes, count the cuts, look for a story and a question aimed at the viewer. Decide if it makes the yes list.",
      "עשו ביקורת לתוכנית האהובה הנוכחית: צפו שתי דקות, ספרו חיתוכים, חפשו סיפור ושאלה שמופנית לצופה. החליטו אם היא נכנסת לרשימת הכן."
    ),
    ask: L("Help me build a short \"yes list\" of quality shows for my child's age.", "עזור לי לבנות \"רשימת כן\" קצרה של תוכניות איכותיות לגיל של הילד שלי."),
  },
  {
    id: "autoplay-design",
    category: "screens",
    domains: ["ecosystem_stressors"],
    ageMin: 2,
    ageMax: 10,
    minutes: 3,
    concerns: ["screens"],
    title: L("Autoplay and the design tricks aimed at kids", "ניגון אוטומטי ותרגילי העיצוב שמכוונים לילדים"),
    hook: L("Your child isn't losing a battle of willpower at the screen — they're playing against professionals. Know the tricks and you can bench most of them.", "הילד שלכם לא מפסיד בקרב כוח רצון מול המסך — הוא משחק נגד מקצוענים. הכירו את התרגילים ותוכלו להוציא את רובם מהמגרש."),
    keyPoints: [
      L("Persuasive design is a discipline: autoplay, endless feeds, streaks and reward loops are engineered choices whose success metric is your child's continued attention.", "עיצוב משכנע הוא דיסציפלינה: ניגון אוטומטי, פידים אינסופיים, רצפים ולולאות תגמול הם בחירות הנדסיות שמדד ההצלחה שלהן הוא המשך הקשב של הילד שלכם."),
      L("Autoplay deletes the decision point: the next episode starts before 'should we stop?' can be asked — which is precisely its job.", "ניגון אוטומטי מוחק את נקודת ההחלטה: הפרק הבא מתחיל לפני שאפשר לשאול \"אולי נפסיק?\" — וזה בדיוק תפקידו."),
      L("Variable rewards — surprise eggs, loot boxes, mystery spins — borrow the unpredictability pattern that makes slot machines gripping for adults.", "תגמולים משתנים — ביצי הפתעה, תיבות שלל, גלגלי מזל — שואלים את דפוס אי־הצפיות שהופך מכונות מזל למהפנטות עבור מבוגרים."),
      L("Streaks and daily bonuses convert absence into loss, recruiting loss-aversion to manufacture obligation in players who can't yet name the feeling.", "רצפים ובונוסים יומיים הופכים היעדרות להפסד, ומגייסים שנאת הפסד כדי לייצר מחויבות אצל שחקנים שעוד לא יודעים לקרוא לתחושה בשם."),
      L("Most tricks have an off switch — autoplay toggles, notification settings, no-ads versions — and naming the trick out loud ('it started by itself!') builds the child's own defense.", "לרוב התרגילים יש כפתור כיבוי — מתגי ניגון אוטומטי, הגדרות התראות, גרסאות בלי פרסומות — ולומר את שם התרגיל בקול (\"זה התחיל לבד!\") בונה את ההגנה של הילד עצמו."),
    ],
    body: L(
      "There's a moment worth reframing: the child who 'can't stop watching' or melts down when the tablet closes. The instinct is to read it as a willpower deficit or a discipline gap. The fairer reading is that your child is in an asymmetric contest — on one side a developing brain whose impulse control is under construction; on the other, product teams whose explicit job is maximizing time-on-app. The techniques have a name in the industry — persuasive design — and children's products use them liberally.\n\nA short field guide. Autoplay removes the natural decision point at the end of an episode; the next one begins before a choice can occur, which is exactly the design goal. Endless feeds do the same trick continuously — there is no bottom, so there is no 'done.' Variable rewards — surprise eggs, mystery boxes, random prize wheels — deliver the unpredictable-payoff pattern behind slot machines; not knowing what's next is the hook itself. Streaks and daily login bonuses weaponize loss aversion: skip a day and something breaks, so absence starts to feel like punishment. Add countdown timers, nagging characters who 'miss you,' and purchase prompts placed where small thumbs wander, and the picture is complete. None of this is accidental, and none of it is your child's fault — or yours.\n\nThe good news is that much of the machinery has an off switch. Disabling autoplay in each app restores the seam between episodes — arguably the single highest-value setting change in family tech. Notifications from children's apps can simply be off. Paid or ad-free versions of a beloved app often remove the most aggressive prompts. Curated services and downloaded playlists beat open feeds, because a bounded shelf has an end. Ten minutes in settings buys back a surprising amount of evening.\n\nThe deeper play is teaching the trick itself. From around four or five, children can grasp 'the app started the next one by itself so you'd keep watching — sneaky, right?' Spotting manipulation together turns your child from target into critic, and children often relish catching the app red-handed. That noticing muscle — 'someone built this to keep me here' — is the beginning of media literacy, and it will matter long after the tablet years.",
      "יש רגע ששווה למסגר מחדש: הילד ש'לא מסוגל להפסיק לצפות' או מתפרק כשהטאבלט נסגר. האינסטינקט הוא לקרוא את זה כגירעון בכוח רצון או כפער בחינוך. הקריאה ההוגנת יותר היא שהילד שלכם נמצא בתחרות לא סימטרית — בצד אחד מוח מתפתח שבקרת הדחפים שלו עוד בבנייה; בצד השני צוותי מוצר שתפקידם המוצהר הוא למקסם זמן באפליקציה. לטכניקות יש שם בתעשייה — עיצוב משכנע — ומוצרים לילדים משתמשים בהן ביד רחבה.\n\nמדריך שדה קצר. ניגון אוטומטי מסיר את נקודת ההחלטה הטבעית בסוף פרק; הבא מתחיל לפני שבחירה יכולה לקרות, וזו בדיוק מטרת העיצוב. פידים אינסופיים עושים את אותו תרגיל ברציפות — אין תחתית, אז אין 'סיימנו'. תגמולים משתנים — ביצי הפתעה, תיבות מסתורין, גלגלי פרסים אקראיים — מספקים את דפוס התגמול הבלתי צפוי שמאחורי מכונות מזל; לא לדעת מה הבא הוא־הוא הקרס. רצפים ובונוסי כניסה יומיים מנצלים שנאת הפסד: דלגו יום ומשהו נשבר, כך שהיעדרות מתחילה להרגיש כמו עונש. הוסיפו טיימרים של ספירה לאחור, דמויות נודניקיות ש'מתגעגעות אליך', וכפתורי רכישה במקומות שאגודלים קטנים משוטטים בהם — והתמונה שלמה. שום דבר מזה אינו מקרי, ושום דבר מזה אינו אשמת הילד — או שלכם.\n\nהחדשות הטובות: לחלק גדול מהמכונה יש כפתור כיבוי. ביטול הניגון האוטומטי בכל אפליקציה מחזיר את התפר בין פרקים — אולי שינוי ההגדרה בעל הערך הגבוה ביותר בטכנולוגיה משפחתית. התראות מאפליקציות ילדים יכולות פשוט להיות כבויות. גרסאות בתשלום או בלי פרסומות של אפליקציה אהובה מסירות לרוב את הדחיפות האגרסיביות ביותר. שירותים אצורים ורשימות מורדות מנצחים פידים פתוחים, כי למדף תחום יש סוף. עשר דקות בהגדרות קונות בחזרה כמות מפתיעה של ערב.\n\nהמהלך העמוק יותר הוא ללמד את התרגיל עצמו. בערך מגיל ארבע־חמש, ילדים מסוגלים לתפוס \"האפליקציה התחילה את הבא לבד כדי שתמשיך לצפות — חמקני, נכון?\". לזהות מניפולציה יחד הופך את הילד ממטרה למבקר, וילדים לרוב מתענגים על לתפוס את האפליקציה על חם. שריר ההבחנה הזה — \"מישהו בנה את זה כדי להשאיר אותי כאן\" — הוא תחילתה של אוריינות מדיה, והוא יהיה חשוב הרבה אחרי שנות הטאבלט."
    ),
    tryToday: L(
      "Open the settings of your child's two most-used apps and turn off autoplay and notifications. Then show your child what you did and why — make them a co-conspirator.",
      "פתחו את ההגדרות של שתי האפליקציות הכי בשימוש אצל הילד וכבו ניגון אוטומטי והתראות. ואז הראו לילד מה עשיתם ולמה — הפכו אותו לשותף לקנוניה."
    ),
    ask: L("Which settings should I change on our apps to remove the stickiest design tricks?", "אילו הגדרות כדאי לי לשנות באפליקציות שלנו כדי להסיר את תרגילי העיצוב הדביקים ביותר?"),
  },
  {
    id: "media-literacy-early",
    category: "screens",
    domains: ["ecosystem_stressors", "cognition_executive_function"],
    ageMin: 4,
    ageMax: 10,
    minutes: 3,
    concerns: ["screens"],
    title: L("Early media literacy: \"who made this and why?\"", "אוריינות מדיה מוקדמת: \"מי עשה את זה ולמה?\""),
    hook: L("You can't preview everything your child will ever watch — but you can install the question that travels with them.", "אי אפשר לצפות מראש בכל מה שהילד אי פעם יראה — אבל אפשר להתקין את השאלה שנוסעת איתו."),
    keyPoints: [
      L("Media literacy at this age is one portable habit — asking 'who made this, and what do they want?' — not a curriculum.", "אוריינות מדיה בגיל הזה היא הרגל נייד אחד — לשאול \"מי עשה את זה, ומה הוא רוצה?\" — לא תוכנית לימודים."),
      L("Young children blur ads and content by default; research finds recognizing persuasive intent develops gradually across the elementary years.", "ילדים צעירים מטשטשים כברירת מחדל בין פרסומות לתוכן; מחקרים מוצאים שזיהוי כוונה שכנועית מתפתח בהדרגה לאורך שנות בית הספר היסודי."),
      L("Today's ads don't look like ads: unboxing videos, sponsored family vloggers and in-game shops sell hardest exactly where the label is missing.", "הפרסומות של היום לא נראות כמו פרסומות: סרטוני פתיחת קופסאות, יוטיוברים ממומנים וחנויות בתוך משחקים מוכרים הכי חזק בדיוק היכן שהתווית חסרה."),
      L("Real versus staged is a second thread: even young viewers can learn that videos are chosen, edited and performed — 'they filmed that lots of times.'", "אמיתי מול מבוים הוא חוט שני: גם צופים צעירים יכולים ללמוד שסרטונים נבחרים, נערכים ומשוחקים — \"צילמו את זה המון פעמים\"."),
      L("Curiosity outperforms lectures: co-viewing with light, playful questions builds the critical reflex; sermons build eye-rolling.", "סקרנות עובדת טוב יותר מהרצאות: צפייה משותפת עם שאלות קלות ומשועשעות בונה את הרפלקס הביקורתי; דרשות בונות גלגול עיניים."),
    ],
    body: L(
      "Somewhere between the first cartoon and the first phone, every child needs to acquire a superpower: the ability to look at a piece of media and wonder about the human behind it. Media-literacy educators compress it into two questions small enough for a five-year-old — who made this? and what do they want me to do? — and the earlier those questions become reflex, the better they'll serve, because you will not be in the room for most of what your child eventually watches.\n\nThe developmental backdrop explains the urgency. Research on advertising and children consistently finds that recognizing persuasive intent — grasping that someone profits when you want the toy — develops gradually through the elementary years; younger children tend to take content at face value. Meanwhile the advertising itself has evolved past the forms parents learned to spot. The commercial break announced itself; an unboxing video, a sponsored family vlogger or a game's glittering item shop does not. Children's media today sells hardest precisely where the 'this is an ad' label is missing, which is why the who-made-this question matters more for this generation, not less.\n\nThe teaching method is conversation, not curriculum. During ordinary co-viewing, drop small, genuinely curious questions: 'Why do you think they show the toy winning every race?' 'Do you think that kid got to keep all those presents?' 'How many times do you think they filmed that jump?' Each one quietly installs a piece of the model: media is made, made by someone, for a reason, and edited to look a particular way. Children take to it quickly — spotting the trick feels like detective work, and a seven-year-old who announces 'that's basically an ad!' mid-video is displaying the reflex you were after.\n\nA few habits deepen the work. Make things together — a filmed puppet show teaches editing-as-choice better than any explanation, because the child cuts the boring parts themselves and realizes everyone does. Let your child catch you evaluating your own feed out loud: 'this headline wants me to be angry — let's see if the story earns it.' And keep the register playful. The goal isn't a suspicious child; it's a curious one — a viewer who enjoys media with one eyebrow slightly raised, and who carries the questions with them long after they've outgrown your yes list.",
      "אי שם בין הסרט המצויר הראשון לטלפון הראשון, כל ילד צריך לרכוש כוח־על: היכולת להסתכל על פיסת מדיה ולתהות על האדם שמאחוריה. אנשי חינוך לאוריינות מדיה מכווצים אותו לשתי שאלות קטנות מספיק לבן חמש — מי עשה את זה? ומה הוא רוצה שאעשה? — וככל שהשאלות האלה הופכות לרפלקס מוקדם יותר, כך הן ישרתו טוב יותר, כי לא תהיו בחדר ברוב מה שהילד שלכם יצפה בו בסופו של דבר.\n\nהרקע ההתפתחותי מסביר את הדחיפות. מחקרים על פרסום וילדים מוצאים בעקביות שזיהוי כוונה שכנועית — להבין שמישהו מרוויח כשאתם רוצים את הצעצוע — מתפתח בהדרגה לאורך שנות היסודי; ילדים צעירים נוטים לקבל תוכן כפשוטו. בינתיים הפרסום עצמו התפתח אל מעבר לצורות שהורים למדו לזהות. הפסקת הפרסומות הכריזה על עצמה; סרטון פתיחת קופסאות, יוטיוברית משפחתית ממומנת או חנות הפריטים הנוצצת של משחק — לא. מדיה לילדים היום מוכרת הכי חזק בדיוק היכן שתווית \"זו פרסומת\" חסרה, ולכן שאלת מי־עשה־את־זה חשובה לדור הזה יותר, לא פחות.\n\nשיטת ההוראה היא שיחה, לא תוכנית לימודים. תוך כדי צפייה משותפת רגילה, שחררו שאלות קטנות וסקרניות באמת: \"למה לדעתך מראים את הצעצוע מנצח בכל מרוץ?\" \"נראה לך שהילד ההוא קיבל לשמור את כל המתנות?\" \"כמה פעמים לדעתך צילמו את הקפיצה הזאת?\" כל אחת מתקינה בשקט חלק מהמודל: מדיה נעשית, על ידי מישהו, מסיבה, ונערכת להיראות בצורה מסוימת. ילדים נדבקים מהר — לזהות את התרגיל מרגיש כמו עבודת בלשות, ובן שבע שמכריז \"זו בעצם פרסומת!\" באמצע סרטון מפגין בדיוק את הרפלקס שחיפשתם.\n\nכמה הרגלים מעמיקים את העבודה. צרו דברים יחד — הצגת בובות מצולמת מלמדת עריכה־כבחירה טוב מכל הסבר, כי הילד חותך את החלקים המשעממים בעצמו ומבין שכולם עושים את זה. תנו לילד לתפוס אתכם מעריכים את הפיד של עצמכם בקול: \"הכותרת הזאת רוצה שאכעס — בואו נראה אם הכתבה מצדיקה את זה.\" ושמרו על משלב משועשע. המטרה אינה ילד חשדן; היא ילד סקרן — צופה שנהנה ממדיה עם גבה אחת מורמת קלות, ולוקח איתו את השאלות הרבה אחרי שגדל מרשימת הכן שלכם."
    ),
    tryToday: L(
      "During today's viewing, ask one detective question: \"Who do you think made this — and what do they want us to do?\" Treat every answer as a good one.",
      "בצפייה של היום, שאלו שאלת בלש אחת: \"מי לדעתך עשה את זה — ומה הוא רוצה שנעשה?\" התייחסו לכל תשובה כתשובה טובה."
    ),
    ask: L("Give me age-right detective questions to ask during my child's favorite videos.", "תן לי שאלות בלש מתאימות לגיל לשאול בזמן הסרטונים האהובים על הילד שלי."),
  },
];
