/**
 * Learn Library seed catalogue — batch 3a (minds · language · feelings ·
 * behavior). Editorial stance per learnLibrary.ts design rules:
 * general developmental education, wide-normal ranges, no diagnosis-shaped
 * copy. EN/HE are parallel transcreations, not translations.
 */
import type { LocalizedText } from "../content/governance";
import type { LearnCard } from "./learnLibrary";

const L = (en: string, he: string): LocalizedText => ({ en, he });

export const LEARN_CARDS_BATCH3A: LearnCard[] = [
  // ── Growing Minds ────────────────────────────────────────────────────────
  {
    id: "memory-development",
    category: "minds",
    domains: ["cognition_executive_function"],
    ageMin: 0,
    ageMax: 8,
    minutes: 4,
    title: L("How memory develops (and why they won't remember being two)", "איך זיכרון מתפתח (ולמה הם לא יזכרו את גיל שנתיים)"),
    hook: L("The zoo trip your toddler forgets by next year is still shaping them — memory systems mature on very different schedules.", "הטיול לגן החיות שהפעוט ישכח עד השנה הבאה עדיין מעצב אותו — מערכות הזיכרון מבשילות בקצבים שונים מאוד."),
    keyPoints: [
      L("The brain runs several memory systems: implicit memory (skills, habits, emotional associations) works from birth; memory for events matures much later.", "המוח מפעיל כמה מערכות זיכרון: זיכרון מרומז (מיומנויות, הרגלים, אסוציאציות רגשיות) עובד מלידה; זיכרון לאירועים מבשיל הרבה אחר כך."),
      L("Infantile amnesia is near-universal: most adults recall almost nothing before age three or four, and that is entirely typical.", "אמנזיה ינקותית היא כמעט אוניברסלית: רוב המבוגרים זוכרים כמעט כלום מלפני גיל שלוש-ארבע, וזה תקין לחלוטין."),
      L("Babies and toddlers do remember — faces, routines, what comes next — but early event memories are fragile and mostly don't survive.", "תינוקות ופעוטות דווקא זוכרים — פנים, שגרות, מה בא עכשיו — אבל זיכרונות אירועים מוקדמים שבריריים ולרוב אינם שורדים."),
      L("Talking about the past together — 'what did we see? then what happened?' — is linked in research with richer, better-organized memories.", "לדבר יחד על העבר — \"מה ראינו? ומה קרה אחר כך?\" — נקשר במחקר לזיכרונות עשירים ומאורגנים יותר."),
      L("Through age eight, memory still leans on cues, repetition and routine; mixing imagination into a retelling is development, not lying.", "עד גיל שמונה הזיכרון עדיין נשען על רמזים, חזרה ושגרה; ערבוב דמיון בתוך סיפור מחדש הוא התפתחות, לא שקר."),
    ],
    body: L(
      "Ask an adult for their earliest memory and it usually lands somewhere around age three or four — almost never earlier. Yet the two-year-old who won't remember today's zoo trip is learning ferociously from it. The resolution to that puzzle is that memory is not one thing. The brain runs several systems on different construction schedules. Implicit memory — skills, habits, emotional associations, the deep sense of how the world treats you — works from birth. Explicit memory for events, the kind with a 'me' at the center of a story, depends on slower-maturing brain structures plus two late arrivals: language and a sense of self.\n\nThe near-total fading of the first years is called infantile amnesia, and it is one of the most reliable findings about human memory. It does not mean babies don't remember. An infant recognizes faces and voices; a toddler knows the bedtime sequence by heart and protests when you skip a page. But those early event memories are fragile, and most dissolve rather than carry into adulthood. What survives is deeper than scenes: the habits, the skills, and the felt sense of being cared for. The days your child won't recall are still building the person who will do the remembering.\n\nAround the preschool years, autobiographical memory starts to bloom alongside language. Researchers who study how families talk about the past find an association worth borrowing: children whose parents reminisce in an elaborated way — open questions, details, sequence — tend to develop richer, better-organized memories of their own lives. 'What did we see at the park? And then what happened?' hands a child the tools memory is made of: structure, order and words.\n\nThrough age eight and beyond, the system stays under construction. Working memory holds only a few items; recall works far better with cues and familiar routines; and small children blend imagination into retellings without any intent to deceive. Practically, that means repetition is how young children remember, revisiting the day at dinner is genuine memory practice, and expectations — 'I told you this morning!' — deserve resizing to a memory system that is still being built.",
      "שאלו מבוגר מה הזיכרון הראשון שלו, והוא ינחת בדרך כלל סביב גיל שלוש-ארבע — כמעט אף פעם לא מוקדם יותר. ובכל זאת, הפעוט בן השנתיים שלא יזכור את הטיול של היום לומד ממנו בעוצמה. הפתרון לחידה הוא שזיכרון אינו דבר אחד. המוח מפעיל כמה מערכות עם לוחות בנייה שונים. זיכרון מרומז — מיומנויות, הרגלים, אסוציאציות רגשיות, התחושה העמוקה של איך העולם מתייחס אליך — עובד מלידה. זיכרון מפורש לאירועים, מהסוג שיש בו \"אני\" במרכז סיפור, תלוי במבנים מוחיים שמבשילים לאט, ובשני מצטרפים מאוחרים: שפה ותחושת עצמי.\n\nלהיעלמות הכמעט מוחלטת של השנים הראשונות קוראים אמנזיה ינקותית, והיא מהממצאים היציבים ביותר על זיכרון אנושי. אין פירושה שתינוקות לא זוכרים. תינוק מזהה פנים וקולות; פעוט יודע בעל פה את רצף השינה ומוחה כשאתם מדלגים על עמוד. אבל זיכרונות האירועים המוקדמים האלה שבריריים, ורובם מתמוססים במקום לעבור לבגרות. מה ששורד עמוק מסצנות: ההרגלים, המיומנויות, והתחושה המופנמת של להיות מטופלים באהבה. הימים שהילד לא יזכור עדיין בונים את האדם שיעשה את הזכירה.\n\nסביב שנות הגן, הזיכרון האוטוביוגרפי מתחיל לפרוח יחד עם השפה. חוקרים שבודקים איך משפחות מדברות על העבר מוצאים קשר ששווה לאמץ: ילדים שהוריהם נזכרים איתם בדרך מפורטת — שאלות פתוחות, פרטים, רצף — נוטים לפתח זיכרונות עשירים ומאורגנים יותר על חייהם. \"מה ראינו בפארק? ומה קרה אחר כך?\" מוסר לילד את הכלים שמהם עשוי זיכרון: מבנה, סדר ומילים.\n\nעד גיל שמונה ומעבר לו, המערכת עדיין בבנייה. זיכרון עבודה מחזיק פריטים ספורים; היזכרות עובדת הרבה יותר טוב עם רמזים ושגרות מוכרות; וילדים קטנים שוזרים דמיון בתוך סיפור מחדש בלי שום כוונה להטעות. בפועל, זה אומר שחזרה היא הדרך שבה ילדים צעירים זוכרים, ששיחזור היום בארוחת הערב הוא אימון זיכרון אמיתי, ושציפיות — \"אמרתי לך הבוקר!\" — ראויות להתאמה למערכת זיכרון שעדיין נבנית."
    ),
    tryToday: L(
      "At dinner, replay one moment from today with three open questions: \"Where were we? What happened first? What was your favorite part?\" That's memory practice, not small talk.",
      "בארוחת הערב, שחזרו רגע אחד מהיום בשלוש שאלות פתוחות: \"איפה היינו? מה קרה קודם? מה הכי אהבת?\" זה אימון זיכרון, לא סתם שיחה."
    ),
    ask: L("What kind of remembering is realistic for my child's age right now?", "איזה סוג של זכירה מציאותי לגיל של הילד שלי עכשיו?"),
  },
  {
    id: "attention-spans",
    category: "minds",
    domains: ["cognition_executive_function"],
    ageMin: 1,
    ageMax: 8,
    minutes: 4,
    concerns: ["attention"],
    title: L("Realistic attention spans: what focus actually looks like by age", "טווחי קשב מציאותיים: איך ריכוז באמת נראה בכל גיל"),
    hook: L("The toddler who can't sit through a story but studies a beetle for ten minutes isn't distractible — there are two kinds of attention, on two schedules.", "הפעוט שלא מחזיק סיפור עד הסוף אבל חוקר חיפושית עשר דקות אינו מוסח — יש שני סוגי קשב, בשני לוחות זמנים."),
    keyPoints: [
      L("A rough ballpark for adult-directed tasks is a few minutes per year of age — a two-year-old may manage 4-6 minutes on someone else's agenda, with wide variation.", "אומדן גס למשימות שמבוגר מכתיב הוא כמה דקות לכל שנת גיל — בן שנתיים עשוי להחזיק 4–6 דקות באג'נדה של מישהו אחר, עם שונות רחבה."),
      L("Self-chosen play runs on different fuel: the same toddler can stay with a bucket of water or a beetle far longer. Both numbers are real attention.", "משחק שהילד בחר רץ על דלק אחר: אותו פעוט יכול להישאר עם דלי מים או חיפושית הרבה יותר זמן. שני המספרים הם קשב אמיתי."),
      L("Flitting between activities is a toddler's normal exploration mode — sampling widely is how young brains map the world, not a failure to focus.", "ריחוף בין פעילויות הוא מצב החקירה התקין של פעוטות — דגימה רחבה היא הדרך שבה מוח צעיר ממפה את העולם, לא כישלון בריכוז."),
      L("Attention stretches with interest, a joining adult, fewer competing signals (background TV fragments play), and one activity out at a time.", "קשב מתארך עם עניין, מבוגר שמצטרף, פחות אותות מתחרים (טלוויזיה ברקע מפרקת משחק) ופעילות אחת בכל פעם."),
      L("What's worth a professional conversation is a pattern across settings and months — trouble staying with anything, even self-chosen — described in observations, not labels.", "מה ששווה שיחה עם איש מקצוע הוא דפוס לרוחב מסגרות וחודשים — קושי להישאר עם כל דבר, גם מה שהילד בחר — מתואר בתצפיות, לא בתוויות."),
    ],
    body: L(
      "\"He can't sit still for five minutes\" is a worry that depends entirely on how old 'he' is. For a task an adult chose — circle time, a worksheet, waiting at a restaurant — a commonly used ballpark is a few minutes of focus per year of age. A two-year-old may genuinely manage four to six minutes of someone else's agenda; a five-year-old perhaps ten to fifteen. These are wide bands, not lines to hit, and any child's number swings with sleep, hunger and interest.\n\nThe more useful move is separating two kinds of attention. Directed attention — focusing on demand, on something unchosen — is effortful executive-function work, and it matures slowly across the whole of childhood. Fascination is different: when a child picks the object, attention comes almost free. That is why the toddler who abandons your puzzle in ninety seconds can pour water between cups for twenty minutes. Flitting itself has a job at this age; sampling widely before settling is how young brains map what the world contains. A toddler in constant motion between stations is usually exploring on schedule, not failing to concentrate.\n\nEnvironment moves the numbers more than exhortation does. Attention stretches when the material is interesting, when an adult joins and follows the child's lead — observational research links that kind of joint play with longer stretches of engagement — and when competition is removed: background television reliably fragments toddler play, and a floor covered in options invites surfing. One activity out at a time, a beat of patience before rescuing a child from mild boredom, and screens kept out of the comparison — engineered feeds hold anyone's gaze and say little about capacity elsewhere.\n\nEvery child has scattered days, and capacity dips when a child is tired, hungry or stressed. Comparisons with a sibling or classmate mislead more than they inform. The pattern worth bringing to a professional is different in kind: months of difficulty staying with anything — including activities the child chose and enjoys — across home and preschool alike, at a level that gets in the child's own way. Bring observations, whens and how-longs, and let the professional do the interpreting.",
      "\"הוא לא מסוגל לשבת חמש דקות\" היא דאגה שתלויה לגמרי בשאלה בן כמה \"הוא\". למשימה שמבוגר בחר — מפגש בגן, דף עבודה, המתנה במסעדה — אומדן מקובל הוא כמה דקות ריכוז לכל שנת גיל. בן שנתיים באמת עשוי להחזיק ארבע עד שש דקות באג'נדה של מישהו אחר; בן חמש אולי עשר עד חמש עשרה. אלה רצועות רחבות, לא קווים לעמוד בהם, והמספר של כל ילד מתנדנד עם שינה, רעב ועניין.\n\nהמהלך המועיל יותר הוא להפריד שני סוגי קשב. קשב מכוון — להתרכז לפי דרישה, במשהו לא נבחר — הוא עבודת תפקודים ניהוליים מאומצת, והוא מבשיל לאט לאורך כל הילדות. הוקסמות היא דבר אחר: כשהילד בוחר את המושא, הקשב מגיע כמעט בחינם. לכן הפעוט שנוטש את הפאזל שלכם אחרי דקה וחצי יכול למזוג מים בין כוסות עשרים דקות. גם לריחוף עצמו יש תפקיד בגיל הזה; לדגום רחב לפני שמתיישבים זו הדרך שבה מוח צעיר ממפה מה יש בעולם. פעוט בתנועה מתמדת בין תחנות בדרך כלל חוקר לפי לוח הזמנים, לא נכשל בריכוז.\n\nהסביבה מזיזה את המספרים יותר מהטפות. קשב מתארך כשהחומר מעניין, כשמבוגר מצטרף והולך אחרי ההובלה של הילד — מחקר תצפיתי קושר משחק משותף כזה לרצפים ארוכים יותר של שקיעה — וכשמסירים תחרות: טלוויזיה ברקע מפרקת משחק פעוטות באופן עקבי, ורצפה מכוסה אפשרויות מזמינה גלישה ביניהן. פעילות אחת בחוץ בכל פעם, רגע של סבלנות לפני שמחלצים ילד משעמום קל, ומסכים מחוץ להשוואה — פיד מהונדס מחזיק כל מבט ואומר מעט על יכולת במקומות אחרים.\n\nלכל ילד יש ימים מפוזרים, והיכולת צונחת כשילד עייף, רעב או לחוץ. השוואות לאח או לילד מהגן מטעות יותר משהן מלמדות. הדפוס ששווה להביא לאיש מקצוע שונה במהותו: חודשים של קושי להישאר עם כל דבר — כולל פעילויות שהילד בחר ואוהב — גם בבית וגם בגן, ברמה שמפריעה לילד עצמו. הביאו תצפיות, מתי וכמה זמן, ותנו לאיש המקצוע לעשות את הפרשנות."
    ),
    tryToday: L(
      "Once today, when your child is deep in something they chose, resist interrupting for two extra minutes — protecting focus builds it as surely as any exercise.",
      "פעם אחת היום, כשהילד שקוע במשהו שהוא בחר, התאפקו מלהפריע עוד שתי דקות — הגנה על ריכוז בונה אותו לא פחות מכל תרגיל."
    ),
    ask: L("What's a realistic focus expectation for my child's age, and how can we stretch it gently?", "מהי ציפיית ריכוז מציאותית לגיל של הילד שלי, ואיך נמתח אותה בעדינות?"),
  },

  // ── Language & Communication ─────────────────────────────────────────────
  {
    id: "language-explosion",
    category: "language",
    domains: ["language_communication"],
    ageMin: 1,
    ageMax: 2,
    minutes: 3,
    title: L("The language explosion: what happens around 18-24 months", "פיצוץ השפה: מה קורה סביב גיל שנה וחצי עד שנתיים"),
    hook: L("Many toddlers hit a stretch where new words seem to arrive daily — here's what's firing underneath, and how to feed it.", "פעוטות רבים מגיעים לתקופה שבה מילים חדשות כאילו נוחתות כל יום — הנה מה שקורה מתחת לפני השטח, ואיך להזין את זה."),
    keyPoints: [
      L("Somewhere around 18-24 months, many toddlers shift from slow, effortful single words to a rush of new vocabulary — sometimes several words a day.", "אי שם סביב 18–24 חודשים, פעוטות רבים עוברים ממילים בודדות איטיות ומאומצות לשטף של אוצר מילים חדש — לפעמים כמה מילים ביום."),
      L("The engine is fast-mapping: the emerging ability to catch a new word from just one or two exposures, plus the insight that everything has a name.", "המנוע הוא מיפוי מהיר: היכולת המתהווה לקלוט מילה חדשה מחשיפה אחת או שתיים, יחד עם התובנה שלכל דבר יש שם."),
      L("Around the 50-word mark, two-word combinations often appear — 'more juice', 'daddy go' — grammar's opening move.", "סביב רף חמישים המילים מופיעים לרוב צירופי שתי מילים — \"עוד מיץ\", \"אבא הלך\" — מהלך הפתיחה של הדקדוק."),
      L("Not every child gets a dramatic burst: steady, gradual growth is an equally normal shape for the same climb.", "לא כל ילד מקבל התפרצות דרמטית: צמיחה יציבה והדרגתית היא צורה נורמלית באותה מידה של אותו טיפוס."),
      L("The best fuel is conversation: label what the child is looking at, expand their words back, sing, read — in every language your home loves.", "הדלק הטוב ביותר הוא שיחה: תנו שם למה שהילד מסתכל עליו, הרחיבו את מילותיו בחזרה, שירו, קראו — בכל שפה שהבית שלכם אוהב."),
    ],
    body: L(
      "For months, each new word arrives like a small construction project: 'ball' after weeks of practice, 'dog' generalized to every four-legged thing in sight. Then, for many toddlers somewhere between eighteen months and their second birthday, the pace changes. Words start arriving in a rush — parents describe whole days of pointing and naming, and vocabularies that double in weeks. Language researchers often call it the vocabulary spurt, and it is one of early childhood's most visible transformations.\n\nUnderneath, two abilities are clicking into place. The first is fast-mapping: the emerging skill of catching a new word from a single exposure or two, instead of dozens. Hear 'flamingo' once at the zoo, own it by dinner. The second is bigger: the dawning insight that everything has a name — that the game of labels is infinite and the adults will keep playing it. Around the fifty-word mark, many toddlers make grammar's opening move: two words snapped together. 'More juice.' 'Daddy go.' Tiny sentences, but sentences — order and meaning working together for the first time.\n\nA note of calibration: the spurt is common, not mandatory. Plenty of typically developing children climb steadily without a dramatic burst, and bilingual toddlers spread their new words across both languages, which makes any single-language count an undercount. The wide-normal rules from the late-talker picture apply here too: understanding, gestures and social connection tell you more than any word tally.\n\nFeeding the fire takes no equipment. Label what your child is already looking at — attention is the open door words walk through. Expand their offerings back: 'truck' becomes 'yes, a big red truck.' Narrate the boring parts of the day, sing the same songs on repeat, and read whatever book they bring you, even the fifth time. This stretch of development is loud, funny and short. Some families keep a note on the fridge of new words as they land — a small record of one of the fastest learning curves a human ever climbs.",
      "במשך חודשים, כל מילה חדשה מגיעה כמו פרויקט בנייה קטן: \"כדור\" אחרי שבועות של אימון, \"כלב\" שמוכלל על כל הולך-על-ארבע באופק. ואז, אצל פעוטות רבים אי שם בין שנה וחצי ליום ההולדת השני, הקצב משתנה. מילים מתחילות להגיע בשטף — הורים מתארים ימים שלמים של הצבעה ומתן שמות, ואוצר מילים שמכפיל את עצמו בשבועות. חוקרי שפה קוראים לזה לעיתים קרובות פרץ אוצר המילים, וזו מהתמורות הגלויות ביותר של הילדות המוקדמת.\n\nמתחת לפני השטח, שתי יכולות נכנסות למקומן. הראשונה היא מיפוי מהיר: המיומנות המתהווה לקלוט מילה חדשה מחשיפה אחת או שתיים, במקום מעשרות. לשמוע \"פלמינגו\" פעם אחת בגן החיות, ולהחזיק בו עד ארוחת הערב. השנייה גדולה יותר: התובנה המפציעה שלכל דבר יש שם — שמשחק השמות אינסופי ושהמבוגרים ימשיכו לשחק אותו. סביב רף חמישים המילים, פעוטות רבים עושים את מהלך הפתיחה של הדקדוק: שתי מילים מוצמדות. \"עוד מיץ.\" \"אבא הלך.\" משפטים זעירים, אבל משפטים — סדר ומשמעות עובדים יחד בפעם הראשונה.\n\nהערת כיול: הפרץ שכיח, לא חובה. הרבה ילדים שמתפתחים באופן תקין מטפסים בהתמדה בלי התפרצות דרמטית, ופעוטות דו־לשוניים מפזרים את המילים החדשות בין שתי השפות, כך שכל ספירה בשפה אחת היא ספירה בחסר. כללי הטווח הרחב מתמונת המדברים־מאוחר תקפים גם כאן: הבנה, מחוות וחיבור חברתי מספרים יותר מכל ספירת מילים.\n\nלהזין את האש לא דורש ציוד. תנו שם למה שהילד כבר מסתכל עליו — קשב הוא הדלת הפתוחה שמילים נכנסות דרכה. הרחיבו את מה שהוא מציע: \"משאית\" הופכת ל\"כן, משאית אדומה וגדולה.\" תארו בקול את החלקים המשעממים של היום, שירו את אותם שירים שוב ושוב, וקראו כל ספר שהוא מביא, גם בפעם החמישית. שלב ההתפתחות הזה רועש, מצחיק וקצר. יש משפחות שמנהלות פתק על המקרר עם המילים החדשות כשהן נוחתות — תיעוד קטן של אחת מעקומות הלמידה המהירות שאדם מטפס עליהן אי פעם."
    ),
    tryToday: L(
      "Pick one ten-minute stretch and narrate only what your toddler looks at — name it, expand it, wait. Attention-matched words are the ones that stick.",
      "בחרו רצועה של עשר דקות ותארו רק את מה שהפעוט מסתכל עליו — תנו שם, הרחיבו, חכו. מילים שמכוונות לקשב הן אלה שנתפסות."
    ),
    ask: L("How can I make the most of my toddler's word-learning window this month?", "איך למצות את חלון לימוד המילים של הפעוט שלי החודש?"),
  },
  {
    id: "phonological-awareness",
    category: "language",
    domains: ["language_communication"],
    ageMin: 3,
    ageMax: 6,
    minutes: 3,
    title: L("Rhymes and sounds: the real pre-reading skill", "חרוזים וצלילים: מיומנות טרום־הקריאה האמיתית"),
    hook: L("Before letters mean anything, reading starts in the ear — noticing that words are built from sounds you can play with.", "לפני שאותיות אומרות משהו, הקריאה מתחילה באוזן — בהבחנה שמילים בנויות מצלילים שאפשר לשחק בהם."),
    keyPoints: [
      L("Phonological awareness is hearing the parts inside words: rhymes, syllables, first sounds. Research links it strongly with how easily reading comes later.", "מודעות פונולוגית היא לשמוע את החלקים שבתוך מילים: חרוזים, הברות, צלילי פתיחה. המחקר קושר אותה חזק לקלות שבה קריאה מגיעה אחר כך."),
      L("It grows in a rough sequence across ages 3-6: rhyme and alliteration first, then syllables, then single sounds — with wide individual timing.", "היא צומחת ברצף גס בין גיל שלוש לשש: קודם חרוז וצליל פותח, אחר כך הברות, ואז צלילים בודדים — עם תזמון אישי רחב."),
      L("It is ear training, not letter training: a child can be excellent at sound games before recognizing a single letter.", "זה אימון אוזן, לא אימון אותיות: ילד יכול להצטיין במשחקי צלילים לפני שהוא מזהה אות אחת."),
      L("The best practice looks like play: nursery rhymes, silly rhyming games, clapping names into syllables, 'I spy something that starts with mmm'.", "האימון הטוב ביותר נראה כמו משחק: שירי ילדים, משחקי חרוזים מטופשים, מחיאת שמות להברות, \"אני רואה משהו שמתחיל ב־ממם\"."),
      L("Nonsense words count double — inventing 'bap, lap, zap' shows a child is playing with sound itself, exactly the point.", "מילות שטות שוות כפול — להמציא \"בָּפ, לָפ, זָפ\" מראה שהילד משחק בצליל עצמו, וזו בדיוק המטרה."),
    ],
    body: L(
      "Long before a child decodes a single word, reading is being prepared in an unexpected organ: the ear. Written letters are a code for sounds, so the child who can already hear that words come apart — that 'cat' and 'hat' share an ending, that 'ba-na-na' has three beats, that 'sun' and 'sock' start the same way — arrives at letters with the hard half done. Researchers call this phonological awareness, and decades of studies place it among the preschool skills most strongly associated with how easily reading comes later.\n\nIt develops in a rough sequence, with wide personal timing. Around three and four, children start to relish rhyme and alliteration — the pleasure of 'moose on the loose' arrives well before any understanding of why it's funny. Next comes the ability to break words into syllables, clapping out 'el-e-phant'. Hearing the first sound of a word tends to follow, and the finest grain — pulling a word apart into every individual sound — typically firms up around kindergarten and first grade, often alongside letters themselves.\n\nThe practice that builds it looks nothing like a lesson. Nursery rhymes and rhyming books read with relish do the heaviest lifting; pausing before the rhyme ('the cat wore a...') lets the child snap the sound into place. Sound games travel anywhere: rhyming ping-pong where nonsense words score double, clapping every family member's name into syllables, 'I spy something that starts with mmm.' Songs, chants and skipping rhymes are the same curriculum in disguise. Silliness is not a bug — a child giggling at 'bap, lap, zap' is manipulating pure sound, which is precisely the skill.\n\nLetters have their place, and sound-play is what makes them make sense on arrival: an alphabet learned on top of a well-tuned ear clicks together. Timing varies widely, and a four-year-old who shrugs at rhymes is well within the band. What's worth mentioning to a professional, observationally, is a child late in kindergarten who persistently doesn't notice sounds or rhymes at all, especially alongside broader language worries — while for everyone, the daily prescription is identical and delightful: rhyme, sing, clap and play.",
      "הרבה לפני שילד מפענח מילה כתובה אחת, הקריאה מתבשלת באיבר לא צפוי: האוזן. אותיות כתובות הן צופן לצלילים, ולכן ילד שכבר שומע שמילים מתפרקות — ש\"גר\" ו\"הר\" חולקים סיום, של\"בָּ-נָ-נָה\" יש שלוש פעימות, ש\"שמש\" ו\"שולחן\" נפתחות באותו צליל — מגיע לאותיות כשחצי העבודה הקשה נעשתה. חוקרים קוראים לזה מודעות פונולוגית, ועשורים של מחקר מציבים אותה בין מיומנויות הגן הקשורות ביותר לקלות שבה קריאה מגיעה אחר כך.\n\nהיא מתפתחת ברצף גס, עם תזמון אישי רחב. סביב שלוש וארבע, ילדים מתחילים להתענג על חרוז וצליל חוזר — ההנאה מ\"דג בגג\" מגיעה הרבה לפני כל הבנה מדוע זה מצחיק. אחר כך באה היכולת לפרק מילים להברות, במחיאות כפיים על \"פי-לו-ן\". שמיעת הצליל הראשון של מילה נוטה לבוא בהמשך, והרזולוציה הדקה ביותר — לפרק מילה לכל צליל בנפרד — מתייצבת בדרך כלל סביב גן חובה וכיתה א', לרוב יחד עם האותיות עצמן.\n\nהאימון שבונה אותה לא נראה כמו שיעור. שירי ילדים וספרים מחורזים שנקראים בהנאה עושים את העבודה הכבדה; עצירה לפני החרוז (\"הדג גר ב...\") נותנת לילד להקפיץ את הצליל למקומו. משחקי צלילים נוסעים לכל מקום: פינג־פונג חרוזים שבו מילות שטות שוות כפול, מחיאת השם של כל בן משפחה להברות, \"אני רואה משהו שמתחיל ב־ממם.\" שירים, מקצבים וחרוזי חצר הם אותה תוכנית לימודים בתחפושת. השטותיות אינה תקלה — ילד שמצחקק על \"בָּפ, לָפ, זָפ\" מתמרן צליל טהור, וזו בדיוק המיומנות.\n\nלאותיות יש מקום, ומשחקי הצלילים הם מה שגורם להן להיות הגיוניות כשהן מגיעות: אלפבית שנלמד מעל אוזן מכוונת היטב מתחבר מעצמו. התזמון משתנה מאוד, וילד בן ארבע שמושך בכתפיים מול חרוזים נמצא היטב בתוך הטווח. מה ששווה להזכיר לאיש מקצוע, בלשון תצפיתית, הוא ילד לקראת סוף גן חובה שבעקביות אינו מבחין בצלילים או בחרוזים כלל, במיוחד לצד דאגות שפה רחבות יותר — ואילו לכולם, המרשם היומי זהה ומענג: לחרוז, לשיר, למחוא ולשחק."
    ),
    tryToday: L(
      "In the bath or the car, play one round of rhyming ping-pong: you say a word, they rhyme it, nonsense words score double. Two minutes is a full session.",
      "באמבטיה או באוטו, שחקו סיבוב אחד של פינג־פונג חרוזים: אתם אומרים מילה, הם מחרזים, מילות שטות שוות כפול. שתי דקות הן אימון שלם."
    ),
    ask: L("Which sound games fit my child's stage on the road to reading?", "אילו משחקי צלילים מתאימים לשלב של הילד שלי בדרך לקריאה?"),
  },
  {
    id: "questions-that-open",
    category: "language",
    domains: ["language_communication"],
    ageMin: 2,
    ageMax: 8,
    minutes: 3,
    title: L("Questions that open conversation (and the ones that close it)", "שאלות שפותחות שיחה (ואלה שסוגרות אותה)"),
    hook: L("\"How was school?\" \"Fine.\" The dead end isn't your child's fault — the question is doing the closing.", "\"איך היה בגן?\" \"בסדר.\" המבוי הסתום אינו אשמת הילד — השאלה היא שסוגרת."),
    keyPoints: [
      L("Global questions ('how was your day?') ask a child to summarize everything at once; specific, concrete openers give a handle to grab.", "שאלות גלובליות (\"איך היה היום?\") מבקשות מהילד לסכם הכול בבת אחת; פתיחים ספציפיים ומוחשיים נותנים ידית לאחוז בה."),
      L("Quizzing and corrections dressed as questions ('what color is it?', 'why would you do that?') teach children that questions are tests.", "בחינות ותיקונים מחופשים לשאלות (\"איזה צבע זה?\", \"למה עשית את זה?\") מלמדים ילדים ששאלות הן מבחנים."),
      L("Wondering aloud and simple statements ('I bet the fire drill was loud') invite talk without demanding it — often better than any question.", "תהייה בקול ואמירות פשוטות (\"בטח תרגיל החירום היה רועש\") מזמינות דיבור בלי לדרוש אותו — לעיתים טוב יותר מכל שאלה."),
      L("One question, then silence: a few extra seconds of wait time reliably buys longer, richer answers than a follow-up barrage.", "שאלה אחת, ואז שקט: כמה שניות נוספות של המתנה קונות תשובות ארוכות ועשירות יותר מכל מטח שאלות המשך."),
      L("Side-by-side beats face-to-face: cars, walks and shared building unlock talk that direct eye contact shuts down.", "צד לצד עדיף על פנים מול פנים: נסיעות, הליכות ובנייה משותפת פותחות דיבור שקשר עין ישיר סוגר."),
    ],
    body: L(
      "\"How was school?\" \"Fine.\" It reads like stonewalling, but it's usually arithmetic: a global question asks a six-year-old to survey an entire day, pick the reportable parts, and compress them into a sentence — heavy lifting for a young brain. Specific questions hand over a smaller package: 'What was the funniest thing that happened today?' 'Who did you sit next to at lunch?' 'Did anything surprising happen?' A concrete handle turns retrieval from an essay question into a story prompt.\n\nSome questions close doors by design. Rapid-fire sequences feel like interrogation, and children respond the way anyone does under questioning — minimally. Quizzing ('what sound does the cow make? what color is this?') teaches that adult questions are tests with right answers, which makes them something to pass rather than a place to think. And questions that are really corrections — 'why would you do that?' — aren't questions at all; children hear the verdict inside them and defend instead of reflecting.\n\nThe openers that work often aren't questions. Wondering aloud ('I wonder what the builders will do with that crane tomorrow') leaves a door open without standing in it. Simple statements about their world ('I bet the fire drill was loud today') invite confirmation, correction or elaboration — all conversation. Sharing your own small news first models the trade: talk is exchanged, not extracted. And after any opener, the underrated tool is silence. A few extra seconds of unhurried waiting — longer than feels natural — reliably buys fuller answers than a quick follow-up does.\n\nSetting does quiet work too. Face-to-face across a table can feel like a spotlight; side-by-side — in the car, on a walk, over LEGO — takes the pressure off, and many children talk most freely at bedtime, when the day finally settles. With toddlers, keep it playful and light: comment more than you ask, and let one 'what happens next?' in pretend play carry the load. The goal was never extracting a report. It's the slow habit, built over years of small exchanges, that talking to you is safe, easy and worth it.",
      "\"איך היה בגן?\" \"בסדר.\" זה נראה כמו התחמקות, אבל בדרך כלל זו אריתמטיקה: שאלה גלובלית מבקשת מילד בן שש לסקור יום שלם, לבחור את החלקים הראויים לדיווח, ולדחוס אותם למשפט — הרמה כבדה למוח צעיר. שאלות ספציפיות מוסרות חבילה קטנה יותר: \"מה היה הדבר הכי מצחיק היום?\" \"ליד מי ישבת בארוחה?\" \"קרה משהו מפתיע?\" ידית מוחשית הופכת את השליפה משאלת חיבור להזמנה לסיפור.\n\nיש שאלות שסוגרות דלתות מעצם עיצובן. רצפי שאלות מהירים מרגישים כמו חקירה, וילדים מגיבים כמו כל אחד תחת חקירה — במינימום. בחינות (\"איך עושה פרה? איזה צבע זה?\") מלמדות ששאלות של מבוגרים הן מבחנים עם תשובות נכונות, ולכן משהו לעבור, לא מקום לחשוב בו. ושאלות שהן בעצם תיקונים — \"למה עשית את זה?\" — אינן שאלות כלל; ילדים שומעים את פסק הדין שבפנים ומתגוננים במקום להרהר.\n\nהפתיחים שעובדים לרוב אינם שאלות. תהייה בקול (\"מעניין מה הבנאים יעשו מחר עם המנוף הזה\") משאירה דלת פתוחה בלי לעמוד בה. אמירות פשוטות על העולם שלהם (\"בטח תרגיל החירום היה רועש היום\") מזמינות אישור, תיקון או הרחבה — כולם שיחה. לשתף קודם חדשות קטנות משלכם מדגים את העסקה: דיבור מוחלף, לא נסחט. ואחרי כל פתיח, הכלי הכי לא מוערך הוא שקט. כמה שניות נוספות של המתנה רגועה — יותר ממה שמרגיש טבעי — קונות באופן עקבי תשובות מלאות יותר מכל שאלת המשך מהירה.\n\nגם למקום יש עבודה שקטה. פנים מול פנים מעבר לשולחן יכול להרגיש כמו זרקור; צד לצד — באוטו, בהליכה, מעל הלגו — מוריד את הלחץ, וילדים רבים מדברים הכי בחופשיות לפני השינה, כשהיום סוף סוף נרגע. עם הקטנים, שמרו על קלילות משחקית: הגיבו ותארו יותר משאתם שואלים, ותנו ל\"מה קורה עכשיו?\" אחד במשחק דמיוני לשאת את המשקל. המטרה מעולם לא הייתה לחלץ דוח. היא ההרגל האיטי, שנבנה בשנים של חילופים קטנים, שלדבר איתכם זה בטוח, קל ושווה."
    ),
    tryToday: L(
      "At pickup, swap \"how was your day?\" for one specific opener — \"what was the funniest thing today?\" — then count five silent seconds before saying anything else.",
      "באיסוף, החליפו את \"איך היה היום?\" בפתיח ספציפי אחד — \"מה היה הכי מצחיק היום?\" — ואז ספרו חמש שניות של שקט לפני שאתם אומרים עוד משהו."
    ),
    ask: L("Give me five conversation openers matched to my child's age.", "תן לי חמישה פתיחי שיחה מותאמים לגיל של הילד שלי."),
  },

  // ── Big Feelings ─────────────────────────────────────────────────────────
  {
    id: "shyness-vs-anxiety",
    category: "feelings",
    domains: ["attachment_regulation", "social_development"],
    ageMin: 2,
    ageMax: 8,
    minutes: 4,
    concerns: ["fears", "separation"],
    title: L("Shy, slow to warm, or something more? Reading a watchful child", "ביישן, מתחמם לאט, או משהו נוסף? לקרוא ילד מתבונן"),
    hook: L("The child watching the party from the edge for twenty minutes isn't broken — for many, that's a temperament working exactly as designed.", "הילד שצופה במסיבה מהצד עשרים דקות אינו שבור — אצל רבים, זה טמפרמנט שעובד בדיוק כמתוכנן."),
    keyPoints: [
      L("Slow-to-warm is a well-described temperament: some children observe first and join later, on their own terms — a style, not a flaw.", "\"מתחמם לאט\" הוא טמפרמנט מתועד היטב: יש ילדים שקודם מתבוננים ומצטרפים אחר כך, בתנאים שלהם — סגנון, לא פגם."),
      L("Wariness has typical windows: stranger wariness in infancy, separation protest in toddlerhood, self-consciousness rising in the school years.", "לזהירות יש חלונות טיפוסיים: חשש מזרים בינקות, מחאת פרידה בגיל הפעוטות, מודעות עצמית שעולה בשנות בית הספר."),
      L("Warm-up time is the signature: given minutes and a familiar adult nearby, a shy child typically engages — the wariness eases.", "זמן התחממות הוא סימן ההיכר: עם כמה דקות ומבוגר מוכר בקרבת מקום, ילד ביישן בדרך כלל מצטרף — הזהירות מתרככת."),
      L("Support without pushing or rescuing: arrive early, stay nearby, give a role — and skip the label ('she's shy') and the forced performance ('say hello!').", "תמכו בלי לדחוף ובלי לחלץ: הגיעו מוקדם, הישארו קרובים, תנו תפקיד — וותרו על התווית (\"היא ביישנית\") ועל ההופעה הכפויה (\"תגיד שלום!\")."),
      L("A pattern worth a professional conversation, described observationally: distress that stays intense despite warm-up time, avoidance that consistently blocks what the child wants, worry that dominates weeks.", "דפוס ששווה שיחה עם איש מקצוע, מתואר תצפיתית: מצוקה שנשארת עזה גם אחרי זמן התחממות, הימנעות שחוסמת בעקביות את מה שהילד רוצה, דאגה ששולטת בשבועות."),
    ],
    body: L(
      "Some children charge into a birthday party before their shoes are off. Others stand at the edge for twenty minutes, watching, and then — on their own schedule — wade in. Temperament research has described this slow-to-warm pattern for decades: a real, stable, common style of meeting the world. Related but distinct is introversion — recharging in quiet, preferring a few deep friendships to a crowd. Neither is a deficiency waiting for a fix, and plenty of watchful children grow into adults whose careful observation is a strength.\n\nWariness also has a developmental calendar. Stranger wariness blooms in the second half of the first year — a sign of good attachment math, not a social problem. Separation protest peaks in toddlerhood. Self-consciousness — caring what others think, fearing embarrassment — rises in the school years right on time. A child can pass through each window looking, briefly, more anxious than before, while developing exactly as expected. The signature of ordinary shyness is the warm-up curve: given a little time, a familiar adult within reach, and no spotlight, the watchful child starts playing.\n\nWhat helps is support that neither pushes nor rescues. Arrive early, so the room fills up around your child instead of confronting them ready-made. Stay quietly nearby without narrating — 'she's shy' said over a child's head tends to become a coat they keep wearing. Give small roles ('you're in charge of handing out the cups'), rehearse new situations in advance ('first we'll ring the bell, then Grandma will open'), and let brave moments pass with quiet acknowledgment rather than fanfare. Forcing a performance ('say hello!') and whisking the child away at the first hesitation both teach the same wrong lesson: that this feeling is unmanageable.\n\nWhen might wariness be something to look at more closely? Patterns, described in observations: distress that stays intense even after generous warm-up time; avoidance that consistently blocks things the child themselves wants to do; stomachaches and sleepless nights around separations; worry that dominates weeks rather than moments. A pattern like that is a good reason for a conversation with a professional — bring your whens and how-oftens. And absent that pattern, the watcher at the edge of the party mostly needs what they already have: time, and you nearby.",
      "יש ילדים שמסתערים על מסיבת יום הולדת עוד לפני שהנעליים ירדו. אחרים עומדים בצד עשרים דקות, מתבוננים, ואז — לפי הלוח שלהם — נכנסים פנימה. מחקר הטמפרמנט מתאר את דפוס ה\"מתחמם לאט\" הזה כבר עשורים: סגנון אמיתי, יציב ושכיח של פגישה עם העולם. קרובה אך נבדלת ממנו היא המופנמות — להיטען בשקט, להעדיף כמה חברויות עמוקות על פני המון. אף אחד מהם אינו ליקוי שמחכה לתיקון, והרבה ילדים מתבוננים גדלים למבוגרים שההתבוננות הזהירה שלהם היא כוח.\n\nגם לזהירות יש לוח שנה התפתחותי. חשש מזרים פורח במחצית השנייה של השנה הראשונה — סימן לחשבון התקשרות תקין, לא לבעיה חברתית. מחאת פרידה מגיעה לשיא בגיל הפעוטות. מודעות עצמית — אכפתיות ממה שאחרים חושבים, פחד ממבוכה — עולה בשנות בית הספר בדיוק בזמן. ילד יכול לעבור כל חלון כזה כשהוא נראה, לרגע, חרד יותר מקודם, ובו בזמן להתפתח בדיוק כמצופה. סימן ההיכר של ביישנות רגילה הוא עקומת ההתחממות: עם קצת זמן, מבוגר מוכר בהישג יד ובלי זרקור, הילד המתבונן מתחיל לשחק.\n\nמה שעוזר הוא תמיכה שלא דוחפת ולא מחלצת. הגיעו מוקדם, כך שהחדר יתמלא סביב הילד במקום להתייצב מולו מוכן מראש. הישארו קרובים בשקט בלי לתאר — \"היא ביישנית\" שנאמר מעל ראשו של ילד נוטה להפוך למעיל שהוא ממשיך ללבוש. תנו תפקידים קטנים (\"אתה אחראי לחלק את הכוסות\"), תדרכו מצבים חדשים מראש (\"קודם נצלצל בפעמון, ואז סבתא תפתח\"), ותנו לרגעים אמיצים לעבור בהכרה שקטה במקום בתרועות. לכפות הופעה (\"תגיד שלום!\") ולחטוף את הילד משם בהיסוס הראשון מלמדים את אותו שיעור שגוי: שהרגש הזה בלתי ניתן לניהול.\n\nמתי כדאי להתבונן מקרוב יותר? דפוסים, מתוארים בתצפיות: מצוקה שנשארת עזה גם אחרי זמן התחממות נדיב; הימנעות שחוסמת בעקביות דברים שהילד עצמו רוצה לעשות; כאבי בטן ולילות בלי שינה סביב פרידות; דאגה ששולטת בשבועות ולא ברגעים. דפוס כזה הוא סיבה טובה לשיחה עם איש מקצוע — הביאו את המתי והכמה שלכם. ובהיעדר דפוס כזה, המתבונן בקצה המסיבה זקוק בעיקר למה שכבר יש לו: זמן, ואתם בקרבת מקום."
    ),
    tryToday: L(
      "Before the next social event, run a one-minute preview: who'll be there, what happens first, and one small job for your child. Predictability shortens the warm-up.",
      "לפני האירוע החברתי הבא, עשו תצוגה מקדימה של דקה: מי יהיה שם, מה קורה קודם, ותפקיד קטן אחד לילד. צפיות מקצרת את ההתחממות."
    ),
    ask: L("How can I support my watchful child at gatherings without pushing?", "איך לתמוך בילד המתבונן שלי במפגשים בלי לדחוף?"),
  },
  {
    id: "regulation-ladder",
    category: "feelings",
    domains: ["attachment_regulation"],
    ageMin: 0,
    ageMax: 8,
    minutes: 4,
    concerns: ["regulation"],
    title: L("The emotional-regulation ladder: what to expect at each age", "סולם הוויסות הרגשי: למה לצפות בכל גיל"),
    hook: L("Self-regulation is a ladder climbed over two decades — knowing which rung your child is on changes what a hard moment means.", "ויסות עצמי הוא סולם שמטפסים עליו שני עשורים — לדעת על איזה שלב הילד נמצא משנה את המשמעות של רגע קשה."),
    keyPoints: [
      L("Babies can't self-regulate at all: regulation is borrowed. Rocking, feeding and holding are you serving as an external nervous system.", "תינוקות לא מסוגלים לווסת את עצמם כלל: הוויסות מושאל. נדנוד, האכלה וחיבוק הם אתם משמשים מערכת עצבים חיצונית."),
      L("Toddlers (1-3) feel adult-sized emotions with tiny tools: meltdowns are the expected rung, with first green shoots — seeking comfort, hugging a lovey, saying 'mad'.", "פעוטות (1–3) מרגישים רגשות בגודל מבוגר עם כלים זעירים: התקפים הם השלב הצפוי, עם ניצנים ראשונים — לבקש נחמה, לחבק בובה, לומר \"כועס\"."),
      L("Preschoolers (3-5) can name feelings and use simple strategies with live coaching — and still collapse entirely when tired or hungry.", "ילדי גן (3–5) יכולים לקרוא לרגשות בשם ולהשתמש באסטרטגיות פשוטות עם ליווי צמוד — ועדיין לקרוס לגמרי כשהם עייפים או רעבים."),
      L("Early school years (5-8) bring self-talk, longer waits and faster recovery — a real but shallow capacity that still needs reminders and drains under load.", "שנות בית הספר הראשונות (5–8) מביאות דיבור עצמי, המתנות ארוכות יותר והתאוששות מהירה יותר — יכולת אמיתית אך רדודה שעדיין צריכה תזכורות ומתרוקנת תחת עומס."),
      L("The ladder is climbed through thousands of co-regulation loops, named feelings, steady routines and adults who regulate out loud — and everyone slips rungs on hard days.", "מטפסים בסולם דרך אלפי לולאות של ויסות משותף, רגשות עם שמות, שגרות יציבות ומבוגרים שמווסתים בקול רם — וכולם מחליקים שלבים בימים קשים."),
    ],
    body: L(
      "Self-regulation — the ability to manage a feeling instead of being managed by it — is one of childhood's longest construction projects, running well into the twenties. Picturing it as a ladder helps, because the question 'why can't he calm down?' has a different answer on every rung. At the bottom is infancy, where the honest answer is: he can't, at all. Babies have no self-regulation machinery; they have signaling. Regulation is borrowed — every rocking, feeding, shushing hold is you operating as an external nervous system. Those thousands of borrowed calms are not spoiling; they are the construction material of the ladder itself.\n\nThe toddler rungs, roughly one to three, pair adult-sized emotions with tiny tools. This is the age of the meltdown, and the meltdown is the expected behavior of the rung — the gap between feeling and managing at its widest. But look for green shoots: a toddler who runs to you when overwhelmed, drags a lovey to a hard moment, or announces 'mad!' is already using strategies. They are just strategies that mostly involve you.\n\nPreschoolers, three to five, climb visibly. They can name a growing set of feelings, catch themselves mid-surge occasionally, and use simple tools — a big breath, squeezing a pillow, stomping to the corner — when a calm adult coaches them live. The capacity is genuine and genuinely shallow: the same child who breathed through a disappointment at ten a.m. dissolves over a broken cracker at six p.m. By early school age, five to eight, self-talk arrives ('it's just a game'), waits stretch longer, recovery speeds up, and strategies work with reminders instead of full coaching. Under load — tired, hungry, overstimulated, a hard week — children of every age slide down rungs, and so do adults.\n\nWhat moves a child up is unglamorous: thousands of co-regulation loops, feelings named as they happen, routines that keep daily load manageable, protected sleep, and adults who regulate out loud ('I'm frustrated — I'm going to take a breath'). Match expectations to the rung, not the ladder's top. And if a child's storms remain far more intense, long and frequent than their peers' for months, without the gradual easing the ladder predicts, that pattern — described in counts and durations — is worth a conversation with a professional.",
      "ויסות עצמי — היכולת לנהל רגש במקום להיות מנוהלים על ידו — הוא מפרויקטי הבנייה הארוכים של הילדות, ונמשך עמוק אל שנות העשרים. עוזר לצייר אותו כסולם, כי לשאלה \"למה הוא לא נרגע?\" יש תשובה שונה בכל שלב. בתחתית נמצאת הינקות, שבה התשובה הכנה היא: הוא לא יכול, בכלל. לתינוקות אין מנגנון ויסות עצמי; יש להם איתות. הוויסות מושאל — כל נדנוד, האכלה וחיבוק מרגיע הם אתם פועלים כמערכת עצבים חיצונית. אלפי ההרגעות המושאלות האלה אינן פינוק; הן חומר הבנייה של הסולם עצמו.\n\nשלבי הפעוטות, בערך אחת עד שלוש, מצמידים רגשות בגודל מבוגר לכלים זעירים. זה גיל ההתקפים, וההתקף הוא ההתנהגות הצפויה של השלב — הפער בין להרגיש לנהל ברוחבו המרבי. אבל חפשו ניצנים: פעוט שרץ אליכם כשהוא מוצף, גורר בובה לרגע קשה, או מכריז \"כועס!\" כבר משתמש באסטרטגיות. פשוט אסטרטגיות שרובן כוללות אתכם.\n\nילדי גן, שלוש עד חמש, מטפסים בגלוי. הם יכולים לקרוא בשם למגוון גדל של רגשות, לתפוס את עצמם באמצע גל מדי פעם, ולהשתמש בכלים פשוטים — נשימה גדולה, לחיצה על כרית, רקיעה עד הפינה — כשמבוגר רגוע מלווה אותם בזמן אמת. היכולת אמיתית ורדודה באמת: אותו ילד שנשם דרך אכזבה בעשר בבוקר מתמוסס על קרקר שבור בשש בערב. בגיל בית הספר המוקדם, חמש עד שמונה, מגיע דיבור עצמי (\"זה רק משחק\"), ההמתנות מתארכות, ההתאוששות מואצת, והאסטרטגיות עובדות עם תזכורות במקום ליווי מלא. תחת עומס — עייפות, רעב, גירוי יתר, שבוע קשה — ילדים בכל גיל מחליקים שלבים, וגם מבוגרים.\n\nמה שמעלה ילד בסולם אינו זוהר: אלפי לולאות של ויסות משותף, רגשות שמקבלים שם ברגע התרחשותם, שגרות ששומרות על עומס יומי סביר, שינה מוגנת, ומבוגרים שמווסתים בקול רם (\"אני מתוסכלת — אני הולכת לקחת נשימה\"). התאימו ציפיות לשלב, לא לראש הסולם. ואם הסערות של ילד נשארות עזות, ארוכות ותכופות בהרבה משל בני גילו לאורך חודשים, בלי ההתמתנות ההדרגתית שהסולם מנבא, הדפוס הזה — מתואר בספירות ובמשכים — שווה שיחה עם איש מקצוע."
    ),
    tryToday: L(
      "Regulate out loud once today: \"I'm frustrated — I'm going to take a slow breath.\" A child watching an adult climb the ladder is taking notes.",
      "וסתו בקול רם פעם אחת היום: \"אני מתוסכל — אני הולך לקחת נשימה איטית.\" ילד שצופה במבוגר מטפס בסולם רושם לעצמו הערות."
    ),
    ask: L("Which rung of the regulation ladder fits my child, and what's the next one?", "איזה שלב בסולם הוויסות מתאים לילד שלי, ומהו השלב הבא?"),
  },

  // ── Behavior & Limits ────────────────────────────────────────────────────
  {
    id: "whining",
    category: "behavior",
    domains: ["attachment_regulation"],
    ageMin: 2,
    ageMax: 6,
    minutes: 3,
    concerns: ["regulation"],
    title: L("Whining: what the voice is telling you, and how to answer", "יבבנות: מה הקול הזה אומר לכם, ואיך לענות"),
    hook: L("The whine is practically engineered to be impossible to ignore — and it usually signals an empty tank, not a manipulative child.", "היבבה כמעט מהונדסת להיות בלתי אפשרית להתעלמות — ובדרך כלל היא מאותתת על מיכל ריק, לא על ילד מניפולטיבי."),
    keyPoints: [
      L("Whining is a half-regulated state: past calm words, not yet a meltdown. It typically appears when a child is running low — tired, hungry, under-connected.", "יבבנות היא מצב מווסת-למחצה: אחרי המילים הרגועות, עוד לא התקף. היא מופיעה בדרך כלל כשהילד על רזרבה — עייף, רעב, חסר חיבור."),
      L("It clusters at predictable times — late afternoon, right after preschool, during your busiest stretches. The cluster is information about the tank, not the character.", "היא מתקבצת בזמנים צפויים — אחר צהריים מאוחר, מיד אחרי הגן, בשעות העמוסות שלכם. הצביר הוא מידע על המיכל, לא על האופי."),
      L("Meet the need without rewarding the tone: connection, snack or rest can be given freely — the whined-for demand itself doesn't have to win.", "פגשו את הצורך בלי לתגמל את הטון: חיבור, חטיף או מנוחה אפשר לתת בשפע — הדרישה המיובבת עצמה לא חייבת לנצח."),
      L("Coach the voice once, calmly and without mockery — 'I want to hear you; try your regular voice' — then respond quickly and warmly when the regular voice arrives.", "אמנו את הקול פעם אחת, ברוגע ובלי לעג — \"אני רוצה לשמוע אותך; נסה את הקול הרגיל\" — ואז הגיבו מהר ובחום כשהקול הרגיל מגיע."),
      L("Prevention beats correction: ten minutes of undivided play before the day's known low point is associated with smoother stretches after.", "מניעה עדיפה על תיקון: עשר דקות של משחק בקשב מלא לפני נקודת השפל הידועה של היום נקשרות לרצף חלק יותר אחריה."),
    ],
    body: L(
      "Researchers who study the acoustics of children's sounds have confirmed what every parent knows: the whine sits in a register adults find almost impossible to tune out. That's not an accident — it is a distress-and-attention signal doing its job. The useful reframe is what the signal usually carries. Whining is a half-regulated state: the child is past their calm words but not yet in a meltdown. It tends to mean the tank is low — tired, hungry, overstimulated, or short on connection — and this tone is the one that has historically gotten through.\n\nLook at when it happens and a pattern usually appears. Late afternoon, when the day's reserves are spent. Right after preschool, when a child who held it together for hours releases the effort at the safest person they know — sometimes called after-school restraint collapse. During your busiest stretches, when attention is hardest to get. The cluster is data about a depleted state, not evidence of a manipulative character. Toddlers and preschoolers don't plot; they escalate along whatever gradient has worked.\n\nAnswering has two channels, and separating them is the trick. The need gets met generously: connection, a snack, a rest, a few minutes of your full attention — none of that is a reward for whining; it's refueling. The demand delivered in the whine doesn't have to win: you can hug a whining child warmly and still not buy the toy. For the voice itself, one calm coaching line without mockery — 'I want to hear you; try your regular voice' — and then the part most of us miss: respond quickly and warmly when the regular voice shows up. That fast response to the ordinary voice is the real teaching. Big irritated reactions to the whine, meanwhile, feed the loop, because for a connection-hungry child, even annoyed attention is attention.\n\nPrevention outperforms correction. Front-load connection before the known low points — ten minutes of undivided, child-led play is a small investment that parents widely report, and some research echoes, is associated with smoother behavior after. Guard the basics: sleep, food, calmer transitions. Persistent whining is best read as a prompt to audit the child's load, not their character. And irritability that is unusually intense, pervasive across settings and lasting for months is a different kind of observation — one worth bringing to a professional conversation.",
      "חוקרים שבודקים את האקוסטיקה של קולות ילדים אישרו את מה שכל הורה יודע: היבבה יושבת בתדר שמבוגרים כמעט לא מסוגלים לסנן. זה לא מקרה — זהו אות מצוקה וקשב שעושה את עבודתו. המסגור המועיל הוא מה שהאות בדרך כלל נושא. יבבנות היא מצב מווסת-למחצה: הילד עבר את המילים הרגועות אבל עוד לא הגיע להתקף. היא נוטה לומר שהמיכל ריק — עייף, רעב, מוצף, או חסר חיבור — ושהטון הזה הוא מה שעבד היסטורית.\n\nהסתכלו מתי זה קורה, ודפוס בדרך כלל יופיע. אחר צהריים מאוחר, כשעתודות היום אזלו. מיד אחרי הגן, כשילד שהחזיק את עצמו שעות משחרר את המאמץ אצל האדם הבטוח ביותר שהוא מכיר — מה שמכונה לפעמים קריסת האיפוק שאחרי הגן. בשעות העמוסות שלכם, כשקשב הכי קשה להשיג. הצביר הוא מידע על מצב מרוקן, לא ראיה לאופי מניפולטיבי. פעוטות וילדי גן לא זוממים; הם מסלימים לאורך כל שיפוע שעבד.\n\nלמענה יש שני ערוצים, וההפרדה ביניהם היא הטריק. את הצורך פוגשים בנדיבות: חיבור, חטיף, מנוחה, כמה דקות של קשב מלא — שום דבר מזה אינו פרס על יבבנות; זה תדלוק. הדרישה שנמסרה ביבבה לא חייבת לנצח: אפשר לחבק ילד מיבב בחום ועדיין לא לקנות את הצעצוע. לקול עצמו, שורת אימון רגועה אחת בלי לעג — \"אני רוצה לשמוע אותך; נסה את הקול הרגיל\" — ואז החלק שרובנו מפספסים: הגיבו מהר ובחום כשהקול הרגיל מופיע. התגובה המהירה לקול הרגיל היא ההוראה האמיתית. תגובות גדולות ומתוסכלות ליבבה, לעומת זאת, מזינות את הלולאה, כי לילד רעב לחיבור, גם קשב עצבני הוא קשב.\n\nמניעה מנצחת תיקון. הקדימו חיבור לפני נקודות השפל הידועות — עשר דקות של משחק בקשב מלא ובהובלת הילד הן השקעה קטנה שהורים רבים מדווחים, וחלק מהמחקר מהדהד, שנקשרת להתנהגות חלקה יותר אחריה. שמרו על הבסיס: שינה, אוכל, מעברים רגועים יותר. יבבנות מתמשכת נקראת הכי נכון כהזמנה לבדוק את העומס של הילד, לא את אופיו. ועצבנות עזה במיוחד, שחוצה מסגרות ונמשכת חודשים, היא תצפית מסוג אחר — כזו ששווה להביא לשיחה עם איש מקצוע."
    ),
    tryToday: L(
      "Spot your child's whiniest hour and plant ten minutes of undivided, child-led play just before it. Refuel the tank before it hits empty.",
      "אתרו את השעה הכי יבבנית של הילד ושתלו עשר דקות של משחק בקשב מלא ובהובלתו ממש לפניה. תדלקו את המיכל לפני שהוא מתרוקן."
    ),
    ask: L("Help me map when the whining happens and build a refueling plan.", "עזור לי למפות מתי היבבנות מופיעה ולבנות תוכנית תדלוק."),
  },
  {
    id: "rewards-sticker-charts",
    category: "behavior",
    domains: ["independence_adaptive_skills"],
    ageMin: 2,
    ageMax: 8,
    minutes: 4,
    title: L("Sticker charts and rewards: what they're good at, and where they stop", "טבלאות מדבקות ופרסים: במה הם טובים, ואיפה הם נעצרים"),
    hook: L("A sticker chart can kick-start a hard habit in days — the craft is knowing what to use it for, and how to retire it.", "טבלת מדבקות יכולה להניע הרגל קשה בתוך ימים — האומנות היא לדעת למה להשתמש בה, ואיך לפרוש ממנה."),
    keyPoints: [
      L("Rewards genuinely work for specific, concrete, achievable behaviors — staying in bed, trying the potty, brushing teeth — often within days.", "פרסים באמת עובדים להתנהגויות ספציפיות, מוחשיות וברות-השגה — להישאר במיטה, לנסות את הסיר, לצחצח שיניים — לרוב בתוך ימים."),
      L("Design rules: one behavior at a time, winnable from day one, sticker right after the action, and stickers once earned are never taken back.", "כללי עיצוב: התנהגות אחת בכל פעם, אפשר לזכות כבר מהיום הראשון, מדבקה מיד אחרי הפעולה, ומדבקה שהורווחה לעולם לא נלקחת בחזרה."),
      L("Research on rewards describes an association worth knowing: rewarding an activity a child already enjoys can dampen the enjoyment — save charts for genuinely hard, new habits.", "מחקר על פרסים מתאר קשר ששווה להכיר: תגמול על פעילות שהילד כבר נהנה ממנה עלול לעמעם את ההנאה — שמרו טבלאות להרגלים חדשים וקשים באמת."),
      L("Charts are bridges, not furniture: plan the fade from the start — stickers, then praise, then the habit carrying itself — and retire the chart within weeks.", "טבלאות הן גשרים, לא רהיטים: תכננו את הדעיכה מההתחלה — מדבקות, אחר כך מילה טובה, ואז ההרגל נושא את עצמו — ופרשו מהטבלה בתוך שבועות."),
      L("Rewards raise motivation, not skill: if the behavior isn't happening because the child can't yet, a chart adds pressure without ability. Feelings and affection are never chartable.", "פרסים מעלים מוטיבציה, לא מיומנות: אם ההתנהגות לא קורית כי הילד עדיין לא מסוגל, טבלה מוסיפה לחץ בלי יכולת. רגשות וחיבה לעולם אינם עניין לטבלה."),
    ],
    body: L(
      "Few parenting tools are debated as hotly as the sticker chart, and the truth is unhelpfully balanced: rewards work, and their working is exactly what to be careful with. For a specific, concrete, achievable behavior — staying in bed after lights out, sitting on the potty, teeth brushed without a chase — a visible chart plus small immediate rewards can shift things within days. Young children respond powerfully to progress they can see and touch; a chart is externalized memory and motivation for a brain still building both.\n\nDesign determines most of the outcome. One behavior at a time, phrased as a do ('stay in bed') rather than a don't. Winnable from day one — a chart the child can't score on by tomorrow teaches hopelessness, not habits. The sticker follows the action immediately; at this age, delay dilutes. Prizes stay small, and the ritual — choosing the sticker, pressing it on — quickly matters more than the trinket. Two never-rules: never remove an earned sticker, since retroactive punishment poisons the whole board; and never chart feelings or affection — behaviors only, and only ones within the child's power.\n\nThe limits deserve equal billing. A well-studied line of research on rewards describes an association every chart-owner should know: when children are rewarded for an activity they already enjoy, the enjoyment itself can fade — psychologists call it the overjustification effect. So charts belong on genuinely hard, new habits, not on reading, kindness or anything you hope becomes its own reward. Charts also drift: the child who asks 'what do I get?' for ordinary cooperation is telling you the tool has overstayed. The fix is planning the fade from day one — stickers thin out, specific praise carries more of the load, and within weeks the chart retires with a small celebration of the habit that now stands on its own.\n\nAnd one boundary matters more than all the design tips: rewards raise motivation, not ability. If a behavior isn't happening because the skill isn't there yet — a five-year-old who cannot yet manage the frustration the chart demands — rewards add pressure without adding capacity, and the chart quietly becomes a record of failure. When a chart keeps not working, the question is rarely 'bigger prize?' and usually 'is this a skill gap?' The strongest reward system in any home remains the boring one: attention, specific praise for effort, predictable routines, and the felt pleasure of getting better at things.",
      "מעט כלי הורות שנויים במחלוקת כמו טבלת המדבקות, והאמת מאוזנת באופן לא נוח: פרסים עובדים, והעובדה שהם עובדים היא בדיוק מה שצריך להיזהר איתו. להתנהגות ספציפית, מוחשית וברת-השגה — להישאר במיטה אחרי כיבוי אורות, לשבת על הסיר, שיניים מצוחצחות בלי מרדף — טבלה גלויה עם פרסים קטנים ומיידיים יכולה להזיז דברים בתוך ימים. ילדים צעירים מגיבים בעוצמה להתקדמות שאפשר לראות ולגעת בה; טבלה היא זיכרון ומוטיבציה מוחצנים עבור מוח שעדיין בונה את שניהם.\n\nהעיצוב קובע את רוב התוצאה. התנהגות אחת בכל פעם, מנוסחת כ\"עשה\" (\"להישאר במיטה\") ולא כ\"אל תעשה\". אפשר לזכות כבר מהיום הראשון — טבלה שהילד לא יכול לנקד בה עד מחר מלמדת ייאוש, לא הרגלים. המדבקה באה מיד אחרי הפעולה; בגיל הזה, דיחוי מדלל. הפרסים נשארים קטנים, והטקס — לבחור את המדבקה, להצמיד אותה — נהיה מהר חשוב יותר מהצעצוע. שני כללי \"לעולם לא\": לעולם לא מסירים מדבקה שהורווחה, כי עונש למפרע מרעיל את כל הלוח; ולעולם לא עושים טבלה לרגשות או לחיבה — התנהגויות בלבד, ורק כאלה שבכוחו של הילד.\n\nהמגבלות ראויות לאותה במה. קו מחקר מוכר על פרסים מתאר קשר שכל בעל טבלה צריך להכיר: כשילדים מתוגמלים על פעילות שהם כבר נהנים ממנה, ההנאה עצמה עלולה לדעוך — פסיכולוגים קוראים לזה אפקט ההצדקה העודפת. לכן טבלאות שייכות להרגלים חדשים וקשים באמת, לא לקריאה, לנדיבות או לכל דבר שאתם מקווים שיהפוך לפרס של עצמו. טבלאות גם נסחפות: ילד ששואל \"מה אני מקבל?\" על שיתוף פעולה רגיל אומר לכם שהכלי נשאר יותר מדי. הפתרון הוא לתכנן את הדעיכה מהיום הראשון — המדבקות מתדללות, מילה טובה ספציפית נושאת יותר מהמשקל, ובתוך שבועות הטבלה פורשת עם חגיגה קטנה של ההרגל שעכשיו עומד בכוחות עצמו.\n\nוגבול אחד חשוב מכל טיפי העיצוב: פרסים מעלים מוטיבציה, לא יכולת. אם התנהגות לא קורית כי המיומנות עוד לא שם — בן חמש שעדיין לא מסוגל לנהל את התסכול שהטבלה דורשת — פרסים מוסיפים לחץ בלי להוסיף יכולת, והטבלה הופכת בשקט לרישום של כישלון. כשטבלה שוב ושוב לא עובדת, השאלה היא כמעט אף פעם לא \"פרס גדול יותר?\" וכמעט תמיד \"האם זה פער מיומנות?\" מערכת התגמול החזקה בכל בית נשארת המשעממת: קשב, מילה טובה ספציפית על מאמץ, שגרות צפויות, וההנאה המורגשת מלהשתפר בדברים."
    ),
    tryToday: L(
      "If a chart is running, check it against three questions: one behavior? winnable today? fade planned? Fix whichever fails — or celebrate and retire it.",
      "אם רצה אצלכם טבלה, בדקו אותה מול שלוש שאלות: התנהגות אחת? אפשר לזכות היום? יש תוכנית דעיכה? תקנו את מה שנכשל — או חגגו ופרשו ממנה."
    ),
    ask: L("Should we use a sticker chart for our current challenge, or is something else better?", "האם כדאי לנו טבלת מדבקות לאתגר הנוכחי, או שמשהו אחר עדיף?"),
  },
];
