/**
 * Learn Library seed catalogue — batch 2b (behavior · sleep · play · screens).
 * Same editorial stance as batch A (see learnCardsCore.ts).
 */
import type { LocalizedText } from "../content/governance";
import type { LearnCard } from "./learnLibrary";

const L = (en: string, he: string): LocalizedText => ({ en, he });

export const LEARN_CARDS_BATCH2B: LearnCard[] = [
  // ── Behavior & Limits ────────────────────────────────────────────────────
  {
    id: "hitting-biting",
    category: "behavior",
    domains: ["attachment_regulation", "language_communication"],
    ageMin: 1,
    ageMax: 3,
    minutes: 4,
    title: L("When toddlers hit and bite: the normal arc and what works", "כשפעוטות מכים ונושכים: המסלול הרגיל ומה עובד"),
    hook: L("A hitting toddler isn't a preview of a violent future — it's a communicator whose hands are still faster than their words.", "פעוט שמכה אינו טריילר לעתיד אלים — הוא מְתקשר שהידיים שלו עדיין מהירות מהמילים שלו."),
    keyPoints: [
      L("Physical aggression typically rises in the second year and peaks somewhere around 18–30 months — before language catches up. It's an arc nearly every child walks.", "תוקפנות פיזית עולה בדרך כלל בשנה השנייה ומגיעה לשיא אי שם סביב 18–30 חודשים — לפני שהשפה מדביקה את הפער. זה מסלול שכמעט כל ילד עובר."),
      L("Hitting and biting are communication before language: frustration, overload, curiosity ('what happens if') — and for biting, often teething or sensory pressure.", "מכות ונשיכות הן תקשורת לפני שפה: תסכול, עומס, סקרנות (\"מה יקרה אם\") — ובנשיכות, לעתים קרובות בקיעת שיניים או לחץ חושי."),
      L("Respond boringly and protect: block the hand mid-air, one short flat line — 'I won't let you hit' — and tend to the hurt child first. Drama turns the button into a lever.", "הגיבו בשעמום והגנו: עצרו את היד באוויר, משפט אחד קצר ושטוח — \"אני לא אתן לך להכות\" — וטפלו קודם בילד שנפגע. דרמה הופכת את הכפתור לידית."),
      L("Teach a replacement the body can use at speed: 'gentle' practiced hand-over-hand, a stop sign, a stomp, a word for help — rehearsed in calm moments, never mid-storm.", "למדו תחליף שהגוף מסוגל לשלוף במהירות: \"בעדינות\" בתרגול יד־על־יד, סימן עצור, רקיעה, מילה לעזרה — מתורגל ברגעים רגועים, אף פעם לא באמצע הסערה."),
      L("The arc bends down as words come in. A pattern that stays intense well past the toddler years, or regularly injures, is a good conversation to have with a professional.", "המסלול יורד ככל שהמילים נכנסות. דפוס שנשאר עז הרבה אחרי גיל הפעוטות, או שפוצע באופן קבוע, הוא נושא טוב לשיחה עם איש מקצוע."),
    ],
    body: L(
      "The first time your toddler sinks teeth into a playmate's arm, it can feel like a verdict — on the child, on you, on the whole project. Developmental research reads the scene differently. Studies that follow children over time find physical aggression is close to universal in the second year, rising as mobility and desire outpace language, peaking somewhere around eighteen to thirty months, and declining steadily as words arrive. Toddlers don't learn aggression from somewhere and then unlearn it; they arrive with strong impulses and slowly grow the equipment to manage them. The hand is simply faster than the sentence.\n\nUnderneath most hits and bites is a message with no other exit: I wanted that. This is too much. You're too close. I'm out of patience and out of vocabulary. Biting carries extra layers of its own — erupting molars, the mouth as a toddler's primary instrument, the sheer sensory relief of clamping down. And some of it is pure science: a child who gets a spectacular reaction from one bite has discovered a button that reliably makes the world do something. None of this is a character finding. It's a snapshot of a nervous system mid-construction.\n\nThe response that works is unglamorous: protect, then bore. Catch the arm before it lands when you can. Keep your script short, flat and identical every time — 'I won't let you hit. Hitting hurts' — while you move bodies apart. Then give your warmth and attention to the child who was hurt, not the one who did the hurting; it models care and quietly removes the audience payoff. What doesn't help is heat: long lectures, big reactions and shaming all feed the button, and biting back or slapping the hand teaches exactly the move you're trying to retire.\n\nThe real teaching happens later, in calm. Bodies learn what they rehearse, so give the impulse somewhere to go: practice 'gentle' hand-over-hand on a parent's arm or a pet, agree on a stomp or a 'STOP' sign for anger, hand over words to request help. Narrate feelings all day so the vocabulary is loaded before it's needed. Then trust the arc — most of this fades as language grows. A pattern that stays intense and frequent well past the toddler years, or that regularly leaves marks, is worth describing — whens, whats, how often — in a good conversation with your pediatric professional.",
      "בפעם הראשונה שהפעוט שלכם נועץ שיניים בזרוע של חבר, זה יכול להרגיש כמו גזר דין — על הילד, עליכם, על כל המפעל. מחקר ההתפתחות קורא את הסצנה אחרת. מחקרים שעוקבים אחרי ילדים לאורך זמן מוצאים שתוקפנות פיזית קרובה לאוניברסלית בשנה השנייה: עולה כשהניידות והרצון עוקפים את השפה, מגיעה לשיא אי שם בין שמונה־עשר לשלושים חודשים, ויורדת בהתמדה ככל שהמילים מגיעות. פעוטות לא לומדים תוקפנות ממקום כלשהו ואז נגמלים ממנה; הם מגיעים עם דחפים חזקים ומגדלים לאט את הציוד לנהל אותם. היד פשוט מהירה מהמשפט.\n\nמתחת לרוב המכות והנשיכות יש הודעה בלי שום יציאה אחרת: רציתי את זה. זה יותר מדי. אתה קרוב מדי. נגמרו לי הסבלנות והמילים. לנשיכות יש שכבות משלהן — טוחנות שבוקעות, הפה ככלי העבודה הראשי של פעוט, וההקלה החושית שבנעילת הלסת. וחלק מזה הוא מדע טהור: ילד שקיבל תגובה מרהיבה מנשיכה אחת גילה כפתור שגורם לעולם לעשות משהו באופן אמין. שום דבר מזה אינו ממצא על האופי. זה צילום של מערכת עצבים באמצע בנייה.\n\nהתגובה שעובדת לא זוהרת: להגן, ואז לשעמם. תפסו את היד לפני שהיא נוחתת כשאפשר. שמרו על תסריט קצר, שטוח וזהה בכל פעם — \"אני לא אתן לך להכות. מכות כואבות\" — בזמן שאתם מפרידים גופים. ואז תנו את החום ותשומת הלב לילד שנפגע, לא לזה שפגע; זה מדגים אכפתיות ומסיר בשקט את תגמול הקהל. מה שלא עוזר הוא חוֹם: הרצאות ארוכות, תגובות גדולות ובושה מזינים את הכפתור, ונשיכה בחזרה או מכה על היד מלמדות בדיוק את המהלך שאתם מנסים להוציא משימוש.\n\nההוראה האמיתית קורית אחר כך, ברוגע. גוף לומד את מה שהוא מתרגל, אז תנו לדחף כתובת: תרגלו \"בעדינות\" יד־על־יד על זרוע של הורה או על חיית מחמד, סכמו על רקיעה או סימן \"עצור\" לכעס, ציידו במילים לבקשת עזרה. תנו שמות לרגשות כל היום, כך שהמילון טעון לפני שצריך אותו. ואז סמכו על המסלול — רוב זה דועך ככל שהשפה גדלה. דפוס שנשאר עז ותכוף הרבה אחרי גיל הפעוטות, או שמשאיר סימנים באופן קבוע, שווה לתאר — מתי, מה, באיזו תדירות — בשיחה טובה עם איש המקצוע שלכם."
    ),
    tryToday: L(
      "In a calm moment today, play the 'gentle hands' game: guide your child's hand slowly over your arm, name it — 'gentle' — and celebrate. Five relaxed repetitions load the word for when it's needed.",
      "ברגע רגוע היום, שחקו במשחק \"ידיים עדינות\": הובילו את יד הילד לאט על הזרוע שלכם, תנו שם — \"בעדינות\" — וחגגו. חמש חזרות רגועות טוענות את המילה לרגע שבו תצטרכו אותה."
    ),
    ask: L("Build me a short, boring script for the moment my toddler hits or bites.", "בנה לי תסריט קצר ומשעמם לרגע שבו הפעוט שלי מכה או נושך."),
    concerns: ["aggression"],
  },
  {
    id: "power-struggles",
    category: "behavior",
    domains: ["attachment_regulation", "independence_adaptive_skills"],
    ageMin: 2,
    ageMax: 6,
    minutes: 4,
    title: L("Power struggles: how to step out of the tug-of-war", "מאבקי כוח: איך יוצאים ממשיכת החבל"),
    hook: L("A power struggle needs two people pulling. The move isn't to pull harder or let go of the limit — it's to put down the rope.", "מאבק כוח דורש שניים שמושכים. המהלך אינו למשוך חזק יותר או לוותר על הגבול — אלא להניח את החבל."),
    keyPoints: [
      L("Behind most defiance is a developmental project, not disrespect: somewhere around age two, children discover they are a separate person — and start field-testing it.", "מאחורי רוב ההתרסה עומד פרויקט התפתחותי, לא חוצפה: אי שם סביב גיל שנתיים ילדים מגלים שהם אדם נפרד — ומתחילים לבדוק את זה בשטח."),
      L("'No' is an achievement before it's a problem. A child asserting will is practicing the same muscle you'll want them to have at fifteen, with peers.", "\"לא\" הוא הישג לפני שהוא בעיה. ילד שמפעיל רצון מתאמן על אותו שריר שתרצו שיהיה לו בגיל חמש־עשרה, מול חברים."),
      L("Real choices within limits defuse most standoffs: two options you're equally fine with — 'coat on here or at the door' — hand over the how while you keep the what.", "בחירות אמיתיות בתוך גבולות מפרקות את רוב העימותים: שתי אפשרויות ששתיהן בסדר מבחינתכם — \"מעיל כאן או ליד הדלת\" — מוסרות את האיך בזמן שאתם שומרים על המה."),
      L("Sidestep, don't surrender: the limit stays, the fight goes. Playfulness, races and silly voices are legitimate tools, not tricks — they change the channel, not the rule.", "לעקוף, לא להיכנע: הגבול נשאר, הקרב הולך. משחקיות, תחרויות וקולות מצחיקים הם כלים לגיטימיים, לא תעלולים — הם מחליפים ערוץ, לא חוק."),
      L("When the struggle lands anyway, hold both halves: 'The answer is no, and you're allowed to be angry about it.' Feelings get room; the limit doesn't move.", "כשהמאבק מגיע בכל זאת, החזיקו את שני החצאים: \"התשובה היא לא, ומותר לך לכעוס על זה.\" לרגשות יש מקום; הגבול לא זז."),
    ],
    body: L(
      "It's 8:12 and you are negotiating with a three-year-old about which cup the milk goes in. You have explained. They have escalated. The milk is getting warm. Welcome to one of the most reliable scenes of early childhood — and one of the most misread. What looks like a discipline problem is usually an autonomy project: somewhere in the second year, children make the enormous discovery that they are a separate person with a will of their own, and then they do what humans do with new equipment. They test it, loudly, on whoever is nearest.\n\nSeen that way, the goal shifts. You're not trying to win the tug-of-war; you're trying to stop holding the rope. A head-on victory — louder voice, bigger consequence — often costs more than it buys, because for a child mid-autonomy-project, backing down in a direct contest feels like losing the self they just found. And full surrender teaches its own lesson: that escalation moves walls. The exit most parenting frameworks converge on is a third door — sidestep. The limit stays exactly where it was; the contest is what disappears.\n\nThe workhorse tool is real choice within the limit. Not 'do you want to get dressed?' (a fake question with one acceptable answer) but two doors you're equally happy with: 'red cup or the bear cup?', 'coat on here or at the door?', 'walk to the bath or fly like an airplane?'. The child steers the how; you quietly keep the what. Add the other autonomy-friendly moves: advance notice before transitions, jobs that confer status ('you're in charge of pressing the elevator button'), and playfulness — racing the timer, the sock that 'refuses' to go on. These aren't manipulations; they're offering the child a dignified way to cooperate.\n\nSome struggles will land anyway, and those moments have a shape worth practicing: warm on the feeling, firm on the line. 'You really wanted to stay. The answer is still no — and you're allowed to be mad at me about it.' Then stop talking; re-litigating invites re-negotiating. Two quiet audits help over time. Count your no's for a day — many are habit, and every recovered yes makes the remaining no's more credible. And notice the timing: struggles cluster when children are hungry, tired or rushed, which means some battles are best solved by a snack and ten minutes of margin, not a strategy.",
      "השעה 8:12 ואתם מנהלים משא ומתן עם בת שלוש על השאלה לאיזו כוס נכנס החלב. הסברתם. היא הסלימה. החלב מתחמם. ברוכים הבאים לאחת הסצנות האמינות ביותר של הילדות המוקדמת — וגם לאחת המפוענחות־לרעה ביותר. מה שנראה כבעיית משמעת הוא בדרך כלל פרויקט אוטונומיה: אי שם בשנה השנייה, ילדים עושים את התגלית העצומה שהם אדם נפרד עם רצון משלו — ואז עושים מה שבני אדם עושים עם ציוד חדש. בודקים אותו, בקול, על מי שהכי קרוב.\n\nבמבט הזה, המטרה משתנה. אתם לא מנסים לנצח במשיכת החבל; אתם מנסים להפסיק להחזיק בחבל. ניצחון חזיתי — קול רם יותר, עונש גדול יותר — עולה לרוב יותר משהוא קונה, כי לילד באמצע פרויקט אוטונומיה, לסגת בעימות ישיר מרגיש כמו לאבד את העצמי שהוא רק עכשיו מצא. וכניעה מלאה מלמדת שיעור משלה: שהסלמה מזיזה קירות. היציאה שרוב הגישות מתכנסות אליה היא דלת שלישית — עקיפה. הגבול נשאר בדיוק איפה שהיה; מה שנעלם הוא התחרות.\n\nכלי העבודה המרכזי הוא בחירה אמיתית בתוך הגבול. לא \"רוצה להתלבש?\" (שאלה מזויפת עם תשובה קבילה אחת) אלא שתי דלתות ששתיהן משמחות אתכם באותה מידה: \"כוס אדומה או כוס הדוב?\", \"מעיל כאן או ליד הדלת?\", \"הולכים לאמבטיה או טסים כמו מטוס?\". הילד מנווט את האיך; אתם שומרים בשקט על המה. הוסיפו את שאר המהלכים ידידותיי־האוטונומיה: התרעה מראש לפני מעברים, תפקידים שמעניקים מעמד (\"אתה אחראי על כפתור המעלית\"), ומשחקיות — מרוץ נגד הטיימר, הגרב ש\"מסרב\" לעלות. אלה אינם תרגילים; זו הצעת דרך מכובדת לשתף פעולה.\n\nחלק מהמאבקים יגיעו בכל זאת, ולרגעים האלה יש צורה ששווה לתרגל: חמים על הרגש, יציבים על הקו. \"ממש רצית להישאר. התשובה עדיין לא — ומותר לך לכעוס עליי על זה.\" ואז להפסיק לדבר; דיון חוזר מזמין משא ומתן חוזר. שתי בדיקות שקטות עוזרות לאורך זמן. ספרו את הלאווים שלכם במשך יום — רבים מהם הרגל, וכל כן שהוחזר הופך את הלאווים שנותרו לאמינים יותר. ושימו לב לתזמון: מאבקים מצטופפים כשילדים רעבים, עייפים או דחוקים בזמן — כלומר, חלק מהקרבות נפתרים הכי טוב עם חטיף ועשר דקות מרווח, לא עם אסטרטגיה."
    ),
    tryToday: L(
      "Pick the day's most reliable standoff and pre-build two doors: two options you're genuinely equally fine with. Offer them before the struggle starts, and let the child own the pick completely.",
      "בחרו את העימות הכי צפוי של היום ובנו מראש שתי דלתות: שתי אפשרויות שבאמת שתיהן בסדר מבחינתכם. הציעו אותן לפני שהמאבק מתחיל, ותנו לילד בעלות מלאה על הבחירה."
    ),
    ask: L("Help me redesign our worst daily standoff with choices within limits.", "עזור לי לעצב מחדש את העימות היומי הקשה שלנו עם בחירות בתוך גבולות."),
    concerns: ["transitions", "regulation"],
  },

  // ── Sleep ────────────────────────────────────────────────────────────────
  {
    id: "night-terrors",
    category: "sleep",
    domains: ["independence_adaptive_skills"],
    ageMin: 2,
    ageMax: 8,
    minutes: 3,
    title: L("Night terrors vs. nightmares: telling them apart", "ביעותי לילה מול סיוטים: איך מבחינים"),
    hook: L("A screaming child who doesn't recognize you is terrifying — until you know which of two very different events you're watching.", "ילד צורח שלא מזהה אתכם זה מבעית — עד שאתם יודעים באיזה משני אירועים שונים מאוד אתם צופים."),
    keyPoints: [
      L("Night terrors happen in the first third of the night, out of the deepest non-dream sleep: eyes may be open, the child is not actually awake, and they won't remember it. You're more scared than they are.", "ביעותי לילה קורים בשליש הראשון של הלילה, מתוך השינה העמוקה ביותר: העיניים אולי פקוחות, הילד לא באמת ער, והוא לא יזכור דבר. אתם מפוחדים יותר ממנו."),
      L("Don't wake a child mid-terror — it tends to prolong and confuse. Stay close, speak low, keep them physically safe, and let it burn out on its own.", "אל תעירו ילד באמצע ביעות — זה נוטה להאריך ולבלבל. הישארו קרובים, דברו בשקט, שמרו על בטיחותו הפיזית, ותנו לזה לדעוך מעצמו."),
      L("Nightmares are the opposite profile: later in the night, out of dream sleep, and the child wakes fully, remembers, and needs real comfort — give it generously.", "סיוטים הם הפרופיל ההפוך: מאוחר יותר בלילה, מתוך שנת חלום, והילד מתעורר לגמרי, זוכר, וזקוק לניחום אמיתי — תנו אותו בנדיבות."),
      L("Overtiredness is the classic terror trigger: an earlier bedtime, a restored nap or quiet time, and a steadier schedule are the levers that matter most.", "עייפות־יתר היא הטריגר הקלאסי לביעותים: הקדמת שעת השינה, החזרת שנ\"צ או שעת שקט, ולוח זמנים יציב יותר הם המנופים שהכי משנים."),
      L("Keep the sleep space calmly safe — clear floor, gated stairs if your child moves during episodes. Very frequent episodes, or ones with injury risk, are a good conversation to have with your pediatrician.", "שמרו על מרחב שינה בטוח ברוגע — רצפה פנויה, שער למדרגות אם הילד נע במהלך אירועים. אירועים תכופים מאוד, או כאלה עם סיכון לפציעה, הם נושא טוב לשיחה עם רופא הילדים."),
    ],
    body: L(
      "An hour or two after bedtime, a scream tears through the house. You find your child sitting up, eyes wide open, drenched and thrashing — and here is the part that undoes parents — looking straight through you, pushing away the comfort you're offering. Take a breath: you are almost certainly watching a night terror, and the single most useful fact about night terrors is that the child is not actually awake, not experiencing the fear the scene suggests, and will remember nothing in the morning. The event is dramatic on the outside and mostly empty on the inside.\n\nThe mechanics explain the strangeness. Terrors are partial arousals: the brain gets stuck between the deepest stage of non-dream sleep and waking, usually in the first third of the night when deep sleep is heaviest. Because the child isn't awake, comfort doesn't land and reasoning doesn't reach — and attempts to wake them tend to prolong the episode or produce a disoriented, frightened child who now genuinely is awake. The evidence-aligned job is quiet lifeguarding: stay near, keep your voice low, block falls and collisions, and let the wave pass — most episodes end within minutes, with the child sliding back into sleep as if nothing happened. Calm safety housekeeping helps you relax into that role: a clear floor, a gate at the stairs if your child moves around during episodes.\n\nNightmares are the mirror image, and the response flips with them. They rise out of dream sleep, which stacks up in the second half of the night; the child wakes truly and fully, knows you, remembers the dream, and needs everything a frightened person needs — arms, a low light, unhurried reassurance. Morning conversation helps with nightmares (drawing the monster, giving the dream a silly ending) and is pointless after a terror, since there's nothing on file to discuss.\n\nFor terrors, prevention lives mostly in one place: sleep debt. Overtiredness deepens the deep sleep the brain must climb out of, and terrors cluster in overtired seasons — a dropped nap, a late vacation week, a schedule gone wobbly. An earlier bedtime and steadier rhythm are unglamorous and effective. Most children simply outgrow terrors as sleep architecture matures. If episodes come many times a night, run long, involve real injury risk, or you'd just like a second opinion on the pattern — note the timing and what you see, and bring it to your pediatrician as a good conversation, not an alarm.",
      "שעה־שעתיים אחרי ההשכבה, צרחה קורעת את הבית. אתם מוצאים את הילד יושב, עיניים פקוחות לרווחה, ספוג זיעה ומפרפר — והנה החלק שמפרק הורים — מביט דרככם, הודף את הניחום שאתם מציעים. קחו נשימה: כמעט בוודאות אתם צופים בביעות לילה, והעובדה השימושית ביותר על ביעותי לילה היא שהילד לא באמת ער, לא חווה את הפחד שהסצנה מרמזת עליו, ולא יזכור דבר בבוקר. האירוע דרמטי מבחוץ וריק ברובו מבפנים.\n\nהמכניקה מסבירה את המוזרות. ביעותים הם יקיצות חלקיות: המוח נתקע בין השלב העמוק ביותר של שינה ללא חלומות לבין ערות, בדרך כלל בשליש הראשון של הלילה, כשהשינה העמוקה בשיאה. מכיוון שהילד אינו ער, ניחום לא נוחת והיגיון לא מגיע — וניסיונות להעיר נוטים להאריך את האירוע או לייצר ילד מבולבל ומבוהל שעכשיו באמת ער. התפקיד שתואם את הראיות הוא מציל שקט: להישאר קרוב, לדבר נמוך, לחסום נפילות והתנגשויות, ולתת לגל לעבור — רוב האירועים נגמרים בתוך דקות, והילד גולש חזרה לשינה כאילו כלום. סדר בטיחות רגוע עוזר לכם להירגע לתוך התפקיד: רצפה פנויה, שער במדרגות אם הילד נע במהלך אירועים.\n\nסיוטים הם תמונת הראי, והתגובה מתהפכת איתם. הם עולים מתוך שנת חלום, שמצטברת במחצית השנייה של הלילה; הילד מתעורר באמת ובמלואו, מזהה אתכם, זוכר את החלום, וזקוק לכל מה שאדם מפוחד זקוק לו — חיבוק, אור קטן, הרגעה בלתי־נחפזת. שיחת בוקר עוזרת עם סיוטים (לצייר את המפלצת, לתת לחלום סוף מצחיק) וחסרת טעם אחרי ביעות — אין שום דבר בתיק לדבר עליו.\n\nלביעותים, המניעה גרה בעיקר במקום אחד: חוב שינה. עייפות־יתר מעמיקה את השינה העמוקה שהמוח צריך לטפס ממנה החוצה, וביעותים מצטופפים בעונות עייפות — שנ\"צ שנשמט, שבוע חופשה מאוחר, לוח זמנים שהתערער. שעת שינה מוקדמת יותר וקצב יציב יותר הם פתרון לא זוהר ויעיל. רוב הילדים פשוט צומחים מתוך הביעותים ככל שארכיטקטורת השינה מבשילה. אם אירועים באים פעמים רבות בלילה, נמשכים זמן רב, כרוכים בסיכון אמיתי לפציעה, או שפשוט הייתם רוצים חוות דעת על הדפוס — רשמו את התזמון ואת מה שאתם רואים, והביאו את זה לרופא הילדים כשיחה טובה, לא כאזעקה."
    ),
    tryToday: L(
      "If night episodes have visited lately, move bedtime 20–30 minutes earlier tonight and jot the clock time of any episode. The timestamp alone usually tells you which event you're dealing with.",
      "אם אירועי לילה ביקרו לאחרונה, הקדימו הערב את שעת השינה ב־20–30 דקות ורשמו את השעה של כל אירוע. חותמת הזמן לבדה בדרך כלל מגלה עם איזה אירוע יש לכם עסק."
    ),
    ask: L("From what I'm describing, does this sound closer to a night terror or a nightmare pattern?", "לפי מה שאני מתאר, זה נשמע קרוב יותר לדפוס של ביעות לילה או של סיוט?"),
    concerns: ["sleep", "fears"],
  },
  {
    id: "nap-transitions",
    category: "sleep",
    domains: ["independence_adaptive_skills"],
    ageMin: 0,
    ageMax: 4,
    minutes: 3,
    title: L("Nap transitions without the chaos", "מעברי שנ\"צ בלי כאוס"),
    hook: L("Three naps to two, two to one, one to none — each drop has readiness signs, an awkward middle, and a bridge across it.", "משלוש שנ\"צים לשתיים, משתיים לאחת, מאחת לאפס — לכל ירידה יש סימני מוכנות, אמצע מביך, וגשר מעליו."),
    keyPoints: [
      L("The rough map: three naps consolidate to two somewhere around 6–9 months, two to one often around 13–18 months, and the last nap fades anywhere from about two-and-a-half to five. All ranges are wide and normal.", "המפה הגסה: שלוש שנ\"צים מתאחדות לשתיים אי שם סביב 6–9 חודשים, שתיים לאחת לרוב סביב 13–18 חודשים, והשנ\"צ האחרון דועך בין בערך שנתיים וחצי לחמש. כל הטווחים רחבים ותקינים."),
      L("Readiness is a two-week pattern, not a bad Tuesday: consistently fighting a nap, naps that suddenly wreck bedtime, or a new habit of very early waking.", "מוכנות היא דפוס של שבועיים, לא יום שלישי גרוע: מלחמה עקבית בשנ\"צ, שנ\"צים שפתאום הורסים את הלילה, או הרגל חדש של השכמה מוקדמת מאוד."),
      L("The in-between weeks are the hard part by design: one nap is too few and two are too many. Expect a wobbly stretch rather than a clean switch.", "השבועות שבאמצע הם החלק הקשה מעצם טבעם: שנ\"צ אחת זה מעט מדי ושתיים זה יותר מדי. צפו לתקופה מתנדנדת, לא למעבר נקי."),
      L("The universal bridge is an earlier bedtime — 30–60 minutes for a few weeks absorbs the lost daytime sleep. Alternating one-nap and two-nap days is fair play.", "הגשר האוניברסלי הוא הקדמת שעת השינה — 30–60 דקות למשך כמה שבועות סופגות את שנת היום שאבדה. לסירוגין יום של שנ\"צ אחת ויום של שתיים — לגיטימי לגמרי."),
      L("When the last nap goes, don't drop the pause: daily quiet time — same hour, same place, books and calm toys — protects the child's downshift and the parent's break.", "כשהשנ\"צ האחרון נגמר, אל תוותרו על ההפסקה: שעת שקט יומית — אותה שעה, אותו מקום, ספרים וצעצועים רגועים — שומרת על הורדת ההילוך של הילד ועל ההפסקה של ההורים."),
    ],
    body: L(
      "Just when a nap schedule finally works, it stops working — which is roughly the whole story of daytime sleep in the first years. Naps aren't a fixed asset; they're scaffolding that comes down in stages as the brain gets better at consolidating sleep into the night. The rough map: newborn sleep scatters across the day, organizes into three-ish naps, drops to two somewhere around six to nine months, to one often between thirteen and eighteen months, and the final nap dissolves anywhere from about two-and-a-half to five years old. Every one of those ranges is wide, and children hit them on their own clocks.\n\nThe practical question is always the same: is this a transition or a blip? Molars, colds, travel and developmental leaps all masquerade as nap readiness. The difference is persistence and pattern. A genuine transition announces itself for two weeks or more: the child consistently plays through a nap they used to take, the nap itself survives but bedtime turns into a battle, or early-morning waking creeps in — signs the day's sleep is now crowding the night's. One rough Tuesday is a Tuesday. Fourteen of them is a memo.\n\nThen comes the honest part: the middle is awkward for everyone, because for a few weeks one nap is genuinely too few and two are genuinely too many. The bridge that carries most families across is an earlier bedtime — thirty to sixty minutes earlier temporarily absorbs the lost daytime sleep and heads off the overtired spiral that makes everything worse. Alternating is also fair play: a two-nap day after a rough night, a one-nap day when the morning nap gets refused. Nudge the surviving nap toward its new time in fifteen-minute steps, and let a car nap patch a bad day without guilt. Wobbliness for three to six weeks is the transition working, not failing.\n\nThe last transition hides a trap worth avoiding: when the nap goes, families often drop the pause it provided — and both child and parent feel the loss by 4pm. Replace it with quiet time: same hour, same room, a basket of books and calm toys, no sleep required. Many children drift off some days anyway; the rest get a genuine downshift that steadies the late afternoon. Protect that pause like an appointment. It's the part of the nap that never needed to be outgrown.",
      "בדיוק כשלוח השנ\"צים סוף סוף עובד, הוא מפסיק לעבוד — וזה בערך כל סיפורה של שנת היום בשנים הראשונות. שנ\"צים אינם נכס קבוע; הם פיגומים שיורדים בשלבים ככל שהמוח משתפר באיחוד השינה אל תוך הלילה. המפה הגסה: שנת יילוד מפוזרת על פני היום, מתארגנת לבערך שלוש שנ\"צים, יורדת לשתיים אי שם סביב שישה עד תשעה חודשים, לאחת לרוב בין שלושה־עשר לשמונה־עשר חודשים, והשנ\"צ האחרון מתמוסס בין בערך שנתיים וחצי לחמש. כל אחד מהטווחים האלה רחב, וילדים מגיעים אליהם בשעונים משלהם.\n\nהשאלה המעשית תמיד זהה: זה מעבר או אפיזודה? טוחנות, הצטננויות, נסיעות וקפיצות התפתחות — כולם מתחפשים למוכנות. ההבדל הוא התמדה ודפוס. מעבר אמיתי מכריז על עצמו שבועיים ויותר: הילד משחק בעקביות לאורך שנ\"צ שפעם ישן בה, השנ\"צ שורדת אבל ההשכבה הופכת לקרב, או שהשכמה מוקדמת מתגנבת פנימה — סימנים ששנת היום דוחקת עכשיו את שנת הלילה. יום שלישי קשה אחד הוא יום שלישי. ארבעה־עשר כאלה הם הודעה רשמית.\n\nואז מגיע החלק הכן: האמצע מביך לכולם, כי במשך כמה שבועות שנ\"צ אחת היא באמת מעט מדי ושתיים באמת יותר מדי. הגשר שמעביר את רוב המשפחות הוא הקדמת שעת השינה — שלושים עד שישים דקות מוקדם יותר, זמנית, סופגות את שנת היום שאבדה ובולמות את ספירלת עייפות־היתר שמחמירה הכול. גם לסירוגין זה משחק הוגן: יום של שתי שנ\"צים אחרי לילה קשה, יום של אחת כשהשנ\"צ של הבוקר נדחית. הזיזו את השנ\"צ ששרדה לעבר זמנה החדש בצעדים של רבע שעה, ותנו לשנ\"צ באוטו להציל יום גרוע בלי אשמה. התנדנדות של שלושה עד שישה שבועות היא המעבר שעובד, לא שנכשל.\n\nבמעבר האחרון מסתתרת מלכודת ששווה לעקוף: כשהשנ\"צ הולך, משפחות מוותרות לרוב גם על ההפסקה שהוא סיפק — וגם הילד וגם ההורה מרגישים את האובדן עד ארבע אחר הצהריים. החליפו אותו בשעת שקט: אותה שעה, אותו חדר, סל ספרים וצעצועים רגועים, בלי חובת שינה. ילדים רבים נרדמים בחלק מהימים בכל מקרה; השאר מקבלים הורדת הילוך אמיתית שמייצבת את אחר הצהריים המאוחר. שמרו על ההפסקה הזאת כמו על פגישה. זה החלק של השנ\"צ שמעולם לא היה צריך לגדול ממנו."
    ),
    tryToday: L(
      "If a nap is wobbling, start a two-week note: nap fought or taken, bedtime mood, morning wake time. Fourteen days of data turns 'is it time?' from a debate into a pattern you can see.",
      "אם שנ\"צ מתנדנדת, פתחו רישום של שבועיים: שנ\"צ שנלחמו בה או שנלקחה, מצב הרוח בהשכבה, שעת ההשכמה. ארבעה־עשר ימי נתונים הופכים את \"הגיע הזמן?\" מוויכוח לדפוס שרואים בעיניים."
    ),
    ask: L("Based on our current schedule, does this look like nap-transition readiness or a passing phase?", "לפי הלו\"ז הנוכחי שלנו, זה נראה כמו מוכנות למעבר שנ\"צ או שלב חולף?"),
    concerns: ["sleep", "routines"],
  },
  {
    id: "early-waking",
    category: "sleep",
    domains: ["independence_adaptive_skills"],
    ageMin: 1,
    ageMax: 6,
    minutes: 3,
    title: L("The 5am club: early waking, causes and levers", "מועדון החמש בבוקר: השכמה מוקדמת, סיבות ומנופים"),
    hook: L("At 5am your child's sleep tank is nearly empty and the day-hormones are rising — which is why the tiniest nudge tips them awake, and why the fixes are mostly math and light.", "בחמש בבוקר מכל השינה של הילד כמעט ריק והורמוני היום מטפסים — ולכן הדחיפה הקטנה ביותר מעירה אותו, ולכן הפתרונות הם בעיקר חשבון ואור."),
    keyPoints: [
      L("Early waking is biology before it's behavior: by early morning, sleep pressure is at its lowest and the body's wake-up systems are already warming up. 5am is the night's weakest link.", "השכמה מוקדמת היא ביולוגיה לפני שהיא התנהגות: לפנות בוקר לחץ השינה בשפל ומערכות היקיצה של הגוף כבר מתחממות. חמש בבוקר היא החוליה החלשה של הלילה."),
      L("Run the sleep-pressure math first: a very early bedtime or generous daytime sleep can simply empty the tank by five. Check the 24-hour total against the (wide) range for the age.", "עשו קודם את חשבון לחץ השינה: שעת שינה מוקדמת מאוד או שנת יום נדיבה יכולות פשוט לרוקן את המכל עד חמש. בדקו את סך 24 השעות מול הטווח (הרחב) של הגיל."),
      L("Overtiredness cuts the other way: a too-late bedtime fragments sleep rather than extending it. The lever moves in 10–15 minute steps over weeks, not one heroic hour.", "עייפות־יתר חותכת לכיוון השני: שעת שינה מאוחרת מדי מפרקת את השינה במקום להאריך אותה. המנוף זז בצעדים של 10–15 דקות לאורך שבועות, לא בשעה הרואית אחת."),
      L("Sweep the room: dawn light through the blinds, hunger during growth spurts, a neighbor's car at 5:10. Blackout shades and a heartier dinner or bedtime snack are cheap experiments.", "סרקו את החדר: אור שחר מבעד לתריס, רעב בתקופות גדילה, אוטו של שכן ב־5:10. החשכה טובה וארוחת ערב או חטיף לילה משביעים יותר הם ניסויים זולים."),
      L("An ok-to-wake cue (a light that turns green) gives pre-clock children a visible finish line — paired with a reliably boring response until it arrives.", "סימן \"מותר לקום\" (מנורה שמתחלפת לירוק) נותן לילדים שעוד לא קוראים שעון קו סיום גלוי — לצד תגובה משעממת באופן אמין עד שהוא מגיע."),
    ],
    body: L(
      "There is a particular despair to hearing a cheerful 'Mama? MAMA!' at 5:04am, and it deserves one reframe before any strategy: your child is not choosing this against you. By the early hours, the pressure to sleep that built all day is nearly spent, the night's deep sleep is behind them, and the body's waking machinery — rising cortisol, climbing temperature — is already coming online. Sleep at 5am is shallow and cheap to break. Any small nudge — a sliver of light, a hungry stomach, a rumbling truck — can tip a child who would have dozed to 6:30 into full, chatty wakefulness. That's not defiance. It's physics with bad timing.\n\nSo start with the math. Children need a lot of sleep, but the tank has a size — broad, individual, and wide-normal at every age. A child asleep at 6:30pm with a lush afternoon nap may simply be full at 5am; the fix is gently shifting bedtime later or trimming the nap, in ten-to-fifteen-minute steps held for several days each. But note the trap on the other side: overtired children sleep worse, not longer, so a too-late bedtime often produces earlier waking, not later. If your early riser is also melting down by dinner, the counterintuitive move — an earlier bedtime — is the one to test.\n\nNext, sweep the environment, because 5am sleep is exactly when small annoyances win. Summer dawn through ordinary blinds is the classic culprit — genuine blackout changes mornings for many families. Growth-spurt hunger is another: try a heartier dinner or a small protein-and-carb bite at bedtime. And listen once at 5am for what you can't hear at noon: the heating clicking on, birds, a neighbor's routine. White noise blunts the spikes.\n\nFinally, give the morning a visible edge. Young children can't read clocks, so 'it's too early' is unfalsifiable from inside a crib. An ok-to-wake light that turns green at the agreed hour turns the rule into something the child can check — and it works only as well as the response that backs it. Before green: boring, dim, minimal service, the same six words every time. After green: warmth, curtains, the day begins. Hold the line for a couple of weeks before judging, shift the target gradually, and make peace with one more truth — some children are simply larks. For them, the win is 6:15 instead of 5:00, and an earlier parental bedtime is a legitimate part of the plan.",
      "יש ייאוש מסוים בשמיעת \"אמא? אמא!!\" עליז ב־5:04, ומגיע לו מסגור אחד מחדש לפני כל אסטרטגיה: הילד לא בוחר בזה נגדכם. לפנות בוקר, לחץ השינה שנבנה כל היום כמעט אזל, השינה העמוקה של הלילה כבר מאחוריו, ומכונת היקיצה של הגוף — קורטיזול שעולה, חום גוף שמטפס — כבר נדלקת. שינה בחמש בבוקר היא רדודה וזולה לשבירה. כל דחיפה קטנה — פס אור, בטן רעבה, משאית רועמת — יכולה להפוך ילד שהיה מנמנם עד 6:30 לערני לגמרי ומדבר. זו לא התרסה. זו פיזיקה עם תזמון גרוע.\n\nאז התחילו בחשבון. ילדים צריכים הרבה שינה, אבל למכל יש גודל — רחב, אישי, ותקין בטווח רחב בכל גיל. ילד שנרדם ב־18:30 עם שנ\"צ אחר צהריים דשנה עשוי פשוט להיות מלא בחמש; התיקון הוא הזזה עדינה של שעת השינה מאוחר יותר או קיצור השנ\"צ, בצעדים של עשר עד חמש־עשרה דקות שמחזיקים כמה ימים כל אחד. אבל שימו לב למלכודת בצד השני: ילדים עייפים מדי ישנים גרוע יותר, לא יותר — ולכן שעת שינה מאוחרת מדי מייצרת לרוב השכמה מוקדמת יותר, לא מאוחרת. אם המשכים המוקדם שלכם גם מתפרק עד ארוחת הערב, המהלך המפתיע — הקדמת שעת השינה — הוא זה ששווה לבדוק.\n\nאחר כך סרקו את הסביבה, כי שנת חמש בבוקר היא בדיוק המקום שבו מטרדים קטנים מנצחים. שחר קיץ מבעד לתריס רגיל הוא האשם הקלאסי — האפלה אמיתית משנה בקרים אצל משפחות רבות. רעב של תקופת גדילה הוא אשם נוסף: נסו ארוחת ערב משביעה יותר או ביס קטן של חלבון ופחמימה לפני השינה. והקשיבו פעם אחת בחמש למה שאי אפשר לשמוע בצהריים: מזגן שנדלק, ציפורים, שגרה של שכן. רעש לבן מקהה את הקפיצות.\n\nלבסוף, תנו לבוקר קצה גלוי. ילדים צעירים לא קוראים שעון, ולכן \"עוד מוקדם מדי\" הוא טענה שאי אפשר להפריך מתוך מיטת תינוק. מנורת \"מותר לקום\" שמתחלפת לירוק בשעה המוסכמת הופכת את הכלל למשהו שהילד יכול לבדוק — והיא עובדת בדיוק כמו התגובה שמגבה אותה. לפני הירוק: משעמם, מעומעם, שירות מינימלי, אותן שש מילים בכל פעם. אחרי הירוק: חום, וילונות, היום מתחיל. החזיקו את הקו שבועיים לפני שאתם שופטים, הזיזו את היעד בהדרגה, והשלימו עם אמת אחת נוספת — יש ילדים שהם פשוט עפרונים. אצלם הניצחון הוא 6:15 במקום 5:00, ושעת שינה מוקדמת יותר להורים היא חלק לגיטימי מהתוכנית."
    ),
    tryToday: L(
      "Tonight, run the cheapest experiment first: make the room genuinely dark (tape a towel over the light gap if needed) and note tomorrow's wake time. One variable, one night, real data.",
      "הלילה, הריצו קודם את הניסוי הזול ביותר: החשיכו את החדר באמת (הצמידו מגבת על חרך האור אם צריך) ורשמו את שעת ההשכמה מחר. משתנה אחד, לילה אחד, נתונים אמיתיים."
    ),
    ask: L("Walk me through the sleep-pressure math for my child's current schedule.", "עבור איתי על חשבון לחץ השינה של הלו\"ז הנוכחי של הילד שלי."),
    concerns: ["sleep"],
  },

  // ── Play & Learning ──────────────────────────────────────────────────────
  {
    id: "play-stages",
    category: "play",
    domains: ["social_development", "cognition_executive_function"],
    ageMin: 1,
    ageMax: 5,
    minutes: 3,
    title: L("The stages of play: why side-by-side counts as social", "שלבי המשחק: למה זה לצד זה נחשב חברתי"),
    hook: L("Two toddlers 'ignoring' each other over separate block piles aren't failing at friendship — they're exactly on the ladder.", "שני פעוטות ש\"מתעלמים\" זה מזה מעל ערימות קוביות נפרדות לא נכשלים בחברות — הם בדיוק על הסולם."),
    keyPoints: [
      L("In the 1930s, researcher Mildred Parten described a ladder of play: solitary → onlooker → parallel → associative → cooperative. It still maps beautifully onto what you see at the playground.", "בשנות השלושים תיארה החוקרת מילדרד פארטן סולם משחק: לבד ← צופה ← מקביל ← משותף־רופף ← שיתופי. הוא עדיין ממפה נהדר את מה שרואים בגן השעשועים."),
      L("The stages layer rather than replace: a five-year-old deep in cooperative games still needs and enjoys solitary play. New rungs add; old ones stay.", "השלבים נערמים ולא מוחלפים: בת חמש ששקועה במשחקים שיתופיים עדיין צריכה ונהנית ממשחק לבד. שלבים חדשים מתווספים; הישנים נשארים."),
      L("Onlooker play — intently watching other children — is study, not shyness: the child is downloading the game before attempting entry.", "משחק צפייה — התבוננות דרוכה בילדים אחרים — הוא לימוד, לא ביישנות: הילד מוריד את חוקי המשחק לפני שהוא מנסה להיכנס."),
      L("Parallel play IS social: side-by-side children track each other closely, imitate, and trade glances and objects. It's the bridge into true joint play, not a detour around it.", "משחק מקביל הוא כן חברתי: ילדים זה לצד זה עוקבים זה אחרי זה מקרוב, מחקים, ומחליפים מבטים וחפצים. זה הגשר אל משחק משותף אמיתי, לא עקיפה שלו."),
      L("Ages are approximate and ranges are wide — so match expectations (and playdates) to the child's current rung, and don't force sharing or joint games before their time.", "הגילים משוערים והטווחים רחבים — התאימו ציפיות (ומפגשי משחק) לשלב הנוכחי של הילד, ואל תכפו שיתוף או משחק משותף לפני זמנם."),
    ],
    body: L(
      "The scene worries a lot of parents: a playdate, arranged with some effort, in which the two toddlers spend an hour back to back, each absorbed in a separate pile of blocks, apparently ignoring each other completely. Is something wrong? Almost certainly not — and the framework that explains why has been useful for nearly a century. In the 1930s, researcher Mildred Parten watched preschoolers play and described a sequence of social stages: solitary play, onlooker play (watching others intently), parallel play (alongside, with similar materials, without joint action), associative play (interacting and swapping, without shared goals), and finally cooperative play — roles, rules, a common project.\n\nTwo readings of the ladder save parents unnecessary worry. First, the ages are rough and the ranges wide: solitary play dominates the first two years, parallel play blooms in the toddler and young-preschool window, associative and cooperative play typically gather strength from around three or four onward — with plenty of individual variation. Second, and more important: the stages layer rather than replace. A child doesn't graduate out of solitary play; a five-year-old orchestrating an elaborate cooperative game at kindergarten still needs stretches of absorbed alone-play at home. Each rung stays useful for life.\n\nThe two middle rungs deserve rehabilitation, because both get misread as failures. The child standing at the edge of the playground watching a game for ten minutes isn't failing to join — onlooker play is reconnaissance, downloading the rules, roles and entry points before risking a bid. And parallel play, the famous back-to-back scene, is quietly saturated with social work: watch closely and you'll see the two toddlers sneaking glances, mirroring each other's constructions, trading an occasional object like diplomats. Researchers regard it as the bridge into joint play. Side by side is how together begins.\n\nThe practical upshot is mostly about calibration. Match playdates to the actual rung: for parallel-stage toddlers, short visits, duplicate materials (two diggers beat one), and zero pressure to 'play together' work best. Skip forcing turn-taking rituals before their time — sharing grows with development, not lectures. And when your child seems 'behind' the ladder at a birthday party, remember what you're seeing is one snapshot of a wide-normal climb. If, over months, a child consistently shows little interest in other children in any mode — not watching, not alongside — that's a pattern worth describing to a professional in a good conversation. Everyone else is just climbing at their own pace.",
      "הסצנה מדאיגה הרבה הורים: מפגש משחק, שאורגן במאמץ, שבו שני הפעוטות מבלים שעה גב אל גב, כל אחד שקוע בערימת קוביות משלו, מתעלמים לכאורה זה מזה לחלוטין. משהו לא בסדר? כמעט בוודאות לא — ולמסגרת שמסבירה למה יש כמעט מאה שנות ותק. בשנות השלושים צפתה החוקרת מילדרד פארטן בילדי גן ותיארה רצף של שלבים חברתיים: משחק לבד, משחק צפייה (התבוננות דרוכה באחרים), משחק מקביל (זה לצד זה, עם חומרים דומים, בלי פעולה משותפת), משחק משותף־רופף (אינטראקציה והחלפות, בלי מטרה משותפת), ולבסוף משחק שיתופי — תפקידים, חוקים, פרויקט משותף.\n\nשתי קריאות של הסולם חוסכות להורים דאגה מיותרת. ראשית, הגילים גסים והטווחים רחבים: משחק לבד שולט בשנתיים הראשונות, משחק מקביל פורח בחלון הפעוטות וראשית הגן, משחק משותף ושיתופי צוברים כוח בדרך כלל מסביבות שלוש־ארבע והלאה — עם שונות אישית גדולה. שנית, וחשוב יותר: השלבים נערמים ולא מוחלפים. ילד לא \"מסיים\" את המשחק לבד; בת חמש שמנצחת על משחק שיתופי מורכב בגן עדיין זקוקה בבית לרצועות של משחק לבד, שקוע ומרוכז. כל שלב נשאר שימושי לכל החיים.\n\nשני השלבים האמצעיים ראויים לשיקום, כי שניהם נקראים בטעות ככישלונות. הילד שעומד בשולי גן השעשועים וצופה במשחק עשר דקות לא נכשל בהצטרפות — משחק צפייה הוא סיור מקדים: הורדת החוקים, התפקידים ונקודות הכניסה לפני שמסתכנים בניסיון. ומשחק מקביל, סצנת הגב־אל־גב המפורסמת, רווי בשקט בעבודה חברתית: הסתכלו מקרוב ותראו את שני הפעוטות גונבים מבטים, משקפים זה את הבנייה של זה, מחליפים מדי פעם חפץ כמו דיפלומטים. חוקרים רואים בו את הגשר אל המשחק המשותף. זה לצד זה — כך מתחיל ביחד.\n\nהמסקנה המעשית היא בעיקר כיול. התאימו מפגשי משחק לשלב האמיתי: לפעוטות בשלב המקביל — ביקורים קצרים, חומרים כפולים (שני מחפרים עדיפים על אחד), ואפס לחץ \"לשחק יחד\". דלגו על כפיית טקסי תורות לפני זמנם — שיתוף גדל עם התפתחות, לא עם הרצאות. וכשהילד שלכם נראה \"מאחור\" על הסולם במסיבת יום הולדת, זכרו שאתם רואים צילום אחד של טיפוס רחב־תקין. אם, לאורך חודשים, ילד מגלה בעקביות עניין מועט בילדים אחרים בכל מצב — לא צופה, לא לצד — זה דפוס ששווה לתאר לאיש מקצוע בשיחה טובה. כל השאר פשוט מטפסים בקצב שלהם."
    ),
    tryToday: L(
      "At the next playground visit, name your child's current rung — solitary, onlooker, parallel, associative, cooperative — and watch for five minutes through that lens. The 'ignoring' usually turns out to be full of glances.",
      "בביקור הבא בגן השעשועים, תנו שם לשלב הנוכחי של הילד — לבד, צופה, מקביל, משותף־רופף, שיתופי — וצפו חמש דקות דרך העדשה הזאת. ה\"התעלמות\" מתגלה בדרך כלל כמלאה במבטים."
    ),
    ask: L("What playdate setup fits my child's current play stage best?", "איזה פורמט של מפגש משחק הכי מתאים לשלב המשחק הנוכחי של הילד שלי?"),
  },
  {
    id: "loose-parts",
    category: "play",
    domains: ["cognition_executive_function"],
    ageMin: 2,
    ageMax: 8,
    minutes: 3,
    title: L("Loose parts: why the box beats the toy", "חלקים פתוחים: למה הקופסה מנצחת את הצעצוע"),
    hook: L("Every parent has watched a child abandon the gift for its box. That's not ingratitude — it's a design principle worth stealing.", "כל הורה ראה ילד נוטש את המתנה לטובת הקופסה שלה. זו לא כפיות טובה — זה עיקרון תכנון ששווה לגנוב."),
    keyPoints: [
      L("Architect Simon Nicholson's 'loose parts' idea, from 1971: the creativity an environment invites is proportional to the number of variables in it — things that can be moved, combined, repurposed.", "רעיון \"החלקים הפתוחים\" של האדריכל סיימון ניקולסון, מ־1971: היצירתיות שסביבה מזמינה יחסית למספר המשתנים שבה — דברים שאפשר להזיז, לשלב, ולהסב לתפקיד חדש."),
      L("A one-function toy finishes: press the button, hear the sound, done. Open-ended materials have no script to complete, so play with them runs longer and returns fresh.", "צעצוע חד־תכליתי נגמר: לוחצים על הכפתור, שומעים את הצליל, סוף. לחומרים פתוחים אין תסריט להשלים, ולכן המשחק בהם נמשך יותר וחוזר רענן."),
      L("The same stick is a spoon, a sword, a wand and a bridge in one afternoon — each conversion is the child doing the cognitive work a scripted toy does for them.", "אותו מקל הוא כף, חרב, שרביט וגשר באותו אחר צהריים — כל הסבה כזאת היא הילד שעושה את העבודה הקוגניטיבית שצעצוע מתוסרט עושה במקומו."),
      L("A junk-drawer play kit costs nothing: cardboard, tape, fabric scraps, tubes, lids, clothespins, stones. For under-threes, keep pieces bigger than a mouth — the calm safety check.", "ערכת משחק ממגירת הגרוטאות לא עולה כלום: קרטון, סלוטייפ, פיסות בד, גלילים, מכסים, אטבים, אבנים. מתחת לגיל שלוש, שמרו על חלקים גדולים מפֶּה — בדיקת הבטיחות הרגועה."),
      L("The adult's job is supply and restraint: offer materials, rotate them, tolerate contained mess — and resist explaining what the things are 'for'.", "תפקיד המבוגר הוא אספקה ואיפוק: להציע חומרים, לסובב אותם, לסבול בלגן תָחום — ולהתאפק מלהסביר בשביל מה הדברים \"נועדו\"."),
    ],
    body: L(
      "It's a running joke of every birthday: the carefully chosen gift is admired for four minutes, and the box it came in becomes a boat, a house, a robot costume and a cave for the next two weeks. In 1971, the architect Simon Nicholson gave the joke a theory. His 'theory of loose parts' proposed that the creativity an environment invites is proportional to the number and kind of variables in it — things that can be moved, carried, stacked, combined and reassigned. A beach is endlessly engaging because everything on it is a variable. A perfect plastic playset, where every piece has one sanctioned function, offers almost none.\n\nThe mechanism is visible in any living room. A toy with one function completes: press the button, hear the moo, done — and the play session with it tends to be short and closed. Open-ended materials never complete. A cardboard tube isn't finished being a telescope, because it can still become a tunnel, a leg, a trumpet and a chute — and every one of those conversions is the child performing the imaginative and problem-solving work that a scripted toy performs on their behalf. Educators who observe children's play consistently report longer, deeper, more elaborated engagement around open materials; the play grows over days instead of wearing out, because the material meets the child wherever today's idea happens to be.\n\nThe practical good news is that this is the cheapest upgrade in parenting. A loose-parts kit assembles itself from the recycling and the junk drawer: boxes and tubes, tape (the premium ingredient — be generous), fabric scraps, lids, clothespins, cups, string, stones and pinecones from the park. For children under three, run the calm safety check — pieces bigger than a mouth, no long unsupervised cords — and then relax. Store the collection in one bin, and rotate: materials that vanish for two weeks return with their novelty reset.\n\nThe harder ingredient is adult restraint. Loose parts work precisely because nobody says what they're for — so offer the bin without instructions, join as an assistant rather than a director ('what should I hold?'), and let constructions be whatever the child says they are. Contain the chaos rather than banning it: a mat or tray defines where the mess lives, and cleanup becomes sorting, which conveniently is also play. Then watch what the box does that the toy couldn't.",
      "זו בדיחה קבועה של כל יום הולדת: המתנה שנבחרה בקפידה זוכה להערצה במשך ארבע דקות, והקופסה שבה הגיעה הופכת לסירה, בית, תחפושת רובוט ומערה לשבועיים הקרובים. ב־1971 נתן האדריכל סיימון ניקולסון לבדיחה תיאוריה. \"תורת החלקים הפתוחים\" שלו הציעה שהיצירתיות שסביבה מזמינה יחסית למספר ולסוג המשתנים שבה — דברים שאפשר להזיז, לסחוב, לערום, לשלב ולהסב. חוף ים מרתק בלי סוף כי הכול בו משתנה. ערכת משחק פלסטיק מושלמת, שבה לכל חלק תפקיד מאושר אחד, מציעה כמעט כלום.\n\nהמנגנון גלוי בכל סלון. צעצוע עם תפקיד אחד מסתיים: לוחצים על הכפתור, שומעים את ה\"מו\", סוף — והמשחק איתו נוטה להיות קצר וסגור. חומרים פתוחים לא מסתיימים לעולם. גליל קרטון לא סיים להיות טלסקופ, כי הוא עוד יכול להפוך למנהרה, לרגל, לחצוצרה ולמגלשה — וכל אחת מההסבות האלה היא הילד שמבצע את עבודת הדמיון ופתרון הבעיות שצעצוע מתוסרט מבצע במקומו. אנשי חינוך שצופים במשחק ילדים מדווחים בעקביות על עיסוק ארוך, עמוק ומפורט יותר סביב חומרים פתוחים; המשחק גדל לאורך ימים במקום להישחק, כי החומר פוגש את הילד בכל מקום שבו הרעיון של היום נמצא.\n\nהבשורה המעשית הטובה: זה השדרוג הזול ביותר בהורות. ערכת חלקים פתוחים מרכיבה את עצמה מהמחזור וממגירת הגרוטאות: קופסאות וגלילים, סלוטייפ (המרכיב היוקרתי — היו נדיבים), פיסות בד, מכסים, אטבי כביסה, כוסות, חוט, אבנים ואצטרובלים מהפארק. מתחת לגיל שלוש, הריצו את בדיקת הבטיחות הרגועה — חלקים גדולים מפה, בלי חוטים ארוכים בלי השגחה — ואז הירגעו. אחסנו את האוסף בארגז אחד, וסובבו: חומרים שנעלמים לשבועיים חוזרים עם החידוש מאופס.\n\nהמרכיב הקשה יותר הוא איפוק של המבוגר. חלקים פתוחים עובדים בדיוק כי אף אחד לא אומר בשביל מה הם — אז הציעו את הארגז בלי הוראות, הצטרפו כעוזרים ולא כבמאים (\"מה להחזיק?\"), ותנו למבנים להיות מה שהילד אומר שהם. תַחמו את הכאוס במקום לאסור אותו: מחצלת או מגש מגדירים איפה הבלגן גר, והסידור הופך למיון — שהוא, בנוחות, גם משחק. ואז תראו מה הקופסה עושה שהצעצוע לא הצליח."
    ),
    tryToday: L(
      "Fill one bin tonight from the recycling: three boxes, two tubes, tape, some fabric. Put it out tomorrow without a word of instruction and time how long the play runs.",
      "מלאו הערב ארגז אחד מהמחזור: שלוש קופסאות, שני גלילים, סלוטייפ, קצת בד. הניחו אותו מחר בלי מילת הוראה ומדדו כמה זמן המשחק נמשך."
    ),
    ask: L("What loose-parts materials fit my child's age and our apartment?", "אילו חומרים פתוחים מתאימים לגיל של הילד שלי ולדירה שלנו?"),
  },
  {
    id: "block-play-math",
    category: "play",
    domains: ["cognition_executive_function", "language_communication"],
    ageMin: 1,
    ageMax: 6,
    minutes: 3,
    title: L("Block play is early math (no worksheet required)", "משחק קוביות הוא מתמטיקה מוקדמת (בלי דף עבודה)"),
    hook: L("A wobbling tower is a physics lab, a fraction lesson and a geometry class — and the parent's main contribution is vocabulary.", "מגדל מתנדנד הוא מעבדת פיזיקה, שיעור שברים ושיעור גיאומטריה — והתרומה העיקרית של ההורה היא אוצר מילים."),
    keyPoints: [
      L("Research links block play with spatial skills and early math ideas — comparison, measurement, symmetry, part-whole — learned by hand, long before symbols.", "מחקרים קושרים משחק קוביות למיומנויות מרחביות ולרעיונות מתמטיים מוקדמים — השוואה, מדידה, סימטריה, חלק־שלם — שנלמדים בידיים, הרבה לפני סמלים."),
      L("Every tower is applied physics: balance, center of gravity, why the big block goes on the bottom. The crash is data, not failure.", "כל מגדל הוא פיזיקה יישומית: שיווי משקל, מרכז כובד, למה הקובייה הגדולה למטה. ההתרסקות היא נתון, לא כישלון."),
      L("Spatial language is the parent's lever: children who hear more words like 'taller', 'under', 'half', 'balance' and 'next to' tend to use more of them — and spatial talk relates to spatial thinking.", "שפה מרחבית היא המנוף של ההורה: ילדים ששומעים יותר מילים כמו \"גבוה יותר\", \"מתחת\", \"חצי\", \"שיווי משקל\" ו\"ליד\" נוטים להשתמש ביותר מהן — ודיבור מרחבי קשור לחשיבה מרחבית."),
      L("Building follows a loose arc — stacking, rows, bridges, enclosures, symmetric and named structures — each stage arriving on a wide-normal schedule.", "הבנייה מתקדמת בקשת רופפת — ערימה, שורות, גשרים, מתחמים, מבנים סימטריים ובעלי שם — כל שלב מגיע בלוח זמנים רחב־תקין."),
      L("Narrate lightly and wonder aloud; don't quiz. 'Which tower is taller?' offered with real curiosity beats any flashcard.", "לוו בקלילות ותהו בקול; אל תבחנו. \"איזה מגדל גבוה יותר?\" שנשאל בסקרנות אמיתית מנצח כל כרטיסיית שינון."),
    ],
    body: L(
      "Watch a four-year-old build a tower with real attention and you're watching a math lesson with no worksheet in sight. To place the next block, she estimates length and weight. To keep the tower standing, she runs live experiments in balance and center of gravity. When it crashes — and the crash is half the point — she revises a theory and rebuilds. Researchers who study early cognition keep finding relationships between rich block play and spatial skills, and between spatial skills and later comfort with mathematics. The claim isn't that blocks manufacture mathematicians; it's that stacking, comparing, halving and balancing are math ideas in their first, physical form.\n\nThe inventory is worth spelling out, because it hides in plain sight. Measurement: which block fills this gap; how many small ones equal the long one. Fractions and part-whole: two square blocks make one rectangle — a fact a three-year-old discovers by hand years before anyone writes ½. Geometry: naming, matching and rotating shapes to fit. Symmetry: the deep satisfaction of a building that matches on both sides. Physics: wide base, big blocks low, the tolerance of a wobble. Even early counting sneaks in, block by block, on the way up.\n\nThe parent's highest-value contribution is almost embarrassingly cheap: words. Studies of parent-child talk find that children who hear more spatial language — taller, shorter, under, behind, corner, edge, half, balance, next to, upside down — tend to produce more of it themselves, and spatial talk travels with spatial thinking. So narrate lightly while you play: 'you put the triangle on top of the arch'; 'this one's wider than that one'; 'whoa — it balanced!'. Wonder aloud instead of quizzing: 'I wonder which tower is taller' invites an experiment, while 'which is taller?' delivered as a test invites performance anxiety. The tone that works is a colleague's, not an examiner's.\n\nExpect the building itself to follow a loose arc, on the usual wide-normal schedule: carrying and knocking down first, then stacking somewhere in the second year, rows and bridges in the toddler years, enclosures and increasingly symmetric, named structures through the preschool window — 'a castle', with a story attached. Plain wooden blocks in good quantity beat electronic anything; the block's silence is what leaves room for the child's thinking. Keep them reachable, build alongside sometimes, and let towers fall. The crash, to a scientist this young, is the best data of the day.",
      "צפו בבת ארבע בונה מגדל בתשומת לב אמיתית ואתם צופים בשיעור מתמטיקה בלי דף עבודה באופק. כדי להניח את הקובייה הבאה היא אומדת אורך ומשקל. כדי שהמגדל יעמוד היא מריצה ניסויים חיים בשיווי משקל ובמרכז כובד. כשהוא מתרסק — וההתרסקות היא חצי מהעניין — היא מעדכנת תיאוריה ובונה מחדש. חוקרי קוגניציה מוקדמת מוצאים שוב ושוב קשרים בין משחק קוביות עשיר למיומנויות מרחביות, ובין מיומנויות מרחביות לנוחות מאוחרת יותר עם מתמטיקה. הטענה אינה שקוביות מייצרות מתמטיקאים; היא שערימה, השוואה, חצייה ואיזון הם רעיונות מתמטיים בצורתם הראשונה, הפיזית.\n\nשווה לפרוש את המלאי, כי הוא מסתתר בשטח פתוח. מדידה: איזו קובייה ממלאת את הרווח; כמה קטנות שוות אחת ארוכה. שברים וחלק־שלם: שתי קוביות ריבועיות עושות מלבן אחד — עובדה שבן שלוש מגלה בידיים שנים לפני שמישהו כותב ½. גיאומטריה: לזהות, להתאים ולסובב צורות כדי שיתאימו. סימטריה: הסיפוק העמוק של בניין שתואם משני הצדדים. פיזיקה: בסיס רחב, קוביות גדולות למטה, כמה נדנוד המגדל סובל. אפילו ספירה מוקדמת מתגנבת פנימה, קובייה אחר קובייה, בדרך למעלה.\n\nהתרומה בעלת הערך הגבוה ביותר של ההורה זולה כמעט במביך: מילים. מחקרי שיח הורה־ילד מוצאים שילדים ששומעים יותר שפה מרחבית — גבוה יותר, נמוך יותר, מתחת, מאחורי, פינה, קצה, חצי, שיווי משקל, ליד, הפוך — נוטים לייצר יותר ממנה בעצמם, ודיבור מרחבי נוסע יחד עם חשיבה מרחבית. אז לוו בקלילות תוך כדי משחק: \"שמת את המשולש על הקשת\"; \"זאת רחבה יותר מזאת\"; \"וואו — זה התאזן!\". תהו בקול במקום לבחון: \"מעניין איזה מגדל גבוה יותר\" מזמין ניסוי, בעוד \"איזה גבוה יותר?\" שנמסר כמבחן מזמין חרדת ביצוע. הטון שעובד הוא של קולגה, לא של בוחן.\n\nצפו שהבנייה עצמה תתקדם בקשת רופפת, בלוח הזמנים הרחב־תקין הרגיל: קודם סחיבה והפלה, אחר כך ערימה אי שם בשנה השנייה, שורות וגשרים בשנות הפעוטות, מתחמים ומבנים סימטריים ובעלי שם לאורך חלון הגן — \"טירה\", עם סיפור מוצמד. קוביות עץ פשוטות בכמות טובה מנצחות כל דבר אלקטרוני; השתיקה של הקובייה היא שמשאירה מקום לחשיבה של הילד. השאירו אותן בהישג יד, בנו לצדם לפעמים, ותנו למגדלים ליפול. ההתרסקות, למדענית צעירה כל כך, היא הנתון הטוב ביותר של היום."
    ),
    tryToday: L(
      "During today's building session, slip in five spatial words — taller, under, half, balance, next to — as narration, not questions. That's the whole assignment.",
      "בבנייה של היום, שלבו חמש מילים מרחביות — גבוה יותר, מתחת, חצי, שיווי משקל, ליד — כליווי, לא כשאלות. זו כל המשימה."
    ),
    ask: L("Give me ten spatial phrases to weave into block play at my child's age.", "תן לי עשרה ביטויים מרחביים לשלב במשחק קוביות בגיל של הילד שלי."),
  },

  // ── Screens & Digital ────────────────────────────────────────────────────
  {
    id: "screen-guidance",
    category: "screens",
    domains: ["ecosystem_stressors"],
    ageMin: 0,
    ageMax: 8,
    minutes: 4,
    title: L("Screen-time guidance by age: what WHO and the AAP actually say", "המלצות זמן מסך לפי גיל: מה ארגון הבריאות העולמי וה־AAP באמת אומרים"),
    hook: L("The real recommendations are milder, more specific and more useful than the guilt suggests — here they are, plainly, band by band.", "ההמלצות האמיתיות מתונות, מדויקות ושימושיות יותר משהאשמה מרמזת — הנה הן, בפשטות, רצועת גיל אחר רצועה."),
    keyPoints: [
      L("Under about 18–24 months, current guidance suggests avoiding screen media — with one named exception: video calls with people who love the child.", "מתחת לבערך 18–24 חודשים, ההנחיות הנוכחיות ממליצות להימנע ממדיה על מסך — עם חריג אחד מפורש: שיחות וידאו עם אנשים שאוהבים את הילד."),
      L("From around 18–24 months, if you introduce screens: high-quality content, together with a parent — the together is part of the recommendation, not a bonus.", "מסביבות 18–24 חודשים, אם מכניסים מסכים: תוכן איכותי, יחד עם הורה — ה\"יחד\" הוא חלק מההמלצה, לא תוספת."),
      L("Ages 2–5: the widely cited benchmark is about an hour a day of quality content, co-viewed when possible; WHO's under-5 guidance adds 'less is better'.", "גילאי 2–5: הרף המצוטט הוא בערך שעה ביום של תוכן איכותי, בצפייה משותפת כשאפשר; הנחיות ארגון הבריאות העולמי לגיל הרך מוסיפות \"פחות זה טוב יותר\"."),
      L("From school age, the guidance shifts from a number to a system: consistent family limits that protect sleep, movement, homework and face-to-face time.", "מגיל בית הספר ההנחיה עוברת ממספר לשיטה: גבולות משפחתיים עקביים שמגנים על שינה, תנועה, שיעורי בית וזמן פנים אל פנים."),
      L("The logic behind every band is displacement — what screens crowd out — which is why quality and context genuinely matter alongside minutes, and why guilt is not a strategy.", "ההיגיון מאחורי כל רצועה הוא דחיקה — מה שמסכים דוחקים החוצה — ולכן איכות והקשר באמת חשובים לצד דקות, ולכן אשמה אינה אסטרטגיה."),
    ],
    body: L(
      "Few parenting topics carry more free-floating guilt than screens, and remarkably few parents have read what the guidance actually says. So here it is, plainly. For children under about 18–24 months, both the American Academy of Pediatrics and the World Health Organization currently point the same direction: avoid screen media, with the AAP naming one explicit exception — video calls with grandparents and other loved people. Between roughly 18 and 24 months, the AAP's advice to families who choose to introduce screens is specific: pick high-quality content and watch it together; a toddler parked alone with a stream is the pattern the guidance is written against. For ages two to five, the widely cited benchmark is about an hour a day of good content, co-viewed when possible — WHO's under-five guidance draws a similar hour line and adds that less is better. From school age, the number gives way to a system: consistent limits, agreed as a family, that keep screens from crowding out sleep, physical activity, schoolwork and face-to-face time.\n\nReading the logic behind the bands matters more than memorizing them. These aren't rays-from-the-screen warnings; the working concern in the research is displacement. A young child's development runs on serve-and-return interaction, movement, sleep and hands-on play — and screen hours are hours those things aren't happening. That's also why the age bands tighten as children get younger: the younger the child, the more of their waking day is developmental workload, and the less an on-screen substitute delivers (young children learn far less from video than from live interaction — the well-documented video deficit).\n\nIt's also why quality and context genuinely change the math. An hour of slow, story-driven content watched with a parent who talks about it afterward is a different event from an hour of algorithmic autoplay alone in a bedroom — same minutes, different displacement, different residue. The highest-yield rules in the research are contextual, not numeric: no screens in the hour before bed, none during meals, devices out of bedrooms overnight, and an adult in the loop for young viewers.\n\nLast, the emotional part: guilt is not a strategy. Every real family exceeds the benchmarks sometimes — flights, illness, the week a sibling arrived. The guidance describes a healthy pattern, not a daily verdict, and children grow on patterns. If your current pattern isn't the one you want, skip the self-sentencing and adjust one structural thing — the bedtime hour, the meal rule, the autoplay setting — and let it hold. A calm, slightly-imperfect system beats a perfect one abandoned by Thursday.",
      "מעט נושאי הורות נושאים יותר אשמה צפה ממסכים, ומעט הורים להפליא קראו מה ההנחיות באמת אומרות. אז הנה, בפשטות. לילדים מתחת לבערך 18–24 חודשים, גם האקדמיה האמריקאית לרפואת ילדים (AAP) וגם ארגון הבריאות העולמי מצביעים כיום לאותו כיוון: להימנע ממדיה על מסך, כשה־AAP נוקב בחריג מפורש אחד — שיחות וידאו עם סבים ואנשים אהובים אחרים. בין בערך 18 ל־24 חודשים, העצה של ה־AAP למשפחות שבוחרות להכניס מסכים היא ספציפית: בחרו תוכן איכותי וצפו בו יחד; פעוט שהוחנה לבד מול זרם תוכן הוא הדפוס שההנחיה נכתבה נגדו. לגילאי שנתיים עד חמש, הרף המצוטט הוא בערך שעה ביום של תוכן טוב, בצפייה משותפת כשאפשר — הנחיות ארגון הבריאות העולמי לגיל הרך מותחות קו שעה דומה ומוסיפות שפחות זה טוב יותר. מגיל בית הספר המספר מפנה את מקומו לשיטה: גבולות עקביים, מוסכמים כמשפחה, ששומרים שמסכים לא ידחקו שינה, פעילות גופנית, לימודים וזמן פנים אל פנים.\n\nלקרוא את ההיגיון מאחורי הרצועות חשוב יותר מלשנן אותן. אלה לא אזהרות מפני קרינה מהמסך; הדאגה העובדת במחקר היא דחיקה. ההתפתחות של ילד צעיר רצה על אינטראקציית הגשה־והחזרה, תנועה, שינה ומשחק בידיים — ושעות מסך הן שעות שבהן הדברים האלה לא קורים. זו גם הסיבה שהרצועות מתהדקות ככל שהילד צעיר יותר: ככל שהילד צעיר, חלק גדול יותר מיום הערות שלו הוא עבודת התפתחות, ותחליף על מסך מספק פחות (ילדים צעירים לומדים הרבה פחות מווידאו מאשר מאינטראקציה חיה — \"גירעון הווידאו\" המתועד היטב).\n\nוזו גם הסיבה שאיכות והקשר באמת משנים את החשבון. שעה של תוכן איטי וסיפורי בצפייה עם הורה שמדבר עליו אחר כך היא אירוע אחר משעה של ניגון אוטומטי אלגוריתמי לבד בחדר — אותן דקות, דחיקה אחרת, משקע אחר. הכללים עם התשואה הגבוהה ביותר במחקר הם הקשריים, לא מספריים: בלי מסכים בשעה שלפני השינה, בלי מסכים בארוחות, מכשירים מחוץ לחדרי שינה בלילה, ומבוגר בלולאה אצל צופים צעירים.\n\nולבסוף, החלק הרגשי: אשמה אינה אסטרטגיה. כל משפחה אמיתית חורגת מהרפים לפעמים — טיסות, מחלה, השבוע שבו נולד אח. ההנחיות מתארות דפוס בריא, לא גזר דין יומי, וילדים גדלים על דפוסים. אם הדפוס הנוכחי אינו זה שאתם רוצים, דלגו על גזירת הדין העצמית ושנו דבר מבני אחד — שעת הערב, כלל הארוחות, הגדרת הניגון האוטומטי — ותנו לו להחזיק. שיטה רגועה וקצת לא מושלמת מנצחת שיטה מושלמת שננטשת עד יום חמישי."
    ),
    tryToday: L(
      "Pick one context rule instead of a number today — screens off in the hour before bed, or no screens at meals — write it where everyone sees it, and let it run for two weeks before judging.",
      "בחרו היום כלל הקשר אחד במקום מספר — מסכים כבויים בשעה שלפני השינה, או בלי מסכים בארוחות — כתבו אותו במקום שכולם רואים, ותנו לו לרוץ שבועיים לפני שאתם שופטים."
    ),
    ask: L("Help me draft a realistic family media plan for our ages and schedule.", "עזור לי לנסח תוכנית מדיה משפחתית ריאלית לגילאים וללו\"ז שלנו."),
    concerns: ["screens"],
  },
  {
    id: "video-calls",
    category: "screens",
    domains: ["ecosystem_stressors", "language_communication"],
    ageMin: 0,
    ageMax: 3,
    minutes: 3,
    title: L("Video calls: the screen exception that works", "שיחות וידאו: חריג המסך שעובד"),
    hook: L("Even the most cautious screen guidance carves out one exception for babies — and the reason it works tells you a lot about all the others.", "אפילו הנחיות המסך הזהירות ביותר מחריגות דבר אחד לתינוקות — והסיבה שהוא עובד מלמדת הרבה על כל השאר."),
    keyPoints: [
      L("Guidance that suggests avoiding screens before 18–24 months explicitly exempts video calls — the AAP names video-chatting as the carve-out.", "הנחיות שממליצות להימנע ממסכים לפני 18–24 חודשים מחריגות במפורש שיחות וידאו — ה־AAP נוקב בשיחת וידאו כחריג."),
      L("The magic word is contingent: a real person responding in real time to this child. Contingency is exactly what prerecorded video lacks — and what the 'video deficit' is made of.", "מילת הקסם היא הֵיענוּת: אדם אמיתי שמגיב בזמן אמת לילד הזה. ההיענות היא בדיוק מה שחסר לווידאו מוקלט — וממנה עשוי \"גירעון הווידאו\"."),
      L("Studies find young children can learn words and routines from responsive video chat where identical prerecorded footage teaches little — the responsiveness, not the screen, is the active ingredient.", "מחקרים מוצאים שילדים צעירים מסוגלים ללמוד מילים ודפוסים משיחת וידאו נענית, בעוד אותם צילומים מוקלטים מלמדים מעט — המרכיב הפעיל הוא ההיענות, לא המסך."),
      L("Grandparent calls double as language practice and relationship glue: turn-taking, naming, waving, peekaboo — real conversation at a distance.", "שיחות עם סבים הן גם תרגול שפה וגם דבק של קשר: תורות, שמות, נפנוף, קוקו — שיחה אמיתית ממרחק."),
      L("Short and supported is the recipe, and it's fine even under two: a parent on the lap, narrating and bridging, and a warm ending before attention runs out.", "קצר ונתמך הוא המתכון, והוא בסדר גם מתחת לגיל שנתיים: הורה על הברכיים, מלווה ומתווך, וסיום חם לפני שהקשב אוזל."),
    ],
    body: L(
      "Tucked inside the strictest screen guidance is a curious exception. The same recommendations that suggest avoiding screen media before 18–24 months make explicit room for one use at any age: video calls with the people who love the child. It isn't sentimentality — it's a clean application of what the research says screens do and don't deliver to young brains.\n\nThe backdrop is the video deficit: across many studies, children under about three learn noticeably less from prerecorded video than from the identical demonstration delivered live. The leading explanation is that a recording can't respond. It doesn't answer to a name, doesn't follow the child's gaze, doesn't pause when attention drifts, doesn't react when the baby waves — and young children's learning machinery is tuned precisely to that back-and-forth. Which predicts something testable: put a responsive person on the screen, and the deficit should shrink. That's what studies of video chat find — toddlers can learn new words and patterns from a live, contingent partner on screen where matched prerecorded footage teaches little. The active ingredient was never the screen; it's the responsiveness coming through it.\n\nIn family life, this cashes out mostly as the grandparent call — and it's worth seeing what that call actually is: real conversation, adapted to distance. Turn-taking as grandmother waits for a babble and answers it. Naming games — 'where's your nose?'. Waving, peekaboo through the camera, showing a toy and getting a reaction. For families separated by geography, these calls do double duty: language practice in its natural serve-and-return form, and a genuine relationship with a person the child may meet in the flesh only occasionally — research suggests even babies build recognition and warmth through regular contingent calls.\n\nThe recipe that makes it work is short and supported. A baby or young toddler shouldn't run a call alone: sit them on your lap and be the bridge — repeat grandpa's question, direct attention ('look, Saba's showing you his hat!'), hand over the toy being discussed. Keep calls inside the child's real attention span — a lovely call is often five minutes — and land it warmly before the wandering starts. And expect wandering anyway: a toddler drifting off mid-call isn't rudeness, it's a toddler. Let them orbit and return while the adults keep talking. The call doesn't need the child's continuous gaze to be doing its quiet work.",
      "בתוך הנחיות המסך המחמירות ביותר מקופל חריג מסקרן. אותן המלצות שמציעות להימנע ממדיה על מסך לפני גיל 18–24 חודשים מפנות מקום מפורש לשימוש אחד בכל גיל: שיחות וידאו עם האנשים שאוהבים את הילד. זו לא סנטימנטליות — זה יישום נקי של מה שהמחקר אומר שמסכים נותנים ולא נותנים למוחות צעירים.\n\nהרקע הוא גירעון הווידאו: במחקרים רבים, ילדים מתחת לבערך גיל שלוש לומדים פחות באופן ניכר מווידאו מוקלט מאשר מאותה הדגמה בדיוק כשהיא חיה. ההסבר המוביל: הקלטה לא יכולה להגיב. היא לא עונה לשם, לא עוקבת אחרי מבט הילד, לא עוצרת כשהקשב נודד, לא מגיבה כשהתינוק מנפנף — ומכונת הלמידה של ילדים צעירים מכוונת בדיוק להלוך־ושוב הזה. מכאן נגזרת תחזית שאפשר לבדוק: שימו אדם מגיב על המסך, והגירעון אמור להצטמק. זה מה שמחקרי שיחות וידאו מוצאים — פעוטות מסוגלים ללמוד מילים ודפוסים חדשים משותף חי ונענה על מסך, במקום שבו צילומים מוקלטים תואמים מלמדים מעט. המרכיב הפעיל מעולם לא היה המסך; זו ההיענות שעוברת דרכו.\n\nבחיי משפחה זה מתממש בעיקר בשיחת הסבים — ושווה לראות מה השיחה הזאת באמת: שיחה אמיתית, מותאמת למרחק. תורות, כשסבתא מחכה למלמול ועונה לו. משחקי שמות — \"איפה האף שלך?\". נפנוף, קוקו דרך המצלמה, להראות צעצוע ולקבל תגובה. למשפחות שהגיאוגרפיה מפרידה ביניהן, השיחות האלה עושות עבודה כפולה: תרגול שפה בצורת ההגשה־וההחזרה הטבעית שלה, וקשר אמיתי עם אדם שהילד אולי פוגש בגוף רק לעתים — מחקרים מרמזים שאפילו תינוקות בונים זיהוי וחום דרך שיחות נענות קבועות.\n\nהמתכון שגורם לזה לעבוד הוא קצר ונתמך. תינוק או פעוט צעיר לא אמורים לנהל שיחה לבד: הושיבו אותם על הברכיים והיו הגשר — חזרו על השאלה של סבא, כוונו קשב (\"תראה, סבא מראה לך את הכובע!\"), הגישו את הצעצוע שמדברים עליו. שמרו על שיחות בתוך טווח הקשב האמיתי של הילד — שיחה מקסימה היא לרוב חמש דקות — והנחיתו אותה בחום לפני שהשוטטות מתחילה. וצפו לשוטטות בכל מקרה: פעוט שנודד באמצע שיחה אינו גס רוח, הוא פעוט. תנו לו להקיף ולחזור בזמן שהמבוגרים ממשיכים לדבר. השיחה לא צריכה מבט רציף של הילד כדי לעשות את עבודתה השקטה."
    ),
    tryToday: L(
      "Schedule one five-minute video call with a loved one this week, with a plan: one naming game, one object to show, and a warm goodbye before attention runs out.",
      "קבעו השבוע שיחת וידאו אחת של חמש דקות עם אדם אהוב, עם תוכנית: משחק שמות אחד, חפץ אחד להראות, ופרידה חמה לפני שהקשב אוזל."
    ),
    ask: L("Give me a five-minute video-call script my toddler and their grandparents will both enjoy.", "תן לי תסריט לשיחת וידאו של חמש דקות שגם הפעוט שלי וגם הסבים ייהנו ממנה."),
    concerns: ["screens"],
  },
];
