/**
 * Learn Library seed catalogue — batch 2a (minds · language · feelings ·
 * behavior). Editorial stance per learnLibrary.ts design rules: general
 * developmental education, wide-normal ranges, no diagnosis-shaped copy.
 * EN/HE are parallel transcreations, not translations.
 */
import type { LocalizedText } from "../content/governance";
import type { LearnCard } from "./learnLibrary";

const L = (en: string, he: string): LocalizedText => ({ en, he });

export const LEARN_CARDS_BATCH2A: LearnCard[] = [
  // ── Growing Minds ────────────────────────────────────────────────────────
  {
    id: "object-permanence",
    category: "minds",
    domains: ["cognition_executive_function", "attachment_regulation"],
    ageMin: 0,
    ageMax: 2,
    minutes: 3,
    title: L("Object permanence: why peekaboo is serious science", "קביעות אובייקט: למה קוקו הוא מדע רציני"),
    hook: L("When you hide behind your hands, your baby is working on one of infancy's biggest questions: do things still exist when you can't see them?", "כשאתם מתחבאים מאחורי הידיים, התינוק שלכם עובד על אחת השאלות הגדולות של הינקות: האם דברים ממשיכים להתקיים כשלא רואים אותם?"),
    keyPoints: [
      L("Object permanence is the understanding that hidden things go on existing — a discovery babies build gradually across the first two years.", "קביעות אובייקט היא ההבנה שדברים מוסתרים ממשיכים להתקיים — תגלית שתינוקות בונים בהדרגה לאורך השנתיים הראשונות."),
      L("Before it develops, out of sight really is out of existence: a toy covered by a cloth simply stops mattering.", "לפני שהיא מתפתחת, מה שמחוץ לעין באמת אינו קיים: צעצוע שכוסה במטפחת פשוט מפסיק לעניין."),
      L("Peekaboo delights babies because it plays at the exact edge of the skill: you vanish, the prediction wobbles, you return — relief and joy.", "קוקו מצחיק תינוקות כי הוא משחק בדיוק על קצה היכולת: אתם נעלמים, התחזית מתערערת, אתם חוזרים — הקלה ושמחה."),
      L("It links to separation: a baby who now knows you exist while gone may protest your leaving more — that's cognitive progress, not a step backward.", "יש לה קשר לפרידה: תינוק שכבר יודע שאתם קיימים גם כשאינכם בחדר עשוי למחות יותר על היציאה — זו התקדמות קוגניטיבית, לא נסיגה."),
      L("Everyday hiding games — a toy under a cup, a scarf over your face — are all the practice it needs; timing varies widely and healthily.", "משחקי הסתרה יומיומיים — צעצוע מתחת לכוס, צעיף על הפנים — הם כל התרגול שנדרש; התזמון משתנה מאוד, ובאופן בריא."),
    ],
    body: L(
      "Drop a toy off the high-chair tray in front of a young baby and watch what happens: often, nothing. No searching, no protest — for a mind that hasn't yet built object permanence, the toy didn't fall somewhere; it stopped being. The understanding that objects keep existing when they leave your sight seems so obvious to adults that it's easy to forget it had to be constructed. Developmental psychology, going back to Jean Piaget's observations, treats it as one of the foundational achievements of infancy.\n\nIt arrives in steps, not a switch. Young infants lose interest the moment something is covered. A few months on, they track a falling object with their eyes, then start pulling the cloth off a hidden toy — one of the great detective moments of the first year. By toddlerhood the skill runs deep: they hunt for the ball behind the couch, remember which cupboard holds the crackers, and notice immediately when a beloved object is not where it lives. The timing of each step varies widely from baby to baby, and the order matters more than the calendar.\n\nThis is why peekaboo never gets old. The game sits precisely on the edge of what the baby is figuring out: a face exists, vanishes, and — against last month's expectations — comes back. As the understanding firms up, the game changes character: the baby starts anticipating the return, then takes over the hiding. The same discovery has a tender side effect. Once a baby knows you continue to exist while out of the room, your absence becomes a real fact to have feelings about. Fresh protest at goodbyes late in the first year is often this new knowledge meeting attachment — a milestone wearing an inconvenient costume.\n\nNo program is needed to build any of this. Hide a toy under a cup and let them find it. Cover your face with a scarf. Narrate your comings and goings — \"I'm going to the kitchen, I'll be right back\" — and reliably come back. Every round of found-it is a small experiment confirming a big truth: things, and people, persist.",
      "הפילו צעצוע ממגש הטרמפולינה מול תינוק צעיר ושימו לב מה קורה: לעיתים קרובות — כלום. בלי חיפוש, בלי מחאה. עבור מוח שעדיין לא בנה קביעות אובייקט, הצעצוע לא נפל לאנשהו; הוא חדל להיות. ההבנה שעצמים ממשיכים להתקיים כשהם יוצאים משדה הראייה נראית למבוגרים כל כך מובנת מאליה, שקל לשכוח שהיה צריך לבנות אותה. הפסיכולוגיה ההתפתחותית, עוד מתצפיותיו של ז'אן פיאז'ה, רואה בה מהישגי היסוד של הינקות.\n\nהיא מגיעה בשלבים, לא במתג. תינוקות צעירים מאבדים עניין ברגע שמשהו מכוסה. כמה חודשים אחר כך הם עוקבים בעיניים אחרי חפץ נופל, ואז מתחילים למשוך את המטפחת מעל צעצוע מוסתר — מרגעי הבילוש הגדולים של השנה הראשונה. בגיל הפעוטות היכולת כבר עמוקה: הם מחפשים את הכדור מאחורי הספה, זוכרים באיזה ארון גרים הקרקרים, ומבחינים מיד כשחפץ אהוב אינו במקומו. התזמון של כל שלב משתנה מאוד מתינוק לתינוק, והסדר חשוב יותר מהלוח.\n\nלכן קוקו לא מתיישן. המשחק יושב בדיוק על קצה מה שהתינוק מפענח: פרצוף קיים, נעלם, ו — בניגוד לציפיות של החודש שעבר — חוזר. ככל שההבנה מתייצבת, המשחק משנה אופי: התינוק מתחיל לצפות את החזרה, ואז לוקח פיקוד על ההסתרה. לאותה תגלית יש גם תופעת לוואי מרגשת. ברגע שתינוק יודע שאתם ממשיכים להתקיים גם מחוץ לחדר, ההיעדרות שלכם הופכת לעובדה אמיתית שאפשר להרגיש כלפיה. מחאה חדשה בפרידות לקראת סוף השנה הראשונה היא לרוב הידע החדש הזה שפוגש התקשרות — אבן דרך בתחפושת לא נוחה.\n\nלא נדרשת שום תוכנית כדי לבנות את כל זה. הסתירו צעצוע מתחת לכוס ותנו להם למצוא. כסו את הפנים בצעיף. תארו בקול את היציאות והחזרות — \"אני הולכת למטבח, תכף חוזרת\" — ותחזרו באמינות. כל סיבוב של מצאתי! הוא ניסוי קטן שמאשר אמת גדולה: דברים, ואנשים, נשארים."
    ),
    tryToday: L(
      "Hide a favorite toy under a cup while your baby watches, and ask: \"Where did it go?\" The triumphant reveal is a full science experiment in one move.",
      "הסתירו צעצוע אהוב מתחת לכוס בזמן שהתינוק מסתכל, ושאלו: \"לאן הוא נעלם?\" רגע הגילוי המנצח הוא ניסוי מדעי שלם במהלך אחד."
    ),
    ask: L("Which hiding games fit my baby's stage of object permanence right now?", "אילו משחקי הסתרה מתאימים לשלב קביעות האובייקט של התינוק שלי עכשיו?"),
  },
  {
    id: "why-phase",
    category: "minds",
    domains: ["cognition_executive_function", "language_communication"],
    ageMin: 2,
    ageMax: 5,
    minutes: 3,
    title: L("The 'why?' phase: a question engine at full throttle", "שלב ה'למה?': מנוע שאלות במלוא הקיטור"),
    hook: L("A preschooler asking dozens of questions a day isn't testing your patience — they're running one of the most efficient learning programs ever observed.", "ילד גן ששואל עשרות שאלות ביום לא בוחן את הסבלנות שלכם — הוא מריץ אחת מתוכניות הלמידה היעילות שנצפו אי פעם."),
    keyPoints: [
      L("Questions are data-gathering: studies of children's everyday talk find preschoolers ask questions at a remarkable rate — and follow up when answers don't satisfy.", "שאלות הן איסוף נתונים: מחקרים על שיח יומיומי של ילדים מוצאים שילדי גן שואלים בקצב מסחרר — וממשיכים לחפור כשהתשובה לא מספקת."),
      L("A 'why' chain is sometimes hunger for mechanism and sometimes a way to keep talking with you; both are legitimate uses of a parent.", "שרשרת 'למה' היא לפעמים רעב אמיתי להסבר ולפעמים דרך להמשיך לדבר איתכם; שני השימושים בהורה לגיטימיים."),
      L("Short, honest, concrete answers beat lectures — one true sentence feeds the loop better than a paragraph.", "תשובות קצרות, כנות ומוחשיות עדיפות על הרצאות — משפט אמיתי אחד מזין את הלולאה טוב יותר מפסקה."),
      L("The turn-around question — 'what do you think?' — hands the engine back to the child and often produces wonderful theories.", "שאלת ההיפוך — \"מה אתה חושב?\" — מחזירה את המנוע לילד, ולעיתים קרובות מולידה תיאוריות נהדרות."),
      L("'I don't know — let's find out' is a top-tier answer: it models how knowledge actually works.", "\"אני לא יודעת — בוא נבדוק\" היא תשובה מהשורה הראשונה: היא מדגימה איך ידע באמת עובד."),
    ],
    body: L(
      "Somewhere around age two or three, a switch flips and the questions begin: why is the moon following us, why do dogs have tails, why do I have to sleep, why, why, why. Researchers who have counted find young children asking questions at rates that would exhaust a press conference — and, crucially, their questions aren't noise. Children track whether the answer actually explains anything, ask follow-ups when it doesn't, and remember what they were told. The 'why' phase is a mind that has discovered explanations exist, and wants them all.\n\nIt helps to know what a why-chain is doing. Often it's genuine mechanism-hunger: the child has noticed that events have causes and adults hold the map. Sometimes, especially at bedtime, it's something simpler — a way to keep the conversation, and you, in the room. Both are real needs; you just answer them differently. Mechanism-hunger gets a real answer. Connection-hunger gets a warm boundary: \"That's a big question. One more, then sleep.\"\n\nYou do not need to be an encyclopedia. Short and true beats long and complete: \"Rain comes from clouds — they're full of tiny water drops\" is a better answer for a three-year-old than the water cycle. When you don't know, say so and enjoy it: \"I don't know! Let's find out\" teaches the most useful lesson available — that not-knowing is the start of something, not an embarrassment. And the best tool in the kit is the turn-around: \"Hm, why do YOU think the moon follows us?\" Children's own theories are often glorious, and generating explanations is better exercise than receiving them.\n\nYou are also allowed to be a human with limits. Deferring — \"great question, let's talk about it at dinner\" — keeps the question welcome without draining you dry, and actually returning to it later teaches that questions are kept, not dodged. The phase itself passes; what persists is what the child learned about asking. A home where questions are met with interest, honesty and the occasional joyful 'let's find out' is quietly training a lifelong habit.",
      "אי שם סביב גיל שנתיים-שלוש נדלק מתג והשאלות מתחילות: למה הירח עוקב אחרינו, למה לכלבים יש זנב, למה צריך לישון, למה, למה, למה. חוקרים שטרחו לספור מצאו שילדים צעירים שואלים בקצב שהיה מתיש מסיבת עיתונאים — וחשוב מזה, השאלות שלהם אינן רעש. ילדים בודקים אם התשובה באמת מסבירה משהו, שואלים שאלת המשך כשהיא לא, וזוכרים מה נאמר להם. שלב ה'למה' הוא מוח שגילה שקיימים הסברים — ורוצה את כולם.\n\nעוזר להבין מה שרשרת למה עושה. לעיתים קרובות זה רעב אמיתי למנגנון: הילד שם לב שלאירועים יש סיבות ושהמבוגרים מחזיקים במפה. לפעמים, במיוחד לפני השינה, זה משהו פשוט יותר — דרך להשאיר את השיחה, ואתכם, בחדר. שני הצרכים אמיתיים; רק עונים עליהם אחרת. רעב למנגנון מקבל תשובה אמיתית. רעב לחיבור מקבל גבול חם: \"זו שאלה גדולה. עוד אחת, ואז ישנים.\"\n\nאתם לא צריכים להיות אנציקלופדיה. קצר ונכון עדיף על ארוך ושלם: \"גשם מגיע מעננים — הם מלאים טיפות מים קטנטנות\" היא תשובה טובה יותר לילד בן שלוש מכל מחזור המים. כשאתם לא יודעים, אמרו זאת ותיהנו מזה: \"אני לא יודעת! בוא נבדוק\" מלמדת את השיעור השימושי מכולם — שאי-ידיעה היא התחלה של משהו, לא מבוכה. והכלי הטוב בערכה הוא ההיפוך: \"הממ, למה אתה חושב שהירח עוקב אחרינו?\" התיאוריות של ילדים מפוארות לעיתים קרובות, ולייצר הסברים זה אימון טוב יותר מלקבל אותם.\n\nמותר לכם גם להיות בני אדם עם גבולות. דחייה — \"שאלה מצוינת, נדבר עליה בארוחת הערב\" — משאירה את השאלה רצויה בלי לרוקן אתכם, וחזרה אמיתית אליה אחר כך מלמדת ששאלות נשמרות, לא מתחמקים מהן. השלב עצמו חולף; מה שנשאר הוא מה שהילד למד על עצם השאילה. בית שבו שאלות נענות בעניין, בכנות ומדי פעם ב\"בוא נבדוק\" שמח — מאמן בשקט הרגל לכל החיים."
    ),
    tryToday: L(
      "Next 'why?', try the turn-around before answering: \"What do you think?\" Listen to the whole theory before offering yours — it's a window into how they reason.",
      "ב'למה?' הבא, נסו את ההיפוך לפני שאתם עונים: \"מה אתה חושב?\" הקשיבו לכל התיאוריה לפני שתציעו את שלכם — זה חלון אל איך שהם חושבים."
    ),
    ask: L("How should I answer my child's endless why-questions without exhausting us both?", "איך לענות על שאלות הלמה האינסופיות של הילד שלי בלי להתיש את שנינו?"),
  },
  {
    id: "growth-mindset",
    category: "minds",
    domains: ["cognition_executive_function"],
    ageMin: 4,
    ageMax: 10,
    minutes: 4,
    title: L("Growth mindset: what praising the process actually does", "חשיבה מתפתחת: מה שבח על תהליך באמת עושה"),
    hook: L("\"You worked hard on that\" and \"you're so smart\" feel interchangeable — but they send children different messages about what to try next.", "\"עבדת קשה על זה\" ו\"איזה חכם אתה\" נשמעים דומים — אבל הם שולחים לילדים מסרים שונים על מה כדאי לנסות הלאה."),
    keyPoints: [
      L("Psychologist Carol Dweck's studies compared praising ability ('you're smart') with praising process ('you found a good strategy') — and found the two shaped different choices afterward.", "מחקריה של הפסיכולוגית קרול דוֶוק השוו שבח על יכולת (\"אתה חכם\") לשבח על תהליך (\"מצאת דרך טובה\") — ומצאו שהשניים עיצבו בחירות שונות אחר כך."),
      L("In those studies, ability-praised children more often chose safer tasks and struggled after setbacks; process-praised children more often chose challenge.", "באותם מחקרים, ילדים ששובחו על יכולת נטו לבחור משימות בטוחות יותר ולהתקשות אחרי כישלון; ילדים ששובחו על תהליך נטו לבחור אתגר."),
      L("Honest footnote: later, larger studies find smaller and more mixed effects — treat this as a sensible habit, not a lever that programs outcomes.", "הערת שוליים כנה: מחקרים מאוחרים וגדולים יותר מוצאים אפקטים קטנים ומעורבים יותר — התייחסו לזה כהרגל נבון, לא כמנוף שמתכנת תוצאות."),
      L("Process praise only works when it's true: praise the actual strategy, persistence or progress you saw — children detect inflation instantly.", "שבח על תהליך עובד רק כשהוא אמיתי: שבחו את האסטרטגיה, ההתמדה או ההתקדמות שבאמת ראיתם — ילדים מזהים אינפלציה מיד."),
      L("The word 'yet' reframes a wall as a location: 'you can't do it yet' says the story isn't over.", "המילה \"עדיין\" הופכת קיר לנקודה על מסלול: \"אתה עדיין לא מצליח\" אומרת שהסיפור לא נגמר."),
    ],
    body: L(
      "A child solves a puzzle and looks up at you. What you say next feels tiny, but it carries information — not about the puzzle, about what you value. \"You're so smart\" points at a fixed trait the child either has or doesn't. \"You kept trying different corners until it worked\" points at something the child did, and could do again on a harder puzzle. This is the heart of Carol Dweck's research on mindset: in her studies, children praised for ability tended afterward to pick tasks they could ace, and to read struggle as evidence they'd hit their limit; children praised for process more often chose the harder task and treated struggle as normal work.\n\nAn honest telling includes the footnote. The original findings sparked an enormous literature, and later, larger replications have found smaller, more mixed effects than the early headlines suggested — mindset interventions are not a magic lever, and no praise style programs a child's future. What survives the debate is more modest and more useful: praise is information about what earns your attention, and pointing it at strategy, effort and progress costs nothing and aligns with the truth of how skills are built.\n\nWhat does process praise sound like in practice? Specific and honest. \"You tried three ways to make the bridge stand\" — when they did. \"That part was frustrating and you stayed with it\" — when they stayed. Avoid the trap of praising effort that wasn't there; children know, and empty 'great effort!' teaches them your words are decoration. When something came easily, you can even say so lightly: \"That was easy for you — want a harder one?\" And when they hit a wall, the smallest useful word is 'yet': \"You can't tie it yet.\" It doesn't deny the wall; it dates it.\n\nThe strongest channel, as usual, is you. Children study how their parents meet their own mistakes. Narrating your process — \"my plan didn't work, let me try another way\" — shows them that competent adults are people mid-practice, not people past it. That lesson doesn't depend on any study's effect size.",
      "ילד פותר פאזל ומרים אליכם מבט. מה שתגידו עכשיו מרגיש זעיר, אבל הוא נושא מידע — לא על הפאזל, על מה שחשוב לכם. \"איזה חכם אתה\" מצביע על תכונה קבועה שלילד יש או אין. \"המשכת לנסות פינות שונות עד שהצליח\" מצביע על משהו שהילד עשה — ויכול לעשות שוב בפאזל קשה יותר. זה לב המחקר של קרול דוֶוק על מיינדסט: במחקריה, ילדים ששובחו על יכולת נטו אחר כך לבחור משימות שבטוח יצליחו בהן, ולקרוא קושי כהוכחה שהגיעו לתקרה; ילדים ששובחו על תהליך בחרו יותר במשימה הקשה והתייחסו לקושי כאל עבודה רגילה.\n\nסיפור כן כולל את הערת השוליים. הממצאים המקוריים הולידו ספרות עצומה, ושחזורים מאוחרים וגדולים יותר מצאו אפקטים קטנים ומעורבים יותר משהכותרות המוקדמות רמזו — התערבויות מיינדסט אינן מנוף קסם, ואף סגנון שבח לא מתכנת את עתידו של ילד. מה ששורד את הוויכוח צנוע יותר ושימושי יותר: שבח הוא מידע על מה שמרוויח את תשומת הלב שלכם, ולכוון אותו אל אסטרטגיה, מאמץ והתקדמות לא עולה כלום — ומתיישב עם האמת על איך מיומנויות נבנות.\n\nאיך נשמע שבח על תהליך בפועל? ספציפי וכן. \"ניסית שלוש דרכים לגרום לגשר לעמוד\" — כשבאמת ניסה. \"החלק הזה תסכל אותך ונשארת איתו\" — כשבאמת נשאר. היזהרו מהמלכודת של לשבח מאמץ שלא היה; ילדים יודעים, ו\"כל הכבוד על המאמץ!\" ריק מלמד אותם שהמילים שלכם הן קישוט. כשמשהו בא בקלות, אפשר אפילו לומר זאת בקלילות: \"זה היה קל לך — רוצה אחד קשה יותר?\" וכשהם נתקלים בקיר, המילה הקטנה והמועילה מכולן היא \"עדיין\": \"אתה עדיין לא מצליח לקשור.\" היא לא מכחישה את הקיר; היא נותנת לו תאריך.\n\nהערוץ החזק ביותר, כרגיל, הוא אתם. ילדים חוקרים איך ההורים שלהם פוגשים את הטעויות של עצמם. תיאור התהליך שלכם בקול — \"התוכנית שלי לא עבדה, אנסה דרך אחרת\" — מראה להם שמבוגרים מוכשרים הם אנשים באמצע אימון, לא אנשים שסיימו אותו. השיעור הזה לא תלוי בגודל האפקט של אף מחקר."
    ),
    tryToday: L(
      "Catch one real moment of strategy or persistence today and name exactly what you saw: \"You turned the piece around until it fit.\" Specific beats superlative.",
      "תפסו היום רגע אמיתי אחד של אסטרטגיה או התמדה ותנו שם מדויק למה שראיתם: \"סובבת את החלק עד שהתאים.\" מדויק מנצח מפוצץ."
    ),
    ask: L("What could process praise sound like for my child this week?", "איך יכול להישמע שבח על תהליך אצל הילד שלי השבוע?"),
  },

  // ── Language & Communication ─────────────────────────────────────────────
  {
    id: "reading-aloud",
    category: "language",
    domains: ["language_communication", "cognition_executive_function"],
    ageMin: 0,
    ageMax: 6,
    minutes: 4,
    title: L("Why reading aloud outperforms every app", "למה הקראה בקול מנצחת כל אפליקציה"),
    hook: L("A lap, a book and ten unhurried minutes deliver something no screen can: rare words, real conversation, and you.", "חיק, ספר ועשר דקות רגועות נותנים משהו ששום מסך לא יכול: מילים נדירות, שיחה אמיתית, ואתכם."),
    keyPoints: [
      L("Children's books are vocabulary gold: research on word frequency finds picture books contain more rare words than everyday conversation between adults.", "ספרי ילדים הם מכרה זהב של אוצר מילים: מחקרי שכיחות מילים מוצאים שבספרים מאוירים יש יותר מילים נדירות מאשר בשיחה יומיומית בין מבוגרים."),
      L("Dialogic reading — asking questions, following the child's comments, expanding their answers — turns a monologue into a conversation, and conversation is where language grows.", "הקראה דיאלוגית — לשאול שאלות, ללכת אחרי ההערות של הילד, להרחיב את התשובות — הופכת מונולוג לשיחה, ושיחה היא המקום שבו שפה צומחת."),
      L("The fortieth reading of the same book is a feature, not a bug: repetition is how young children move from hearing words to owning them.", "הקריאה הארבעים של אותו ספר היא יתרון, לא תקלה: חזרה היא הדרך שבה ילדים עוברים משמיעת מילים לבעלות עליהן."),
      L("Apps can't time their responses to your child's gaze and comments; a person reading responsively can — and that timing is the active ingredient.", "אפליקציות לא יכולות לתזמן תגובה למבט ולהערות של הילד שלכם; אדם שמקריא בהיענות — כן. והתזמון הזה הוא החומר הפעיל."),
      L("There is no performance bar: a few minutes a day, in any language you love, from birth onward, counts in full.", "אין רף ביצוע: כמה דקות ביום, בכל שפה שאתם אוהבים, מלידה והלאה — נחשבות במלואן."),
    ],
    body: L(
      "Open a picture book about a mole losing his trousers and you will meet words that almost never visit spoken conversation. Researchers who count word frequencies keep landing on the same surprise: children's books are denser in rare words than most everyday adult talk. Dinner conversation runs on a few thousand workhorse words; books casually deploy burrow, furious, enormous, vanish. A child who is read to regularly is bathing in vocabulary that ordinary days simply don't supply — years before they can read a word themselves.\n\nBut the words are only half of it. The technique researchers call dialogic reading turns the book from a script into a playing field: you ask open questions (\"what's he doing?\"), follow the child's pointing and comments, expand their answers (\"yes — a huge digger, it's lifting the dirt\"), and gradually let them tell you the story. Studies of shared reading keep finding that this back-and-forth, not the page-turning itself, is where the language gains live. The book is a conversation machine; the conversation is the point.\n\nThen there is the fortieth reading of the same book, requested tonight with total confidence. Take heart: the boredom is yours alone. For the child, repetition is the method — the first readings are for the plot, the next for the words, the later ones for the joy of predicting every page and catching you if you skip one. Deep familiarity is exactly how new words move from recognized to owned, and the mastery feeling is itself part of the pull.\n\nThis is also why no app has managed to replace a reading lap. Language grows in loops that are timed to the child — a response landing in the second their attention serves it — and software cannot see where your child is looking or hear what they just half-said. You can. Add the warmth of the lap and the ritual of the routine, and shared reading turns out to be several good things wearing one disguise: vocabulary, conversation, attention, closeness. Ten minutes counts. Any language you love counts. Starting in infancy counts — babies who chew the book are still attending the lesson.",
      "פתחו ספר מאויר על חפרפרת שאיבדה את המכנסיים ותפגשו מילים שכמעט אינן מבקרות בשיחה מדוברת. חוקרים שסופרים שכיחויות מילים נוחתים שוב ושוב על אותה הפתעה: ספרי ילדים צפופים במילים נדירות יותר מרוב הדיבור היומיומי של מבוגרים. שיחת ערב רצה על כמה אלפי מילות עבודה; ספרים משלפים בלי מאמץ מאורה, זועם, עצום, נעלם. ילד שמקריאים לו באופן קבוע טובל באוצר מילים שימים רגילים פשוט לא מספקים — שנים לפני שיקרא מילה בעצמו.\n\nאבל המילים הן רק חצי מהעניין. הטכניקה שחוקרים מכנים הקראה דיאלוגית הופכת את הספר מתסריט למגרש משחקים: שואלים שאלות פתוחות (\"מה הוא עושה?\"), הולכים אחרי ההצבעות וההערות של הילד, מרחיבים את תשובותיו (\"כן — דחפור ענק, הוא מרים את החול\"), ולאט לאט נותנים לו לספר לכם את הסיפור. מחקרים על קריאה משותפת מוצאים שוב ושוב שההלוך־ושוב הזה, לא דפדוף הדפים עצמו, הוא המקום שבו רווחי השפה גרים. הספר הוא מכונת שיחה; השיחה היא העיקר.\n\nואז יש את הקריאה הארבעים של אותו ספר, שמוזמנת הערב בביטחון מלא. התעודדו: השעמום הוא שלכם בלבד. עבור הילד, החזרה היא השיטה — הקריאות הראשונות בשביל העלילה, הבאות בשביל המילים, המאוחרות בשביל העונג לחזות כל עמוד ולתפוס אתכם אם דילגתם. היכרות עמוקה היא בדיוק הדרך שבה מילים חדשות עוברות ממוּכּרות לשלי, ותחושת השליטה היא עצמה חלק מהמשיכה.\n\nזו גם הסיבה שאף אפליקציה לא הצליחה להחליף חיק מקריא. שפה צומחת בלולאות שמתוזמנות לילד — תגובה שנוחתת בשנייה שבה הקשב שלו מגיש אותה — ותוכנה לא יכולה לראות לאן הילד שלכם מסתכל או לשמוע מה הוא בדיוק חצי-אמר. אתם כן. הוסיפו את חום החיק ואת טקס השגרה, וקריאה משותפת מתגלה ככמה דברים טובים בתחפושת אחת: אוצר מילים, שיחה, קשב, קרבה. עשר דקות נחשבות. כל שפה שאתם אוהבים נחשבת. להתחיל בינקות נחשב — תינוק שלועס את הספר עדיין נוכח בשיעור."
    ),
    tryToday: L(
      "Tonight, hand over one job: your child fills in the last word of familiar pages, or 'reads' one spread to you from the pictures. Co-telling beats listening.",
      "הערב, העבירו תפקיד אחד: הילד משלים את המילה האחרונה בעמודים מוכרים, או \"מקריא\" לכם כפולה אחת מהתמונות. לספר יחד מנצח להקשיב."
    ),
    ask: L("How can I make our reading time more of a conversation at my child's age?", "איך להפוך את זמן הקריאה שלנו ליותר שיחה בגיל של הילד שלי?"),
  },
  {
    id: "gestures-before-words",
    category: "language",
    domains: ["language_communication"],
    ageMin: 0,
    ageMax: 2,
    minutes: 3,
    title: L("The point that speaks: gestures before words", "ההצבעה שמדברת: מחוות לפני מילים"),
    hook: L("Months before the first word, a pointing finger is already holding full conversations — and how you answer it shapes what comes next.", "חודשים לפני המילה הראשונה, אצבע מצביעה כבר מנהלת שיחות שלמות — ואיך שתענו לה מעצב את מה שיבוא."),
    keyPoints: [
      L("Pointing typically emerges somewhere around 9 to 14 months — a wide, healthy window — and it is a genuine language milestone, not a warm-up act.", "הצבעה מופיעה בדרך כלל אי שם בין 9 ל־14 חודשים — חלון רחב ובריא — והיא אבן דרך שפתית של ממש, לא חימום."),
      L("There are two kinds: imperative pointing ('get me that') and declarative pointing ('look at that — share it with me'). The declarative kind is a conversation invitation.", "יש שני סוגים: הצבעה מבקשת (\"תביאו לי את זה\") והצבעה מכריזה (\"תראו! — בואו נתפעל יחד\"). הסוג המכריז הוא הזמנה לשיחה."),
      L("Research finds early gesture use predicts later vocabulary: the things a child points at now tend to show up as words months later.", "המחקר מוצא ששימוש מוקדם במחוות מנבא אוצר מילים מאוחר יותר: הדברים שילד מצביע עליהם עכשיו נוטים להופיע כמילים כעבור חודשים."),
      L("The power move is simple: when your child points, name the thing in that exact second — attention is wide open and the label lands.", "המהלך החזק פשוט: כשהילד מצביע, תנו שם לדבר באותה שנייה בדיוק — הקשב פתוח לרווחה והמילה נוחתת."),
      L("Waving, showing, giving and head-shaking all count as communication; a busy gesturer with few words is usually a child mid-build.", "נפנוף, הושטה להראות, נתינה והנדת ראש — כולם תקשורת; ילד עתיר מחוות ודל מילים הוא בדרך כלל ילד באמצע בנייה."),
    ],
    body: L(
      "Around the end of the first year, a small finger rises and aims at a dog, a light, a plane — and everything changes. Pointing looks trivial and is anything but: to point for someone, a baby must understand that you have attention, that it can be aimed, and that a gesture can aim it. That insight — minds can be directed at the same thing together — is the platform language gets built on. Developmental researchers treat the emergence of pointing, typically in a wide window around nine to fourteen months, as one of the quiet headline events of infancy.\n\nWatch closely and you'll see two different points. The imperative point is a request with a fingertip: that snack, that toy, bring it. The declarative point wants nothing but company: look at that truck — see it with me. Declarative pointing is the more socially remarkable one; it's a pure invitation to share an experience, a conversation before words exist. Babies also build a whole gesture vocabulary around it: showing you objects, giving them, waving, nodding and refusing with the whole body. All of it is language infrastructure.\n\nThe practical part is what happens next. Gesture research keeps finding that early pointing and showing predict later vocabulary — and the mechanism seems delightfully direct: a child who points at something is announcing exactly what they're attending to, and a parent who names it in that second is delivering the word onto open circuits. \"Dog! Yes, a big brown dog.\" You don't need to quiz or drill; you need to answer the point. Each answered point is a tiny lesson placed precisely where the child asked for it.\n\nThe range here is wide, as everywhere in communication. But gestures are also worth noticing for their own sake: a child rich in points, shows and waves is communicating well no matter the word count, while very few gestures alongside limited shared attention is a pattern worth describing — as observations, not conclusions — in a conversation with your pediatric professional. For most families, the takeaway is simpler: the pointing finger is your child's first question mark. Answer it generously.",
      "לקראת סוף השנה הראשונה, אצבע קטנה מתרוממת ומכוונת אל כלב, מנורה, מטוס — והכול משתנה. הצבעה נראית טריוויאלית והיא ממש לא: כדי להצביע עבור מישהו, תינוק צריך להבין שיש לכם קשב, שאפשר לכוון אותו, ושמחווה יכולה לכוון אותו. התובנה הזאת — שמוחות יכולים להיות מכוונים יחד לאותו דבר — היא הפלטפורמה ששפה נבנית עליה. חוקרי התפתחות רואים בהופעת ההצבעה, בדרך כלל בחלון רחב סביב תשעה עד ארבעה־עשר חודשים, מאירועי המפתח השקטים של הינקות.\n\nהתבוננו מקרוב ותראו שתי הצבעות שונות. ההצבעה המבקשת היא דרישה עם קצה אצבע: החטיף ההוא, הצעצוע ההוא, תביאו. ההצבעה המכריזה לא רוצה דבר מלבד חברה: תראו את המשאית — תראו אותה איתי. ההצבעה המכריזה היא המרשימה חברתית מבין השתיים; היא הזמנה טהורה לחלוק חוויה, שיחה לפני שקיימות מילים. תינוקות בונים סביבה אוצר מחוות שלם: מושיטים לכם חפצים להראות, נותנים אותם, מנפנפים, מהנהנים ומסרבים עם כל הגוף. כל זה תשתית של שפה.\n\nהחלק המעשי הוא מה שקורה אחר כך. מחקר המחוות מוצא שוב ושוב שהצבעה והושטה מוקדמות מנבאות אוצר מילים מאוחר יותר — והמנגנון פשוט להפליא: ילד שמצביע על משהו מכריז בדיוק על מה הקשב שלו, והורה שנותן שם באותה שנייה מניח את המילה על מעגלים פתוחים. \"כלב! כן, כלב חום גדול.\" לא צריך לתחקר או לתרגל; צריך לענות להצבעה. כל הצבעה שנענתה היא שיעור זעיר שהונח בדיוק במקום שהילד ביקש.\n\nהטווח כאן רחב, כמו בכל תחומי התקשורת. אבל שווה לשים לב למחוות גם בזכות עצמן: ילד עשיר בהצבעות, הושטות ונפנופים מתקשר היטב בלי קשר לספירת המילים, ואילו מעט מאוד מחוות לצד קשב משותף מוגבל הם דפוס ששווה לתאר — כתצפיות, לא כמסקנות — בשיחה עם איש מקצוע. לרוב המשפחות המסקנה פשוטה יותר: האצבע המצביעה היא סימן השאלה הראשון של הילד שלכם. ענו עליו בנדיבות."
    ),
    tryToday: L(
      "On today's walk or from the window, follow every point: name the thing, add one detail, pause. \"Bird! It's hopping.\" Ten answered points is a language session.",
      "בטיול של היום או מהחלון, לכו אחרי כל הצבעה: תנו שם, הוסיפו פרט אחד, עצרו. \"ציפור! היא מקפצת.\" עשר הצבעות שנענו הן שיעור שפה."
    ),
    ask: L("What are my baby's gestures telling me about their communication right now?", "מה המחוות של התינוק שלי מספרות לי על התקשורת שלו עכשיו?"),
  },
  {
    id: "bilingual-mixing",
    category: "language",
    domains: ["language_communication"],
    ageMin: 1,
    ageMax: 6,
    minutes: 3,
    title: L("Mixing languages isn't confusion — it's skill", "ערבוב שפות אינו בלבול — הוא מיומנות"),
    hook: L("\"אני רוצה the red one!\" is not a system error. It's a small bilingual mind using everything it has — exactly as designed.", "\"אני רוצה the red one!\" זו לא תקלת מערכת. זה מוח דו־לשוני קטן שמשתמש בכל מה שיש לו — בדיוק כמתוכנן."),
    keyPoints: [
      L("Mixing languages in one sentence is called code-switching; bilingual adults do it constantly, and children's mixing usually respects the grammar of both languages.", "ערבוב שפות במשפט אחד נקרא code-switching; מבוגרים דו־לשוניים עושים זאת כל הזמן, והערבוב של ילדים בדרך כלל מכבד את הדקדוק של שתי השפות."),
      L("Research finds bilingualism itself does not cause language delay; bilingual children hit major milestones on broadly the same timetable.", "המחקר מוצא שדו־לשוניות כשלעצמה אינה גורמת לעיכוב שפתי; ילדים דו־לשוניים מגיעים לאבני הדרך המרכזיות בערך באותו לוח זמנים."),
      L("Count vocabulary across both languages: early words split between them, and only the combined list shows the true picture.", "ספרו אוצר מילים על פני שתי השפות: מילים ראשונות מתפצלות ביניהן, ורק הרשימה המשולבת מראה את התמונה האמיתית."),
      L("One-parent-one-language is one workable arrangement, not a requirement; what matters is rich, sustained, meaningful exposure to each language.", "הורה-אחד-שפה-אחת היא שיטה אפשרית אחת, לא דרישה; מה שקובע הוא חשיפה עשירה, מתמשכת ומשמעותית לכל שפה."),
      L("Speak to your child in the language where you are richest and most yourself — that's where your best serve-and-return lives.", "דברו עם הילד בשפה שבה אתם הכי עשירים והכי אתם — שם גרה ההגשה־וחזרה הטובה ביותר שלכם."),
    ],
    body: L(
      "A three-year-old announces \"I want עוד juice\" and somewhere a grandparent worries: is she confused? The reassuring answer from decades of bilingualism research is no — she is doing what bilinguals of every age do. Mixing languages within a sentence, known as code-switching, is a normal feature of bilingual life, not a symptom. Look closely at children's mixes and they usually land where both grammars allow, which is evidence of two systems being managed, not one system in disarray. Most commonly, a child simply reaches for the word they have — or the shorter one — and keeps the conversation moving. That's resourcefulness.\n\nThe larger worry underneath — that two languages overload a small brain and delay speech — hasn't held up either. Studies of bilingual development find children acquiring two languages hit the major milestones of babbling, first words and word combinations on broadly the same timetable as single-language peers. One accounting detail matters: a bilingual toddler's early vocabulary is split across two languages, so counting words in only one language will always undercount the child. Tally both lists together and the picture usually looks very different.\n\nFamilies often ask whether they must run a strict system — one parent one language, home language versus outside language. These arrangements can work well, but research doesn't crown any of them as required. The ingredients that actually matter are quantity and quality: each language needs rich, regular, meaningful exposure — conversation, books, songs, people the child loves using the language for real life. A practical corollary: speak to your child in the language where you have the most words, the best jokes and the fullest self. A parent's richest language is their richest serve-and-return.\n\nAnd the home language deserves defending, because the community language will take care of itself — school and street are relentless teachers. The language of grandparents, of your family's stories and songs, survives only if it's lived at home. Keeping it is not an obstacle to the majority language; it's a second inheritance, handed over one ordinary conversation at a time.",
      "ילדה בת שלוש מכריזה \"I want עוד מיץ\" ואי שם סבתא דואגת: היא מבולבלת? התשובה המרגיעה מעשורים של חקר דו־לשוניות היא לא — היא עושה מה שדו־לשוניים בכל גיל עושים. ערבוב שפות בתוך משפט, המכונה code-switching, הוא מאפיין רגיל של חיים דו־לשוניים, לא סימפטום. התבוננו מקרוב בערבובים של ילדים והם בדרך כלל נוחתים היכן ששני הדקדוקים מרשים — עדות לשתי מערכות מנוהלות, לא למערכת אחת בבלגן. לרוב, הילד פשוט שולף את המילה שיש לו — או את הקצרה יותר — וממשיך את השיחה. זו תושייה.\n\nגם הדאגה הגדולה שמתחת — ששתי שפות מעמיסות על מוח קטן ומעכבות דיבור — לא החזיקה מעמד. מחקרי התפתחות דו־לשונית מוצאים שילדים שרוכשים שתי שפות מגיעים לאבני הדרך המרכזיות — מלמול, מילים ראשונות, צירופי מילים — בערך באותו לוח זמנים כמו בני גילם החד־לשוניים. פרט חשבונאי אחד חשוב: אוצר המילים המוקדם של פעוט דו־לשוני מפוצל בין שתי שפות, ולכן ספירה בשפה אחת בלבד תמיד תחסיר. חברו את שתי הרשימות והתמונה בדרך כלל נראית אחרת לגמרי.\n\nמשפחות שואלות לעיתים קרובות אם חובה לנהל שיטה קפדנית — הורה אחד שפה אחת, שפת בית מול שפת חוץ. הסידורים האלה יכולים לעבוד יפה, אבל המחקר לא מכתיר אף אחד מהם כחובה. המרכיבים שבאמת קובעים הם כמות ואיכות: כל שפה זקוקה לחשיפה עשירה, סדירה ומשמעותית — שיחה, ספרים, שירים, אנשים שהילד אוהב ומשתמש איתם בשפה בחיים אמיתיים. מסקנה מעשית: דברו עם הילד בשפה שבה יש לכם הכי הרבה מילים, הבדיחות הכי טובות והעצמי הכי מלא. השפה העשירה של ההורה היא ההגשה־וחזרה העשירה שלו.\n\nועל שפת הבית שווה להגן, כי שפת הסביבה תסתדר בעצמה — הגן והרחוב הם מורים בלתי נלאים. שפת הסבים, שפת הסיפורים והשירים של המשפחה, שורדת רק אם חיים אותה בבית. לשמור עליה אינו מכשול לשפת הרוב; זו ירושה שנייה, שמועברת שיחה רגילה אחת בכל פעם."
    ),
    tryToday: L(
      "When your child mixes today, don't correct — recast: answer naturally in your language, folding in the word they borrowed. The model teaches; the correction discourages.",
      "כשהילד מערבב היום, אל תתקנו — נסחו מחדש: ענו טבעי בשפה שלכם, ושלבו את המילה שהוא שאל. הדוגמה מלמדת; התיקון מרפה ידיים."
    ),
    ask: L("How do we keep both of our languages strong at my child's age?", "איך נשמור על שתי השפות שלנו חזקות בגיל של הילד שלי?"),
  },

  // ── Big Feelings ─────────────────────────────────────────────────────────
  {
    id: "separation-anxiety",
    category: "feelings",
    domains: ["attachment_regulation"],
    ageMin: 0,
    ageMax: 4,
    minutes: 4,
    concerns: ["separation"],
    title: L("Separation anxiety: attachment working as designed", "חרדת פרידה: התקשרות שעובדת בדיוק כמתוכנן"),
    hook: L("The tears at daycare drop-off aren't a malfunction — they're proof your child has built exactly the bond they were supposed to build.", "הדמעות בפרידה בגן אינן תקלה — הן הוכחה שהילד בנה בדיוק את הקשר שהיה אמור לבנות."),
    keyPoints: [
      L("Separation distress typically rises late in the first year, often surges again around age two, and fades gradually — on a schedule that varies widely.", "מצוקת פרידה עולה בדרך כלל לקראת סוף השנה הראשונה, מתחזקת שוב לעיתים סביב גיל שנתיים, ודועכת בהדרגה — בלוח זמנים שמשתנה מאוד."),
      L("It runs on two achievements: the baby now knows you exist while gone, and cares deeply that you're the one who's gone. Both are milestones.", "היא רצה על שני הישגים: התינוק כבר יודע שאתם קיימים גם כשאינכם, ואכפת לו עמוקות שדווקא אתם אלה שהלכו. שניהם אבני דרך."),
      L("A short, warm, identical goodbye ritual — hug, phrase, wave — carries the moment better than a long farewell that stretches the pain.", "טקס פרידה קצר, חם וזהה — חיבוק, משפט, נפנוף — נושא את הרגע טוב יותר מפרידה ארוכה שמותחת את הכאב."),
      L("Never sneak out: it saves one hard goodbye and buys many, because the child learns you might vanish at any moment and starts guarding you.", "לעולם אל תתגנבו החוצה: זה חוסך פרידה קשה אחת וקונה רבות, כי הילד לומד שאתם עלולים להיעלם בכל רגע — ומתחיל לשמור עליכם."),
      L("Your calm confidence is information: children read your face to decide whether this goodbye is safe. If distress stays intense and unrelenting well past these windows, that's a good conversation to have with a professional.", "הביטחון הרגוע שלכם הוא מידע: ילדים קוראים את הפנים שלכם כדי להחליט אם הפרידה הזאת בטוחה. אם המצוקה נשארת עזה ובלתי פוסקת הרבה מעבר לחלונות האלה — זו שיחה טובה לקיים עם איש מקצוע."),
    ],
    body: L(
      "For months, your baby beamed at anyone who held them — and then, seemingly overnight, only you will do, and every goodbye is a small tragedy. It feels like a step backward. Developmentally, it's the opposite. Separation anxiety appears when two abilities come online together: object permanence, which tells the baby you still exist somewhere when you leave, and focused attachment, which makes you specifically irreplaceable. The distress typically rises late in the first year, often peaks again somewhere around two — when imagination has grown but the concept of 'later' hasn't — and eases on its own uneven schedule. A child who protests your leaving is a child whose bonding system works.\n\nWhat helps most at the door is ritual. A goodbye that is short, warm and identical every time — one hug, one phrase (\"I love you, I always come back\"), one wave from the window — gives the child a knowable shape for a hard moment. Long, lingering farewells feel kinder but usually stretch the pain, and an anxious face reads as confirmation that something scary is happening. Children are expert readers of parental weather: a calm, unhurried, confident goodbye is itself the message that this place is safe.\n\nOne rule earns its capital letters: don't sneak out. Slipping away while the child is distracted is deeply tempting — no tears, no scene. But the tears come anyway when they turn and find you gone, and something more expensive comes with them: the lesson that you can vanish without warning. A child who has learned that tends to guard the exit, cling harder and trust goodbyes less. The honest version — say it, keep it brief, leave — costs more this morning and far less this month. What happens after the door closes belongs in the picture too: most children settle within minutes, and it's fair to ask the caregiver how long the tears actually lasted.\n\nReunions are half the curriculum: a warm, unrushed hello confirms that partings end. The whole arc — protest, adjust, reunite — is how children learn that separation is survivable, and the range of normal here is very wide. If distress stays intense, unrelenting and life-limiting well beyond these windows, bring your observations — the whens, the how-longs — to a good conversation with a professional. For most families, the tears at the door are what love looks like before it learns the word 'later'.",
      "במשך חודשים התינוק חייך אל כל מי שהחזיק אותו — ואז, כאילו בן לילה, רק אתם קבילים, וכל פרידה היא טרגדיה קטנה. זה מרגיש כמו צעד אחורה. התפתחותית, זה ההפך. חרדת פרידה מופיעה כששתי יכולות מבשילות יחד: קביעות אובייקט, שמספרת לתינוק שאתם ממשיכים להתקיים איפשהו כשאתם יוצאים, והתקשרות ממוקדת, שהופכת אתכם ספציפית לבלתי ניתנים להחלפה. המצוקה עולה בדרך כלל לקראת סוף השנה הראשונה, מגיעה לרוב לשיא נוסף אי שם סביב שנתיים — כשהדמיון גדל אבל המושג 'אחר כך' עוד לא — ונרגעת בקצב לא אחיד משלה. ילד שמוחה על היציאה שלכם הוא ילד שמערכת ההתקשרות שלו עובדת.\n\nמה שעוזר יותר מכול ליד הדלת הוא טקס. פרידה קצרה, חמה וזהה בכל פעם — חיבוק אחד, משפט אחד (\"אני אוהבת אותך, אני תמיד חוזרת\"), נפנוף אחד מהחלון — נותנת לילד צורה מוכרת לרגע קשה. פרידות ארוכות ומתמשכות מרגישות רחומות יותר אבל בדרך כלל מותחות את הכאב, ופנים חרדות נקראות כאישור שמשהו מפחיד קורה. ילדים הם קוראים מומחים של מזג האוויר ההורי: פרידה רגועה, לא לחוצה ובטוחה היא בעצמה המסר שהמקום הזה בטוח.\n\nכלל אחד ראוי לאותיות גדולות: לא מתגנבים החוצה. לחמוק כשהילד מוסח זה מפתה עמוקות — בלי דמעות, בלי סצנה. אבל הדמעות מגיעות בכל מקרה כשהוא מסתובב ומגלה שנעלמתם, ואיתן מגיע משהו יקר יותר: השיעור שאתם עלולים להיעלם בלי אזהרה. ילד שלמד את זה נוטה לשמור על היציאה, להיצמד חזק יותר ולבטוח פחות בפרידות. הגרסה הכנה — אומרים, מקצרים, הולכים — עולה יותר הבוקר והרבה פחות החודש. גם מה שקורה אחרי שהדלת נסגרת שייך לתמונה: רוב הילדים נרגעים בתוך דקות, ולגיטימי לשאול את הצוות כמה זמן הדמעות באמת נמשכו.\n\nהאיחודים הם חצי מתוכנית הלימודים: שלום חם ולא ממהר מאשר שלפרידות יש סוף. הקשת כולה — מחאה, הסתגלות, איחוד — היא הדרך שבה ילדים לומדים שפרידה היא דבר ששורדים, וטווח הנורמלי כאן רחב מאוד. אם המצוקה נשארת עזה, בלתי פוסקת ומגבילת חיים הרבה מעבר לחלונות האלה, הביאו את התצפיות שלכם — המתי, כמה זמן — לשיחה טובה עם איש מקצוע. לרוב המשפחות, הדמעות ליד הדלת הן איך שאהבה נראית לפני שהיא לומדת את המילה 'אחר כך'."
    ),
    tryToday: L(
      "Design tomorrow's goodbye tonight: one hug, one fixed phrase, one wave — then go. Tell your child the plan in advance; predictable partings are smaller partings.",
      "עצבו הערב את הפרידה של מחר: חיבוק אחד, משפט קבוע אחד, נפנוף אחד — והולכים. ספרו לילד את התוכנית מראש; פרידות צפויות הן פרידות קטנות יותר."
    ),
    ask: L("Help me build a goodbye ritual that fits our mornings.", "עזור לי לבנות טקס פרידה שמתאים לבקרים שלנו."),
  },
  {
    id: "fears-by-age",
    category: "feelings",
    domains: ["attachment_regulation", "cognition_executive_function"],
    ageMin: 2,
    ageMax: 8,
    minutes: 4,
    concerns: ["fears"],
    title: L("Monsters, dark, dogs, death: the fear timetable", "מפלצות, חושך, כלבים, מוות: לוח הזמנים של הפחדים"),
    hook: L("Childhood fears arrive on a surprisingly predictable schedule — because each one mirrors exactly what the growing mind just learned to imagine.", "פחדי ילדות מגיעים בלוח זמנים צפוי להפתיע — כי כל אחד מהם משקף בדיוק את מה שהמוח הגדל בדיוק למד לדמיין."),
    keyPoints: [
      L("Fears track cognition: babies and toddlers fear the immediate (loud noises, strangers, separation); preschoolers fear the imagined (dark, monsters); school-age children fear the real (dogs, storms, injury, death).", "פחדים עוקבים אחרי הקוגניציה: תינוקות ופעוטות פוחדים מהמיידי (רעשים, זרים, פרידה); ילדי גן — מהמדומיין (חושך, מפלצות); ילדי בית ספר — מהאמיתי (כלבים, סערות, פציעה, מוות)."),
      L("Preschool fears bloom because imagination has surged ahead of reality-testing: a mind that can conjure a monster can't yet un-conjure it with logic.", "פחדי גיל הגן פורחים כי הדמיון זינק לפני בדיקת המציאות: מוח שיכול לזמן מפלצת עדיין לא יודע לבטל אותה בעזרת היגיון."),
      L("Validate first, always: 'that's not scary' teaches a child their alarm is broken; 'you're scared — I'm here' teaches that fear can be held.", "קודם כול תיקוף, תמיד: \"אין ממה לפחד\" מלמד ילד שהאזעקה שלו מקולקלת; \"אתה מפחד — אני כאן\" מלמד שאפשר להחזיק פחד."),
      L("Avoidance feeds fear; small, child-paced steps toward the feared thing shrink it — with you nearby and the child holding the throttle.", "הימנעות מזינה פחד; צעדים קטנים, בקצב הילד, לעבר הדבר המפחיד מכווצים אותו — כשאתם קרובים והילד מחזיק בהגה."),
      L("Fears that pass are the norm; a fear that consistently blocks ordinary life — sleep, school, leaving the house — for weeks is a good conversation to have with a professional, described in observations.", "פחדים שחולפים הם הכלל; פחד שחוסם באופן עקבי חיים רגילים — שינה, גן, יציאה מהבית — לאורך שבועות הוא שיחה טובה לקיים עם איש מקצוע, מתוארת בתצפיות."),
    ],
    body: L(
      "A two-year-old who napped happily in a dark room becomes a four-year-old who needs the hall light, a monster check and the door open at a precise angle. Nothing went wrong; something grew. Childhood fears follow the mind's construction schedule with almost comic reliability. Infants and toddlers fear what's immediate and concrete: loud noises, sudden looming, strangers, being apart from you. The preschool years bring the imaginary bloom — dark, monsters, masks, the vacuum with intent to harm — precisely because imagination has surged while the ability to test reality lags behind. A brain that can now picture a wolf under the bed cannot yet argue itself out of the picture. School age trades monsters for the real world: dogs, storms, burglars, getting hurt — and the death questions, which typically arrive around five to seven as children grasp that endings are permanent. Answer those simply and honestly; children handle plain truth better than mystery.\n\nWhatever the fear, the first move is the same: take it seriously without taking it over. 'There's nothing to be scared of' is meant kindly, but the child's alarm is genuinely ringing, and being told it shouldn't be teaches them either that their signals are defective or that you don't get it. 'You're really scared of that dog — I'm right here' costs nothing and keeps you on the same side. Validation isn't surrender; you can honor the feeling and still hold the plan.\n\nThen comes the counterintuitive part: the road out of a fear runs toward it, in steps small enough to survive. Avoidance is fear's fertilizer — every skipped dog-street confirms that dogs were worth avoiding. Gradual approach, with the child setting the pace and you close by, works the opposite way: watch dogs from across the park, then from the path, then meet one sleepy old dog on a leash. Each survivable step files evidence against the fear. For monster-class fears, comfort beats debate at midnight — a check-under-the-bed ritual or a guard teddy gives the child agency where logic can't reach, and the fear fades as reality-testing matures.\n\nMost fears follow that arc: arrive on schedule, get handled with respect and small steps, and leave. What's worth more attention is not any single fear but a pattern of blocking — a fear that keeps ruling sleep, school, or the front door for weeks despite gentle approach. That's not a verdict about your child; it's a pattern worth describing, in whens and how-oftens, in a good conversation with a professional. Everything else is a growing imagination doing exactly what it should — a little ahead of its brakes.",
      "ילדה בת שנתיים שנרדמה בשמחה בחדר חשוך הופכת לבת ארבע שצריכה אור במסדרון, בדיקת מפלצות ודלת פתוחה בזווית מדויקת. שום דבר לא התקלקל; משהו גדל. פחדי ילדות עוקבים אחרי לוח הבנייה של המוח באמינות כמעט קומית. תינוקות ופעוטות פוחדים מהמיידי והמוחשי: רעשים חזקים, התקרבות פתאומית, זרים, להיות בנפרד מכם. שנות הגן מביאות את פריחת הדמיון — חושך, מפלצות, מסכות, שואב האבק עם כוונות זדון — בדיוק מפני שהדמיון זינק בעוד היכולת לבדוק מציאות מפגרת מאחור. מוח שמסוגל עכשיו לצייר זאב מתחת למיטה עדיין לא מסוגל להתווכח עם הציור. גיל בית הספר מחליף מפלצות בעולם האמיתי: כלבים, סערות, גנבים, פציעות — ושאלות המוות, שמגיעות בדרך כלל סביב חמש עד שבע, כשילדים תופסים שסוף הוא סופי. ענו עליהן בפשטות ובכנות; ילדים מתמודדים עם אמת פשוטה טוב יותר מאשר עם מסתורין.\n\nיהיה הפחד אשר יהיה, הצעד הראשון זהה: לקחת אותו ברצינות בלי להשתלט עליו. \"אין ממה לפחד\" נאמר מכוונה טובה, אבל האזעקה של הילד באמת מצלצלת, ולשמוע שהיא לא אמורה לצלצל מלמד אותו או שהאותות שלו פגומים או שאתם לא מבינים. \"אתה ממש מפחד מהכלב הזה — אני כאן\" לא עולה כלום ומשאיר אתכם באותו צד. תיקוף אינו כניעה; אפשר לכבד את הרגש ועדיין להחזיק בתוכנית.\n\nואז מגיע החלק המפתיע: הדרך החוצה מפחד עוברת לעברו, בצעדים קטנים מספיק כדי לשרוד אותם. הימנעות היא הדשן של הפחד — כל רחוב-עם-כלב שדילגנו עליו מאשר שהיה שווה להימנע מכלבים. התקרבות הדרגתית, כשהילד קובע את הקצב ואתם קרובים, פועלת הפוך: מסתכלים על כלבים מהצד השני של הפארק, אחר כך מהשביל, אחר כך פוגשים כלב זקן ורדום אחד ברצועה. כל צעד ששורדים מתייק ראיה נגד הפחד. בפחדים ממשפחת המפלצות, נחמה מנצחת ויכוח בחצות — טקס בדיקה מתחת למיטה או דובי שומר נותנים לילד שליטה במקום שההיגיון לא מגיע אליו, והפחד דוהה כשבדיקת המציאות מבשילה.\n\nרוב הפחדים עוברים את הקשת הזאת: מגיעים בזמנם, מטופלים בכבוד ובצעדים קטנים, והולכים. מה שראוי ליותר תשומת לב אינו פחד בודד אלא דפוס של חסימה — פחד שממשיך לשלוט בשינה, בגן או בדלת הבית שבועות למרות התקרבות עדינה. זה לא פסק דין על הילד; זה דפוס ששווה לתאר, במתי ובכמה, בשיחה טובה עם איש מקצוע. כל השאר הוא דמיון גדל שעושה בדיוק את מה שהוא צריך — קצת לפני הבלמים שלו."
    ),
    tryToday: L(
      "Pick your child's current fear and shrink one step: watch the feared thing together from a distance they choose, narrating calmly. Approach at their pace counts double.",
      "בחרו את הפחד הנוכחי של הילד והקטינו צעד אחד: התבוננו יחד בדבר המפחיד ממרחק שהוא בוחר, ותארו ברוגע. התקרבות בקצב שלו שווה כפול."
    ),
    ask: L("How do we build a gradual plan for my child's current fear?", "איך בונים תוכנית הדרגתית לפחד הנוכחי של הילד שלי?"),
  },
  {
    id: "empathy-development",
    category: "feelings",
    domains: ["attachment_regulation", "social_development"],
    ageMin: 1,
    ageMax: 6,
    minutes: 3,
    title: L("How empathy grows: from contagious tears to real comfort", "איך אמפתיה צומחת: מדמעות מידבקות לנחמה אמיתית"),
    hook: L("The toddler who hands a crying adult their own teddy is showing you empathy mid-construction — caring is online, perspective is still loading.", "פעוט שמגיש למבוגר בוכה את הדובי שלו מראה לכם אמפתיה באמצע בנייה — האכפתיות כבר עובדת, נקודת המבט עדיין נטענת."),
    keyPoints: [
      L("Empathy starts as contagion: newborns cry at other newborns' cries — feelings spread before they're understood.", "אמפתיה מתחילה כהידבקות: תינוקות בוכים לשמע בכי של תינוקות אחרים — רגשות מתפשטים לפני שהם מובנים."),
      L("Toddlers comfort with what would comfort them — their blanket, their teddy, their mom — which is caring filtered through one available perspective: their own.", "פעוטות מנחמים במה שהיה מנחם אותם — השמיכה שלהם, הדובי שלהם, אמא שלהם — אכפתיות מסוננת דרך נקודת המבט היחידה הזמינה: שלהם."),
      L("With theory of mind, around ages three to five, comfort starts fitting the other person: the child grasps that different people need different things.", "עם תיאוריית המיינד, סביב גיל שלוש עד חמש, הנחמה מתחילה להתאים לאדם השני: הילד קולט שאנשים שונים צריכים דברים שונים."),
      L("Development is uneven by design: the same child can comfort tenderly at nine and snatch a toy at ten. Both are the same age.", "ההתפתחות לא אחידה מטבעה: אותו ילד יכול לנחם ברוך בתשע ולחטוף צעצוע בעשר. שניהם אותו גיל."),
      L("Empathy is caught more than taught: children learn it from receiving it and watching it — modeling and naming feelings beat lectures about kindness.", "אמפתיה נקלטת יותר משהיא נלמדת: ילדים סופגים אותה מקבלה שלה ומצפייה בה — דוגמה אישית ומתן שמות לרגשות מנצחים הרצאות על נחמדות."),
    ],
    body: L(
      "Visit a newborn nursery and you'll hear empathy's raw material: one baby cries, and the cries spread down the row. Emotional contagion — catching a feeling without understanding it — is present almost from the start, and it's the seed everything else grows from. Through the first year, babies read faces and borrow their emotional weather from yours; by toddlerhood, the caring impulse is unmistakable. A toddler who sees you sad may pat you, bring you their bottle, or fetch their own comfort object and press it into your hands.\n\nThat teddy handed to a crying adult is worth pausing on, because it's a perfect snapshot of empathy mid-build. The care is fully real: the child registered your distress and mobilized to fix it. But the fix comes from the only perspective currently installed — their own. What comforts me will comfort you. Developmental psychologists sometimes call this egocentric empathy, and it's not a flaw to correct but a floor to build on. The upgrade arrives with theory of mind, typically somewhere between three and five: once a child grasps that other people have their own inner worlds, comfort starts fitting the recipient. They bring Grandpa his glasses rather than a teddy, and ask a sad friend what happened rather than assuming.\n\nExpect the whole build to be gloriously uneven. Empathy isn't a trait that switches on; it's a skill exercised feeling by feeling, and it competes with impulse, fatigue and the magnetic pull of the toy in someone else's hand. The same child can be a tender comforter at nine in the morning and a toy-snatcher at ten. That's not hypocrisy; that's a skill under construction meeting a hard moment.\n\nAs for teaching it — empathy is caught far more than taught. Children who receive empathy learn what it feels like from the inside; children who watch you wonder aloud about others' feelings — 'that baby is crying, I think he dropped his snack' — learn that inner worlds are worth reading. Naming your child's own feelings builds the vocabulary; repairing warmly after your own missteps shows that empathy includes getting it wrong and coming back. Lectures about kindness mostly bounce. Being on the receiving end of it, daily, is the course.",
      "בקרו בתינוקייה ותשמעו את חומר הגלם של האמפתיה: תינוק אחד בוכה, והבכי מתפשט לאורך השורה. הידבקות רגשית — לתפוס רגש בלי להבין אותו — קיימת כמעט מההתחלה, והיא הזרע שממנו הכול צומח. לאורך השנה הראשונה תינוקות קוראים פרצופים ושואלים את מזג האוויר הרגשי שלהם מכם; בגיל הפעוטות דחף האכפתיות כבר בלתי ניתן לטעות. פעוט שרואה אתכם עצובים עשוי ללטף אתכם, להביא לכם את הבקבוק שלו, או לשלוף את חפץ הנחמה שלו ולדחוף אותו לידיכם.\n\nשווה לעצור רגע על הדובי שנמסר למבוגר בוכה, כי הוא תצלום מושלם של אמפתיה באמצע בנייה. האכפתיות אמיתית לגמרי: הילד קלט את המצוקה שלכם והתגייס לתקן. אבל התיקון מגיע מנקודת המבט היחידה שמותקנת כרגע — שלו. מה שמנחם אותי ינחם אותך. פסיכולוגים התפתחותיים מכנים זאת לעיתים אמפתיה אגוצנטרית, וזה לא פגם לתקן אלא רצפה לבנות עליה. השדרוג מגיע עם תיאוריית המיינד, בדרך כלל אי שם בין שלוש לחמש: ברגע שילד קולט שלאנשים אחרים יש עולמות פנימיים משלהם, הנחמה מתחילה להתאים למקבל. הוא מביא לסבא את המשקפיים ולא דובי, ושואל חבר עצוב מה קרה במקום להניח.\n\nצפו לכך שכל הבנייה תהיה לא אחידה באופן מפואר. אמפתיה אינה תכונה שנדלקת; היא מיומנות שמתאמנים בה רגש אחר רגש, והיא מתחרה בדחפים, בעייפות ובמשיכה המגנטית של הצעצוע שביד של מישהו אחר. אותו ילד יכול להיות מנחם רך בתשע בבוקר וחוטף צעצועים בעשר. זו לא צביעות; זו מיומנות בבנייה שפוגשת רגע קשה.\n\nובאשר ללימוד — אמפתיה נקלטת הרבה יותר משהיא מלומדת. ילדים שמקבלים אמפתיה לומדים איך היא מרגישה מבפנים; ילדים שרואים אתכם תוהים בקול על רגשות של אחרים — \"התינוק הזה בוכה, נראה לי שהחטיף שלו נפל\" — לומדים שעולמות פנימיים שווים קריאה. מתן שמות לרגשות של הילד עצמו בונה את אוצר המילים; תיקון חם אחרי טעויות שלכם מראה שאמפתיה כוללת לטעות ולחזור. הרצאות על נחמדות בעיקר מוחזרות מהקיר. לקבל אותה, יום־יום, זה הקורס."
    ),
    tryToday: L(
      "Wonder aloud about one stranger's feelings today — \"that man is running, I think he's worried about the bus.\" Reading minds out loud is empathy homework disguised as people-watching.",
      "תהו היום בקול על הרגשות של אדם זר אחד — \"האיש הזה רץ, נראה לי שהוא דואג לאוטובוס.\" קריאת מחשבות בקול היא שיעורי בית באמפתיה במסווה של צפייה באנשים."
    ),
    ask: L("Where is my child on the empathy curve, and what feeds the next step?", "איפה הילד שלי על עקומת האמפתיה, ומה מזין את הצעד הבא?"),
  },

  // ── Behavior & Limits ────────────────────────────────────────────────────
  {
    id: "why-kids-lie",
    category: "behavior",
    domains: ["social_development", "cognition_executive_function"],
    ageMin: 3,
    ageMax: 8,
    minutes: 4,
    title: L("Why kids lie — and why the first fib is a milestone", "למה ילדים משקרים — ולמה השקר הראשון הוא אבן דרך"),
    hook: L("A child can only lie once they've discovered you don't know what they know. The chocolate-chin denial is theory of mind, freshly unwrapped.", "ילד יכול לשקר רק אחרי שגילה שאתם לא יודעים מה שהוא יודע. ההכחשה עם סנטר השוקולד היא תיאוריית מיינד טרייה מהאריזה."),
    keyPoints: [
      L("First lies, typically around age three or four, ride a cognitive breakthrough: lying requires understanding that your mind holds different contents than theirs.", "שקרים ראשונים, בדרך כלל סביב גיל שלוש-ארבע, רוכבים על פריצת דרך קוגניטיבית: כדי לשקר צריך להבין שבראש שלכם יש תוכן שונה משלהם."),
      L("Wish-lies ('my dog can fly', 'I didn't spill it' meaning 'I wish I hadn't') differ from cover-lies told to dodge consequences — and deserve different responses.", "שקרי משאלה (\"הכלב שלי עף\", \"לא שפכתי\" במובן \"הלוואי שלא\") שונים משקרי חיפוי שנועדו לחמוק מתוצאות — ומגיעה להם תגובה שונה."),
      L("Don't set traps: asking 'did you eat the cookie?' when you already know invites the lie; state what you see instead and move to fixing.", "אל תטמנו מלכודות: לשאול \"אכלת את העוגייה?\" כשאתם כבר יודעים מזמין את השקר; במקום זה אמרו מה אתם רואים ועברו לתיקון."),
      L("Keep truth cheap: when confession is met with calm and repair rather than a storm, telling the truth stays the rational choice.", "השאירו את האמת זולה: כשהודאה נענית ברוגע ובתיקון במקום בסערה, לומר אמת נשאר הבחירה ההגיונית."),
      L("Research finds children lie less, and confess more, where honesty is safe; your own small daily honesty — including to them — is the loudest lesson.", "המחקר מוצא שילדים משקרים פחות, ומודים יותר, במקום שבו כנות בטוחה; הכנות היומיומית הקטנה שלכם — כולל כלפיהם — היא השיעור הרם ביותר."),
    ],
    body: L(
      "The scene is a classic: an empty cookie wrapper, a chocolate-smeared chin, and a firm declaration of innocence. Infuriating — and, developmentally, rather impressive. Lying is cognitively expensive: to do it at all, a child must understand that your mind and theirs hold different contents, that you don't automatically know what they know, and that words can install a false picture in your head. That's theory of mind — the same breakthrough that powers real conversation, pretend play and comforting a friend. First lies typically appear around three or four, and they arrive charmingly bad: the machinery for deceiving exists, the craft doesn't. The fib is not a character verdict. It's a milestone wearing chocolate.\n\nNot all lies are the same animal, and sorting them changes your response. Wish-lies live half in imagination: 'my dog can fly', or 'I didn't break it' spoken in the register of I wish I hadn't. Young children's grip on the wall between wished and real is still soft, and these mostly want gentle reality-keeping, not prosecution: 'That would be amazing. What really happened?' Cover-lies — told to dodge consequences — are the ones parents worry about, and they respond to economics more than to lectures: a child lies to escape a cost, so the question is what truth-telling costs in your house.\n\nWhich leads to the most practical rule in this territory: don't set traps. 'Did you eat the cookie?' asked while holding the wrapper is not an inquiry; it's an invitation to lie, with an audience. The child, cornered, takes the exit — and now there are two problems where there was one. State what you see and move to the fix: 'I see the cookie's gone and lunch is soon. Next time, ask me.' You keep your credibility, they keep their dignity, and the conversation is about the actual issue.\n\nThe long game is making honesty the cheap option. When confession is met with calm — 'thank you for telling me; let's clean it up' — truth stays rational. When it triggers a storm, lying becomes self-defense, and studies of children's honesty find exactly that pattern: in punitive climates children don't lie less, they lie better. Add the quiet curriculum of your own example — the small daily honesties, including keeping your word to them and owning your own misses out loud — and most children grow into truth-tellers the unglamorous way: by living where the truth was always safe to say.",
      "הסצנה קלאסית: עטיפת עוגייה ריקה, סנטר מרוח בשוקולד, והצהרת חפות נחרצת. מקומם — והתפתחותית, דווקא מרשים. שקר הוא יקר קוגניטיבית: כדי לשקר בכלל, ילד צריך להבין שבראש שלכם ובראש שלו יש תכנים שונים, שאתם לא יודעים אוטומטית מה שהוא יודע, ושמילים יכולות להתקין תמונה כוזבת בראשכם. זו תיאוריית המיינד — אותה פריצת דרך שמניעה שיחה אמיתית, משחק דמיוני וניחום חבר. שקרים ראשונים מופיעים בדרך כלל סביב שלוש-ארבע, ומגיעים גרועים באופן מקסים: המנגנון לרמות קיים, האומנות עוד לא. הפיברוק אינו פסק דין על אופי. הוא אבן דרך מרוחה בשוקולד.\n\nלא כל השקרים אותה חיה, והמיון משנה את התגובה. שקרי משאלה חיים חצי בדמיון: \"הכלב שלי עף\", או \"לא שברתי\" שנאמר במשלב של הלוואי שלא. האחיזה של ילדים צעירים בקיר שבין מבוקש למציאותי עדיין רכה, והשקרים האלה צריכים בעיקר עיגון עדין למציאות, לא תביעה: \"זה היה מדהים. מה קרה באמת?\" שקרי חיפוי — שנועדו לחמוק מתוצאות — הם אלה שמדאיגים הורים, והם מגיבים לכלכלה יותר מאשר להרצאות: ילד משקר כדי להימלט ממחיר, אז השאלה היא כמה עולה אצלכם בבית לומר אמת.\n\nומכאן הכלל המעשי ביותר בשטח הזה: לא טומנים מלכודות. \"אכלת את העוגייה?\" כשנשאל עם העטיפה ביד אינו בירור; זו הזמנה לשקר, עם קהל. הילד, בפינה, לוקח את היציאה — ועכשיו יש שתי בעיות במקום אחת. אמרו מה אתם רואים ועברו לתיקון: \"אני רואה שהעוגייה נגמרה ותכף צהריים. בפעם הבאה, תשאל אותי.\" אתם שומרים על אמינותכם, הוא שומר על כבודו, והשיחה עוסקת בעניין האמיתי.\n\nהמשחק הארוך הוא להפוך את הכנות לאופציה הזולה. כשהודאה נענית ברוגע — \"תודה שסיפרת לי; בוא ננקה\" — האמת נשארת הגיונית. כשהיא מציתה סערה, השקר נעשה הגנה עצמית, ומחקרים על כנות של ילדים מוצאים בדיוק את הדפוס הזה: באקלים מעניש ילדים לא משקרים פחות — הם משקרים טוב יותר. הוסיפו את תוכנית הלימודים השקטה של הדוגמה שלכם — הכנויות היומיומיות הקטנות, כולל לעמוד במילה שלכם כלפיהם ולהודות בקול בפספוסים שלכם — ורוב הילדים גדלים לדוברי אמת בדרך הלא-זוהרת: הם חיים במקום שבו תמיד היה בטוח לומר את האמת."
    ),
    tryToday: L(
      "Next time you already know what happened, skip the quiz. Say what you see — \"I see the water spilled\" — and go straight to the fix together. No trap, no lie, no trial.",
      "בפעם הבאה שאתם כבר יודעים מה קרה, ותרו על החקירה. אמרו מה אתם רואים — \"אני רואה שהמים נשפכו\" — ועברו ישר לתיקון ביחד. בלי מלכודת, בלי שקר, בלי משפט."
    ),
    ask: L("How should I respond when my child tells an obvious lie?", "איך כדאי להגיב כשהילד שלי משקר שקר גלוי?"),
  },
];
