/**
 * Learn Library seed catalogue — batch 2C (screens · eating · motion ·
 * parent). Same editorial stance as batches A/B (see learnCardsCore.ts).
 */
import type { LocalizedText } from "../content/governance";
import type { LearnCard } from "./learnLibrary";

const L = (en: string, he: string): LocalizedText => ({ en, he });

export const LEARN_CARDS_BATCH2C: LearnCard[] = [
  // ── Screens & Digital ────────────────────────────────────────────────────
  {
    id: "parent-phone-modeling",
    category: "screens",
    domains: ["ecosystem_stressors", "language_communication"],
    ageMin: 0,
    ageMax: 10,
    minutes: 3,
    title: L("Your phone habits are the curriculum", "הרגלי הטלפון שלכם הם תוכנית הלימודים"),
    hook: L("Children learn what a phone is for by watching yours — long before any screen rule you set for them applies.", "ילדים לומדים בשביל מה טלפון קיים מצפייה בשלכם — הרבה לפני שכל כלל מסכים שקבעתם להם רלוונטי."),
    keyPoints: [
      L("Media habits are learned mostly by observation: the house's real screen policy is whatever the adults visibly do.", "הרגלי מדיה נלמדים בעיקר מהתבוננות: מדיניות המסכים האמיתית של הבית היא מה שהמבוגרים עושים בגלוי."),
      L("Researchers call phone interruptions of parent-child moments 'technoference' — studies link frequent interruptions with more bids for attention and rockier interactions.", "חוקרים קוראים להפרעות טלפון ברגעי הורה־ילד 'טכנופרנס' — מחקרים קושרים הפרעות תכופות ליותר קריאות לתשומת לב ולאינטראקציות סוערות יותר."),
      L("A face aimed at a screen is unreadable; children register the flat, delayed responses within seconds and work harder to break through.", "פנים שמופנות למסך אינן קריאות; ילדים קולטים את התגובות השטוחות והמאוחרות בתוך שניות ומתאמצים יותר לפרוץ פנימה."),
      L("Narrate your use out loud — 'I'm checking the map, then it goes in my pocket' — a phone's purpose is invisible unless you say it.", "תארו את השימוש שלכם בקול — \"אני בודקת את המפה, ואז הוא נכנס לכיס\" — המטרה של טלפון בלתי נראית אלא אם אומרים אותה."),
      L("Visible endings teach more than limits: putting the phone down, out loud, at predictable anchors (meals, pickup, bedtime) is the lesson itself.", "סיומים גלויים מלמדים יותר מהגבלות: להניח את הטלפון, בקול, בעוגנים צפויים (ארוחות, איסוף, השכבה) הוא השיעור עצמו."),
    ],
    body: L(
      "Most family screen rules point at the children: how many episodes, which apps, no tablets at the table. Meanwhile the most-watched screen in the house is the one in the adult's hand. Children build their model of what phones are — how often you check one, what it does to a conversation, whether it wins against a person — almost entirely by observation. Whatever you announce, the visible habit is the curriculum.\n\nResearchers have a name for the moments when the device cuts into the relationship: technoference. Studies of parent-child interaction find that when a phone interrupts play or a meal, conversations shorten, responses flatten and slow, and children work harder — sometimes louder — to reclaim attention; frequent interruptions show up alongside more frustration and more attention-seeking behavior. These are associations, not verdicts on any single glance at a notification. But the mechanism is easy to feel from the child's side: a parent mid-scroll has the unresponsive face of someone who has briefly left the room without moving.\n\nThe honest fix is not zero phone — parents navigate, pay, coordinate and work on these devices, and children benefit from seeing that tools have uses. What children can't see is which use is happening. A parent staring at a screen might be reading poetry or buying socks; to a four-year-old it's all the same absence. So narrate: 'I'm answering Grandma, then I'm done.' 'I need two minutes for a work thing — then it goes on the shelf.' Narration turns opaque absorption into a legible, bounded action — with a stated ending you can then visibly honor.\n\nStructure does the rest. Pick a few phone-free anchors where the adults' devices go away first — meals, the first ten minutes after pickup or reunion, the bedtime runway — and let children catch you ending your scroll out loud: 'Okay, phone away. I want to hear about the fort.' You don't need to be a monk. You need to be watchable. The goal is a house where phones are visibly tools with visible endings — because that, not the posted rules, is what your children are memorizing.",
      "רוב כללי המסכים המשפחתיים מצביעים על הילדים: כמה פרקים, אילו אפליקציות, בלי טאבלט ליד השולחן. בינתיים המסך הנצפה ביותר בבית הוא זה שביד של המבוגר. ילדים בונים את המודל שלהם למה זה טלפון — כמה פעמים בודקים אותו, מה הוא עושה לשיחה, האם הוא מנצח בן אדם — כמעט כולו מהתבוננות. מה שלא תכריזו, ההרגל הגלוי הוא תוכנית הלימודים.\n\nלחוקרים יש שם לרגעים שבהם המכשיר חותך לתוך הקשר: טכנופרנס. מחקרי אינטראקציית הורה־ילד מוצאים שכשטלפון קוטע משחק או ארוחה, שיחות מתקצרות, תגובות נעשות שטוחות ואיטיות, וילדים מתאמצים יותר — לפעמים בקול רם יותר — להחזיר אליהם את תשומת הלב; הפרעות תכופות מופיעות לצד יותר תסכול ויותר התנהגות מושכת תשומת לב. אלה קשרים סטטיסטיים, לא גזר דין על הצצה בודדת בהתראה. אבל את המנגנון קל להרגיש מהצד של הילד: הורה באמצע גלילה נושא את הפנים הלא־מגיבות של מי שיצא לרגע מהחדר בלי לזוז.\n\nהתיקון הכן אינו אפס טלפון — הורים מנווטים, משלמים, מתאמים ועובדים על המכשירים האלה, וילדים מרוויחים מלראות שלכלים יש שימושים. מה שילדים לא יכולים לראות הוא איזה שימוש קורה עכשיו. הורה שבוהה במסך אולי קורא שירה ואולי קונה גרביים; לילד בן ארבע הכול אותה היעדרות. אז תארו: \"אני עונה לסבתא, ואז סיימתי.\" \"אני צריך שתי דקות למשהו מהעבודה — ואז הוא עולה למדף.\" תיאור בקול הופך שקיעה אטומה לפעולה קריאה ותחומה — עם סיום מוצהר שאפשר אחר כך לכבד בגלוי.\n\nהמבנה עושה את השאר. בחרו כמה עוגנים נטולי טלפון שבהם המכשירים של המבוגרים נעלמים ראשונים — ארוחות, עשר הדקות הראשונות אחרי האיסוף או המפגש, המסלול להשכבה — ותנו לילדים לתפוס אתכם מסיימים את הגלילה בקול: \"טוב, טלפון בצד. אני רוצה לשמוע על המבצר.\" אתם לא צריכים להיות נזירים. אתם צריכים להיות ניתנים לצפייה. המטרה היא בית שבו טלפונים הם בגלוי כלים עם סיומים גלויים — כי זה, ולא הכללים שנתלו, מה שהילדים שלכם משננים."
    ),
    tryToday: L(
      "Pick one anchor — dinner or the first ten minutes after reunion — and park your phone somewhere visible and out of reach. Narrate it once: \"Phone's on the shelf. I'm all here.\"",
      "בחרו עוגן אחד — ארוחת ערב או עשר הדקות הראשונות אחרי המפגש — והחנו את הטלפון במקום גלוי ומחוץ להישג יד. תארו זאת פעם אחת: \"הטלפון על המדף. אני כולי כאן.\""
    ),
    ask: L("Help me design realistic phone-free anchors for our family's day.", "עזור לי לתכנן עוגנים ריאליים בלי טלפון ביום של המשפחה שלנו."),
    concerns: ["screens"],
  },

  // ── Eating & Growing ─────────────────────────────────────────────────────
  {
    id: "family-meals",
    category: "eating",
    domains: ["language_communication", "ecosystem_stressors", "independence_adaptive_skills"],
    ageMin: 2,
    ageMax: 12,
    minutes: 3,
    title: L("Family meals: the strongest habit in the research", "ארוחות משפחתיות: ההרגל החזק ביותר במחקר"),
    hook: L("Few household routines show up as consistently in child-development research as eating together — and the active ingredient isn't the food.", "מעט שגרות ביתיות מופיעות במחקר ההתפתחות בעקביות כמו לאכול יחד — והמרכיב הפעיל אינו האוכל."),
    keyPoints: [
      L("Regular shared meals appear in study after study alongside richer vocabulary, better wellbeing and steadier eating patterns — honest caveat: these are correlations, and families who eat together differ in many ways.", "ארוחות משותפות קבועות מופיעות מחקר אחרי מחקר לצד אוצר מילים עשיר יותר, רווחה טובה יותר ודפוסי אכילה יציבים יותר — הסתייגות כנה: אלה מתאמים, ומשפחות שאוכלות יחד שונות בהרבה מובנים."),
      L("The plausible ingredient is conversation: mealtime talk serves children rare words, family stories and turn-taking that few other daily moments provide.", "המרכיב הסביר הוא שיחה: שיחת ארוחה מגישה לילדים מילים נדירות, סיפורים משפחתיים ותורות דיבור שמעט רגעים יומיומיים אחרים מספקים."),
      L("The bar is lower than the ideal in your head: research patterns show up from around three shared meals a week — and breakfast or a weekend lunch counts.", "הרף נמוך מהאידיאל שבראש שלכם: הדפוסים המחקריים מופיעים כבר מסביבות שלוש ארוחות משותפות בשבוע — וגם ארוחת בוקר או צהריים של שבת נספרות."),
      L("What makes the minutes work: screens away, plates un-policed, and questions that open stories rather than audit the day.", "מה שגורם לדקות לעבוד: מסכים בצד, צלחות בלי שיטור, ושאלות שפותחות סיפורים במקום לבקר את היום."),
      L("Small rituals carry the conversation — highlight-and-lowlight, a question of the day, everyone gets a turn including the adults.", "טקסים קטנים נושאים את השיחה — רגע שיא ורגע שפל, שאלת היום, לכל אחד תור כולל המבוגרים."),
    ],
    body: L(
      "If you went looking for one household habit with the broadest research footprint, the family meal would be a strong candidate. Across decades of studies, children in families that regularly eat together show up with larger vocabularies, better reported wellbeing, and steadier relationships with food. An honest reading adds the caveat immediately: these are correlations. Families who manage frequent shared meals tend to differ in schedules, stress and resources, and no study hands the meal itself a guaranteed effect. But the association is unusually persistent — and the likely mechanism is cheap, pleasant and worth having anyway.\n\nThat mechanism is talk. Mealtime conversation is a strange, rich genre: it wanders across the day's events, family lore, plans and jokes, and along the way it serves children unusual words in meaningful context — researchers studying dinner-table language have found it a denser source of rare vocabulary than many storybooks. It also trains the invisible mechanics of conversation: waiting a turn, holding a thread, telling a story so someone else can follow it. The menu is beside the point. Pasta again is fine. The ingredient is faces, unhurried, around the same food.\n\nWhich means the standard can relax. The researched pattern is not a nightly candlelit dinner; signals show up in families managing around three shared meals a week, and nothing anoints dinner specifically — a slow weekend breakfast or a Saturday lunch counts in full. Twenty minutes is a real family meal. So is takeaway. If evenings are impossible in this season of your family's life, aim the ritual at the meals you can actually share, and let the impossible ones go without guilt.\n\nProtect the feel more than the frequency. Screens away — the adults' too, which is the hard half. Keep plates un-policed: the meal works as connection, and dies as inspection (bite-counting has its own card). And when conversation stalls, borrow a ritual: highlight and lowlight of the day, a question of the day, 'tell me something that made you laugh.' Adults answer too — children talk at tables where talk flows both ways.",
      "אם הייתם מחפשים הרגל ביתי אחד עם טביעת הרגל המחקרית הרחבה ביותר, הארוחה המשפחתית הייתה מועמדת חזקה. לאורך עשורים של מחקרים, ילדים במשפחות שאוכלות יחד באופן קבוע מופיעים עם אוצר מילים גדול יותר, רווחה מדווחת טובה יותר ויחסים יציבים יותר עם אוכל. קריאה כנה מוסיפה מיד את ההסתייגות: אלה מתאמים. משפחות שמצליחות לקיים ארוחות משותפות תכופות נוטות להיות שונות בלוחות זמנים, בלחץ ובמשאבים, ואף מחקר לא מעניק לארוחה עצמה אפקט מובטח. אבל הקשר עקבי במיוחד — והמנגנון הסביר זול, נעים ושווה שיהיה בבית בכל מקרה.\n\nהמנגנון הזה הוא דיבור. שיחת ארוחה היא ז'אנר מוזר ועשיר: היא משוטטת בין אירועי היום, סיפורי משפחה, תוכניות ובדיחות, ובדרך היא מגישה לילדים מילים לא שגרתיות בהקשר בעל משמעות — חוקרים שבדקו את שפת שולחן האוכל מצאו בה מקור צפוף יותר למילים נדירות מהרבה ספרי ילדים. היא גם מאמנת את המכניקה הסמויה של שיחה: לחכות לתור, להחזיק חוט מחשבה, לספר סיפור כך שמישהו אחר יוכל לעקוב. התפריט אינו העניין. שוב פסטה זה בסדר גמור. המרכיב הוא פנים, בלי חיפזון, סביב אותו אוכל.\n\nמה שאומר שאפשר להרפות מהסטנדרט. הדפוס שנחקר אינו ארוחת ערב חגיגית מדי לילה; אותות מופיעים אצל משפחות שמצליחות בסביבות שלוש ארוחות משותפות בשבוע, ושום דבר לא מקדש דווקא את ארוחת הערב — ארוחת בוקר איטית בסוף השבוע או צהריים של שבת נספרות במלואן. עשרים דקות הן ארוחה משפחתית אמיתית. גם אוכל מוזמן. אם הערבים בלתי אפשריים בעונה הזאת של חיי המשפחה, כוונו את הטקס לארוחות שאתם באמת יכולים לחלוק, ושחררו את הבלתי אפשריות בלי אשמה.\n\nהגנו על התחושה יותר מאשר על התדירות. מסכים בצד — גם של המבוגרים, וזה החצי הקשה. השאירו צלחות בלי שיטור: הארוחה עובדת כחיבור, ומתה כביקורת (לספירת ביסים יש כרטיס משלה). וכשהשיחה נתקעת, שאלו טקס: רגע שיא ורגע שפל של היום, שאלת היום, \"ספר לי משהו שהצחיק אותך.\" גם המבוגרים עונים — ילדים מדברים ליד שולחנות שבהם הדיבור זורם לשני הכיוונים."
    ),
    tryToday: L(
      "At the next meal you share, run one round of highlight-and-lowlight — everyone, adults included. Phones in another room. Notice how long the table lingers.",
      "בארוחה המשותפת הבאה, הריצו סבב אחד של רגע שיא ורגע שפל — כולם, כולל המבוגרים. טלפונים בחדר אחר. שימו לב כמה זמן השולחן מתעכב."
    ),
    ask: L("Give me a week of table questions that fit my child's age.", "תן לי שבוע של שאלות לשולחן שמתאימות לגיל של הילד שלי."),
    concerns: ["food", "routines"],
  },
  {
    id: "cooking-together",
    category: "eating",
    domains: ["independence_adaptive_skills", "cognition_executive_function"],
    ageMin: 2,
    ageMax: 8,
    minutes: 3,
    title: L("Cooking with kids: the hidden development activity", "לבשל עם ילדים: פעילות ההתפתחות הסמויה"),
    hook: L("A child stirring pancake batter is doing food exposure, math, sequencing and fine motor work at once — disguised as making a mess.", "ילד שמערבב בלילת פנקייק עושה בו־זמנית חשיפה לאוכל, חשבון, רצפים ומוטוריקה עדינה — בתחפושת של עשיית בלגן."),
    keyPoints: [
      L("Cooking is food exposure with zero table pressure: washing, smelling and handling a vegetable moves it toward familiar — no bite required.", "בישול הוא חשיפה לאוכל בלי שום לחץ של שולחן: לשטוף, להריח ולמשש ירק מקרב אותו אל המוכר — בלי שום ביס נדרש."),
      L("Research links helping to cook with more willingness to try foods — children eat differently what they had a hand in making.", "מחקרים קושרים עזרה בבישול לנכונות רבה יותר לטעום — ילדים אוכלים אחרת את מה שידם הייתה בהכנתו."),
      L("Measuring is math you can eat: cups, halves, counting eggs — quantity concepts land better in batter than on paper.", "מדידה היא חשבון שאפשר לאכול: כוסות, חצאים, ספירת ביצים — מושגי כמות נוחתים טוב יותר בבלילה מאשר על נייר."),
      L("A recipe is executive-function training: hold the goal, follow steps in order, wait for the oven — sequencing and patience with a delicious payoff.", "מתכון הוא אימון תפקודים ניהוליים: להחזיק מטרה, לעקוב אחרי שלבים בסדר, לחכות לתנור — רצף וסבלנות עם תמורה טעימה."),
      L("Give real jobs by age: around 2-3 wash, tear, stir; 3-5 measure, pour, spread, cut soft things with a butter knife; 5-8 crack eggs, read steps aloud, plan the salad.", "תנו תפקידים אמיתיים לפי גיל: בסביבות 2–3 לשטוף, לקרוע, לערבב; 3–5 למדוד, למזוג, למרוח, לחתוך דברים רכים בסכין קהה; 5–8 לשבור ביצים, להקריא שלבים, לתכנן את הסלט."),
    ],
    body: L(
      "Invite a preschooler into the kitchen and the first thing you get is slower dinner and a floury floor. Look past that, and you're running one of the denser development activities available in an ordinary home. Cooking touches food familiarity, math, language, sequencing and fine motor skill at once — and unlike most enrichment, it ends in something you can eat.\n\nStart with the food itself. For hesitant eaters, the kitchen is exposure without stakes: at the table, a new vegetable arrives as a demand; at the counter, it arrives as material. Washing it, peeling it, watching it change color in the pan — every contact lowers its strangeness, and none of it requires tasting. Studies of cooking involvement find children who help prepare food show more willingness to try it, vegetables included. It isn't magic; it's ownership. 'I made this' and 'I won't touch this' are hard positions to hold at the same time.\n\nThen there's the stealth academics. A recipe is a project plan a four-year-old can hold: a goal, steps in order, waiting built in. Measuring is quantity made physical — two cups, half a spoon, three eggs and one more. Following 'first the flour, then the milk' is sequencing; noticing the batter needs more stirring is monitoring; not eating the chocolate chips yet is inhibition, barely. Language rides along, as it usually does: whisk, knead, drizzle, simmer — verbs daily life never serves.\n\nThe craft is in the jobs. Children can tell decorative tasks from real ones, and real ones are what hold attention: around two to three, washing produce, tearing lettuce, stirring, sprinkling; three to five, measuring, pouring, spreading, cutting soft things with a butter knife; five to eight, cracking eggs, reading steps aloud, planning and assembling a dish of their own. Choose low-stakes recipes when you're learning this together — pancakes forgive, soufflés don't — and cook when nobody is desperately hungry, because teaching and starving mix badly. Expect mess; count it as tuition. The floor sweeps clean, and the child who stirred the soup sits differently at the table where it's served.",
      "הזמינו ילד בגיל הגן למטבח והדבר הראשון שתקבלו הוא ארוחת ערב איטית יותר ורצפה מקומחת. הביטו מעבר לזה, ואתם מריצים אחת מפעילויות ההתפתחות הצפופות ביותר שבית רגיל מציע. בישול נוגע בבת אחת בהיכרות עם אוכל, בחשבון, בשפה, ברצפים ובמוטוריקה עדינה — ובניגוד לרוב ההעשרות, הוא נגמר במשהו שאפשר לאכול.\n\nהתחילו באוכל עצמו. לאוכלים מהוססים, המטבח הוא חשיפה בלי הימור: ליד השולחן, ירק חדש מגיע כדרישה; ליד השיש, הוא מגיע כחומר גלם. לשטוף אותו, לקלף אותו, לראות אותו משנה צבע במחבת — כל מגע מפחית את הזרות שלו, ושום דבר מזה לא דורש טעימה. מחקרים על מעורבות בבישול מוצאים שילדים שעוזרים להכין אוכל מגלים נכונות רבה יותר לטעום אותו, כולל ירקות. זה לא קסם; זו בעלות. \"אני הכנתי את זה\" ו\"אני לא נוגע בזה\" הן עמדות שקשה להחזיק יחד.\n\nואז יש הלימודים הסמויים. מתכון הוא תוכנית פרויקט שילד בן ארבע מסוגל להחזיק: מטרה, שלבים בסדר, המתנה מובנית. מדידה היא כמות שנעשתה מוחשית — שתי כוסות, חצי כף, שלוש ביצים ועוד אחת. לעקוב אחרי \"קודם הקמח, אחר כך החלב\" זה רצף; לשים לב שהבלילה צריכה עוד ערבוב זה ניטור; לא לאכול עדיין את שבבי השוקולד זו שליטה בדחף, בקושי. השפה נוסעת יחד, כרגיל: להקציף, ללוש, לזלף, להרתיח על אש קטנה — פעלים שחיי היומיום לא מגישים.\n\nהאומנות היא בתפקידים. ילדים יודעים להבחין בין משימות קישוטיות לאמיתיות, והאמיתיות הן שמחזיקות קשב: בסביבות שנתיים־שלוש — לשטוף ירקות, לקרוע חסה, לערבב, לפזר; שלוש עד חמש — למדוד, למזוג, למרוח, לחתוך דברים רכים בסכין קהה; חמש עד שמונה — לשבור ביצים, להקריא שלבים, לתכנן ולהרכיב מנה משלהם. בחרו מתכונים סלחניים כשאתם לומדים את זה יחד — פנקייקים סולחים, סופלה לא — ובשלו כשאף אחד לא רעב נואשות, כי הוראה ורעב מתערבבים רע. צפו לבלגן; רשמו אותו כשכר לימוד. הרצפה מתנקה, והילד שערבב את המרק יושב אחרת ליד השולחן שבו הוא מוגש."
    ),
    tryToday: L(
      "Pick tonight's simplest dish and carve out one real job in it for your child — washing, stirring, measuring. Announce the title too: \"You're the sauce chef.\"",
      "בחרו את המנה הפשוטה של הערב וגזרו בה תפקיד אמיתי אחד לילד — לשטוף, לערבב, למדוד. הכריזו גם על התואר: \"אתה שף הרוטב.\""
    ),
    ask: L("Suggest three forgiving recipes with real jobs for my child's age.", "הצע שלושה מתכונים סלחניים עם תפקידים אמיתיים לגיל של הילד שלי."),
    concerns: ["food"],
  },
  {
    id: "food-as-reward",
    category: "eating",
    domains: ["independence_adaptive_skills", "attachment_regulation"],
    ageMin: 1,
    ageMax: 8,
    minutes: 3,
    title: L("Food as reward or comfort: a pattern worth retiring", "אוכל כפרס או כנחמה: דפוס ששווה לפרוש ממנו"),
    hook: L("\"Finish your broccoli and you'll get dessert\" works tonight — and teaches exactly the two lessons feeding research warns about.", "\"תגמור את הברוקולי ותקבל קינוח\" עובד הערב — ומלמד בדיוק את שני השיעורים שמחקר ההאכלה מזהיר מפניהם."),
    keyPoints: [
      L("The dessert-for-vegetables trade re-prices both foods: research on reward framing finds it raises the treat's glamour and casts the vegetable as the toll you pay for it.", "עסקת קינוח־תמורת־ירקות מתמחרת מחדש את שני המאכלים: מחקרים על מסגור פרסים מוצאים שהיא מעלה את זוהר הממתק ומציגה את הירק כאגרה שמשלמים עבורו."),
      L("Food given as a prize teaches eating for reasons other than hunger — the treat arrives because of behavior, not appetite.", "אוכל שניתן כפרס מלמד אכילה מסיבות שאינן רעב — הממתק מגיע בגלל התנהגות, לא בגלל תיאבון."),
      L("Food given as the default comfort wires eating to feelings; studies link habitual 'emotional feeding' with more emotional eating later — an association worth taking seriously.", "אוכל שניתן כנחמת ברירת המחדל מחווט אכילה לרגשות; מחקרים קושרים 'האכלה רגשית' הרגלית ליותר אכילה רגשית בהמשך — קשר ששווה להתייחס אליו ברצינות."),
      L("Rewards that work without side effects: time and experience — choosing the game, an extra story, a stamp on the hand, your delight.", "פרסים שעובדים בלי תופעות לוואי: זמן וחוויה — לבחור את המשחק, סיפור נוסף, חותמת על היד, ההתלהבות שלכם."),
      L("This is not a ban on treats: served occasionally, neutrally — sometimes even alongside the meal — dessert loses its throne and becomes food again.", "זה אינו איסור על ממתקים: כשהם מוגשים מדי פעם, בניטרליות — לפעמים אפילו לצד הארוחה — הקינוח מאבד את כס המלכות וחוזר להיות אוכל."),
    ],
    body: L(
      "The vegetable-for-dessert deal is one of parenting's oldest trades, and it usually works — tonight. The broccoli goes down, the ice cream comes out, everyone survives dinner. The trouble is what the deal teaches over hundreds of repetitions. Feeding researchers who study reward framing keep finding the same inversion: making one food the payment for another raises the reward food's status and marks the required food as an obstacle. The child learns, precisely and durably, that broccoli is the thing you endure and dessert is the thing that matters. You have not sold the vegetable; you have advertised against it.\n\nThe second pattern is quieter. Food is a genuine soother — sweet and rich foods do calm a distressed body, at any age — which is exactly why using it as the default comfort deserves caution. A scraped knee met reliably with a cookie teaches an association that has nothing to do with knees: feelings are fixed by eating. Studies following families over time link habitual emotional feeding with more emotional eating as children grow — an association, honestly stated, not a sentence passed on any single consoling biscuit. Patterns groove; moments don't.\n\nThe alternatives are cheap once you look for them. For comfort, lead with what the child is actually seeking — presence. Arms, acknowledgment, a name for the feeling; the cookie was always a proxy for you. For rewards, spend time and experience instead of sugar: choosing tonight's game, an extra story, ten minutes of wrestling, a stamp on the hand, your loud specific delight. These carry no pricing side effects and often outrank the treat anyway.\n\nNone of this exiles dessert — restriction runs the same machine in reverse, inflating exactly what it forbids. The evidence-aligned posture is neutrality: treats appear sometimes, unearned, in ordinary portions, announced with the same voice as the rice. Some feeding specialists even suggest occasionally serving the small dessert alongside dinner, dethroning it entirely. And forgive yourself the trades already made; every parent has bought a quiet supermarket trip with a biscuit. You're not erasing a record. You're changing a pattern, and patterns change from today forward.",
      "עסקת ירק־תמורת־קינוח היא מהעתיקות שבעסקאות ההורות, והיא בדרך כלל עובדת — הערב. הברוקולי יורד, הגלידה יוצאת, כולם שורדים את ארוחת הערב. הבעיה היא מה שהעסקה מלמדת לאורך מאות חזרות. חוקרי האכלה שבודקים מסגור פרסים מוצאים שוב ושוב את אותו היפוך: להפוך מאכל אחד לתשלום עבור אחר מעלה את מעמד מאכל־הפרס ומסמן את המאכל הנדרש כמכשול. הילד לומד, במדויק ולאורך זמן, שברוקולי הוא הדבר שסובלים וקינוח הוא הדבר שחשוב. לא מכרתם את הירק; פרסמתם נגדו.\n\nהדפוס השני שקט יותר. אוכל הוא מרגיע אמיתי — מאכלים מתוקים ועשירים באמת מרגיעים גוף במצוקה, בכל גיל — וזו בדיוק הסיבה ששימוש בו כנחמת ברירת המחדל דורש זהירות. ברך שרוטה שנענית באמינות בעוגייה מלמדת קשר שאין לו שום קשר לברכיים: רגשות מתוקנים באכילה. מחקרים שעוקבים אחרי משפחות לאורך זמן קושרים האכלה רגשית הרגלית ליותר אכילה רגשית כשהילדים גדלים — קשר סטטיסטי, בכנות, לא גזר דין על ביסקוויט מנחם בודד. דפוסים חורצים תלם; רגעים לא.\n\nהחלופות זולות ברגע שמחפשים אותן. לנחמה, פתחו במה שהילד באמת מחפש — נוכחות. זרועות, הכרה, שם לרגש; העוגייה תמיד הייתה תחליף לכם. לפרסים, שלמו בזמן ובחוויה במקום בסוכר: לבחור את משחק הערב, סיפור נוסף, עשר דקות התגוששות, חותמת על היד, ההתלהבות הרועמת והמפורטת שלכם. לאלה אין תופעות לוואי של תמחור, והם לא פעם גוברים על הממתק ממילא.\n\nכל זה לא מגלה את הקינוח — הגבלה מפעילה את אותה מכונה הפוך, ומנפחת בדיוק את מה שהיא אוסרת. העמדה שתואמת את הראיות היא ניטרליות: ממתקים מופיעים לפעמים, לא כפרס, במנות רגילות, מוכרזים באותו קול כמו האורז. יש מומחי האכלה שמציעים אפילו להגיש מדי פעם את הקינוח הקטן לצד ארוחת הערב, ולהדיח אותו מהכס לגמרי. וסלחו לעצמכם על העסקאות שכבר נעשו; כל הורה קנה פעם סיבוב סופר שקט בביסקוויט. אתם לא מוחקים רישום. אתם משנים דפוס, ודפוסים משתנים מהיום והלאה."
    ),
    tryToday: L(
      "Next scraped knee or hard moment, comfort with presence first: arms, a name for the feeling, a minute of quiet. Notice whether the snack still gets asked for.",
      "בברך השרוטה או ברגע הקשה הבא, נחמו קודם בנוכחות: זרועות, שם לרגש, דקה של שקט. שימו לב אם החטיף בכלל עוד מתבקש."
    ),
    ask: L("Help me build a list of non-food rewards and comforts my child would love.", "עזור לי לבנות רשימת פרסים ונחמות שאינם אוכל שהילד שלי יאהב."),
    concerns: ["food"],
  },

  // ── Body & Motion ────────────────────────────────────────────────────────
  {
    id: "tummy-time",
    category: "motion",
    domains: ["sensory_motor_patterns"],
    ageMin: 0,
    ageMax: 1,
    minutes: 3,
    title: L("Tummy time: why it matters, and how to make it bearable", "זמן בטן: למה זה חשוב, ואיך לעשות אותו נסבל"),
    hook: L("Back to sleep, tummy to play — the safe-sleep win created a daytime training need, and most babies file a formal complaint about it.", "על הגב לישון, על הבטן לשחק — ניצחון השינה הבטוחה יצר צורך אימון ביום, ורוב התינוקות מגישים עליו תלונה רשמית."),
    keyPoints: [
      L("The backstory: back-sleeping sharply reduced sleep-related infant deaths — a public-health success — which made awake tummy time the main training window for the upper body.", "הרקע: שינה על הגב הפחיתה בחדות מקרי מוות בשינה אצל תינוקות — הצלחה בריאותית — ולכן זמן בטן בערות נעשה חלון האימון המרכזי לפלג הגוף העליון."),
      L("Tummy time builds the neck, shoulder and core strength that rolling, sitting and crawling later stand on, and gives the head time off the mattress — which helps ward off flat spots.", "זמן בטן בונה את כוח הצוואר, הכתפיים והליבה שגלגול, ישיבה וזחילה יישענו עליו בהמשך, ונותן לראש זמן מחוץ למזרן — מה שעוזר למנוע השטחות."),
      L("Start with seconds, not minutes, from the first weeks — a few short rounds a day add up, and the totals grow with the baby.", "התחילו בשניות, לא בדקות, כבר מהשבועות הראשונים — כמה סבבים קצרים ביום מצטברים, והסכומים גדלים עם התינוק."),
      L("Chest-to-chest counts: baby prone on your chest, across your lap, or in a carry — tummy time is a position, not a location.", "חזה־אל־חזה נחשב: תינוק על הבטן על החזה שלכם, לרוחב הברכיים, או בנשיאה — זמן בטן הוא תנוחה, לא מיקום."),
      L("Protest is common and not a verdict; timing (fresh, not just-fed), your face at floor level, and a mirror or toy make it workable.", "מחאה היא שכיחה ואינה גזר דין; תזמון (רענן, לא מיד אחרי אוכל), הפנים שלכם בגובה הרצפה, ומראה או צעצוע הופכים את זה לבר־ביצוע."),
    ],
    body: L(
      "Tummy time exists because of one of pediatrics' clearest wins. When back-sleeping became the standard advice, sleep-related infant deaths fell dramatically — and babies, now spending their nights supine, lost the hours of prone strengthening that earlier generations got by accident. The fix is the slogan your nurse has already recited: back to sleep, tummy to play. The waking hours took over the job the nights used to do.\n\nWhat the position trains is the launch pad for nearly everything that follows. Lifting that oversized head against gravity builds neck and shoulder strength; pushing up through the forearms wakes the arms and upper back; the whole arrangement recruits the core. Rolling, sitting, crawling and pulling to stand all draw on this account later. There's a shape benefit too, stated calmly: heads that spend all their time against a surface can flatten at the contact point. Positional flat spots are common, usually mild, largely cosmetic and tend to improve as babies move more — and time spent off the back of the head, awake and supervised, is the everyday preventive.\n\nNow the honest part: many babies hate it at first, and the protest can rattle a new parent into quietly dropping the whole project. Don't drop it — shrink it. Tummy time starts in seconds, not minutes: two or three tiny rounds a day in the early weeks, stretching gradually as strength arrives. And the position is broader than the play-mat marketing suggests. A baby prone on your chest while you recline is doing tummy time with the best view in the house. Across your lap works. The football carry works. Floor sessions get friendlier with your face at floor level — the strongest lure there is — plus a low mirror or a high-contrast toy, timed for a fresh baby rather than a just-fed or exhausted one.\n\nThen watch momentum rather than the clock: over weeks, the head steadies, the push-up rises, the complaints shorten. Worth mentioning to your doctor: a baby who strongly tilts or turns the head to one side only, or who still can't tolerate any prone time after months of gentle practice — as an observation for a good conversation, not a conclusion.",
      "זמן בטן קיים בזכות אחד הניצחונות הברורים של רפואת הילדים. כששינה על הגב הפכה להמלצה הסטנדרטית, מקרי מוות בשינה אצל תינוקות צנחו דרמטית — ותינוקות, שמבלים עכשיו את לילותיהם על הגב, איבדו את שעות החיזוק על הבטן שדורות קודמים קיבלו במקרה. התיקון הוא הסיסמה שהאחות בטיפת חלב כבר דקלמה לכם: על הגב לישון, על הבטן לשחק. שעות הערות קיבלו את התפקיד שהלילות עשו פעם.\n\nמה שהתנוחה מאמנת הוא כן השיגור של כמעט כל מה שיבוא. הרמת הראש הענק כנגד הכובד בונה כוח צוואר וכתפיים; דחיפה דרך האמות מעירה את הזרועות והגב העליון; כל הסידור מגייס את הליבה. גלגול, ישיבה, זחילה ומשיכה לעמידה — כולם מושכים מהחשבון הזה אחר כך. יש גם יתרון צורה, בניסוח רגוע: ראשים שמבלים את כל זמנם כנגד משטח יכולים להשתטח בנקודת המגע. השטחות תנוחתיות הן שכיחות, בדרך כלל קלות, בעיקרן קוסמטיות ונוטות להשתפר ככל שהתינוק זז יותר — וזמן מחוץ לגב הראש, בערות ובהשגחה, הוא המניעה היומיומית.\n\nועכשיו החלק הכן: הרבה תינוקות שונאים את זה בהתחלה, והמחאה יכולה לזעזע הורה טרי עד כדי נטישה שקטה של כל הפרויקט. אל תנטשו — הקטינו. זמן בטן מתחיל בשניות, לא בדקות: שניים־שלושה סבבים זעירים ביום בשבועות הראשונים, שמתארכים בהדרגה כשהכוח מגיע. והתנוחה רחבה ממה שפרסומות המזרנים מרמזות. תינוק על הבטן על החזה שלכם כשאתם שכובים למחצה עושה זמן בטן עם הנוף הטוב בבית. לרוחב הברכיים עובד. נשיאת פוטבול עובדת. מפגשי רצפה נעשים ידידותיים יותר כשהפנים שלכם בגובה הרצפה — הפיתיון החזק ביותר שיש — בתוספת מראה נמוכה או צעצוע בניגודיות גבוהה, ובתזמון של תינוק רענן ולא אחד שזה עתה אכל או מותש.\n\nואז צפו בתנופה ולא בשעון: לאורך שבועות, הראש מתייצב, שכיבת הסמיכה עולה, התלונות מתקצרות. שווה אזכור לרופא: תינוק שמטה או מסובב את הראש בחוזקה לצד אחד בלבד, או שאחרי חודשים של תרגול עדין עדיין לא סובל שום זמן בטן — כתצפית לשיחה טובה, לא כמסקנה."
    ),
    tryToday: L(
      "After the next nap, do one chest-to-chest round: recline, baby prone on you, and chat for a minute. That's real tummy time — log it as a win.",
      "אחרי השינה הבאה, עשו סבב אחד חזה־אל־חזה: הישענו לאחור, התינוק על הבטן עליכם, ופטפטו דקה. זה זמן בטן אמיתי — רשמו ניצחון."
    ),
    ask: L("Build me a tiny tummy-time routine that fits our day and my baby's tolerance.", "בנה לי שגרת זמן בטן זעירה שמתאימה ליום שלנו ולסבולת של התינוק."),
  },
  {
    id: "fine-motor-writing",
    category: "motion",
    domains: ["sensory_motor_patterns", "cognition_executive_function"],
    ageMin: 2,
    ageMax: 6,
    minutes: 3,
    title: L("From fist to pencil grip: how hand skill really builds", "מאגרוף לאחיזת עיפרון: איך מיומנות היד באמת נבנית"),
    hook: L("The road to handwriting runs through shoulders, playdough and clothespins — and almost never through earlier worksheets.", "הדרך לכתב יד עוברת דרך כתפיים, בצק ואטבי כביסה — וכמעט אף פעם לא דרך דפי עבודה מוקדמים יותר."),
    keyPoints: [
      L("Grasp matures on a long arc — whole-fist hold, then crude finger grips, then something tripod-like — each stage functional for its age, with wide-normal timing.", "האחיזה מבשילה על קשת ארוכה — אחיזת אגרוף מלאה, אחר כך אחיזות אצבעות גסות, ואז משהו דמוי־חצובה — כל שלב תפקודי לגילו, עם תזמון רחב־נורמלי."),
      L("Fingers stand on shoulders and core: stability close to the body comes before control far from it — a wobbly trunk makes a wobbly pencil.", "אצבעות נשענות על כתפיים וליבה: יציבות קרוב לגוף קודמת לשליטה רחוק ממנו — גו רופף עושה עיפרון רופף."),
      L("Climbing, crawling, hanging and easel painting are handwriting prerequisites in disguise — big before small.", "טיפוס, זחילה, תלייה וציור על כן הם דרישות קדם לכתב יד בתחפושת — גדול לפני קטן."),
      L("At preschool age, playdough, tongs, clothespins, stickers, threading and spray bottles build the hand better than worksheets do.", "בגיל הגן, בצק, מלקחיים, אטבי כביסה, מדבקות, השחלה ובקבוקי התזה בונים את היד טוב יותר מדפי עבודה."),
      L("Writing readiness is wide-normal; pushing pencil grip early can entrench awkward patterns. Months of avoiding all fine-motor play plus frustration across settings is a fair topic for a professional conversation.", "מוכנות לכתיבה היא רחבת־נורמלי; דחיפת אחיזת עיפרון מוקדם עלולה לקבע דפוסים מסורבלים. חודשים של הימנעות מכל משחק מוטוריקה עדינה בתוספת תסכול בכל מסגרת הם נושא הוגן לשיחה מקצועית."),
    ],
    body: L(
      "Somewhere between preschool and the first school forms, parents start watching the pencil grip like a verdict. It helps to see the whole arc first. A toddler holds a crayon in a full fist and scribbles from the shoulder — correct for that age. Over the next years the grip migrates down the arm: elbow strokes, then wrist, then fingers, arriving somewhere around a tripod-like hold in the preschool-to-school window. Each stage is functional for its moment, the timing is wide-normal, and a five-year-old's slightly odd-looking grip that works — comfortable, legible output, no fatigue — is usually just that: a grip that works.\n\nThe counterintuitive part is where the skill comes from. Fine motor control is built proximal-to-distal: stability near the body's center first, control at the fingertips last. A child whose shoulder girdle and trunk are weak has nothing to steady the hand against, and no amount of tracing drills fixes that from the fingers backward. Which promotes an unexpected set of activities to handwriting preparation: climbing, crawling games, wheelbarrow walks, hanging from monkey bars, painting on an easel where the arm works against a vertical surface. Big before small — the writing arm is trained at the playground.\n\nCloser in, the hand itself wants strength and separation — the ability to move some fingers while others hold still. The best equipment is household-grade: playdough squeezed, rolled and pinched; tongs and clothespins moving pompoms between bowls; stickers peeled; beads threaded; spray bottles doing the plants; coins into a piggy bank. These beat worksheets at this age for an honest reason — they load the same muscles and precision with motivation built in, and they end before frustration does.\n\nSo hold formal writing loosely. Interest is the green light, and readiness scatters across a wide band; pressing a pencil into a hand that isn't ready mostly practices awkward patterns that later need undoing. Offer chunky crayons, short strokes, names in sand and steam — and let the letters come when the hand does. Worth a professional conversation, described in whens and whats: months of avoiding all fine-motor play, visible frustration with hands across home and preschool, or skills that were present and faded. For everyone else: more playdough, more monkey bars, less worry.",
      "אי שם בין הגן לטפסים הראשונים של בית הספר, הורים מתחילים לצפות באחיזת העיפרון כמו בגזר דין. עוזר לראות קודם את הקשת כולה. פעוט מחזיק צבע באגרוף מלא ומשרבט מהכתף — נכון לגילו. בשנים הבאות האחיזה נודדת במורד הזרוע: משיכות מהמרפק, אחר כך מפרק כף היד, ואז האצבעות, עד הגעה לאחיזה דמוית־חצובה איפשהו בחלון שבין הגן לבית הספר. כל שלב תפקודי לרגעו, התזמון רחב־נורמלי, ואחיזה קצת מוזרה למראה של בן חמש שעובדת — נוחה, תוצר קריא, בלי עייפות — היא בדרך כלל בדיוק זה: אחיזה שעובדת.\n\nהחלק המפתיע הוא מאיפה המיומנות מגיעה. שליטה מוטורית עדינה נבנית מהמרכז החוצה: יציבות קרוב למרכז הגוף קודם, שליטה בקצות האצבעות אחרונה. לילד שחגורת הכתפיים והגו שלו חלשים אין על מה לייצב את היד, ושום כמות של תרגילי עקיבה לא תתקן את זה מהאצבעות אחורה. וזה מקדם סט לא צפוי של פעילויות למעמד של הכנה לכתיבה: טיפוס, משחקי זחילה, הליכת מריצה, תלייה על מתקנים, ציור על כן שבו הזרוע עובדת כנגד משטח אנכי. גדול לפני קטן — זרוע הכתיבה מתאמנת בגן השעשועים.\n\nקרוב יותר, היד עצמה רוצה כוח והפרדה — היכולת להזיז חלק מהאצבעות בזמן שאחרות מחזיקות. הציוד הטוב ביותר הוא ביתי לגמרי: בצק שנמעך, מגולגל ונצבט; מלקחיים ואטבי כביסה שמעבירים פונפונים בין קערות; מדבקות שמקולפות; חרוזים שמושחלים; בקבוקי התזה שמשקים את העציצים; מטבעות לקופת חיסכון. אלה מנצחים דפי עבודה בגיל הזה מסיבה כנה — הם מעמיסים את אותם שרירים ואותו דיוק עם מוטיבציה מובנית, והם נגמרים לפני שהתסכול מתחיל.\n\nאז החזיקו את הכתיבה הפורמלית ברפיון. עניין הוא האור הירוק, והמוכנות מפוזרת על רצועה רחבה; לדחוף עיפרון ליד שאינה מוכנה בעיקר מתרגל דפוסים מסורבלים שאחר כך צריך לפרק. הציעו צבעים עבים, קווים קצרים, שמות בחול ובאדים על החלון — ותנו לאותיות לבוא כשהיד באה. שווה שיחה מקצועית, מתוארת במתי ומה: חודשים של הימנעות מכל משחק מוטוריקה עדינה, תסכול נראה לעין מהידיים גם בבית וגם בגן, או מיומנויות שהיו ודעכו. לכל השאר: עוד בצק, עוד מתקני תלייה, פחות דאגה."
    ),
    tryToday: L(
      "Set out a bowl of pompoms, a pair of kitchen tongs and an empty egg carton. \"Fill every cup\" is a full hand workout that feels like a game.",
      "הניחו קערת פונפונים, מלקחי מטבח ותבנית ביצים ריקה. \"מלאו כל שקע\" הוא אימון יד שלם שמרגיש כמו משחק."
    ),
    ask: L("What hand-building games fit my child's current stage?", "אילו משחקים בוני־יד מתאימים לשלב הנוכחי של הילד שלי?"),
  },
  {
    id: "outdoor-time",
    category: "motion",
    domains: ["sensory_motor_patterns", "ecosystem_stressors"],
    ageMin: 1,
    ageMax: 10,
    minutes: 3,
    title: L("Outdoor time: eyes, sleep, mood — the quiet multivitamin", "זמן בחוץ: עיניים, שינה, מצב רוח — המולטי־ויטמין השקט"),
    hook: L("Daylight, terrain and room to run reach systems no indoor activity touches — and the dose is more forgiving than you'd think.", "אור יום, שטח ומקום לרוץ מגיעים למערכות ששום פעילות בתוך הבית לא נוגעת בהן — והמינון סלחני משתחשבו."),
    keyPoints: [
      L("Eyes first: time outdoors in daylight is one of the more consistent factors studies associate with lower rates of childhood nearsightedness — bright light, not sport, appears to be the ingredient.", "קודם העיניים: זמן בחוץ באור יום הוא מהגורמים העקביים יותר שמחקרים קושרים לשיעורים נמוכים יותר של קוצר ראייה בילדות — האור החזק, לא הספורט, נראה כמרכיב הפעיל."),
      L("Morning daylight anchors the body clock; outdoor mornings show up in research alongside easier evenings and steadier sleep.", "אור בוקר מעגן את השעון הביולוגי; בקרים בחוץ מופיעים במחקר לצד ערבים קלים יותר ושינה יציבה יותר."),
      L("Outdoor movement is naturally varied and vigorous — uneven ground, climbing, distance running — a motor diet indoor play can't match.", "תנועה בחוץ מגוונת ונמרצת מטבעה — קרקע לא אחידה, טיפוס, ריצה למרחק — תפריט מוטורי שמשחק בבית לא משתווה לו."),
      L("Green time and mood: studies find time in natural settings associated with calmer, more attentive children — framed honestly as association, it's still a cheap bet.", "זמן ירוק ומצב רוח: מחקרים מוצאים שזמן בסביבה טבעית קשור לילדים רגועים וקשובים יותר — במסגור כן כקשר סטטיסטי, זה עדיין הימור זול."),
      L("Dose: aim generous — an hour or more on days you can — and take any amount on days you can't. Weather is mostly a clothing problem.", "מינון: כוונו בנדיבות — שעה ומעלה בימים שאפשר — וקחו כל כמות בימים שאי אפשר. מזג אוויר הוא בעיקר בעיית ביגוד."),
    ],
    body: L(
      "Of all the things researchers have measured about childhood lately, one of the stranger findings concerns eyes. Nearsightedness has been rising worldwide, and across multiple large studies, one protective factor keeps surfacing: time outdoors in daylight. The leading explanation isn't about screens or reading at all — it's light intensity. Outdoor light is many times brighter than any living room, and that brightness appears to matter for how the growing eye regulates itself. Framed honestly, these are associations plus a plausible mechanism, not a guarantee for any child. But 'send them outside' has become a mainstream line in pediatric eye care, which is remarkable for advice this pleasant.\n\nThe eyes are just the newest entry on an older list. Morning daylight is the body clock's anchor: light early in the day helps set the rhythm that makes melatonin arrive on time that night, and outdoor mornings show up in sleep research alongside easier bedtimes. The body gets a different curriculum out there too — uneven ground, slopes, things to climb and real distances produce movement that is more varied and more vigorous than nearly anything indoors, training balance and strength as a side effect of chasing a ball. And the mood file keeps thickening: studies of time in green settings find associations with calmer, more attentive, less stressed children. Every parent has run the informal replication — the fractious afternoon that dissolved at the park.\n\nOutside is also where risky play lives — the graded thrills of height and speed that build judgment and confidence (that card is worth reading alongside this one). A backyard, a courtyard, a strip of park: none of it needs to be wilderness to count.\n\nOn dose, be ambitious and forgiving at once. An hour-plus of outdoor time on days you can manage it is a generous, reachable aim — and on the days you can't, twenty minutes beats zero by exactly twenty minutes. The practical trick is making outside a default rather than an event: walk part of the daycare run, move the after-dinner slump to a loop around the block, take the snack to the steps. Weather is mostly a gear problem — the Scandinavian line that there's no bad weather, only bad clothes, is annoying and largely true. Rain gear is cheaper than another indoor afternoon.",
      "מכל הדברים שחוקרים מדדו על ילדוּת לאחרונה, אחד הממצאים המוזרים נוגע לעיניים. קוצר ראייה נמצא בעלייה עולמית, ובמחקרים גדולים רבים גורם מגן אחד צף שוב ושוב: זמן בחוץ באור יום. ההסבר המוביל אינו עוסק כלל במסכים או בקריאה — אלא בעוצמת האור. אור חוץ בהיר פי כמה וכמה מכל סלון, ולבהירות הזאת יש כנראה משמעות לאופן שבו העין הגדלה מווסתת את עצמה. במסגור כן, אלה קשרים סטטיסטיים ועוד מנגנון סביר, לא הבטחה לאף ילד. אבל \"תשלחו אותם החוצה\" הפך לשורה מקובלת ברפואת עיניים לילדים, וזה מרשים עבור עצה נעימה כל כך.\n\nהעיניים הן רק הרשומה החדשה ברשימה ישנה יותר. אור בוקר הוא העוגן של השעון הביולוגי: אור מוקדם ביום עוזר לכוון את המקצב שמביא את המלטונין בזמן באותו לילה, ובקרים בחוץ מופיעים במחקרי שינה לצד השכבות קלות יותר. גם הגוף מקבל שם תוכנית לימודים אחרת — קרקע לא אחידה, מדרונות, דברים לטפס עליהם ומרחקים אמיתיים מייצרים תנועה מגוונת ונמרצת יותר כמעט מכל דבר בבית, ומאמנים שיווי משקל וכוח כתופעת לוואי של מרדף אחרי כדור. ותיק מצב הרוח ממשיך להתעבות: מחקרים על זמן בסביבה ירוקה מוצאים קשרים לילדים רגועים, קשובים ופחות לחוצים. כל הורה כבר הריץ את השחזור הלא רשמי — אחר הצהריים העצבני שנמס בפארק.\n\nבחוץ גר גם המשחק הנועז — הריגושים המדורגים של גובה ומהירות שבונים שיקול דעת וביטחון (שווה לקרוא את הכרטיס ההוא לצד זה). חצר, חורשה, רצועת פארק: שום דבר מזה לא צריך להיות טבע פראי כדי להיספר.\n\nלגבי המינון, היו שאפתנים וסלחניים בבת אחת. שעה ומעלה בחוץ בימים שאתם מסוגלים היא יעד נדיב ובר־השגה — ובימים שלא, עשרים דקות מנצחות אפס בדיוק בעשרים דקות. הטריק המעשי הוא להפוך את החוץ לברירת מחדל ולא לאירוע: ללכת ברגל חלק מהדרך לגן, להעביר את שקיעת אחרי־הארוחה לסיבוב סביב הבלוק, לקחת את החטיף למדרגות. מזג אוויר הוא בעיקר בעיית ציוד — השורה הסקנדינבית שאין מזג אוויר רע, רק בגדים לא נכונים, מעצבנת ונכונה ברובה. חליפת גשם זולה מעוד אחר צהריים בבית."
    ),
    tryToday: L(
      "Move one indoor slot outside today — snack on the steps, the after-dinner slump to a block loop. Same activity, different sky.",
      "העבירו היום חלון אחד מהבית החוצה — חטיף על המדרגות, שקיעת אחרי־הארוחה לסיבוב סביב הבלוק. אותה פעילות, שמיים אחרים."
    ),
    ask: L("Help me build a realistic daily outdoor rhythm for our schedule and weather.", "עזור לי לבנות קצב יומי ריאלי של זמן בחוץ ללוח הזמנים ולמזג האוויר שלנו."),
  },

  // ── The Parent ───────────────────────────────────────────────────────────
  {
    id: "parental-burnout",
    category: "parent",
    domains: ["ecosystem_stressors", "attachment_regulation"],
    ageMin: 0,
    ageMax: 12,
    minutes: 4,
    title: L("Parental burnout: the signs, and what actually helps", "שחיקה הורית: הסימנים, ומה באמת עוזר"),
    hook: L("Researchers describe a specific triad — exhaustion, distance, lost joy — and it strikes devoted parents, not careless ones.", "חוקרים מתארים שלישייה מסוימת — תשישות, ריחוק, שמחה שאבדה — והיא פוגעת דווקא בהורים מסורים, לא במזלזלים."),
    keyPoints: [
      L("The research triad: exhaustion the usual rest doesn't touch, creeping emotional distance from your children, and lost pleasure and confidence in the role.", "השלישייה המחקרית: תשישות שהמנוחה הרגילה לא נוגעת בה, ריחוק רגשי מתגנב מהילדים, ואובדן הנאה וביטחון בתפקיד."),
      L("Burnout is not proof of bad parenting — if anything it tracks investment: it takes deep caring to burn.", "שחיקה אינה הוכחה להורות גרועה — אם כבר היא הולכת עם השקעה: צריך אכפתיות עמוקה כדי להישרף."),
      L("The engine is a sustained gap between demands and resources — which yields exactly two families of levers: shrink demands, grow resources.", "המנוע הוא פער מתמשך בין דרישות למשאבים — ומזה נגזרות בדיוק שתי משפחות של מנופים: להקטין דרישות, להגדיל משאבים."),
      L("The most editable demands are invisible standards — the home-cooked-everything, always-patient, enriched-every-afternoon bar nobody actually set for you.", "הדרישות הניתנות ביותר לעריכה הן סטנדרטים סמויים — רף הכל־מבושל־בבית, תמיד־סבלנית, העשרה־כל־אחר־צהריים שאף אחד לא באמת הציב לכם."),
      L("Load-sharing must include the mental load — who tracks, plans and remembers — and micro-recovery works: small, protected, daily beats rare and grand. When weeks pass and nothing refills, a professional conversation is a strong move, and it helps.", "חלוקת עומס חייבת לכלול את העומס המנטלי — מי עוקב, מתכנן וזוכר — ומיקרו־התאוששות עובדת: קטן, מוגן ויומי מנצח נדיר ומפואר. כשעוברים שבועות ושום דבר לא מתמלא, שיחה מקצועית היא מהלך חזק, והיא עוזרת."),
    ],
    body: L(
      "There is a specific state beyond ordinary parental tiredness, and researchers have spent the last decade mapping it. Parental burnout, in the scientific literature, is a triad: exhaustion so deep the usual weekend doesn't dent it; a creeping emotional distance from your children — going through the caregiving motions with the feeling switched off; and a collapse of pleasure and confidence in the role, the sense that you've lost the parent you meant to be. If parts of that list read like a description rather than a definition, keep reading — this card is for you, and you have company. Studies across many countries find meaningful numbers of parents in this state, most of them silent about it.\n\nStart with the reframe the research insists on: burnout is not evidence of bad parenting. It concentrates among invested parents — the ones carrying high standards, high vigilance and high care. Detachment isn't absence of love; it's what an overdrawn nervous system does to keep functioning. It takes real devotion to burn.\n\nThe mechanics are almost banal: burnout grows in a sustained gap between demands and resources. Banal is good news, because gaps have two sides. On the demand side, the most editable items are invisible standards — the everything-home-cooked, always-patient, enriched-every-afternoon bar that nobody actually set and nobody is auditing. Lowering an invisible standard costs no one anything and refunds hours. Name yours out loud; pick one to retire this month. On the resource side, load-sharing only works when it includes the mental load — not just who does bath time, but who tracks the shoe sizes, the appointments, the permission slips. Handing over a whole domain, tracking included, beats 'helping.' And micro-recovery genuinely counts: research on recovery finds small, protected, daily pockets — a walk alone, coffee before wake-ups, twenty guarded minutes — outperform the rare grand break that's always about to be scheduled.\n\nIf weeks pass and nothing refills — the rage stays close to the surface, the detachment you hate persists, or thoughts of escape start visiting — that is the pattern where a conversation with a professional stops being optional-nice and becomes the strong move. Parental burnout responds well to support. Getting help with it isn't stepping away from your children; it's maintenance on the person they regulate against — the least selfish thing on your list.",
      "יש מצב מסוים מעבר לעייפות הורית רגילה, וחוקרים בילו את העשור האחרון במיפויו. שחיקה הורית, בספרות המדעית, היא שלישייה: תשישות עמוקה כל כך שסוף השבוע הרגיל לא עושה בה שקע; ריחוק רגשי מתגנב מהילדים — ביצוע תנועות הטיפול כשהרגש כבוי; וקריסה של הנאה וביטחון בתפקיד, התחושה שאיבדתם את ההורה שהתכוונתם להיות. אם חלקים מהרשימה הזאת נקראים כתיאור ולא כהגדרה, המשיכו לקרוא — הכרטיס הזה בשבילכם, ויש לכם חברה. מחקרים במדינות רבות מוצאים מספרים משמעותיים של הורים במצב הזה, רובם שותקים לגביו.\n\nהתחילו במסגור שהמחקר מתעקש עליו: שחיקה אינה ראיה להורות גרועה. היא מתרכזת אצל הורים משקיעים — אלה שנושאים סטנדרטים גבוהים, דריכות גבוהה ואכפתיות גבוהה. הריחוק אינו היעדר אהבה; זה מה שמערכת עצבים במשיכת יתר עושה כדי להמשיך לתפקד. צריך מסירות אמיתית כדי להישרף.\n\nהמכניקה כמעט בנאלית: שחיקה גדלה בפער מתמשך בין דרישות למשאבים. בנאלי זה חדשות טובות, כי לפער יש שני צדדים. בצד הדרישות, הפריטים הניתנים ביותר לעריכה הם סטנדרטים סמויים — רף הכל־מבושל־בבית, תמיד־סבלנית, העשרה־כל־אחר־צהריים שאף אחד לא באמת הציב ואף אחד לא מבקר. הורדת סטנדרט סמוי לא עולה לאיש דבר ומחזירה שעות. תנו לשלכם שם בקול; בחרו אחד לפרוש ממנו החודש. בצד המשאבים, חלוקת עומס עובדת רק כשהיא כוללת את העומס המנטלי — לא רק מי עושה אמבטיה, אלא מי עוקב אחרי מידות הנעליים, התורים, האישורים לטיול. מסירת תחום שלם, כולל המעקב, מנצחת \"עזרה\". ומיקרו־התאוששות באמת נספרת: מחקרי התאוששות מוצאים שכיסים קטנים, מוגנים ויומיים — הליכה לבד, קפה לפני ההשכמות, עשרים דקות שמורות — עולים על החופשה הגדולה והנדירה שתמיד עומדת להיקבע.\n\nאם עוברים שבועות ושום דבר לא מתמלא — הזעם נשאר קרוב לפני השטח, הריחוק שאתם שונאים נמשך, או שמחשבות בריחה מתחילות לבקר — זה הדפוס שבו שיחה עם איש מקצוע מפסיקה להיות נחמד־אם־יש והופכת למהלך החזק. שחיקה הורית מגיבה היטב לתמיכה. לקבל עזרה איתה אינו להתרחק מהילדים; זו תחזוקה של האדם שהם מווסתים מולו — הדבר הכי פחות אנוכי ברשימה שלכם."
    ),
    tryToday: L(
      "Write down three invisible standards you're currently meeting. Cross out one, tonight, out loud to your partner or to yourself. Then guard one fifteen-minute pocket tomorrow that is only yours.",
      "כתבו שלושה סטנדרטים סמויים שאתם עומדים בהם כרגע. מחקו אחד, הערב, בקול — מול בן או בת הזוג או מול עצמכם. ואז שריינו מחר כיס אחד של רבע שעה שהוא רק שלכם."
    ),
    ask: L("Help me map my demands and resources and find the two easiest levers.", "עזור לי למפות את הדרישות והמשאבים שלי ולמצוא את שני המנופים הקלים ביותר."),
    concerns: ["regulation"],
  },
  {
    id: "sibling-arrival",
    category: "parent",
    domains: ["attachment_regulation", "social_development"],
    ageMin: 0,
    ageMax: 8,
    minutes: 4,
    title: L("Welcoming a sibling: preparing the older child", "מקבלים אח או אחות: להכין את הילד הגדול"),
    hook: L("For the older child, a new baby is real loss arriving with real gain — and a few deliberate moves make the difference between rivalry and room.", "עבור הילד הגדול, תינוק חדש הוא אובדן אמיתי שמגיע עם רווח אמיתי — וכמה מהלכים מכוונים עושים את ההבדל בין יריבות למרחב."),
    keyPoints: [
      L("Regression after a sibling arrives — potty steps backward, night waking, baby talk — is common, normal and usually temporary; it's a bid for care, not lost ground.", "נסיגה אחרי הגעת אח — צעדים אחורה בגמילה, יקיצות לילה, דיבור תינוקי — היא שכיחה, תקינה ולרוב זמנית; זו קריאה לטיפול, לא קרקע שאבדה."),
      L("The older child's experience holds loss and gain at once; naming both — 'you love the baby and you miss how it was' — is honest and steadying.", "החוויה של הילד הגדול מחזיקה אובדן ורווח בבת אחת; לתת שם לשניהם — \"אתה אוהב את התינוקת וגם מתגעגע לאיך שהיה\" — זה כן ומייצב."),
      L("Protected one-on-one time is the most reliable steadier: short, predictable, named — ten minutes that are visibly and only theirs.", "זמן אחד־על־אחד מוגן הוא המייצב האמין ביותר: קצר, צפוי, עם שם — עשר דקות שהן בגלוי ורק שלהם."),
      L("Let the older child hear the baby wait sometimes: 'The baby can wait — I'm finishing this puzzle with you' rebalances the ledger out loud.", "תנו לילד הגדול לשמוע את התינוק מחכה לפעמים: \"התינוקת יכולה לחכות — אני מסיימת איתך את הפאזל\" מאזן את הספרים בקול."),
      L("Small tactics earn their keep: a gift 'from the baby', real helper jobs freely chosen, and honest prep — newborns mostly sleep, cry and feed; the playmate comes later.", "טקטיקות קטנות מצדיקות את עצמן: מתנה \"מהתינוק\", תפקידי עוזר אמיתיים שנבחרים חופשי, והכנה כנה — יילודים בעיקר ישנים, בוכים ואוכלים; השותף למשחק יגיע אחר כך."),
    ],
    body: L(
      "The classic analogy is worth hearing once, because it recalibrates expectations instantly. Imagine your partner announcing, radiant: wonderful news — a second spouse is moving in. You'll love them! You'll share your things! From the older child's seat, a new sibling is something like that: a permanent, adorable rival for the two people who used to be entirely theirs. Which is why ambivalence is the honest baseline. Most older siblings feel love and grief and fascination and fury, sometimes within one afternoon — and a parent who expects the mix weathers it far better than one holding out for pure delight.\n\nThe most common storm is regression. The proudly potty-trained three-year-old has accidents; the solid sleeper wakes; a fluent talker rediscovers baby babble. It looks like lost ground and it isn't — skills wobble under stress at every age, and the older child has also just watched baby-behavior visibly summon around-the-clock care. Reading regression as a bid rather than a defeat changes your response: warmth, zero shame, a quiet offer of babying on demand — 'want me to carry you like a baby? You're always my baby too' — and the phase mostly passes on its own. Punishing it reliably lengthens it.\n\nThe steadying levers are concrete. First, protected one-on-one time: short, predictable, and named — ten or fifteen minutes that are visibly theirs, ideally daily, defended like an appointment. Its power isn't the minutes; it's the proof that they still have you on purpose, not just in the gaps. Second, say 'the baby can wait' out loud sometimes, and let the older child hear it: babies genuinely can wait thirty seconds, and the sentence rebalances a ledger the older child is definitely keeping. Third, real jobs freely offered — fetching, singing, choosing the outfit — make the baby partly theirs; keep the role voluntary, because a drafted assistant becomes a resentful one.\n\nBefore the birth, prepare with concrete truth rather than marketing: newborns mostly sleep, cry and feed, and the playmate arrives much later. A small gift 'from the baby' on day one is transparent theater that works anyway. Then hold the long view: the early jealousy season is not the relationship — that gets built over years of shared jokes and alliances. If aggression toward the baby stays intense and frequent for months past the adjustment window, that pattern is worth a good conversation with a professional. For most families, the wobble settles — and something new grows in its place.",
      "האנלוגיה הקלאסית שווה שמיעה פעם אחת, כי היא מכיילת ציפיות באחת. דמיינו את בן או בת הזוג מכריזים, קורנים: חדשות נהדרות — בת זוג שנייה עוברת לגור איתנו. אתם תאהבו אותה! תחלקו איתה את הדברים שלכם! מהכיסא של הילד הגדול, אח חדש הוא משהו כזה: יריב קבוע ומקסים על שני האנשים שהיו כולם שלו. ולכן דו־ערכיות היא נקודת הבסיס הכנה. רוב האחים הגדולים מרגישים אהבה ואבל וקסם וזעם, לפעמים באותו אחר צהריים — והורה שמצפה לתערובת צולח אותה הרבה יותר טוב מהורה שמחכה לאושר טהור.\n\nהסערה השכיחה ביותר היא נסיגה. בן השלוש שנגמל בגאווה עושה פיפי במכנסיים; הישן־היטב מתעורר; דובר שוטף מגלה מחדש מלמול תינוקי. זה נראה כמו קרקע שאבדה וזה לא — מיומנויות מתנדנדות תחת לחץ בכל גיל, והילד הגדול גם בדיוק צפה איך התנהגות־תינוק מזמנת בגלוי טיפול מסביב לשעון. לקרוא נסיגה כקריאה ולא כתבוסה משנה את התגובה שלכם: חום, אפס בושה, הצעה שקטה של פינוק תינוקי לפי דרישה — \"רוצה שאסחוב אותך כמו תינוק? אתה תמיד גם התינוק שלי\" — והשלב לרוב חולף מעצמו. להעניש אותו מאריך אותו באמינות.\n\nהמנופים המייצבים מוחשיים. ראשון, זמן אחד־על־אחד מוגן: קצר, צפוי, ועם שם — עשר או חמש־עשרה דקות שהן בגלוי שלו, רצוי יומיות, מוגנות כמו פגישה. הכוח אינו בדקות; הוא בהוכחה שהוא עדיין מקבל אתכם בכוונה, לא רק ברווחים. שני, אמרו \"התינוקת יכולה לחכות\" בקול לפעמים, ותנו לילד הגדול לשמוע: תינוקות באמת יכולים לחכות שלושים שניות, והמשפט מאזן ספרים שהילד הגדול בהחלט מנהל. שלישי, תפקידים אמיתיים שמוצעים חופשי — להביא, לשיר, לבחור את הבגד — הופכים את התינוק קצת לשלו; שמרו על התפקיד וולונטרי, כי עוזר מגויס הופך לעוזר ממורמר.\n\nלפני הלידה, הכינו באמת מוחשית ולא בפרסומת: יילודים בעיקר ישנים, בוכים ואוכלים, והשותף למשחק מגיע הרבה אחר כך. מתנה קטנה \"מהתינוק\" ביום הראשון היא תיאטרון שקוף שעובד בכל זאת. ואז החזיקו את המבט הארוך: עונת הקנאה המוקדמת אינה מערכת היחסים — זו נבנית לאורך שנים של בדיחות משותפות ובריתות. אם תוקפנות כלפי התינוק נשארת עזה ותכופה חודשים מעבר לחלון ההסתגלות, הדפוס הזה שווה שיחה טובה עם איש מקצוע. אצל רוב המשפחות, הטלטלה נרגעת — ומשהו חדש צומח במקומה."
    ),
    tryToday: L(
      "If the baby is already here, name and schedule the one-on-one slot today — \"our ten minutes\" — and say \"the baby can wait\" out loud once. If the baby is on the way, describe a newborn honestly at dinner: sleeps, cries, feeds, adores you eventually.",
      "אם התינוק כבר כאן, תנו היום שם וזמן לחלון האחד־על־אחד — \"עשר הדקות שלנו\" — ואמרו פעם אחת בקול \"התינוקת יכולה לחכות\". אם התינוק בדרך, תארו בארוחת הערב יילוד בכנות: ישן, בוכה, אוכל, ובסוף מעריץ אותך."
    ),
    ask: L("Help me plan the first month with the new baby from my older child's point of view.", "עזור לי לתכנן את החודש הראשון עם התינוק מנקודת המבט של הילד הגדול."),
    concerns: ["peer-conflict", "separation"],
  },
  {
    id: "parenting-styles",
    category: "parent",
    domains: ["attachment_regulation", "ecosystem_stressors"],
    ageMin: 0,
    ageMax: 12,
    minutes: 4,
    title: L("Warmth plus structure: what parenting-styles research actually says", "חום ועוד מבנה: מה מחקר סגנונות ההורות באמת אומר"),
    hook: L("Fifty years of research keeps landing on the same quadrant: high warmth and high expectations aren't opposites — they're the combination.", "חמישים שנות מחקר נוחתות שוב ושוב על אותו רביע: חום גבוה וציפיות גבוהות אינם הפכים — הם השילוב."),
    keyPoints: [
      L("The classic map (Baumrind, later refined) has two axes — warmth and expectations — giving four styles: authoritative, authoritarian, permissive, uninvolved.", "המפה הקלאסית (באומרינד, ששוכללה בהמשך) מציירת שני צירים — חום וציפיות — שנותנים ארבעה סגנונות: סמכותי־קשוב, סמכותני, מתירני ומנותק."),
      L("Authoritative — high warmth with high, explained expectations — shows the most consistent positive associations across decades of studies; associations, honestly, not guarantees.", "הסגנון הסמכותי־קשוב — חום גבוה עם ציפיות גבוהות ומוסברות — מציג את הקשרים החיוביים העקביים ביותר לאורך עשורי מחקר; קשרים סטטיסטיים, בכנות, לא הבטחות."),
      L("The axes don't trade off: adding structure doesn't cost warmth, and warmth doesn't dissolve limits — each makes the other work better.", "הצירים אינם באים זה על חשבון זה: הוספת מבנה לא עולה בחום, וחום לא ממוסס גבולות — כל אחד גורם לשני לעבוד טוב יותר."),
      L("Two parents don't need identical rules: what research suggests matters more is each being warm and firm — and not undermining each other, which is a different thing than differing.", "שני הורים לא צריכים חוקים זהים: מה שהמחקר מרמז שחשוב יותר הוא שכל אחד יהיה חם ויציב — ושלא יחתרו זה תחת זה, וזה דבר שונה מלהיות שונים."),
      L("Cultural humility: how warmth and firmness look varies across cultures and families; the deep pattern — children who feel loved and know what's expected — travels well.", "ענווה תרבותית: איך חום ויציבות נראים משתנה בין תרבויות ומשפחות; הדפוס העמוק — ילדים שמרגישים אהובים ויודעים מה מצופה — נודד היטב."),
    ],
    body: L(
      "In the 1960s, psychologist Diana Baumrind watched parents and children closely and proposed a map that research has been refining ever since. It has two axes. One is warmth: how much affection, responsiveness and acceptance flows toward the child. The other is expectations — sometimes called demandingness: how much structure, limit-setting and asked-of-them there is. Cross them and you get four styles. High warmth, high expectations: authoritative. Low warmth, high expectations: authoritarian — rules without relationship. High warmth, low expectations: permissive — relationship without rules. Low on both: uninvolved.\n\nThe headline finding has held up unusually well across decades, countries and study designs: the authoritative quadrant — warm and firm at once — shows the most consistent positive associations with how children fare, from emotional wellbeing to behavior to school life. Stated honestly, these are associations, not guarantees; children and contexts vary, and no style is a machine that outputs outcomes. But the pattern's persistence makes sense mechanically. Warmth keeps the connection open, so the child actually wants to cooperate and can hear you. Structure makes the world predictable and teaches that limits survive feelings. Explanation — the authoritative signature — turns rules from arbitrary weather into things with reasons, which is how children eventually internalize rather than merely obey them. Each axis makes the other work: a limit set inside a warm relationship reads as care; the same limit from a cold one reads as force.\n\nA practical liberation hides in the second finding: the 'united front' matters less than advertised. Two parents rarely run identical settings — one is bedtime-strict, one negotiates — and children handle different rules with different people remarkably well, the way they handle different rules at grandma's. What research suggests corrodes things isn't difference but undermining: contradicting, mocking or overruling each other in front of the child. Each parent warm and firm in their own register beats two parents enforcing a treaty neither believes in.\n\nHold the map with cultural humility, too. What warmth looks like — effusive praise or quiet acts of devotion — and what firmness looks like vary across cultures, and some of the classic research reads differently outside the contexts it was built in. The deep pattern is what travels: children do well when they feel unmistakably loved and know what's expected of them. And style is not a personality diagnosis — it's a bundle of practices, movable in small pieces: keep the limit, add the explanation, stay warm while enforcing. Any of those, started this week, moves you on the map.",
      "בשנות השישים, הפסיכולוגית דיאנה באומרינד צפתה מקרוב בהורים וילדים והציעה מפה שהמחקר משכלל מאז. יש לה שני צירים. אחד הוא חום: כמה חיבה, היענות וקבלה זורמות אל הילד. השני הוא ציפיות — לפעמים קוראים לזה דרישתיות: כמה מבנה, הצבת גבולות ומה־שמבקשים־מהם יש. הצליבו אותם ותקבלו ארבעה סגנונות. חום גבוה, ציפיות גבוהות: סמכותי־קשוב. חום נמוך, ציפיות גבוהות: סמכותני — חוקים בלי קשר. חום גבוה, ציפיות נמוכות: מתירני — קשר בלי חוקים. נמוך בשניהם: מנותק.\n\nממצא הכותרת החזיק מעמד יוצא דופן לאורך עשורים, מדינות ועיצובי מחקר: הרביע הסמכותי־קשוב — חם ויציב בבת אחת — מציג את הקשרים החיוביים העקביים ביותר עם איך שילדים מסתדרים, מרווחה רגשית דרך התנהגות ועד חיי בית הספר. בניסוח כן, אלה קשרים סטטיסטיים, לא הבטחות; ילדים והקשרים משתנים, ואף סגנון אינו מכונה שמייצרת תוצאות. אבל עקביות הדפוס הגיונית מכנית. חום משאיר את החיבור פתוח, כך שהילד באמת רוצה לשתף פעולה ומסוגל לשמוע אתכם. מבנה הופך את העולם לצפוי ומלמד שגבולות שורדים רגשות. הסבר — החתימה של הסגנון הסמכותי־קשוב — הופך חוקים ממזג אוויר שרירותי לדברים עם סיבות, וכך ילדים בסוף מפנימים במקום רק לציית. כל ציר גורם לשני לעבוד: גבול שמוצב בתוך קשר חם נקרא כאכפתיות; אותו גבול מקשר קר נקרא ככוח.\n\nשחרור מעשי מתחבא בממצא השני: 'החזית האחידה' חשובה פחות ממה שפרסמו לה. שני הורים כמעט אף פעם לא מריצים הגדרות זהות — אחת קפדנית בהשכבה, אחד מנהל משא ומתן — וילדים מתמודדים עם חוקים שונים אצל אנשים שונים טוב להפליא, כמו שהם מתמודדים עם חוקים אחרים אצל סבתא. מה שהמחקר מרמז שמשחית אינו השוני אלא החתירה: לסתור, ללגלג או לבטל זה את זה מול הילד. כל הורה חם ויציב במשלב שלו מנצח שני הורים שאוכפים אמנה שאף אחד מהם לא מאמין בה.\n\nהחזיקו את המפה גם בענווה תרבותית. איך חום נראה — שבחים שופעים או מעשי מסירות שקטים — ואיך יציבות נראית משתנים בין תרבויות, וחלק מהמחקר הקלאסי נקרא אחרת מחוץ להקשרים שבהם נבנה. הדפוס העמוק הוא שנודד: ילדים משגשגים כשהם מרגישים אהובים באופן שאינו משתמע לשתי פנים ויודעים מה מצופה מהם. וסגנון אינו אבחנת אישיות — הוא חבילת פרקטיקות, שזזה בחלקים קטנים: החזיקו את הגבול, הוסיפו את ההסבר, הישארו חמים בזמן האכיפה. כל אחד מאלה, שמתחיל השבוע, מזיז אתכם על המפה."
    ),
    tryToday: L(
      "Pick one rule you'll enforce today and run the authoritative triple: state it warmly, give the one-sentence reason, hold it kindly when it's tested. Notice how different holding feels with the reason said out loud.",
      "בחרו חוק אחד שתאכפו היום והריצו את השלשה הסמכותית־קשובה: אמרו אותו בחום, תנו את הסיבה במשפט אחד, החזיקו אותו בנעימות כשהוא נבחן. שימו לב כמה אחרת ההחזקה מרגישה כשהסיבה נאמרה בקול."
    ),
    ask: L("Where do I land on the warmth-and-structure map, and what's one small move toward warm-and-firm?", "איפה אני נוחת על מפת החום־והמבנה, ומהו צעד קטן אחד לעבר חם־ויציב?"),
  },
];
