/**
 * Learn Library seed catalogue — batch 3c (eating · motion · parent).
 * Same editorial stance as batch A (see learnCardsCore.ts).
 */
import type { LocalizedText } from "../content/governance";
import type { LearnCard } from "./learnLibrary";

const L = (en: string, he: string): LocalizedText => ({ en, he });

export const LEARN_CARDS_BATCH3C: LearnCard[] = [
  // ── Eating & Growing ─────────────────────────────────────────────────────
  {
    id: "baby-led-weaning",
    category: "eating",
    domains: ["independence_adaptive_skills", "sensory_motor_patterns"],
    ageMin: 0,
    ageMax: 1,
    minutes: 4,
    title: L("Baby-led weaning vs. purées: evidence, not camps", "אכילה בהובלת התינוק מול מחית: ראיות, לא מחנות"),
    hook: L("The internet splits first foods into rival ideologies. The research is calmer: both roads lead to eating.", "האינטרנט מפצל מזון ראשון לאידיאולוגיות יריבות. המחקר רגוע יותר: שתי הדרכים מובילות לאכילה."),
    keyPoints: [
      L("Readiness beats the calendar: sitting steadily, reaching and grabbing, real interest in your plate, and the fading tongue-thrust reflex — usually converging around six months.", "מוכנות מנצחת לוח שנה: ישיבה יציבה, הושטה ותפיסה, עניין אמיתי בצלחת שלכם, ורפלקס דחיפת הלשון שדועך — בדרך כלל מתכנסים סביב חצי שנה."),
      L("Studies comparing spoon-fed purées with baby-led weaning find both routes can support healthy growth; neither has proven superiority worth a family feud.", "מחקרים שמשווים האכלת מחית בכפית לאכילה בהובלת התינוק מוצאים ששני המסלולים יכולים לתמוך בגדילה בריאה; לאף אחד אין עליונות מוכחת ששווה ריב משפחתי."),
      L("Choking research is reassuring with conditions: self-feeding hasn't been linked to more choking when safety rules hold — seated upright, adult present, no hard round foods.", "מחקר החנק מרגיע — בתנאים: אכילה עצמית לא נקשרה ליותר חנק כשכללי הבטיחות מתקיימים — ישיבה זקופה, מבוגר נוכח, בלי מאכלים קשים ועגולים."),
      L("Gagging is not choking: gagging is loud, common and protective — the system learning textures. Choking is silent. Learn the difference once and fear less at every meal.", "רפלקס הקאה אינו חנק: הוא רועש, שכיח ומגונן — המערכת לומדת מרקמים. חנק הוא שקט. למדו את ההבדל פעם אחת ופחדו פחות בכל ארוחה."),
      L("Whichever route, two anchors matter at this age: iron-rich foods on the menu, and responsive feeding — the baby's hunger and fullness cues stay in charge.", "בכל מסלול, שני עוגנים חשובים בגיל הזה: מאכלים עשירים בברזל בתפריט, והאכלה קשובה — אותות הרעב והשובע של התינוק נשארים המפקדים."),
    ],
    body: L(
      "Somewhere around the six-month mark, feeding a baby becomes a debate club. One camp swears by purées, graduating texture by texture; the other — baby-led weaning — hands the baby soft, graspable pieces from day one and lets them steer. Online, the camps barely speak. In feeding research, the temperature is far lower: what matters most is that solids start when the baby shows readiness — sitting steadily, grabbing at food, the tongue-thrust reflex fading — and that the feeding relationship stays responsive from there.\n\nOn outcomes, comparative studies keep returning modest news. Both routes can support healthy growth. Claims that baby-led weaning produces less picky, better-regulated eaters are, so far, associations from observational work rather than proven causation. The most-studied fear — choking — has the most useful finding: trials of baby-led approaches with safety guidance built in found no increase in choking compared with spoon feeding. The guidance is the point: baby seated upright, an adult present and attentive, and no hard round foods — whole grapes, nuts, raw carrot coins, cherry tomatoes uncut. Along the way you will see gagging, and it helps to know it for what it is: a loud, dramatic, protective reflex that moves food forward while the baby maps new textures. Choking, the actual emergency, is silent.\n\nTwo anchors hold whichever style you choose. First, iron: a baby's stores from pregnancy run down around this age, so iron-rich foods — meat, legumes, fortified cereals — deserve an early seat at the table. Second, responsiveness: the well-supported core of infant feeding is following the baby's cues of hunger and fullness rather than a target amount, which both purée spoons and self-fed strips can honor or violate.\n\nAnd in practice? Most families mix. A preloaded spoon the baby steers, purées some meals, a strip of soft omelet at others. Texture variety in the first year, a shared table, and a relaxed adult matter more than brand loyalty to a method. If meals consistently involve struggle, persistent coughing with feeds, or refusal of whole texture groups over time, those are observations worth describing to your doctor. Otherwise: spread something washable on the floor, and let the experiments begin.",
      "אי שם סביב גיל חצי שנה, האכלת תינוק הופכת למועדון דיונים. מחנה אחד נשבע במחיות, מרקם אחרי מרקם; המחנה השני — אכילה בהובלת התינוק — מגיש לתינוק חתיכות רכות שאפשר לתפוס כבר מהיום הראשון ונותן לו לנווט. ברשת, המחנות בקושי מדברים. במחקר ההאכלה, הטמפרטורה נמוכה בהרבה: מה שהכי חשוב הוא שהמוצקים מתחילים כשהתינוק מראה מוכנות — ישיבה יציבה, הושטת יד לאוכל, רפלקס דחיפת הלשון שדועך — ושיחסי ההאכלה נשארים קשובים משם והלאה.\n\nבתוצאות, מחקרים השוואתיים חוזרים עם בשורות צנועות. שני המסלולים יכולים לתמוך בגדילה בריאה. טענות שאכילה בהובלת התינוק מייצרת אוכלים פחות בררנים ומווסתים יותר הן, בינתיים, מִתאמים ממחקר תצפיתי ולא סיבתיות מוכחת. לפחד הנחקר ביותר — חנק — יש הממצא השימושי ביותר: ניסויים בגישות בהובלת התינוק עם הדרכת בטיחות מובנית לא מצאו יותר חנק בהשוואה להאכלה בכפית. ההדרכה היא הנקודה: תינוק יושב זקוף, מבוגר נוכח וקשוב, ובלי מאכלים קשים ועגולים — ענבים שלמים, אגוזים, מטבעות גזר חי, עגבניות שרי לא חתוכות. בדרך תראו רפלקס הקאה, ועוזר לדעת מה הוא: רפלקס רועש, דרמטי ומגונן שמקדם אוכל קדימה בזמן שהתינוק ממפה מרקמים חדשים. חנק, מקרה החירום האמיתי, הוא שקט.\n\nשני עוגנים מחזיקים בכל סגנון שתבחרו. ראשית, ברזל: מאגרי ההיריון של תינוק מתרוקנים סביב הגיל הזה, ולכן מאכלים עשירים בברזל — בשר, קטניות, דגנים מועשרים — ראויים למקום מוקדם ליד השולחן. שנית, קשב: הליבה המבוססת של האכלת תינוקות היא מעקב אחרי אותות הרעב והשובע של התינוק במקום כמות יעד — עיקרון שגם כפית מחית וגם רצועת אוכל ביד יכולות לכבד או להפר.\n\nובפועל? רוב המשפחות מערבבות. כפית טעונה שהתינוק מנווט, מחית בחלק מהארוחות, רצועת חביתה רכה באחרות. מגוון מרקמים בשנה הראשונה, שולחן משותף ומבוגר רגוע חשובים יותר מנאמנות מותג לשיטה. אם ארוחות כרוכות בעקביות במאבק, בשיעול חוזר תוך כדי אכילה או בסירוב לקבוצות מרקם שלמות לאורך זמן — אלה תצפיות ששווה לתאר לרופא. אחרת: פרשו משהו רחיץ על הרצפה, ותנו לניסויים להתחיל."
    ),
    tryToday: L(
      "At one meal today, put a preloaded spoon or a soft graspable strip in front of your baby and let their hands run the show — your job is company, not delivery.",
      "בארוחה אחת היום, הניחו מול התינוק כפית טעונה או רצועה רכה שנוחה לתפיסה ותנו לידיים שלו לנהל את ההצגה — התפקיד שלכם הוא חברה, לא משלוחים."
    ),
    ask: L("Which iron-rich first foods fit the feeding style we've started?", "אילו מאכלים ראשונים עשירים בברזל מתאימים לסגנון ההאכלה שהתחלנו?"),
    concerns: ["food"],
  },
  {
    id: "appetite-swings",
    category: "eating",
    domains: ["independence_adaptive_skills"],
    ageMin: 1,
    ageMax: 6,
    minutes: 3,
    title: L("Why toddlers eat air some days", "למה פעוטות אוכלים אוויר בחלק מהימים"),
    hook: L("Three helpings Monday, three bites Tuesday. Toddler appetite is built to swing — and it balances on a scale you can't see at dinner.", "שלוש מנות ביום שני, שלושה ביסים ביום שלישי. תיאבון של פעוט בנוי להתנדנד — והוא מתאזן על מאזניים שלא רואים בארוחת ערב."),
    keyPoints: [
      L("Growth slows sharply after the first year — a toddler simply needs less per kilo than a baby did, and appetite drops to match.", "הגדילה מאטה בחדות אחרי השנה הראשונה — פעוט פשוט צריך פחות לקילו ממה שתינוק היה צריך, והתיאבון יורד בהתאם."),
      L("Intake self-balances across days, not meals: feeding studies find wildly uneven single meals adding up to surprisingly steady weekly totals.", "הצריכה מאזנת את עצמה על פני ימים, לא ארוחות: מחקרי האכלה מוצאים ארוחות בודדות לא אחידות בעליל שמסתכמות בסך שבועי יציב להפתיע."),
      L("Growth spurts, molars, colds, a huge snack at four o'clock — appetite has honest reasons that never announce themselves at dinner.", "פרצי גדילה, טוחנות, הצטננויות, חטיף ענק בארבע — לתיאבון יש סיבות כנות שאף פעם לא מכריזות על עצמן בארוחת הערב."),
      L("Chasing the low days with pressure or replacement meals teaches children to ignore fullness; trusting the swing keeps their internal signals intact.", "לרדוף אחרי הימים החלשים בלחץ או בארוחות חלופיות מלמד ילדים להתעלם משובע; אמון בתנודה שומר על האותות הפנימיים שלהם."),
      L("Judge the month, not the meal: energy, mood and growth over weeks are the real gauges. A consistently fading appetite alongside low energy is worth describing to your doctor.", "שפטו את החודש, לא את הארוחה: אנרגיה, מצב רוח וגדילה לאורך שבועות הם המדדים האמיתיים. תיאבון שדועך בעקביות לצד אנרגיה נמוכה שווה לתאר לרופא."),
    ],
    body: L(
      "Every parent of a toddler knows both children. There's the one who eats like a stevedore — seconds, thirds, eyeing your plate. And there's the one who arrives two days later in the same body and subsists, apparently, on air and two noodles. The whiplash convinces many families something is wrong. Feeding science mostly shrugs: this is what toddler appetite looks like from the inside of normal.\n\nThe first reason is arithmetic. A baby may triple their birth weight by the first birthday; no later year comes close. When growth decelerates, energy needs per kilo fall, and the appetite that fueled the baby year quietly steps down. Parents keep serving yesterday's portions and read the leftovers as a problem; the toddler is reading their own fuel gauge. The second reason is where the balancing happens. Classic studies that tracked young children's intake found single meals varying enormously while the running weekly total stayed remarkably steady — a child compensating for a barely-touched lunch with tomorrow's enthusiastic breakfast. The regulation is real; it just operates on a longer clock than one dinner.\n\nAdd the honest noise: a growth spurt raises appetite for a week, a molar or a cold lowers it, a big afternoon snack quietly spends the dinner appetite in advance. None of these announce themselves at the table, so the low days look mysterious — and mystery invites pressure. That's the move worth resisting. Coaxing, bribing, or producing a replacement meal for every refusal teaches a child that eating is negotiated rather than felt, and research on feeding pressure keeps associating it with poorer self-regulation and pickier eating, not fuller plates.\n\nThe steadier play: keep meals and sit-down snacks on a predictable rhythm, keep water (not milk or juice) between them, serve reasonable portions with seconds available, and let both the big days and the air days pass without commentary. Then judge the pattern where it actually lives — over weeks. An energetic, growing, generally cheerful child is eating enough, whatever Tuesday looked like. If appetite fades consistently for weeks alongside low energy or weight concerns, describe that pattern to your doctor: when it started, what changed. That's signal. Tuesday was just weather.",
      "כל הורה לפעוט מכיר את שני הילדים. יש זה שאוכל כמו סַוואר — תוספת, עוד תוספת, עין על הצלחת שלכם. ויש זה שמגיע יומיים אחר כך באותו גוף וניזון, ככל הנראה, מאוויר ושני אטריות. הטלטלה משכנעת משפחות רבות שמשהו לא תקין. מדע ההאכלה בעיקר מושך בכתפיים: כך נראה תיאבון של פעוט מבפנים של הנורמלי.\n\nהסיבה הראשונה היא חשבון. תינוק עשוי לשלש את משקל הלידה עד יום ההולדת הראשון; אף שנה מאוחרת לא מתקרבת לזה. כשהגדילה מאטה, צורכי האנרגיה לקילו יורדים, והתיאבון שתדלק את שנת התינוקות יורד מדרגה בשקט. הורים ממשיכים להגיש את המנות של אתמול וקוראים את השאריות כבעיה; הפעוט קורא את מד הדלק של עצמו. הסיבה השנייה היא איפה האיזון קורה. מחקרים קלאסיים שעקבו אחרי צריכת מזון של ילדים צעירים מצאו ארוחות בודדות משתנות בפראות בזמן שהסך השבועי המצטבר נשאר יציב להפליא — ילד שמפצה על צהריים שבקושי נגע בהם בארוחת בוקר נלהבת למחרת. הוויסות אמיתי; הוא פשוט פועל על שעון ארוך יותר מארוחת ערב אחת.\n\nהוסיפו את הרעש הכן: פרץ גדילה מעלה תיאבון לשבוע, טוחנת או הצטננות מורידות אותו, חטיף גדול אחר הצהריים מבזבז מראש ובשקט את תיאבון הערב. אף אחד מאלה לא מכריז על עצמו ליד השולחן, ולכן הימים החלשים נראים מסתוריים — ומסתורין מזמין לחץ. זה המהלך ששווה לעצור. שכנועים, שוחד או ייצור ארוחה חלופית לכל סירוב מלמדים ילד שאכילה היא משא ומתן ולא תחושה, ומחקר על לחץ בהאכלה קושר אותו שוב ושוב לוויסות חלש יותר ולאכילה בררנית יותר — לא לצלחות מלאות יותר.\n\nהמהלך היציב יותר: שמרו על ארוחות וחטיפים בישיבה בקצב צפוי, מים (לא חלב או מיץ) בין לבין, מנות סבירות עם תוספת זמינה, ותנו גם לימים הגדולים וגם לימי האוויר לעבור בלי פרשנות. ואז שפטו את הדפוס איפה שהוא באמת גר — על פני שבועות. ילד אנרגטי, גדל ובדרך כלל עליז אוכל מספיק, איך שיום שלישי לא נראה. אם התיאבון דועך בעקביות שבועות לצד אנרגיה נמוכה או דאגות משקל, תארו את הדפוס לרופא: מתי התחיל, מה השתנה. זה אות. יום שלישי היה סתם מזג אוויר."
    ),
    tryToday: L(
      "Tonight, serve the meal and say nothing about amounts — no bite counts, no 'you barely ate.' Write down what was actually eaten across the whole day instead, and do it for a week.",
      "הערב, הגישו את הארוחה ואל תגידו דבר על כמויות — בלי ספירת ביסים, בלי \"בקושי אכלת\". במקום זה רשמו מה באמת נאכל לאורך היום כולו, ועשו זאת שבוע."
    ),
    ask: L("Help me look at my child's eating across the last week instead of per meal — what does the pattern say?", "עזור לי להסתכל על האכילה של הילד לאורך השבוע האחרון במקום לפי ארוחה — מה הדפוס אומר?"),
    concerns: ["food"],
  },

  // ── Body & Motion ────────────────────────────────────────────────────────
  {
    id: "handedness",
    category: "motion",
    domains: ["sensory_motor_patterns"],
    ageMin: 1,
    ageMax: 6,
    minutes: 3,
    title: L("Handedness: when it settles, and why not to force it", "יד מובילה: מתי היא מתייצבת, ולמה לא לכפות אותה"),
    hook: L("The crayon changes hands mid-drawing and grandma has theories. Hand preference is a slow election — and the brain gets the only vote.", "העיפרון מחליף ידיים באמצע הציור ולסבתא יש תיאוריות. העדפת יד היא בחירות איטיות — ולמוח יש את הקול היחיד."),
    keyPoints: [
      L("Hand preference emerges gradually: a lean often shows by 18-24 months, but many children keep switching well into the preschool years, settling around ages 4-6.", "העדפת יד מתגבשת בהדרגה: נטייה נראית לרוב עד גיל שנה וחצי־שנתיים, אבל ילדים רבים ממשיכים להחליף עמוק אל תוך גיל הגן, ומתייצבים סביב גיל 4–6."),
      L("Switching hands during this window is exploration, not confusion — the brain is auditioning both candidates under real workloads.", "החלפת ידיים בחלון הזה היא חקירה, לא בלבול — המוח עורך אודישן לשני המועמדים תחת עומסי עבודה אמיתיים."),
      L("Handedness reflects brain organization, not habit; roughly one child in ten lands left-handed, and that is a variant, not a flaw.", "יד מובילה משקפת ארגון מוחי, לא הרגל; בערך ילד אחד מעשרה נוחת שמאלי — וזה וריאנט, לא פגם."),
      L("Retraining left-handers — a common practice historically — has been associated in research with frustration and slower writing fluency; the modern consensus is simply to follow the child's lead.", "אימון־מחדש של שמאליים — מנהג נפוץ בעבר — נקשר במחקר לתסכול ולשטף כתיבה איטי יותר; הקונצנזוס המודרני הוא פשוט ללכת אחרי הילד."),
      L("A strong, consistent one-hand preference before the first birthday is worth mentioning to your doctor — early fixedness, not early choice, is the observation.", "העדפה חזקה ועקבית ליד אחת לפני גיל שנה שווה אזכור לרופא — קיבעון מוקדם, לא בחירה מוקדמת, הוא התצפית."),
    ],
    body: L(
      "Watch a two-year-old at a drawing session and you may see a small mystery: the crayon starts in the right hand, migrates to the left, and returns — sometimes within a single scribble. Relatives read tea leaves in it. Is she left-handed? Should we correct him? Development research suggests a calmer frame: handedness is not a decision made at a moment but an election counted slowly, over years of ordinary use.\n\nThe timeline is wider than most expect. Babies show fleeting preferences that come and go through the first year. A more visible lean often appears between 18 and 24 months, and yet plenty of children keep swapping hands for tasks — spoon right, crayon left — through age three and four. Consolidation, where one hand reliably takes skilled work, commonly lands somewhere around four to six. All of that switching is not indecision to be fixed; it's the motor system testing both candidates under real conditions and gradually giving the finer contracts to the stronger bidder.\n\nWhat should a parent do about which hand wins? Essentially nothing — and the history here is instructive. For generations, left-handed children were routinely retrained to write with the right hand. Handedness, it turns out, reflects how a particular brain organizes skilled movement, not a habit that transfers cleanly; studies of forced switching have associated it with frustration and slower, more effortful writing. About one child in ten settles left-handed, and the modern consensus across pediatric and occupational-therapy guidance is simple: present objects at the middle of the body, let either hand take them, and equip whichever hand wins (left-handed scissors exist and matter).\n\nOne timing note runs the other way. If a baby shows a strong, consistent preference for one hand well before the first birthday — one arm doing all the reaching while the other stays quiet — that early fixedness is worth mentioning at a checkup, described plainly: which hand, since when, what the other one does. Past infancy, the watchword is patience. Set the spoon down in the middle. The election is running; the results arrive on their own schedule.",
      "צפו בבן שנתיים בפינת ציור ואולי תראו תעלומה קטנה: העיפרון מתחיל ביד ימין, נודד לשמאל, וחוזר — לפעמים בתוך שרבוט אחד. קרובי משפחה קוראים בזה בקפה. היא שמאלית? צריך לתקן אותו? מחקר ההתפתחות מציע מסגרת רגועה יותר: יד מובילה אינה החלטה שמתקבלת ברגע אלא בחירות שנספרות לאט, על פני שנים של שימוש יומיומי.\n\nציר הזמן רחב משרוב האנשים מצפים. תינוקות מראים העדפות חולפות שבאות והולכות לאורך השנה הראשונה. נטייה גלויה יותר מופיעה לרוב בין שנה וחצי לשנתיים, ובכל זאת ילדים רבים ממשיכים להחליף ידיים לפי משימה — כפית בימין, עיפרון בשמאל — לאורך גיל שלוש וארבע. ההתייצבות, שבה יד אחת לוקחת באמינות את העבודה העדינה, נוחתת בדרך כלל סביב ארבע עד שש. כל ההחלפות האלה אינן חוסר החלטיות שצריך לתקן; זו המערכת המוטורית שבוחנת את שני המועמדים בתנאי אמת ומעבירה בהדרגה את החוזים העדינים למציע החזק.\n\nמה הורה אמור לעשות בשאלה איזו יד תנצח? בעצם כלום — וההיסטוריה כאן מאלפת. במשך דורות, ילדים שמאליים אומנו־מחדש באופן שגרתי לכתוב ביד ימין. יד מובילה, מסתבר, משקפת איך מוח מסוים מארגן תנועה מיומנת, לא הרגל שעובר בנקיון; מחקרים על החלפה כפויה קשרו אותה לתסכול ולכתיבה איטית ומאומצת יותר. בערך ילד אחד מעשרה מתייצב שמאלי, והקונצנזוס המודרני בהנחיות רפואת ילדים וריפוי בעיסוק פשוט: הגישו חפצים באמצע הגוף, תנו לכל יד לקחת אותם, וציידו את היד שמנצחת (מספריים לשמאליים קיימים וחשובים).\n\nהערת תזמון אחת רצה בכיוון ההפוך. אם תינוק מראה העדפה חזקה ועקבית ליד אחת הרבה לפני גיל שנה — זרוע אחת עושה את כל ההושטות בזמן שהשנייה שקטה — הקיבעון המוקדם הזה שווה אזכור בביקורת, מתואר בפשטות: איזו יד, ממתי, מה השנייה עושה. אחרי גיל הינקות, מילת המפתח היא סבלנות. הניחו את הכפית באמצע. הבחירות רצות; התוצאות מגיעות בלוח הזמנים שלהן."
    ),
    tryToday: L(
      "For one day, place spoons, crayons and cups at your child's midline instead of into a hand — and just note, without comment, which hand keeps volunteering.",
      "ליום אחד, הניחו כפיות, עפרונות וכוסות מול אמצע הגוף של הילד במקום לתוך יד — ורק שימו לב, בלי הערות, איזו יד ממשיכה להתנדב."
    ),
    ask: L("My child still switches hands — what should I notice at this age, and what should I leave alone?", "הילד שלי עדיין מחליף ידיים — למה כדאי לשים לב בגיל הזה, ומה להשאיר במנוחה?"),
  },
  {
    id: "crossing-midline",
    category: "motion",
    domains: ["sensory_motor_patterns", "cognition_executive_function"],
    ageMin: 2,
    ageMax: 7,
    minutes: 3,
    title: L("Crossing the midline: the skill behind reading and writing", "חציית קו האמצע: המיומנות שמאחורי קריאה וכתיבה"),
    hook: L("There's an invisible line down your child's middle — and learning to reach across it quietly prepares the hand and eyes for the page.", "יש קו בלתי נראה במרכז הגוף של הילד — וללמוד להושיט יד מעברו מכין בשקט את היד והעיניים לדף."),
    keyPoints: [
      L("The midline is the invisible vertical line splitting the body in two; crossing it means one hand or eye working comfortably in the other side's territory.", "קו האמצע הוא הקו האנכי הבלתי נראה שמחלק את הגוף לשניים; לחצות אותו פירושו יד או עין שעובדות בנוחות בטריטוריה של הצד השני."),
      L("It's a coordination feat: the two body sides — and the two brain hemispheres directing them — learning to work as one team on one task.", "זהו הישג של תיאום: שני צדי הגוף — ושתי ההמיספרות שמנהלות אותם — לומדים לעבוד כצוות אחד על משימה אחת."),
      L("Comfortable crossing is associated with handedness settling and with desk skills: writing a line of text and tracking print both travel across the middle.", "חצייה נוחה נקשרת להתייצבות היד המובילה ולמיומנויות שולחן: כתיבת שורה ומעקב אחרי טקסט שניהם נוסעים לרוחב האמצע."),
      L("Young children naturally avoid it — turning the whole body or swapping hands at the line — and the skill consolidates gradually across the preschool years.", "ילדים צעירים נמנעים מזה באופן טבעי — מסובבים את כל הגוף או מחליפים יד על הקו — והמיומנות מתגבשת בהדרגה לאורך שנות הגן."),
      L("It grows through play, not drills: big figure-eights, window washing, drumming, threading, ball games across the body. No worksheets required.", "היא צומחת דרך משחק, לא תרגולים: שמיניות גדולות, ניקוי חלונות, תיפוף, השחלה, משחקי כדור לרוחב הגוף. לא נדרשים דפי עבודה."),
    ],
    body: L(
      "Ask a three-year-old to wipe a long table and you may watch a small revealing dance: the right hand wipes the right half, then the cloth changes hands at an invisible border, and the left hand finishes the job. Or the whole child pivots, feet and all, rather than reach across. That border is the midline — the imaginary line from nose to navel — and learning to send a hand smoothly across it is one of childhood's quietly important coordination projects.\n\nWhat makes it a project is teamwork. Each brain hemisphere primarily runs the opposite side of the body, so a reach across the middle asks both sides — and the connections between them — to coordinate on a single act: one hand working in foreign territory while the trunk rotates and the eyes lead. Occupational therapists watch midline crossing closely because of what it's associated with downstream. Comfortable crossing lets one hand log the practice hours that consolidate handedness, instead of splitting skilled work between two moderately-practiced hands. And the desk skills of early school quietly run on it: writing a line of text carries the hand across the body's middle; reading tracks print across the same territory; scissors, rulers and shoelaces all stage their own two-sided negotiations.\n\nThe reassuring part is the timeline. Reaching across begins in infancy, but easy, habitual crossing consolidates gradually through the preschool years, and the body-pivots and hand-swaps of a three-year-old are ordinary technique for the stage, not warning signs. The skill also doesn't need worksheets — it is built by exactly the kind of big, playful, two-sided movement children already chase: drawing giant figure-eights on paper taped to a wall, washing windows in sweeping arcs, drumming, threading beads, popping bubbles with one chosen hand, tossing balls to the side pockets of their reach.\n\nIf, well into the school years, a child still consistently avoids crossing — always turning the page instead of the arm, swapping hands mid-line of writing — and desk work brings outsized fatigue or frustration, those are concrete observations worth describing to a teacher, doctor or occupational therapist: what you see, in which tasks, since when. For everyone else, tape a big sheet of paper to the wall and hand over one marker. The eights do the rest.",
      "בקשו מילדת שלוש לנגב שולחן ארוך ואולי תראו ריקוד קטן ומגלה: יד ימין מנגבת את החצי הימני, ואז המטלית מחליפה ידיים על גבול בלתי נראה, ויד שמאל מסיימת את העבודה. או שכל הילדה מסתובבת, כולל רגליים, במקום להושיט יד מעבר. הגבול הזה הוא קו האמצע — הקו הדמיוני מהאף לטבור — וללמוד לשלוח יד בחלקות מעברו הוא אחד מפרויקטי התיאום החשובים־בשקט של הילדות.\n\nמה שהופך אותו לפרויקט הוא עבודת צוות. כל המיספרה מוחית מפעילה בעיקר את הצד הנגדי של הגוף, ולכן הושטה מעבר לאמצע מבקשת משני הצדדים — ומהחיבורים ביניהם — לתאם פעולה אחת: יד עובדת בטריטוריה זרה בזמן שהגו מסתובב והעיניים מובילות. מרפאים בעיסוק עוקבים מקרוב אחרי חציית קו האמצע בגלל מה שהיא נקשרת אליו בהמשך. חצייה נוחה מאפשרת ליד אחת לצבור את שעות התרגול שמייצבות יד מובילה, במקום לפצל עבודה עדינה בין שתי ידיים מאומנות־למחצה. ומיומנויות השולחן של תחילת בית הספר רצות עליה בשקט: כתיבת שורה נושאת את היד לרוחב אמצע הגוף; קריאה עוקבת אחרי טקסט על פני אותה טריטוריה; מספריים, סרגלים ושרוכים מנהלים כל אחד משא ומתן דו־צדדי משלו.\n\nהחלק המרגיע הוא ציר הזמן. הושטה מעבר לאמצע מתחילה בינקות, אבל חצייה קלה והרגלית מתגבשת בהדרגה לאורך שנות הגן, וסיבובי הגוף והחלפות הידיים של בני שלוש הם טכניקה רגילה לשלב, לא אותות אזהרה. המיומנות גם לא צריכה דפי עבודה — היא נבנית בדיוק מסוג התנועה הגדולה, המשחקית והדו־צדדית שילדים ממילא רודפים: ציור שמיניות ענקיות על נייר שמודבק לקיר, ניקוי חלונות בקשתות רחבות, תיפוף, השחלת חרוזים, פיצוץ בועות ביד נבחרת אחת, זריקת כדורים לצדי טווח ההושטה.\n\nאם, עמוק אל תוך שנות בית הספר, ילד עדיין נמנע בעקביות מחצייה — תמיד מסובב את הדף במקום את הזרוע, מחליף ידיים באמצע שורת כתיבה — ועבודת שולחן מביאה עייפות או תסכול חריגים, אלה תצפיות מוחשיות ששווה לתאר למורה, לרופא או למרפאה בעיסוק: מה אתם רואים, באילו משימות, ממתי. לכל השאר: הדביקו גיליון נייר גדול לקיר ומסרו טוש אחד. השמיניות יעשו את השאר."
    ),
    tryToday: L(
      "Tape a big sheet of paper to the wall and have your child draw giant sideways figure-eights with one hand — three lazy loops each way, feet planted, music on.",
      "הדביקו גיליון נייר גדול לקיר ותנו לילד לצייר שמיניות שוכבות ענקיות ביד אחת — שלוש לולאות עצלות לכל כיוון, רגליים נטועות, מוזיקה ברקע."
    ),
    ask: L("What midline-crossing games fit my child's age and favorite kinds of play?", "אילו משחקי חציית קו אמצע מתאימים לגיל של הילד ולסוגי המשחק שהוא אוהב?"),
  },
  {
    id: "sensory-movement",
    category: "motion",
    domains: ["sensory_motor_patterns"],
    ageMin: 1,
    ageMax: 8,
    minutes: 4,
    title: L("Spinning, crashing, squeezing: the sensory side of movement", "להסתובב, להתרסק, להתכווץ: הצד החושי של התנועה"),
    hook: L("The child spinning until they fall over isn't malfunctioning — they're feeding two hidden senses that never make the famous list of five.", "הילד שמסתובב עד שהוא נופל לא מקולקל — הוא מזין שני חושים נסתרים שאף פעם לא נכנסים לרשימת החמישה המפורסמת."),
    keyPoints: [
      L("Beyond the famous five, two body senses run movement: the vestibular sense (motion and balance, from the inner ear) and proprioception (body position, from muscles and joints).", "מעבר לחמישייה המפורסמת, שני חושי גוף מנהלים תנועה: החוש הווסטיבולרי (תנועה ושיווי משקל, מהאוזן הפנימית) ופרופריוצפציה (תחושת מנח הגוף, מהשרירים והמפרקים)."),
      L("Spinning, swinging, crashing into cushions and squeezing into tight spots are how children calibrate these systems — the seeking is purposeful, not random chaos.", "להסתובב, להתנדנד, להתרסק על כריות ולהידחס לפינות צרות — כך ילדים מכיילים את המערכות האלה; החיפוש תכליתי, לא כאוס אקראי."),
      L("Appetites vary widely and normally: some children need huge daily doses of movement input, others are cautious about swings and heights. Both live inside the wide normal.", "התיאבון משתנה מאוד ובאופן תקין: יש ילדים שצריכים מנות ענק של קלט תנועתי כל יום, ואחרים זהירים עם נדנדות וגבהים. שניהם גרים בתוך הנורמה הרחבה."),
      L("'Heavy work' — pushing, pulling, carrying, squeezing — tends to be organizing and calming; occupational therapists reach for it deliberately, and parents can too.", "\"עבודה כבדה\" — לדחוף, למשוך, לסחוב, ללחוץ — נוטה לארגן ולהרגיע; מרפאים בעיסוק פונים אליה במכוון, וגם הורים יכולים."),
      L("Schedule movement before stillness rather than fighting it during: a body that got its input sits, listens and settles more easily afterwards.", "תזמנו תנועה לפני דרישות שקט במקום להילחם בה תוך כדי: גוף שקיבל את הקלט שלו יושב, מקשיב ונרגע אחר כך בקלות רבה יותר."),
    ],
    body: L(
      "Some evenings the living room looks like a physics experiment: a child spinning in circles until the floor tilts, launching off the couch arm into a cushion pile, then wedging themselves behind it in the tightest possible gap. It's tempting to read this as energy to be burned or chaos to be stopped. There's a more useful frame: the child is feeding senses you can't see.\n\nBeyond sight, sound, smell, taste and touch, the body runs two quieter sensory systems. The vestibular sense, seated in the inner ear, reports motion, gravity and balance — it's what spinning, swinging, hanging upside down and rolling downhill stimulate. Proprioception, wired through muscles and joints, reports where the body is and how hard it's pushing — fed by jumping, crashing, climbing, carrying, and being squeezed. Children calibrate these systems by using them, and the seeking is strikingly purposeful: the spinner is dosing the inner ear; the crasher is asking joints and muscles for loud, clear position reports. Appetites differ enormously between children, and widely from day to day — a range that is, in itself, normal.\n\nThe most practical discovery from occupational therapy is which input calms. Vestibular input tends to be alerting — spinning revs many children up — while proprioceptive 'heavy work' tends to organize and settle: pushing a loaded laundry basket, carrying groceries, wall pushes, tug-of-war, dough kneading, a tight blanket burrito, a long hug with real squeeze. That asymmetry is a parenting tool. A child fresh from an hour of stillness who is asked for another hour rarely finds it; a child who first pushed, jumped, hung and hauled often can. Working with the appetite — big-movement time scheduled before sitting demands, a crash corner that is allowed, heavy jobs handed out as privileges — usually beats fighting it mid-wobble.\n\nAs always, the wide range has edges worth describing rather than diagnosing. If movement-seeking is so constant it overrides safety and play, if ordinary movement like swings reliably brings distress rather than caution, or if everyday textures and sounds regularly trigger outsized reactions that disrupt the day, note what happens, in which situations, how often — and bring those observations to your doctor or an occupational therapist. For most families, the takeaway is cheaper: the spinning is not the problem. It might be the maintenance schedule.",
      "יש ערבים שהסלון נראה כמו ניסוי בפיזיקה: ילדה מסתובבת במעגלים עד שהרצפה נוטה, מזנקת ממשענת הספה אל ערימת כריות, ואז דוחסת את עצמה מאחוריה לחריץ הצר ביותר האפשרי. מפתה לקרוא את זה כאנרגיה שצריך לשרוף או כאוס שצריך לעצור. יש מסגרת שימושית יותר: הילדה מזינה חושים שאתם לא רואים.\n\nמעבר לראייה, שמיעה, ריח, טעם ומגע, הגוף מפעיל שתי מערכות חישה שקטות יותר. החוש הווסטיבולרי, שיושב באוזן הפנימית, מדווח על תנועה, כבידה ושיווי משקל — אותו מגרים הסיבובים, הנדנדות, התלייה במהופך וההתגלגלות במדרון. הפרופריוצפציה, שמחווטת דרך שרירים ומפרקים, מדווחת איפה הגוף וכמה חזק הוא דוחף — אותה מזינים קפיצות, התרסקויות, טיפוס, סחיבה ולחיצה. ילדים מכיילים את המערכות האלה דרך שימוש, והחיפוש תכליתי להפליא: המסתובבת מחלקת מנות לאוזן הפנימית; המתרסק מבקש מהמפרקים והשרירים דוחות מיקום רמים וברורים. התיאבון שונה מאוד בין ילדים, ומשתנה מיום ליום — טווח שהוא, כשלעצמו, תקין.\n\nהתגלית המעשית ביותר מריפוי בעיסוק היא איזה קלט מרגיע. קלט וסטיבולרי נוטה לעורר — סיבובים מדליקים הרבה ילדים — בעוד \"עבודה כבדה\" פרופריוצפטיבית נוטה לארגן וליישב: לדחוף סל כביסה עמוס, לסחוב קניות, דחיפות קיר, משיכת חבל, לישת בצק, בוריטו שמיכה הדוק, חיבוק ארוך עם לחיצה אמיתית. האסימטריה הזאת היא כלי הורות. ילד שיוצא משעה של ישיבה ומתבקש לשעה נוספת ימצא אותה לעתים רחוקות; ילד שקודם דחף, קפץ, נתלה וסחב — לרוב כן. לעבוד עם התיאבון — זמן תנועה גדולה מתוזמן לפני דרישות ישיבה, פינת התרסקות שמותרת, עבודות כבדות שמחולקות כפריבילגיות — בדרך כלל מנצח את המלחמה בו באמצע הטלטלה.\n\nכתמיד, לטווח הרחב יש קצוות ששווה לתאר ולא לאבחן. אם חיפוש התנועה כה קבוע שהוא גובר על בטיחות ומשחק, אם תנועה רגילה כמו נדנדה מביאה באמינות מצוקה ולא זהירות, או אם מרקמים וצלילים יומיומיים מציתים דרך קבע תגובות חריגות שמשבשות את היום — רשמו מה קורה, באילו מצבים, באיזו תדירות, והביאו את התצפיות לרופא או למרפאה בעיסוק. לרוב המשפחות, המסקנה זולה יותר: הסיבובים אינם הבעיה. ייתכן שהם לוח התחזוקה."
    ),
    tryToday: L(
      "Before today's hardest sit-still stretch, run ten minutes of heavy work: push the laundry basket, carry the shopping, wheelbarrow-walk to the bath. Then watch what the stillness costs.",
      "לפני קטע הישיבה הקשה של היום, הריצו עשר דקות של עבודה כבדה: לדחוף את סל הכביסה, לסחוב את הקניות, הליכת מריצה עד האמבטיה. ואז ראו כמה השקט עולה."
    ),
    ask: L("Build me a daily movement menu that fits my child's sensory appetite.", "בנה לי תפריט תנועה יומי שמתאים לתיאבון החושי של הילד שלי."),
    concerns: ["regulation"],
  },

  // ── The Parent ───────────────────────────────────────────────────────────
  {
    id: "mental-load",
    category: "parent",
    domains: ["ecosystem_stressors"],
    ageMin: 0,
    ageMax: 12,
    minutes: 4,
    title: L("The mental load: naming the invisible job", "העומס המנטלי: לתת שם לעבודה הבלתי נראית"),
    hook: L("Someone in your house is tracking shoe sizes, vaccine dates and the dwindling snack supply — all at once, all the time. That's a job. It has a name.", "מישהו בבית שלכם עוקב אחרי מידות נעליים, תאריכי חיסונים ומלאי החטיפים המידלדל — הכול בבת אחת, כל הזמן. זו עבודה. יש לה שם."),
    keyPoints: [
      L("The mental load is the thinking layer of family life: noticing, anticipating, deciding, tracking — work that runs even when the hands are idle.", "העומס המנטלי הוא שכבת החשיבה של חיי המשפחה: להבחין, לצפות מראש, להחליט, לעקוב — עבודה שרצה גם כשהידיים נחות."),
      L("Because it's invisible, it can't be shared, scheduled or thanked until it's named; unnamed, it defaults quietly to one person.", "בגלל שהוא בלתי נראה, אי אפשר לחלוק אותו, לתזמן אותו או להודות עליו עד שנותנים לו שם; בלי שם, הוא נופל בשקט על אדם אחד."),
      L("Research on household labor associates a chronically unequal invisible load with parental exhaustion and relationship strain — the carrier can't truly go off duty.", "מחקר על עבודת הבית קושר עומס בלתי נראה שאינו שוויוני באופן כרוני לתשישות הורית ולשחיקה בזוגיות — מי שנושא אותו לא באמת יוצא ממשמרת."),
      L("Sharing means transferring ownership, not tasks: 'tell me what to buy' keeps the load; owning a whole domain — notice, decide, do — actually moves it.", "לחלוק פירושו להעביר בעלות, לא משימות: \"תגידי לי מה לקנות\" משאיר את העומס; בעלות על תחום שלם — להבחין, להחליט, לבצע — באמת מזיזה אותו."),
      L("Externalize the family's memory: shared calendars and lists mean the household's operating system stops living in one person's head.", "החצינו את זיכרון המשפחה: יומנים ורשימות משותפים גורמים למערכת ההפעלה של הבית להפסיק לגור בראש של אדם אחד."),
    ],
    body: L(
      "There's a category of family work that never appears on any chore chart. Knowing the winter boots are a size too small before winter. Registering that the birthday party is Saturday, a gift is needed, and the child's friend is allergic to nuts. Tracking the vaccine schedule, the sunscreen supply, the teacher's name, the phase the bedtime routine is in. Researchers who study household labor call this the mental load: the noticing, anticipating, deciding and monitoring layer of family life. It is genuinely work — cognitively expensive, always on — and it is invisible, because its product is things not going wrong.\n\nInvisibility is the trap. A task nobody can see cannot be shared, scheduled, or thanked; it simply defaults, and in many households it defaults heavily to one partner. Studies of family labor keep associating a chronically lopsided mental load with exhaustion and relationship strain, and the mechanism is easy to feel from inside: the partner carrying it can never fully clock out, because the monitoring runs during dinner, during rest, during the film. Meanwhile the other partner may be doing plenty of visible tasks — and be sincerely confused by the resentment, because the invisible layer never made it into view.\n\nThe fix that tends to hold is a transfer of ownership, not assistance. 'Tell me what to buy and I'll shop' is help that leaves the noticing, deciding and remembering exactly where it was. Owning a domain end to end — clothes and shoes, say: tracking sizes and seasons, deciding, buying, culling the outgrown — actually moves load. So the working move is to sit down together and make the invisible visible: list the domains (health appointments, school logistics, gifts and social calendar, food supply, clothing, childcare coverage), see honestly who carries what, and reassign whole domains, accepting that the new owner will do them differently.\n\nTwo maintenance notes. A short weekly logistics huddle — fifteen minutes, calendars open — catches the week's handoffs before they become 3 a.m. remembering. And wherever possible, move the family's memory out of anyone's head into shared systems: one calendar, standing lists, written routines. Solo parents can't split the load, but externalizing it and borrowing a village for pieces of it works on the same principle. The load is real. Named, it can finally be carried on purpose.",
      "יש קטגוריה של עבודת משפחה שאף פעם לא מופיעה בשום טבלת מטלות. לדעת שמגפי החורף קטנים במידה — לפני החורף. לקלוט שמסיבת יום ההולדת בשבת, שצריך מתנה, ושהחבר של הילד אלרגי לאגוזים. לעקוב אחרי לוח החיסונים, מלאי קרם ההגנה, שם הגננת, השלב שבו נמצא טקס השינה. חוקרי עבודת הבית קוראים לזה העומס המנטלי: שכבת ההבחנה, הציפייה מראש, ההחלטה והניטור של חיי המשפחה. זו עבודה אמיתית — יקרה קוגניטיבית, פועלת תמיד — והיא בלתי נראית, כי התוצר שלה הוא דברים שלא משתבשים.\n\nהאי־נראות היא המלכודת. משימה שאיש לא רואה אי אפשר לחלוק, לתזמן או להודות עליה; היא פשוט נופלת כברירת מחדל, ובבתים רבים היא נופלת בכבדות על בן זוג אחד. מחקרי עבודת משפחה קושרים שוב ושוב עומס מנטלי חד־צדדי כרוני לתשישות ולשחיקה זוגית, ואת המנגנון קל להרגיש מבפנים: מי שנושא אותו לא יכול באמת להחתים כרטיס יציאה, כי הניטור רץ בזמן ארוחת הערב, בזמן המנוחה, בזמן הסרט. בינתיים בן הזוג השני אולי מבצע שפע משימות גלויות — ומתבלבל בכנות מהטינה, כי השכבה הבלתי נראית מעולם לא נכנסה לשדה הראייה.\n\nהתיקון שנוטה להחזיק הוא העברת בעלות, לא עזרה. \"תגידי לי מה לקנות ואני אקנה\" היא עזרה שמשאירה את ההבחנה, ההחלטה והזיכרון בדיוק איפה שהיו. בעלות על תחום מקצה לקצה — בגדים ונעליים, למשל: מעקב מידות ועונות, החלטה, קנייה, פינוי מה שנהיה קטן — באמת מזיזה עומס. לכן המהלך העובד הוא לשבת יחד ולהפוך את הבלתי נראה לנראה: רשמו את התחומים (תורים רפואיים, לוגיסטיקת גן ובית ספר, מתנות ולוח חברתי, מלאי אוכל, ביגוד, כיסוי בייביסיטר), ראו בכנות מי נושא מה, והקצו מחדש תחומים שלמים — תוך קבלה שהבעלים החדשים יעשו אותם אחרת.\n\nשתי הערות תחזוקה. ישיבת לוגיסטיקה שבועית קצרה — רבע שעה, יומנים פתוחים — תופסת את מסירות השבוע לפני שהן הופכות להיזכרות בשלוש לפנות בוקר. ובכל מקום אפשרי, העבירו את זיכרון המשפחה מראש של מישהו למערכות משותפות: יומן אחד, רשימות קבועות, שגרות כתובות. הורים יחידניים לא יכולים לפצל את העומס, אבל החצנה שלו והשאלת כפר לחלקים ממנו עובדות על אותו עיקרון. העומס אמיתי. עם שם, אפשר סוף סוף לשאת אותו בכוונה."
    ),
    tryToday: L(
      "Tonight, each partner writes every invisible thing they're currently tracking — five minutes, no editing. Swap lists. The gap between the two pages is the conversation.",
      "הערב, כל אחד מבני הזוג כותב כל דבר בלתי נראה שהוא עוקב אחריו כרגע — חמש דקות, בלי עריכה. החליפו רשימות. הפער בין שני הדפים הוא השיחה."
    ),
    ask: L("Help me map our family's invisible-work domains and draft a fair split.", "עזור לי למפות את תחומי העבודה הבלתי נראית במשפחה שלנו ולנסח חלוקה הוגנת."),
  },
  {
    id: "parents-disagree",
    category: "parent",
    domains: ["ecosystem_stressors", "attachment_regulation"],
    ageMin: 0,
    ageMax: 12,
    minutes: 4,
    title: L("When parents disagree on parenting", "כשההורים לא מסכימים על הורות"),
    hook: L("Two people raised in two different families are now running one child's childhood together. Disagreement isn't the failure — it's the starting condition.", "שני אנשים שגדלו בשתי משפחות שונות מנהלים עכשיו יחד ילדות של ילד אחד. אי־הסכמה אינה הכישלון — היא תנאי הפתיחה."),
    keyPoints: [
      L("Every co-parenting pair merges two upbringings, two temperaments and two sets of defaults; some collisions are guaranteed and normal.", "כל צמד הורים ממזג שתי ילדויות, שני מזגים ושתי מערכות ברירות מחדל; חלק מההתנגשויות מובטחות ותקינות."),
      L("Research distinguishes the conflict styles: chronic, hostile, unresolved conflict in front of children is associated with strain — while respectful, resolved disagreement can model negotiation.", "המחקר מבחין בין סגנונות הקונפליקט: מריבה כרונית, עוינת ולא פתורה מול ילדים נקשרת למצוקה — בעוד אי־הסכמה מכבדת שנפתרת יכולה לדגמן משא ומתן."),
      L("Children handle 'daddy's rules vs. mommy's rules' better than adults expect; what unsettles them is watching their parents attack each other over it.", "ילדים מתמודדים עם \"החוקים של אבא מול החוקים של אמא\" טוב משמבוגרים מצפים; מה שמערער אותם הוא לראות את ההורים תוקפים זה את זה בגלל זה."),
      L("Don't undermine a call in the moment: back it or stay neutral, then renegotiate offline. Kids who find the crack learn to widen it.", "אל תחתרו תחת החלטה ברגע עצמו: גבו אותה או הישארו ניטרליים, ואז נהלו משא ומתן מחדש בצד. ילדים שמוצאים את הסדק לומדים להרחיב אותו."),
      L("Separate values from style: align on the few non-negotiables (safety, respect, screens-at-night); let style differences breathe. Recurring deadlocks on big ones are fair material for a session with a family professional.", "הפרידו ערכים מסגנון: התיישרו על הבל־יעבורים המעטים (בטיחות, כבוד, מסכים בלילה); תנו להבדלי סגנון לנשום. מבוי סתום חוזר בנושא גדול הוא חומר לגיטימי לפגישה עם איש מקצוע משפחתי."),
    ],
    body: L(
      "One of you was raised in a home where dessert followed dinner like a law of physics; the other grew up grazing freely. One had a 7:30 lights-out enforced to the minute; the other read under the covers till whenever. Now you share a child, and every one of those inherited settings is suddenly up for negotiation — usually discovered mid-collision, at bedtime, with an audience. It helps to start from the honest premise: two people from two families will disagree about parenting. The disagreement is not the malfunction. What you do with it is the variable.\n\nThe research on family conflict draws a line worth knowing. What studies consistently associate with strain in children is not the existence of parental disagreement but its climate: chronic, hostile, unresolved conflict — especially the kind children witness and the kind that runs through them, each parent recruiting the child or undercutting the other. By contrast, children who watch parents disagree respectfully and land somewhere — 'you're right, let's try your way this week' — are watching a live tutorial in how adults negotiate. And children turn out to be more flexible about inconsistency between homes and parents than adults assume: 'abba lets me, mama doesn't' is legible to a four-year-old. What's illegible is watching the two people they depend on treat each other as opponents.\n\nA few operating rules keep the machine stable. First, protect each other's calls in real time: if one parent has ruled, the other backs it or stays neutral, and the appeal happens later, out of earshot — because a child who discovers the crack between you will, quite rationally, widen it. Second, sort your disagreements into values and style. The values list should be short — safety, how people are spoken to, a handful of family lines — and genuinely aligned. Most of the rest is style, and style can differ without harm: one parent roughhouses, one reads; one runs a tight bath schedule, one improvises.\n\nFor the recurring deadlocks, schedule the negotiation instead of having it at the scene: a recurring twenty-minute parenting sync, no children present, one topic at a time, with real curiosity about where the other's setting came from — 'what did bedtime look like in your house?' unlocks more than any debate. And if the same big disagreement survives every round, bringing it to a family counselor is not a verdict on the marriage; it's hiring a translator for the two family languages you each arrived speaking.",
      "אחד מכם גדל בבית שבו קינוח בא אחרי ארוחת ערב כמו חוק פיזיקה; השנייה גדלה על נשנוש חופשי. לאחד היה כיבוי אורות ב־19:30 שנאכף לדקה; השנייה קראה מתחת לשמיכה עד מתי שבא. עכשיו יש לכם ילד משותף, וכל אחת מההגדרות שירשתם עומדת פתאום למשא ומתן — שמתגלה בדרך כלל באמצע התנגשות, בזמן השכבה, עם קהל. עוזר להתחיל מהנחת היסוד הכנה: שני אנשים משתי משפחות יחלקו על הורות. אי־ההסכמה אינה התקלה. מה שעושים איתה — זה המשתנה.\n\nמחקר הקונפליקט המשפחתי מותח קו ששווה להכיר. מה שמחקרים קושרים בעקביות למצוקה אצל ילדים אינו עצם קיומה של מחלוקת הורית אלא האקלים שלה: קונפליקט כרוני, עוין ולא פתור — במיוחד מהסוג שילדים עדים לו ומהסוג שעובר דרכם, כשכל הורה מגייס את הילד או חותר תחת השני. לעומת זאת, ילדים שרואים הורים חולקים בכבוד ונוחתים איפשהו — \"אתה צודק, ננסה השבוע בדרך שלך\" — צופים בשיעור חי באיך מבוגרים מנהלים משא ומתן. וילדים מתגלים כגמישים יותר לגבי חוסר עקביות בין בתים והורים משמבוגרים מניחים: \"אבא מרשה, אמא לא\" הוא קריא לילד בן ארבע. מה שלא קריא הוא לראות את שני האנשים שהוא תלוי בהם מתייחסים זה לזה כיריבים.\n\nכמה כללי הפעלה שומרים על יציבות המכונה. ראשית, הגנו על ההחלטות זה של זה בזמן אמת: אם הורה אחד פסק, השני מגבה או נשאר ניטרלי, והערעור קורה אחר כך, הרחק מאוזניים — כי ילד שמגלה את הסדק ביניכם ירחיב אותו, ובצדק מבחינתו. שנית, מיינו את המחלוקות לערכים וסגנון. רשימת הערכים צריכה להיות קצרה — בטיחות, איך מדברים אל אנשים, קומץ קווים משפחתיים — ומיושרת באמת. רוב השאר הוא סגנון, וסגנון יכול להיות שונה בלי נזק: הורה אחד משתולל, אחד מקריא; אחד מנהל לוח אמבטיה הדוק, אחד מאלתר.\n\nלמבואות הסתומים החוזרים, קבעו את המשא ומתן במקום לנהל אותו בזירה: סנכרון הורות קבוע של עשרים דקות, בלי ילדים, נושא אחד בכל פעם, עם סקרנות אמיתית לגבי מקור ההגדרה של הצד השני — \"איך נראתה השכבה בבית שלך?\" פותח יותר מכל ויכוח. ואם אותה מחלוקת גדולה שורדת כל סיבוב, להביא אותה ליועץ משפחתי אינו גזר דין על הזוגיות; זה שכירת מתרגם לשתי שפות המשפחה שכל אחד מכם הגיע דובר."
    ),
    tryToday: L(
      "Pick your most repeated clash and ask your partner one question tonight: \"What did this look like in your house growing up?\" Just listen — negotiation comes later.",
      "בחרו את ההתנגשות החוזרת ביותר שלכם ושאלו את בן או בת הזוג שאלה אחת הערב: \"איך זה נראה בבית שגדלת בו?\" רק הקשיבו — המשא ומתן יבוא אחר כך."
    ),
    ask: L("Help us split our parenting disagreements into real values and mere style.", "עזור לנו למיין את מחלוקות ההורות שלנו לערכים אמיתיים לעומת סגנון בלבד."),
  },
  {
    id: "asking-for-help",
    category: "parent",
    domains: ["ecosystem_stressors"],
    ageMin: 0,
    ageMax: 12,
    minutes: 3,
    title: L("Building the village on purpose: asking for help", "לבנות את הכפר בכוונה: לבקש עזרה"),
    hook: L("The village that once raised children by default now has to be recruited by hand. Asking is the skill — and it's more welcome than it feels.", "הכפר שפעם גידל ילדים כברירת מחדל צריך היום גיוס ידני. הבקשה היא המיומנות — והיא רצויה יותר משהיא מרגישה."),
    keyPoints: [
      L("For most of history, childcare was distributed across relatives and neighbors by default; two adults (or one) doing it alone is the historical anomaly, not the standard.", "לאורך רוב ההיסטוריה, הטיפול בילדים התחלק כברירת מחדל בין קרובים ושכנים; שני מבוגרים (או אחד) שעושים זאת לבד הם החריגה ההיסטורית, לא התקן."),
      L("The main barrier is internal: research on help-seeking finds people consistently underestimate how willing others are to help — and how good helping makes them feel.", "המחסום העיקרי פנימי: מחקר על בקשת עזרה מוצא שאנשים ממעיטים בעקביות בנכונות של אחרים לעזור — וכמה טוב העזרה גורמת להם להרגיש."),
      L("Specific, bounded asks beat open-ended ones: 'could you take pickup this Thursday?' is easy to grant and easy to decline; 'let me know if you ever...' is neither.", "בקשות מוגדרות ותחומות מנצחות בקשות פתוחות: \"תוכלי לקחת את האיסוף ביום חמישי?\" קל להיענות לה וקל לסרב לה; \"תגידו אם פעם...\" — לא זה ולא זה."),
      L("Standing structures compound: a pickup pool, a dinner swap, an alternating playdate afternoon build a village that runs without weekly courage.", "מבנים קבועים צוברים ריבית: קבוצת איסוף, החלפת ארוחות, אחר צהריים מתחלף של מפגשי משחק בונים כפר שרץ בלי אומץ שבועי."),
      L("Children are watching how you do interdependence: a parent who asks, receives and reciprocates is teaching that needing people is normal — a lesson they'll reuse.", "הילדים צופים איך אתם עושים תלות הדדית: הורה שמבקש, מקבל ומחזיר מלמד שלהזדקק לאנשים זה נורמלי — שיעור שהם ישתמשו בו שוב."),
    ],
    body: L(
      "The phrase 'it takes a village' gets said wistfully, as if the village were a poetic exaggeration. It wasn't. For most of human history, children were raised amid grandmothers, aunts, older cousins and neighbors, and the daily work of care was distributed by default. Anthropologists studying childrearing across cultures describe shared care as the human norm. The modern arrangement — one or two adults providing what a network once did, often far from family — is the anomaly. Which reframes the exhaustion: the job wasn't designed for this few people. The gap is structural, not a personal shortfall.\n\nBut if the village no longer assembles itself, it has to be recruited — and the recruiting tool is the ask, which is exactly where many parents stall. The barriers are mostly internal: a culture that grades self-sufficiency, the fear of imposing, the sense that everyone else is managing. Here the research on help-seeking is genuinely cheering: across studies, people asked for help say yes far more often than askers predict, and helpers report liking the helper role — being trusted with someone's real need tends to build closeness rather than burden it. The ask you've been swallowing is, more often than it feels, a gift to the person receiving it.\n\nAsking well is a learnable mechanic. Specific and bounded beats open-ended: 'could you take school pickup this Thursday?' can be granted or declined in five seconds, while 'let me know if you ever want to help' politely transfers all the work back to the other person. Even better than good single asks are standing structures, because they replace repeated courage with routine: a two-family pickup pool, a Sunday dinner swap, an alternating playdate afternoon that buys each set of parents a free one. Reciprocity is the engine — the village runs on loops, not favors — and being easy to help matters too: accept the imperfect version, skip the apology spiral, say what actually helped.\n\nSo build the roster before the crisis: a few names for emergencies, a few for logistics, one or two for the hard evenings when what you need is an adult voice. And notice who's watching. A child who grows up seeing their parent ask, receive and give back is learning that needing people is not weakness but how humans have always done this. That lesson may outlast every other item on the list.",
      "המשפט \"צריך כפר שלם לגדל ילד\" נאמר בערגה, כאילו הכפר היה הגזמה פיוטית. הוא לא היה. לאורך רוב ההיסטוריה האנושית, ילדים גדלו בין סבתות, דודות, בני דודים גדולים ושכנים, ועבודת הטיפול היומית התחלקה כברירת מחדל. אנתרופולוגים שחוקרים גידול ילדים בין תרבויות מתארים טיפול משותף כנורמה האנושית. הסידור המודרני — מבוגר אחד או שניים שמספקים מה שרשת שלמה סיפקה פעם, לרוב רחוק מהמשפחה — הוא החריגה. וזה ממסגר מחדש את התשישות: העבודה לא תוכננה לכל כך מעט אנשים. הפער מבני, לא כשל אישי.\n\nאבל אם הכפר כבר לא מתכנס מעצמו, צריך לגייס אותו — וכלי הגיוס הוא הבקשה, בדיוק המקום שבו הורים רבים נתקעים. המחסומים בעיקר פנימיים: תרבות שמצייננת הסתדרות עצמית, החשש להטריח, התחושה שכולם חוץ מכם מסתדרים. כאן מחקר בקשת העזרה משמח באמת: לרוחב מחקרים, אנשים שמתבקשים לעזור אומרים כן הרבה יותר משהמבקשים חוזים, ועוזרים מדווחים שהם אוהבים את תפקיד העוזר — לקבל אמון עם צורך אמיתי של מישהו נוטה לבנות קרבה, לא להעמיס עליה. הבקשה שאתם בולעים היא, לעתים קרובות משזה מרגיש, מתנה למי שמקבל אותה.\n\nלבקש היטב היא מכניקה שאפשר ללמוד. מוגדר ותחום מנצח פתוח: \"תוכלי לקחת את האיסוף מבית הספר ביום חמישי?\" אפשר להיענות או לסרב לה בחמש שניות, בעוד \"תגידו אם בא לכם פעם לעזור\" מעביר בנימוס את כל העבודה בחזרה לצד השני. טובים אף יותר מבקשות בודדות הם מבנים קבועים, כי הם מחליפים אומץ חוזר בשגרה: קבוצת איסוף של שתי משפחות, החלפת ארוחת ערב של יום ראשון, אחר צהריים מתחלף של מפגש משחק שקונה לכל זוג הורים אחד חופשי. הדדיות היא המנוע — הכפר רץ על לולאות, לא על טובות — וגם להיות קלים לעזרה חשוב: קבלו את הגרסה הלא מושלמת, דלגו על ספירלת ההתנצלות, אמרו מה באמת עזר.\n\nאז בנו את הסגל לפני המשבר: כמה שמות לחירום, כמה ללוגיסטיקה, אחד או שניים לערבים הקשים שבהם מה שצריך הוא קול של מבוגר. ושימו לב מי צופה. ילד שגדל ורואה את ההורה שלו מבקש, מקבל ומחזיר לומד שלהזדקק לאנשים אינו חולשה אלא הדרך שבה בני אדם תמיד עשו את זה. השיעור הזה עשוי להאריך ימים מכל סעיף אחר ברשימה."
    ),
    tryToday: L(
      "Send one specific, bounded ask today — \"could you take pickup Thursday?\" — to someone you've been not-asking for weeks. Note how the answer compares to your forecast.",
      "שלחו היום בקשה אחת מוגדרת ותחומה — \"תוכלי לקחת את האיסוף ביום חמישי?\" — למישהו שאתם לא־מבקשים ממנו כבר שבועות. שימו לב איך התשובה משתווה לתחזית שלכם."
    ),
    ask: L("Help me draft a help roster for our family — who could we ask, for what, and how?", "עזור לי לבנות סגל עזרה למשפחה שלנו — את מי אפשר לבקש, למה, ואיך?"),
  },
];
