export const COMPANION_CONSENT_COPY = {
  en: {
    control: "File permissions",
    title: "Let Arbor understand your files",
    active: "File analysis is allowed for this child",
    inactive: "Your permission comes first",
    processing: "When you ask Arbor to analyse a file, it sends your selected images or PDFs to its AI provider to answer a question or prepare a document import for this child.",
    record: "Original files are processed temporarily. Conversations keep the explanation and file names; imports keep the text you review and save. Interpretations can be wrong, so check them against the original.",
    duration: "This permission lasts up to one year. You can turn it off here at any time. Avatar, voice and AI-training permissions are separate.",
    checkbox: "I am this child’s parent or guardian and allow Arbor to analyse images and documents I send for this child.",
    allow: "Allow file analysis",
    later: "Back to my draft",
    close: "Close permissions",
    revoke: "Turn off file analysis",
    revoking: "Turning off…",
    saving: "Saving permission…",
    loading: "Checking your permission…",
    failed: "We couldn’t confirm the permission. Your draft and files are still here.",
    retry: "Check again",
    saved: "Permission saved. Your file is ready for you to continue when you choose.",
    revoked: "File analysis is off. Your draft and saved conversations are unchanged.",
    noDelete: "Turning this off stops future file analysis. It does not delete explanations or imported text you have already saved.",
  },
  he: {
    control: "הרשאות לקבצים",
    title: "נותנים לארבור להבין את הקבצים",
    active: "ניתנה הרשאה לניתוח קבצים עבור הילד/ה",
    inactive: "קודם מקבלים את הרשות שלכם",
    processing: "כשמבקשים מארבור לנתח קובץ, הוא שולח לספק ה־AI שלו את התמונות או קובצי ה־PDF שבחרתם, כדי לענות על שאלה או להכין ייבוא ממסמך עבור הילד/ה.",
    record: "הקבצים המקוריים מעובדים באופן זמני. בשיחות נשמרים ההסבר ושמות הקבצים; בייבוא נשמר הטקסט שבדקתם ושמרתם. הפרשנות יכולה להיות שגויה, ולכן כדאי לבדוק מול המקור.",
    duration: "ההרשאה תקפה למשך שנה לכל היותר. אפשר לבטל אותה כאן בכל עת. ההרשאות לדמות מצוירת, לקול ולאימון AI נפרדות.",
    checkbox: "אני ההורה או האפוטרופוס של הילד/ה, ומאשר/ת לארבור לנתח תמונות ומסמכים שאשלח עבורו/ה.",
    allow: "אישור ניתוח קבצים",
    later: "חזרה לטיוטה",
    close: "סגירת ההרשאות",
    revoke: "ביטול הרשאה לניתוח קבצים",
    revoking: "מבטלים…",
    saving: "שומרים את ההרשאה…",
    loading: "בודקים את ההרשאה…",
    failed: "לא הצלחנו לאמת את ההרשאה. הטיוטה והקבצים עדיין כאן.",
    retry: "בדיקה נוספת",
    saved: "ההרשאה נשמרה. הקובץ מחכה לכם, ואפשר להמשיך כשתבחרו.",
    revoked: "ההרשאה לניתוח קבצים בוטלה. הטיוטה והשיחות השמורות נשארו כפי שהיו.",
    noDelete: "הביטול עוצר ניתוח קבצים בעתיד. הוא לא מוחק הסברים או טקסט מיובא שכבר שמרתם.",
  },
} as const;
