/** Surface-owned copy: both parent languages travel with the shared Now view. */
export const NOW_COPY = {
  en: {
    title: (name: string) => `Today with ${name}`,
    subtitle: "One useful next step. Space for whatever the day brings.",
    today: "A little help for today",
    chosen: "The step you chose",
    visit: "Your upcoming visit",
    visitTitle: (profession: string, date: string) => `${profession} · ${date}`,
    visitBody: "Look over the page from your record before the visit.",
    visitOpen: "Look over the page",
    visitLater: "Not now",
    chosenTitle: "Pick up where you left off",
    chosenWhy: "You chose this step. Keep it, adapt it, or tell Arbor how it went.",
    finishedTitle: "Your experience stays with this step",
    finished: "Your response is saved. You can leave it here or talk it through.",
    helped: "It helped",
    notToday: "Not this time",
    saving: "Saving…",
    saved: "Saved",
    saveError: "That didn’t save. Please try again.",
    adapt: "Adapt it with Arbor",
    adaptPrompt: (step: string) => `Help me adapt this idea to our day: ${step}`,
    continueProgram: "Continue your program",
    programWhy: (week: number) => `Week ${week} of the program you chose. Your next step is ready when you are.`,
    programLabel: "Your chosen program",
    recommendation: "An idea for today",
    curated: "From the activity library",
    curatedWhy: "A library idea for this age. Choose what fits your day.",
    goalsWhy: "Selected for a focus you chose, from the activity library.",
    momentsWhy: "Selected for an area in your recent notes, from the activity library.",
    interestWhy: (interest: string) => `A library idea you can make your own with ${interest}.`,
    continuationWhy: "You said a step in this area helped. Here is something to try next.",
    why: "Why this idea",
    say: "Words you could try",
    choose: "Make this my next step",
    begin: "See how to begin",
    otherIdea: "Another idea",
    library: "Browse activities",
    hide: "Close the steps",
    putDown: "Ready when you are. You can put the screen down and try it together.",
    materials: "What you’ll need",
    steps: "How to begin",
    minutes: (n: number) => `${n} min`,
    loading: "Arbor is preparing an idea. You can explore this activity while you wait.",
    focusError: "Arbor couldn’t refresh today’s idea. This library activity is still available.",
    retry: "Try again",
    talkTitle: "What’s on your mind?",
    talkBody: "Bring a question, a photo, or the words you haven’t found yet.",
    talk: "Ask Arbor",
    continueTopic: "Continue this question",
    practiceDetails: "Words and details",
    topic: "A question you’re exploring",
    topics: "Your saved questions",
    capture: "Keep a moment",
    captureShort: "Keep",
    captureBody: "A few words are enough. Add more when you want to.",
    write: "Write",
    dictate: "Dictate",
    photo: "Photo",
    quickSave: "Quick ways to keep a moment",
    hardTitle: "A hard moment?",
    hardBody: "Words and one step for right now",
    weeklyTitle: "Pause and look back on the week",
    weeklyBody: "Bring your moments together, notice patterns, and choose what to carry forward.",
    pictureTitle: (name: string) => `${name}’s whole picture`,
    pictureBody: "Connect the moments. See what is taking shape.",
    togetherTitle: "A little time together",
    togetherBody: "Stories, games, and ideas away from the screen",
    learning: "For you",
    care: "Care & collaboration",
    outcomes: "How did the step go for you?",
    noOffer: "A little time together is a place to start",
    noOfferBody: "Explore stories and everyday ideas, then choose what fits your family.",
  },
  he: {
    title: (name: string) => `היום עם ${name}`,
    subtitle: "צעד אחד שיכול לעזור. מקום לכל מה שהיום יביא.",
    today: "קצת עזרה להיום",
    chosen: "הצעד שבחרתם",
    visit: "הפגישה הקרובה שלכם",
    visitTitle: (profession: string, date: string) => `${profession} · ${date}`,
    visitBody: "עברו על הדף מהתיעוד שלכם לפני הפגישה.",
    visitOpen: "עברו על הדף",
    visitLater: "לא עכשיו",
    chosenTitle: "ממשיכים מהמקום שלכם",
    chosenWhy: "זה הצעד שבחרתם. אפשר להמשיך, להתאים אותו או לספר לארבור איך היה.",
    finishedTitle: "החוויה שלכם נשארת עם הצעד הזה",
    finished: "התשובה נשמרה. אפשר לעצור כאן או לחשוב עליה יחד עם ארבור.",
    helped: "זה עזר",
    notToday: "לא הפעם",
    saving: "שומרים…",
    saved: "נשמר",
    saveError: "השמירה לא הצליחה. אפשר לנסות שוב.",
    adapt: "מתאימים יחד עם ארבור",
    adaptPrompt: (step: string) => `עזור לי להתאים את הרעיון הזה ליום שלנו: ${step}`,
    continueProgram: "ממשיכים בתוכנית",
    programWhy: (week: number) => `שבוע ${week} בתוכנית שבחרתם. הצעד הבא מחכה לזמן שמתאים לכם.`,
    programLabel: "התוכנית שבחרתם",
    recommendation: "רעיון להיום",
    curated: "מתוך ספריית הפעילויות",
    curatedWhy: "רעיון מהספרייה שמתאים לגיל. בוחרים מה שמתאים ליום שלכם.",
    goalsWhy: "נבחר מתוך הספרייה לפי תחום שבחרתם להתמקד בו.",
    momentsWhy: "נבחר מתוך הספרייה לפי תחום שעולה ברגעים האחרונים שתיעדתם.",
    interestWhy: (interest: string) => `רעיון מהספרייה שאפשר להתאים בעזרת ${interest}.`,
    continuationWhy: "סיפרתם שצעד בתחום הזה עזר. הנה משהו שאפשר לנסות בהמשך.",
    why: "למה הרעיון הזה",
    say: "מילים שאפשר לנסות",
    choose: "נבחר את זה כצעד הבא",
    begin: "איך מתחילים",
    otherIdea: "רעיון אחר",
    library: "לספריית הפעילויות",
    hide: "סגירת ההנחיות",
    putDown: "מתחילים כשמתאים לכם. אפשר להניח את המסך ולנסות יחד.",
    materials: "מה צריך",
    steps: "איך מתחילים",
    minutes: (n: number) => `${n} דקות`,
    loading: "ארבור מכין רעיון. בינתיים אפשר להכיר את הפעילות הזאת.",
    focusError: "ארבור לא הצליח לעדכן את הרעיון להיום. הפעילות הזאת מהספרייה עדיין זמינה.",
    retry: "ננסה שוב",
    talkTitle: "מה מעסיק אתכם?",
    talkBody: "שאלה, תמונה או מחשבה שעוד קשה לשים במילים — אפשר להתחיל מכאן.",
    talk: "שואלים את ארבור",
    continueTopic: "ממשיכים עם השאלה",
    practiceDetails: "מילים ופרטים",
    topic: "שאלה שאתם בוחנים יחד",
    topics: "השאלות ששמרתם",
    capture: "שומרים רגע",
    captureShort: "שמירה",
    captureBody: "מספיקות כמה מילים. תמיד אפשר להוסיף בהמשך.",
    write: "כתיבה",
    dictate: "הכתבה",
    photo: "תמונה",
    quickSave: "דרכים מהירות לשמור רגע",
    hardTitle: "רגע קשה?",
    hardBody: "מילים וצעד אחד לעכשיו",
    weeklyTitle: "עוצרים לרגע ומסתכלים על השבוע",
    weeklyBody: "מחברים את הרגעים שתיעדתם, מבחינים בדפוסים ובוחרים מה לקחת הלאה.",
    pictureTitle: (name: string) => `התמונה השלמה של ${name}`,
    pictureBody: "מחברים בין הרגעים. רואים מה הולך ונבנה.",
    togetherTitle: "קצת זמן ביחד",
    togetherBody: "סיפורים, משחקים ורעיונות לזמן בלי מסך",
    learning: "בשבילכם",
    care: "אנשי המקצוע שלצדכם",
    outcomes: "איך הצעד הזה עבד בשבילכם?",
    noOffer: "אפשר להתחיל מרגע קטן ביחד",
    noOfferBody: "מגלים סיפורים ורעיונות ליומיום, ובוחרים מה מתאים למשפחה שלכם.",
  },
} as const;
