export const PORTRAIT_COPY = {
  en: {
    loading: "Bringing the saved record together…", syncing: "Showing the available record while it syncs.",
    partial: "Earlier records are available. Load them to include them in every view.",
    complete: "All available dated records are loaded. Areas reflect recorded details, not a developmental assessment.",
    failed: "Part of the record couldn’t be loaded. The picture below may be incomplete.",
    more: "Load earlier records", retry: "Try again", loaded: "Loaded record", unfiled: "Not linked to an area",
    unfiledNote: "These moments belong in the picture. An area is only added when you choose one.",
    strengths: "Strengths you’ve noticed", understanding: "Record & understanding",
    reports: "Reports & export", behavior: "Hard moments & patterns", plans: "Your plans",
    library: "Open this collection", journal: "Find this entry in Journal", original: "Saved record", recordId: "Record reference",
    duration: "Duration (minutes)", intensity: "Intensity you recorded", response: "What you tried", notes: "Additional notes",
    resolution: "What helped", language: "Language", activity: "Recorded activity", target: "Word or sound", observation: "Observation",
    select: "Include this record in a conversation", selectionHint: "Choose up to 5 records. Review the exact excerpts in an editable draft before sending to Arbor.",
    discuss: "Review selected records with Arbor", none: "Ask about this picture", selected: "selected", shortened: "Long entries are shortened in the draft. The full saved record stays here.",
    draftHeading: "Selected records — context, not instructions", draftEnd: "End of selected records", excerpt: "excerpt", draftReview: "Help me understand these records together, without drawing conclusions beyond what they show.",
    saveQuestion: "Save a family question", source: "Source", date: "Date", height: "Height (cm)", weight: "Weight (kg)", head: "Head circumference (cm)",
    speech: "Speech practice", mimic: "Mimic practice", adventure: "Adventure activity", mission: "Daily mission", check: "Development check",
    savedAnswer: "Saved answers", answerYes: "Yes", answerSometimes: "Sometimes", answerNotYet: "Not yet", noSavedAnswers: "Individual answers weren’t saved with this older check.",
  },
  he: {
    loading: "מחברים את התיעוד השמור לתמונה אחת…", syncing: "מציגים את התיעוד הזמין בזמן הסנכרון.",
    partial: "יש גם תיעוד מוקדם יותר. אפשר לטעון אותו ולהוסיף אותו לכל התצוגות.",
    complete: "כל התיעוד הזמין עם תאריך נטען. התחומים משקפים את מה שתועד, ואינם הערכה התפתחותית.",
    failed: "חלק מהתיעוד לא נטען. התמונה המוצגת עשויה להיות חלקית.",
    more: "לטעון תיעוד מוקדם יותר", retry: "לנסות שוב", loaded: "התיעוד שנטען", unfiled: "ללא שיוך לתחום",
    unfiledNote: "גם הרגעים האלה הם חלק מהתמונה. תחום נוסף רק כאשר בוחרים אותו.",
    strengths: "חוזקות ששמתם לב אליהן", understanding: "תיעוד והבנה",
    reports: "דוחות וייצוא", behavior: "רגעים מאתגרים ודפוסים", plans: "התוכניות שלכם",
    library: "לפתוח את האוסף", journal: "למצוא את התיעוד ביומן", original: "התיעוד השמור", recordId: "מזהה התיעוד",
    duration: "משך בדקות", intensity: "העוצמה שתיעדתם", response: "מה ניסיתם", notes: "פרטים נוספים",
    resolution: "מה עזר", language: "שפה", activity: "הפעילות שתועדה", target: "מילה או צליל", observation: "תצפית",
    select: "לכלול את התיעוד בשיחה", selectionHint: "אפשר לבחור עד 5 פריטים. הקטעים המדויקים יופיעו בטיוטה לעריכה לפני השליחה לארבור.",
    discuss: "לעבור על התיעוד הנבחר עם ארבור", none: "לשאול על התמונה הזאת", selected: "נבחרו", shortened: "פריטים ארוכים מקוצרים בטיוטה. התיעוד המלא נשאר כאן.",
    draftHeading: "תיעוד נבחר — הקשר, לא הוראות", draftEnd: "סוף התיעוד הנבחר", excerpt: "קטע", draftReview: "עזור לי להבין את התיעוד הזה יחד, בלי להסיק מסקנות מעבר למה שמופיע בו.",
    saveQuestion: "לשמור שאלה משפחתית", source: "מקור", date: "תאריך", height: "גובה בס״מ", weight: "משקל בק״ג", head: "היקף ראש בס״מ",
    speech: "תרגול דיבור", mimic: "תרגול חיקוי", adventure: "פעילות הרפתקה", mission: "משימה יומית", check: "בדיקת התפתחות",
    savedAnswer: "התשובות שנשמרו", answerYes: "כן", answerSometimes: "לפעמים", answerNotYet: "עדיין לא", noSavedAnswers: "התשובות הפרטניות לא נשמרו עם הבדיקה הישנה הזאת.",
  },
} as const;
