import { Icon } from "./Icon";

/**
 * S4 — visible provenance badge for AI-generated art.
 *
 * States ONLY what Arbor can stand behind: this picture was generated by
 * Arbor's AI. It previously told parents the image was "invisibly watermarked
 * (Google SynthID + C2PA Content Credentials)" — a specific technical claim
 * that NOTHING in this codebase embeds, verifies or can prove, and which the AI
 * backlog's standing correction says never to assert. A trust badge that
 * overstates is worse than no badge. If provenance signing is ever verified
 * end-to-end, restore the claim together with the check that backs it.
 */
export function ProvenanceBadge({
  lang = "en",
  className = "",
}: {
  lang?: "en" | "he";
  className?: string;
}) {
  const label = lang === "he" ? "נוצר ב‑AI" : "AI-made";
  const title =
    lang === "he"
      ? "נוצר על‑ידי ה‑AI של Arbor. זו אינה תמונה של ילד אמיתי."
      : "Generated by Arbor's AI. It is not a photograph of a real child.";
  return (
    <span
      title={title}
      // The badge opens with an <Icon> ligature (Latin text), so dir="auto"
      // would resolve the Hebrew label LTR; the label's language is `lang`.
      dir={lang === "he" ? "rtl" : "ltr"}
      className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10.5px] font-bold ${className}`}
      style={{ background: "rgba(15,23,20,0.55)", color: "#fff", backdropFilter: "blur(4px)" }}
    >
      <Icon name="auto_awesome" size={12} />
      {label}
    </span>
  );
}

export default ProvenanceBadge;
