import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db, firebaseEnabled } from "./firebase";
import { ATTRIBUTION_PROP_KEYS } from "./attribution";
import { isKidModeActive } from "./kidModeGate";

/**
 * Minimal first-party analytics. Writes events to the signed-in user's own
 * Firestore collection so we can learn which capabilities get used — no
 * third-party scripts, no cross-site tracking. Best-effort and fire-and-forget.
 */
let uidProvider: () => string | undefined = () => undefined;

export function setAnalyticsUser(fn: () => string | undefined) {
  uidProvider = fn;
}

/**
 * Props merged onto EVERY event — set once at startup to the first-touch
 * attribution (market, source, referral_code, utm_*) from lib/attribution. This
 * is what makes the growth loop measurable: activation/retention events become
 * sliceable by acquisition channel without touching each call site.
 */
let globalPropsProvider: () => Record<string, unknown> = () => ({});

export function setGlobalProps(fn: () => Record<string, unknown>) {
  globalPropsProvider = fn;
}

/**
 * KID-MODE EGRESS GATE (STORE-K1, WS-4.0 SDK audit finding 1).
 *
 * Kid Mode is a CHILD-operated surface, and it fires first-party events
 * (practice_event, speech_attempt, mimic_*, adventure_*, kidlock_blocked_nav).
 * Without this gate the parent's first-touch marketing attribution (utm_*,
 * source, market, referral_code) rides on every one of them via the global
 * props above — campaign-attributed behavioural events generated by a child,
 * which is what Play's Families policy calls tracking in child flows.
 *
 * The gate is here, at the ONE choke point, never at the call sites: a new kid
 * surface is covered the day it is written. Behaviour while Kid Mode is off is
 * byte-identical to before.
 *
 * Events still FIRE in Kid Mode — safety telemetry (kidlock_blocked_nav) and
 * play signals the parent owns must not be silently dropped. What changes:
 *  - attribution props are never merged and never survive (stripped after the
 *    merge too, so an explicit call-site prop can't smuggle one through);
 *  - the event is tagged `kid_mode: true` so first-party dashboards segment
 *    child-generated activity honestly instead of guessing.
 *
 * Kid-surface call sites must therefore not use an ATTRIBUTION_PROP_KEYS name
 * (e.g. `source`) for their own semantics — it will be stripped. None do.
 */
export const KID_MODE_PROP = "kid_mode";

/** Drops every marketing-attribution key from a prop bag (pure; new object). */
export function stripAttributionProps(props: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(props)) {
    if ((ATTRIBUTION_PROP_KEYS as readonly string[]).includes(k)) continue;
    out[k] = v;
  }
  return out;
}

export function track(event: string, props: Record<string, unknown> = {}) {
  let merged: Record<string, unknown> = props;
  if (isKidModeActive()) {
    // Child-generated event: no attribution in, none out, tagged as kid-mode.
    merged = { ...stripAttributionProps(props), [KID_MODE_PROP]: true };
  } else {
    try {
      merged = { ...globalPropsProvider(), ...props }; // explicit props win over globals
    } catch {
      /* fall back to bare props */
    }
  }
  const uid = uidProvider();
  if (firebaseEnabled && db && uid && uid !== "local-sandbox") {
    try {
      void addDoc(collection(db, `users/${uid}/events`), { event, props: merged, at: serverTimestamp() });
    } catch {
      /* ignore */
    }
  } else if (import.meta.env.DEV) {
    // eslint-disable-next-line no-console
    console.debug("[track]", event, merged);
  }
}
