import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db, firebaseEnabled } from "./firebase";
import { ATTRIBUTION_PROP_KEYS } from "./attribution";
import { isKidModeActive } from "./kidModeGate";
import { awaitsAnalyticsOptOutHydration, isAnalyticsOptedOut, onAnalyticsOptOutSettled } from "./analyticsOptOut";

/**
 * Minimal first-party analytics. Writes events to the signed-in user's own
 * Firestore collection so we can learn which capabilities get used — no
 * third-party scripts, no cross-site tracking. Best-effort and fire-and-forget.
 */
let uidProvider: () => string | undefined = () => undefined;

export function setAnalyticsUser(fn: () => string | undefined) {
  uidProvider = fn;
}

/**
 * Props merged onto EVERY event — set once at startup to the first-touch
 * attribution (market, source, referral_code, utm_*) from lib/attribution. This
 * is what makes the growth loop measurable: activation/retention events become
 * sliceable by acquisition channel without touching each call site.
 */
let globalPropsProvider: () => Record<string, unknown> = () => ({});

export function setGlobalProps(fn: () => Record<string, unknown>) {
  globalPropsProvider = fn;
}

/**
 * KID-MODE EGRESS GATE (STORE-K1, WS-4.0 SDK audit finding 1).
 *
 * Kid Mode is a CHILD-operated surface, and it fires first-party events
 * (practice_event, speech_attempt, mimic_*, adventure_*, kidlock_blocked_nav).
 * Without this gate the parent's first-touch marketing attribution (utm_*,
 * source, market, referral_code) rides on every one of them via the global
 * props above — campaign-attributed behavioural events generated by a child,
 * which is what Play's Families policy calls tracking in child flows.
 *
 * The gate is here, at the ONE choke point, never at the call sites: a new kid
 * surface is covered the day it is written. Behaviour while Kid Mode is off is
 * byte-identical to before.
 *
 * Events still FIRE in Kid Mode — safety telemetry (kidlock_blocked_nav) and
 * play signals the parent owns must not be silently dropped. What changes:
 *  - attribution props are never merged and never survive (stripped after the
 *    merge too, so an explicit call-site prop can't smuggle one through);
 *  - the event is tagged `kid_mode: true` so first-party dashboards segment
 *    child-generated activity honestly instead of guessing.
 *
 * Kid-surface call sites must therefore not use an ATTRIBUTION_PROP_KEYS name
 * (e.g. `source`) for their own semantics — it will be stripped. None do.
 */
export const KID_MODE_PROP = "kid_mode";

/** Drops every marketing-attribution key from a prop bag (pure; new object). */
export function stripAttributionProps(props: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(props)) {
    if ((ATTRIBUTION_PROP_KEYS as readonly string[]).includes(k)) continue;
    out[k] = v;
  }
  return out;
}

/**
 * B-DATA-05: events fired before the sign-in hydration has read an account's
 * opt-out on a fresh browser (lib/analyticsOptOut) wait here — at most this
 * many, the first ones kept — and are written once the account turns out to
 * be opted in, or dropped when it is opted out. Props are merged (and the
 * kid-mode gate applied) at FIRE time, so a buffered event cannot pick up
 * attribution later.
 */
export const PRE_HYDRATION_EVENT_CAP = 20;

type PendingEvent = { uid: string; event: string; props: Record<string, unknown> };
const pendingEvents: PendingEvent[] = [];

/** How many events are waiting on hydration (read by the guard). */
export function pendingAnalyticsEventCount(): number {
  return pendingEvents.length;
}

function writeEvent(uid: string, event: string, props: Record<string, unknown>) {
  if (!firebaseEnabled || !db) return;
  try {
    void addDoc(collection(db, `users/${uid}/events`), { event, props, at: serverTimestamp() });
  } catch {
    /* ignore */
  }
}

onAnalyticsOptOutSettled((uid, optedOut) => {
  const waiting = pendingEvents.splice(0, pendingEvents.length);
  for (const pending of waiting) {
    if (pending.uid !== uid) pendingEvents.push(pending); // another account's: still waiting
    else if (!optedOut) writeEvent(pending.uid, pending.event, pending.props);
    // opted out: dropped, never written
  }
});

export function track(event: string, props: Record<string, unknown> = {}) {
  // B-DATA-05: the analytics opt-out is checked FIRST, before any other logic —
  // an opted-out account writes nothing, in parent mode and in Kid Mode alike.
  const uid = uidProvider();
  if (isAnalyticsOptedOut(uid)) return;
  let merged: Record<string, unknown> = props;
  if (isKidModeActive()) {
    // Child-generated event: no attribution in, none out, tagged as kid-mode.
    merged = { ...stripAttributionProps(props), [KID_MODE_PROP]: true };
  } else {
    try {
      merged = { ...globalPropsProvider(), ...props }; // explicit props win over globals
    } catch {
      /* fall back to bare props */
    }
  }
  if (firebaseEnabled && db && uid && uid !== "local-sandbox") {
    if (awaitsAnalyticsOptOutHydration(uid)) {
      // B-DATA-05: fresh browser, preference not read yet — hold, never send.
      if (pendingEvents.length < PRE_HYDRATION_EVENT_CAP) pendingEvents.push({ uid, event, props: merged });
      return;
    }
    writeEvent(uid, event, merged);
  } else if (import.meta.env.DEV) {
    // eslint-disable-next-line no-console
    console.debug("[track]", event, merged);
  }
}
