// AUTHORED + adversarially verified via the Peterson parent-layer workflow, then
// integrated as data. Family Formation rituals (Six-Frames-routed), EN+HE.
import type { FrameId } from "./masterclasses";

export interface FamilyRitual {
  id: string;
  title: string; titleHe: string;
  frame: FrameId;
  purpose: string; purposeHe: string;
  cadence: string; cadenceHe: string;
  steps: string[]; stepsHe: string[];
  why: string; whyHe: string;
}

export const FAMILY_RITUALS: FamilyRitual[] = [
  {
    id: "truth-practice-weekly",
    title: "Truth Practice",
    titleHe: "תרגול האמת",
    frame: "shadow",
    purpose: "Once a week, make telling a hard truth and repairing a mistake the most ordinary, safe thing that happens in your home. The aim is simple: your child learns that hiding costs more than honesty, and that nothing they did is too big to bring to you. You are building the habit before the stakes are high, so when something real happens at fifteen, the path back to you is already worn smooth.",
    purposeHe: "פעם בשבוע, הפכו את אמירת האמת הקשה ואת התיקון של טעות לדבר הכי רגיל ובטוח שקורה בבית. המטרה פשוטה: הילד לומד שלהסתיר עולה יותר מלהיות כן, ושאין שום דבר שהוא עשה גדול מכדי להביא אליכם. אתם בונים את ההרגל לפני שהמחיר גבוה, כך שכשמשהו אמיתי יקרה בגיל חמש-עשרה, הדרך חזרה אליכם כבר תהיה סלולה וברורה.",
    cadence: "Weekly, same evening each week, 10 to 15 minutes around the table.",
    cadenceHe: "שבועי, באותו ערב בכל שבוע, עשר עד חמש-עשרה דקות סביב השולחן.",
    steps: ["Go first, as the parent. Name one thing you got wrong this week in plain words: 'I snapped at you Tuesday when I was tired, and that was on me, not you.' This teaches that admitting fault is what strong people do, not weak ones.","Open the floor with a calm, fixed phrase the whole family learns: 'Is there anything you've been carrying that you want to put down?' Say it the same way every week so it becomes a safe door, not a trap.","When a child tells a hard truth, your first response is always the same two beats: thank them for telling you, then deal with the thing. 'Thank you for telling me. That took courage. Now let's sort it out.' The truth gets honored before the problem gets solved.","Separate the truth from the consequence out loud. Make clear that telling you never makes the consequence worse, and hiding never makes it better. If a real consequence is needed, it stays small and fair, and it never lands on the honesty itself.","Close with repair, not lecture. If someone was hurt, agree on one concrete thing to make it right this week, a real apology, a fixed toy, a redo. Repair is an action, not a feeling, and it ends the matter cleanly so no shame lingers.","End by marking the courage. A simple line works: 'This is what our family does. We tell the truth and we fix things.' The child leaves the table lighter, having learned that honesty is rewarded with relief, not punishment."],
    stepsHe: ["התחילו אתם, ההורים. ציינו דבר אחד שטעיתם בו השבוע במילים פשוטות: 'התפרצתי עליך ביום שלישי כשהייתי עייף, וזה היה באחריותי, לא שלך.' זה מלמד שלהודות בטעות זה מה שאנשים חזקים עושים, לא חלשים.","פתחו את הבמה במשפט קבוע ורגוע שכל המשפחה לומדת: 'יש משהו שאתה נושא על הלב ורוצה להניח?' אמרו אותו באותו אופן בכל שבוע כדי שיהפוך לדלת בטוחה, לא למלכודת.","כשילד מספר אמת קשה, התגובה הראשונה שלכם תמיד זהה בשני חלקים: תודו לו על שסיפר, ואז טפלו בעניין. 'תודה שסיפרת לי. זה דרש אומץ. עכשיו בוא נסדר את זה.' מכבדים את האמת לפני שפותרים את הבעיה.","הפרידו בקול בין האמת לבין התוצאה. הבהירו שלספר לכם אף פעם לא מחמיר את התוצאה, ולהסתיר אף פעם לא משפר אותה. אם נדרשת תוצאה אמיתית, היא נשארת קטנה והוגנת, ולעולם לא נופלת על הכנות עצמה.","סיימו בתיקון, לא בהטפה. אם מישהו נפגע, סכמו על דבר אחד מוחשי לתקן השבוע: התנצלות אמיתית, צעצוע שמתקנים, ניסיון חוזר. תיקון הוא פעולה, לא תחושה, והוא סוגר את העניין בנקיות כך שלא נשארת בושה.","סיימו בציון האומץ. משפט פשוט עובד: 'זה מה שהמשפחה שלנו עושה. אנחנו אומרים את האמת ומתקנים דברים.' הילד קם מהשולחן קליל יותר, אחרי שלמד שכנות זוכה בהקלה, לא בעונש."],
    why: "Children hide when the cost of telling feels higher than the cost of concealing. The math is set early, long before adolescence. When honesty reliably brings relief and a clear path to repair, and when the consequence never punishes the telling itself, a child stops calculating and starts coming to you. You are not avoiding the hard emotion by smoothing it over; you are sitting in it together and showing that it can be faced and resolved. That worn path back to you is the single most protective thing you can build, and it is built in ordinary weeks, not in crises.",
    whyHe: "ילדים מסתירים כשהמחיר של לספר מרגיש גבוה מהמחיר של להסתיר. החשבון נקבע מוקדם, הרבה לפני גיל ההתבגרות. כשכנות באופן עקבי מביאה הקלה ודרך ברורה לתיקון, וכשהתוצאה אף פעם לא מענישה את עצם האמירה, הילד מפסיק לחשב ומתחיל לבוא אליכם. אתם לא בורחים מהרגש הקשה על ידי החלקה שלו; אתם יושבים בתוכו יחד ומראים שאפשר להתמודד איתו ולפתור אותו. אותה דרך סלולה חזרה אליכם היא הדבר המגונן ביותר שתוכלו לבנות, והיא נבנית בשבועות רגילים, לא במשברים.",
  },
  {
    id: "responsibility-ladder",
    title: "The Responsibility Ladder",
    titleHe: "סולם האחריות",
    frame: "aim",
    purpose: "Build a clear, age-banded map of what your child can own, then move them up one rung at a time. A child who can do real things for the family grows into an adult who can do real things in the world. You are not raising someone to be served. You are raising someone to be capable, and the ladder is how competence gets handed over on purpose instead of by accident.",
    purposeHe: "בנו מפה ברורה לפי גיל של מה שהילד יכול לקחת על עצמו, ואז קדמו אותו שלב אחד בכל פעם. ילד שיודע לעשות דברים אמיתיים למען המשפחה גדל להיות מבוגר שיודע לעשות דברים אמיתיים בעולם. אינכם מגדלים מישהו שישרתו אותו. אתם מגדלים מישהו מסוגל, וסולם האחריות הוא הדרך שבה מוסרים יכולת מתוך כוונה ולא במקרה.",
    cadence: "Ongoing, with a 10-minute weekly review",
    cadenceHe: "מתמשך, עם סקירה שבועית של עשר דקות",
    steps: ["Write your child's current age band at the top of a page: 2-4 (puts toys away, carries their own plate to the sink), 5-7 (sets the table, feeds a pet, packs their own bag), 8-11 (makes a simple breakfast, does their own laundry start to finish, takes out the trash on a fixed day), 12-15 (cooks one family dinner a week, manages their own schedule and alarm, handles a small budget). Circle the band they are in now.","Pick exactly ONE responsibility from their current band that they do not yet own, and hand it over completely this week. Show them once, do it beside them once, then step back. Resist redoing it your way. A job done at 80 percent by them beats one done at 100 percent by you.","Make it visible and theirs. Write the one responsibility on a card or the fridge with their name on it. This is their rung, not a chore on your list. Ownership is the point, not compliance.","Hold the line warmly when they resist. Do not lecture and do not rescue. Say once, calmly: 'This is yours now. I know you can do it.' Then wait. The discomfort of doing it is the muscle growing.","Every week, sit for ten minutes together and look at the ladder. Ask one question: 'What did you handle this week that you could not handle a month ago?' Name it out loud. When a rung feels easy and automatic, add the next one from their band, or move up a band.","Once a child masters their full band, hand off the next steward role: a 12-year-old who runs their own morning can help a younger sibling run theirs. Competence that overflows into caring for others is the top of the ladder."],
    stepsHe: ["כתבו בראש הדף את טווח הגיל הנוכחי של הילד: 2-4 (מסדר צעצועים, נושא את הצלחת שלו לכיור), 5-7 (עורך שולחן, מאכיל חיית מחמד, אורז את התיק שלו), 8-11 (מכין ארוחת בוקר פשוטה, מכבס את הכביסה שלו מהתחלה ועד הסוף, מוציא את האשפה ביום קבוע), 12-15 (מבשל ארוחת ערב משפחתית אחת בשבוע, מנהל את הלוח והשעון המעורר שלו, מתנהל עם תקציב קטן). הקיפו את הטווח שבו הוא נמצא עכשיו.","בחרו אחריות אחת בדיוק מהטווח הנוכחי שהוא עוד לא לקח על עצמו, ומסרו אותה לו במלואה השבוע. הראו פעם אחת, עשו לצדו פעם אחת, ואז התרחקו. התאפקו מלעשות מחדש בדרך שלכם. עבודה שנעשתה על ידו בשמונים אחוז עדיפה על עבודה שנעשתה על ידכם במאה אחוז.","הפכו את זה לגלוי ולשלו. כתבו את האחריות האחת על כרטיס או על המקרר עם השם שלו. זה השלב שלו, לא משימה ברשימה שלכם. הבעלות היא העיקר, לא הציות.","החזיקו את הגבול בחום כשהוא מתנגד. אל תטיפו ואל תצילו. אמרו פעם אחת, בשקט: זה שלך עכשיו. אני יודע שאתה מסוגל. ואז חכו. אי הנוחות של העשייה היא השריר שגדל.","בכל שבוע שבו יחד עשר דקות והביטו בסולם. שאלו שאלה אחת: מה הצלחת להתמודד איתו השבוע שלא יכולת לפני חודש? אמרו זאת בקול. כששלב מרגיש קל ואוטומטי, הוסיפו את הבא בטווח שלו, או עלו טווח.","ברגע שהילד שולט בכל הטווח שלו, מסרו את תפקיד האחראי הבא: ילד בן שתים עשרה שמנהל את הבוקר שלו יכול לעזור לאח צעיר לנהל את שלו. יכולת שגולשת לדאגה לאחרים היא ראש הסולם."],
    why: "A child's sense of self-worth is not built by praise. It is built by doing hard things and seeing they can. Every responsibility you hand over is a vote of confidence the child can feel. The home is the first place where someone learns they are needed and capable, and a child who is needed at home walks into the world expecting to contribute rather than waiting to be carried.",
    whyHe: "תחושת הערך העצמי של ילד אינה נבנית ממחמאות. היא נבנית מעשיית דברים קשים ומהגילוי שהוא מסוגל. כל אחריות שאתם מוסרים היא הצבעת אמון שהילד יכול להרגיש. הבית הוא המקום הראשון שבו אדם לומד שהוא נחוץ ומסוגל, וילד שנחוץ בבית נכנס לעולם מתוך ציפייה לתרום במקום לחכות שיישאו אותו.",
  },
  {
    id: "family-story-canon",
    title: "Family Story Canon",
    titleHe: "ספר הסיפורים של המשפחה",
    frame: "story",
    purpose: "Write down, in your own words, the handful of stories your family tells about who you are. The origin story of how the family began. The hard time you got through together. The line you keep repeating. Children build their sense of self from the story they live inside, and a family that knows its own story gives a child something solid to stand on. Once a month or so, you add to it, retell one out loud, and tie it back to what your family actually values.",
    purposeHe: "לכתוב, במילים שלכם, את אותם כמה סיפורים שהמשפחה מספרת על מי אתם. סיפור ההתחלה של איך המשפחה נוצרה. התקופה הקשה שעברתם יחד. המשפט שאתם חוזרים עליו שוב ושוב. ילד בונה את תחושת העצמי שלו מתוך הסיפור שהוא חי בתוכו, ומשפחה שמכירה את הסיפור שלה נותנת לילד קרקע יציבה לעמוד עליה. פעם בחודש בערך אתם מוסיפים לספר, מספרים סיפור אחד בקול, וקושרים אותו חזרה לערכים שהמשפחה באמת מחזיקה.",
    cadence: "occasional/monthly",
    cadenceHe: "מדי פעם / חודשי",
    steps: ["Start the canon. Open a notebook, a notes file, or a shared doc and write three headings: How We Began, The Time We..., and Our Motto. You do not need to fill all three tonight. Pick the one that comes easiest and write a few honest sentences.","Tell one origin story out loud at the table. How the two of you met, the day this child arrived, where the family name comes from. Let the child ask questions. Keep it true, including the ordinary and the hard parts, not a polished fairy tale.","Name one The Time We... story: a hard stretch the family got through. Money was tight, someone was sick, you moved. Tell what you did, not just what happened. The point the child takes home is we are people who handle things, together.","Draft your family motto in one short line. Ask everyone what we stand for and listen for the recurring word. Honesty. We finish what we start. Nobody eats alone. Write the line everyone recognizes, even if it is plain.","Tie each story to a value out loud. Say it plainly: that is why we tell the truth, that is why we show up for each other. The story is the reason the value sticks.","Save it and set the next visit. Put the canon somewhere you will find it again and agree to add one story next month. Over a year you will have something a child can carry for life."],
    stepsHe: ["פותחים את הספר. פתחו מחברת, קובץ הערות או מסמך משותף וכתבו שלוש כותרות: איך התחלנו, הפעם ש..., והמוטו שלנו. לא צריך למלא את כל השלוש הערב. בחרו את זו שבאה הכי בקלות וכתבו כמה משפטים כנים.","ספרו סיפור התחלה אחד בקול ליד השולחן. איך השניים שלכם נפגשתם, היום שבו הילד הזה הגיע, מאיפה בא שם המשפחה. תנו לילד לשאול. שמרו על אמת, כולל החלקים הרגילים והקשים, לא אגדה מלוטשת.","תנו שם לסיפור אחד של הפעם ש...: תקופה קשה שהמשפחה צלחה. היה צפוף בכסף, מישהו חלה, עברתם דירה. ספרו מה עשיתם, לא רק מה קרה. מה שהילד לוקח הביתה הוא אנחנו אנשים שמתמודדים, ביחד.","נסחו את המוטו המשפחתי בשורה אחת קצרה. שאלו את כולם על מה אנחנו עומדים והקשיבו למילה שחוזרת. יושר. מסיימים מה שמתחילים. אף אחד לא אוכל לבד. כתבו את השורה שכולם מזהים, גם אם היא פשוטה.","קשרו כל סיפור לערך בקול. אמרו זאת בפשטות: בגלל זה אנחנו אומרים אמת, בגלל זה אנחנו נמצאים אחד בשביל השני. הסיפור הוא הסיבה שהערך נדבק.","שמרו וקבעו את הפעם הבאה. שימו את הספר במקום שתמצאו שוב והסכימו להוסיף סיפור אחד בחודש הבא. תוך שנה יהיה לכם משהו שילד יכול לשאת איתו לכל החיים."],
    why: "A child who knows where the family came from and what it stood through is harder to knock over. Belonging is not a feeling you give a child once; it is a story they hear enough times to believe. When you name your origin, your hard-won wins, and your motto, and you tie each to a value, you hand the child an answer to the quiet question every child asks: who are we, and where do I fit. That answer steadies them long after they leave the table.",
    whyHe: "ילד שיודע מאיפה המשפחה באה ומה היא צלחה קשה יותר להפיל. שייכות אינה תחושה שנותנים לילד פעם אחת; היא סיפור שהוא שומע מספיק פעמים כדי להאמין בו. כשאתם נותנים שם להתחלה שלכם, לניצחונות שהושגו בקושי, ולמוטו שלכם, וקושרים כל אחד לערך, אתם נותנים לילד תשובה לשאלה השקטה שכל ילד שואל: מי אנחנו, ואיפה מקומי. התשובה הזו מייצבת אותו זמן רב אחרי שהוא קם מהשולחן.",
  },
  {
    id: "weekly-reflection-sunday-reset",
    title: "The Sunday Reset",
    titleHe: "איפוס יום ראשון",
    frame: "aim",
    purpose: "Ten minutes once a week to look up from the daily grind and ask the only question that compounds: are we raising this child toward something? You name one real win, notice one place they grew, and set one small direction for the week. Not a performance review. A chance to see your child clearly and remember where you are pointed.",
    purposeHe: "עשר דקות פעם בשבוע להרים את הראש מעל השגרה היומיומית ולשאול את השאלה היחידה שמצטברת לאורך זמן: לאן אנחנו מגדלים את הילד הזה? אתם מנסחים ניצחון אחד אמיתי, שמים לב למקום אחד שבו הוא גדל, ומכוונים כיוון קטן אחד לשבוע. זה לא תיק הערכת עובד. זו הזדמנות לראות את הילד שלכם בבהירות ולזכור לאן אתם מכוונים.",
    cadence: "Weekly, about 10 minutes, Sunday evening or whenever your week resets.",
    cadenceHe: "שבועי, כעשר דקות, ביום ראשון בערב או מתי שהשבוע שלכם מתאפס.",
    steps: ["Sit somewhere quiet for two minutes before you start. Put the phone in another room. You are not solving anything yet, you are just arriving.","Name one real win from the week out loud. Something your child did, not something you did for them. Be specific: not 'she was good' but 'she waited her turn without being asked.'","Notice one place they grew, even slightly. A fear that got smaller, a skill that got steadier, a moment they chose the harder right thing. Growth is usually quiet.","Pick one small direction for the coming week. One thing you want to point them toward. Keep it to a single sentence and keep it doable, like 'we practice saying thank you to the person, looking at them.'","Write the win and the direction in one line where you will see it. A note on the fridge, a line in your phone. The point is not the record, it is that you said it on purpose.","If you parent with a partner, share your one win and one direction with them before bed. Two minutes. You are aiming at the same thing or you are not, and this is how you find out."],
    stepsHe: ["שבו במקום שקט שתי דקות לפני שאתם מתחילים. הניחו את הטלפון בחדר אחר. אתם עוד לא פותרים שום דבר, אתם רק מגיעים.","נסחו בקול ניצחון אחד אמיתי מהשבוע. משהו שהילד עשה, לא משהו שעשיתם בשבילו. היו מדויקים: לא 'היא הייתה טובה' אלא 'היא חיכתה לתורה בלי שביקשו'.","שימו לב למקום אחד שבו הוא גדל, ולו במעט. פחד שהתכווץ, מיומנות שהתייצבה, רגע שבו הוא בחר בדבר הנכון והקשה יותר. צמיחה היא בדרך כלל שקטה.","בחרו כיוון קטן אחד לשבוע הקרוב. דבר אחד שאליו אתם רוצים לכוון אותו. השאירו את זה במשפט אחד ובר-ביצוע, למשל 'אנחנו מתרגלים לומר תודה לאדם, מסתכלים עליו'.","כתבו את הניצחון ואת הכיוון בשורה אחת במקום שתראו. פתק על המקרר, שורה בטלפון. העיקר אינו התיעוד, אלא שאמרתם את זה בכוונה.","אם אתם מגדלים יחד עם בן או בת זוג, שתפו אותם בניצחון האחד ובכיוון האחד לפני השינה. שתי דקות. או שאתם מכוונים לאותו דבר או שלא, וכך מגלים."],
    why: "Children grow slowly and daily life moves fast, so most of the growth goes unseen and most weeks blur together. A short weekly look-up does two things. It lets you actually notice your child instead of only managing them, and it keeps you honest about direction, because a family that never asks where it is going tends to drift toward whatever is loudest. Ten minutes a week will not fix everything, but parents who aim on purpose raise children who feel aimed at, and that is most of what a child needs to know about home.",
    whyHe: "ילדים גדלים לאט וחיי היומיום נעים מהר, ולכן רוב הצמיחה נשארת בלתי נראית ורוב השבועות מיטשטשים זה בזה. הרמת ראש שבועית קצרה עושה שני דברים. היא מאפשרת לכם באמת לראות את הילד שלכם ולא רק לנהל אותו, והיא שומרת אתכם כנים לגבי הכיוון, כי משפחה שלא שואלת לאן היא הולכת נוטה להיסחף אל מה שהכי רועש. עשר דקות בשבוע לא יתקנו הכול, אבל הורים שמכוונים בכוונה מגדלים ילדים שמרגישים שמכוונים אליהם, וזה רוב מה שילד צריך לדעת על הבית שלו.",
  },
];
