export const coParentCopy = {
  en: {
    choose: "Choose an activity for us", chooseHint: "Choose one small thing you can both try. Sharing a choice saves it to this child’s record; looking through the options changes nothing.", chooseLabel: "Activity", chooseSave: "Share this activity", chooseSaved: "Your shared activity is ready", chooseError: "The activity wasn’t saved. Your choice is still here; try again.", choiceLoadError: "We couldn’t load the activities. Try again.", choiceEmpty: "Add your child’s age in their profile to find activities for your family.", doLabel: "Try this together", sayLabel: "You can say", minutes: "min", pinned: "Your choice from Today", chooseLoading: "Loading activities…", changed: "The shared activity changed. Refresh to see the latest choice.", completeError: "We couldn’t mark this done. Try again.", refreshError: "Saved, but we couldn’t refresh the view. Try again to see the latest record.",
    previewChild: "Noam · example family", previewDo: "Build a tower together. Place one block and wait for your child.", previewSay: "Your turn.", previewMoment: "After preschool, we sat together on the rug. Noam chose the first block.",
    title: "Parenting, together", intro: "One child, one shared record. Your co-parent can see the chosen activity and the 20 most recent moments, add a note, and mark an activity done.",
    free: "Free on every plan", email: "Your co-parent’s email", invite: "Create an invitation", creating: "Creating…", consent: "Only invite an adult you trust with these records. You can stop access here at any time. Your account settings, billing and private conversations stay yours.",
    send: "Share invitation", copy: "Copy invitation link", ready: "Invitation ready", sendHint: "Send the link yourself. Arbor has not sent an email. They must sign in with the invited email to join.", copied: "Link copied", copyFailed: "Couldn’t copy. Select and copy the link below.",
    inviteMessage: "Join me in Arbor to see our chosen activity and add moments to the same child’s record. Sign in with the email address I invited.",
    error: "We couldn’t load the shared space. Try again.", saveError: "That wasn’t saved. Your note is still here; try again.", createError: "The invitation wasn’t created. Check the email and try again.",
    loading: "Opening your shared space…", heading: "A shared space for your family", invitation: "You’ve been invited", invitedBy: "Invited by", join: "Join this child’s record", open: "Open shared space", joining: "Joining…", joined: "You’re using the same record. No new child profile needed.",
    empty: "No invitation is available for this account. Sign in with the invited email, or ask the other parent to create a new invitation.", verify: "To join, use the invited email with a verified account. Signing in with Google verifies your email.", ended: "This invitation is unavailable, has ended, or belongs to another account. Ask the other parent for a new invitation.",
    refresh: "Refresh", retry: "Try again", back: "Back to my Arbor", own: "Create my own child profile", signOut: "Use another account", activity: "The activity you chose", noActivity: "No activity has been chosen yet. You can still add a moment below.", done: "We did this", completed: "Marked done", moments: "Recent moments", noMoments: "Your first note can start the shared record.",
    note: "What would you like the other parent to know?", placeholder: "For example: We took turns building a tower before dinner.", noteHint: "Your words are saved to the same Moments record and visible to the other parent.", save: "Save to our record", saving: "Saving…", saved: "Saved to your shared record", you: "Your note", shared: "Shared moment", workspaceLabel: "Shared family workspace", statusPending: "Waiting to join", statusAccepted: "Joined", stop: "Stop access", stopped: "Access stopped", roster: "Co-parents", viewAll: "Choose another invitation", preview: "Preview with invented data",
  },
  he: {
    choose: "בוחרים פעילות בשבילנו", chooseHint: "בוחרים דבר קטן ששניכם תוכלו לנסות. שיתוף הבחירה שומר אותה בתיעוד של הילד; עיון באפשרויות לא משנה דבר.", chooseLabel: "פעילות", chooseSave: "שיתוף הפעילות הזאת", chooseSaved: "הפעילות המשותפת מוכנה", chooseError: "הפעילות לא נשמרה. הבחירה עדיין כאן; אפשר לנסות שוב.", choiceLoadError: "לא הצלחנו לטעון את הפעילויות. אפשר לנסות שוב.", choiceEmpty: "הוסיפו את גיל הילד בפרופיל כדי למצוא פעילויות למשפחה שלכם.", doLabel: "מנסים ביחד", sayLabel: "אפשר לומר", minutes: "דק׳", pinned: "הבחירה שלכם מהיום", chooseLoading: "טוענים פעילויות…", changed: "הפעילות המשותפת השתנתה. רעננו כדי לראות את הבחירה האחרונה.", completeError: "לא הצלחנו לסמן את הפעילות כבוצעה. אפשר לנסות שוב.", refreshError: "נשמר, אבל לא הצלחנו לרענן את התצוגה. נסו שוב כדי לראות את התיעוד העדכני.",
    previewChild: "נועם · משפחה לדוגמה", previewDo: "בונים מגדל ביחד. מניחים קובייה אחת ומחכים לילד.", previewSay: "עכשיו תורך.", previewMoment: "אחרי הגן ישבנו ביחד על השטיח. נועם בחר את הקובייה הראשונה.",
    title: "הורות, ביחד", intro: "אותו ילד, אותו תיעוד. ההורה הנוסף יוכל לראות את הפעילות שנבחרה ואת 20 הרגעים האחרונים, להוסיף תצפית ולסמן פעילות כבוצעה.",
    free: "ללא תשלום בכל מסלול", email: "כתובת המייל של ההורה הנוסף", invite: "יצירת הזמנה", creating: "יוצרים הזמנה…", consent: "מזמינים רק מבוגר שסומכים עליו עם התיעוד הזה. אפשר להפסיק את הגישה כאן בכל רגע. הגדרות החשבון, התשלום והשיחות הפרטיות נשארים שלכם.",
    send: "שיתוף ההזמנה", copy: "העתקת קישור ההזמנה", ready: "ההזמנה מוכנה", sendHint: "שלחו את הקישור בעצמכם. Arbor לא שלחה מייל. כדי להצטרף צריך להתחבר עם כתובת המייל שהוזמנה.", copied: "הקישור הועתק", copyFailed: "ההעתקה לא הצליחה. אפשר לסמן ולהעתיק את הקישור למטה.",
    inviteMessage: "הצטרפו אליי ל־Arbor כדי לראות את הפעילות שבחרנו ולהוסיף רגעים לאותו תיעוד של הילד. יש להתחבר עם כתובת המייל שאליה הוזמנתם.",
    error: "לא הצלחנו לפתוח את המרחב המשותף. אפשר לנסות שוב.", saveError: "השמירה לא הצליחה. הטקסט עדיין כאן; אפשר לנסות שוב.", createError: "ההזמנה לא נוצרה. בדקו את כתובת המייל ונסו שוב.",
    loading: "פותחים את המרחב המשותף…", heading: "מרחב משותף למשפחה שלכם", invitation: "קיבלתם הזמנה", invitedBy: "הזמנה מאת", join: "הצטרפות לתיעוד של הילד", open: "פתיחת המרחב המשותף", joining: "מצטרפים…", joined: "אתם באותו תיעוד. אין צורך ליצור פרופיל ילד נוסף.",
    empty: "לא נמצאה הזמנה לחשבון הזה. התחברו עם כתובת המייל שהוזמנה, או בקשו מההורה השני ליצור הזמנה חדשה.", verify: "כדי להצטרף נדרש חשבון עם כתובת המייל שהוזמנה ואומתה. התחברות דרך Google מאמתת את הכתובת.", ended: "ההזמנה אינה זמינה, הסתיימה או שייכת לחשבון אחר. אפשר לבקש מההורה השני הזמנה חדשה.",
    refresh: "רענון", retry: "ניסיון נוסף", back: "בחזרה ל־Arbor שלי", own: "יצירת פרופיל ילד משלי", signOut: "התחברות עם חשבון אחר", activity: "הפעילות שבחרתם", noActivity: "עדיין לא נבחרה פעילות. אפשר להוסיף רגע משותף למטה.", done: "עשינו את זה", completed: "סומנה כבוצעה", moments: "הרגעים האחרונים", noMoments: "התצפית הראשונה שלכם יכולה להתחיל את התיעוד המשותף.",
    note: "מה תרצו שההורה השני ידע?", placeholder: "למשל: בנינו מגדל בתורות לפני ארוחת הערב.", noteHint: "המילים שלכם נשמרות באותו תיעוד רגעים, וההורה השני יוכל לקרוא אותן.", save: "שמירה בתיעוד שלנו", saving: "שומרים…", saved: "נשמר בתיעוד המשותף", you: "התצפית שלכם", shared: "רגע משותף", workspaceLabel: "מרחב משפחתי משותף", statusPending: "ממתינים להצטרפות", statusAccepted: "הצטרף לחשבון המשותף", stop: "הפסקת הגישה", stopped: "הגישה הופסקה", roster: "הורים נוספים", viewAll: "בחירת הזמנה אחרת", preview: "תצוגה מקדימה עם נתונים מומצאים",
  },
} as const;

// Register every string in the shared dictionary and its clinical-language scan.
export const en: Record<string, string> = Object.fromEntries(Object.entries(coParentCopy.en).map(([key, value]) => [`elev.coParent.${key}`, value]));
export const he: Record<string, string> = Object.fromEntries(Object.entries(coParentCopy.he).map(([key, value]) => [`elev.coParent.${key}`, value]));
